(function () {
  'use strict';

  window.LECTURE_CONTENT = {
    ko: {
      s01_eyebrow: '2025학년도 2학기 실전웹서비스개발',
      s01_title: '실전 웹서비스개발 – 1주차',
      s01_subtitle: '강의소개',
      s02_title: '강의 소개 및 운영 방식',
      s03_title: '강의 개요',
      s03_goal_label: '목표',
      s03_goal: '직접 기획·제작한 웹서비스를 세상에 공개',
      s03_learning_label: '학습 내용',
      s03_learning: '웹 프론트엔드 → 서버 → 데이터베이스 → AI 연동 → 배포',
      s03_result_label: '결과물',
      s03_result: '실무에 바로 쓸 수 있는 개인 포트폴리오 1개 완성',
      s04_title: '강사 소개',
      s04_meta: '오현석 00 학번 / 개발경력 22년',
      s04_item_1: '現 아주대학교 디지털미디어학과 겸임교수',
      s04_item_2: '現 (주)트리플엔게임즈 대표',
      s04_item_3: '前 (주)원밀리언 CTO',
      s04_item_4: '前 (주)우아한형제들 시니어 엔지니어',
      s04_item_5: '前 스노우(주) 시니어 엔지니어',
      s04_image_alt: '강사의 주요 개발 프로젝트 이미지',
      s05_title: '수업 진행 방식',
      s05_lead: '이론 + 실습(과제 & 개인 프로젝트)',
      s05_before_label: '중간고사 이전',
      s05_before_1: '이론 - 강의를 통해 학습 목표와 실습에 필요한 핵심 개념 설명',
      s05_before_2: '실습 - 직접 AI 서비스와 질의 응답을 하며 학습 목표를 달성하기 위해 실습 진행',
      s05_before_3: '실습 과제 제출은 아주 Bb 코스에 제출',
      s05_before_4: '학습 목표의 이해 여부를 중간고사를 통해 확인',
      s05_after_label: '중간고사 이후',
      s05_after_1: '개인 프로젝트 수행',
      s05_project_1: '제안 발표 - 보고서',
      s05_project_2: '진행 상황 발표 - 시연',
      s05_project_3: '최종 결과 제출 - 보고서',
      s05_after_2: '웹 서비스 기획 및 AI 연동 서비스 제작 관련 강의',
      s05_after_2_sub: '실습 과제 없음',
      s06_title: '주차별 학습 흐름',
      s06_phase_1_label: '1 ~ 7 주차',
      s06_phase_1: '웹 프론트엔드 → 서버 → 데이터베이스 → AI 연동 → 배포에 필요한 개발 기술 학습',
      s06_phase_2_label: '8주차',
      s06_phase_2: '중간고사 (1 ~ 7 주차 핵심 개념 평가 - 서술형, 손코딩)',
      s06_phase_3_label: '9 ~ 10 주차',
      s06_phase_3_1: '웹 서비스 기획',
      s06_phase_3_2: '최신 AI 서비스, OpenAI API 연동',
      s06_phase_4_label: '11 주차',
      s06_phase_4: '프로젝트 제안 발표 (5분 스피치) + 제안서 제출',
      s06_phase_5_label: '12 ~ 14 주차',
      s06_phase_5: 'AI 연동 활용 서비스 제작 강의',
      s06_phase_6_label: '15 ~ 16 주차',
      s06_phase_6_1: '프로젝트 진행 상황 또는 결과 발표 (10분 + 데모 시연)',
      s06_phase_6_2: '기말고사 기간 종료 전까지 - 코드 제출 및 개발 보고서 작성 후 제출',
      s07_title: '평가',
      s07_participation: '참여 점수 (50 %)',
      s07_attendance: '출석 - 10%',
      s07_assignments: '과제 - 20%',
      s07_presentation: '프로젝트 발표 - 10%',
      s07_report: '프로젝트 보고서 및 결과 제출 - 10%',
      s07_performance: '수행 점수 (50 %)',
      s07_midterm: '중간 고사 - 30%',
      s07_project: '프로젝트 평가 - 20%',
      s07_note: '※ 학교 규정에 따라 점수 총합 순위를 기준으로 학점 산정',
      s08_title: '학습 기술 스택',
      s09_title: '질문과 답변',
      s10_title: '웹서비스 개요 및 개발 흐름',
      s11_title: '웹서비스란 무엇인가?',
      s11_standard: '기술 표준 정의(W3C Web Services Architecture, 2004)',
      s11_definition: '네트워크 상에서 상호 운용 가능한 시스템 간 상호작용을 지원하는 소프트웨어 시스템',
      s11_w3c: 'W3C : 팀 버너스리를 중심으로 1994년 10월에 설립된 월드 와이드 웹을 위한 표준을 개발하고 장려하는 조직',
      s12_title: '웹서비스란 무엇인가?',
      s12_broad: '넓은 의미(일반적 정의)',
      s12_broad_1: '인터넷을 통해 제공되는 모든 형태의 서비스',
      s12_broad_2: '웹 브라우저나 앱을 통해 사용자에게 콘텐츠·기능을 제공',
      s12_kinds: '종류',
      s13_title: '정적 웹페이지(Static Web Page)',
      s13_item_1: 'HTML/CSS 파일이 서버에 고정되어 있음',
      s13_item_2: '서버가 파일 그대로 전송 → 사용자 화면에 표시',
      s13_item_3: '콘텐츠 변경 시, 파일 자체를 수정·배포해야 함',
      s13_example: 'Ex) 회사 소개 페이지, 개인 블로그(순수 HTML), 안내 사이트',
      s13_html_label: 'HTML 표준이란?',
      s13_html_1: 'HTML 표준은 “웹 문서를 어떻게 써야 브라우저가 모두 똑같이 이해할 수 있는가”를 정한 공식 규격',
      s13_html_2: '태그·속성의 의미(시맨틱), 문법과 파싱 규칙, 폼/미디어 같은 동작 방식까지 포함해 웹 호환성의 공통 언어',
      s13_html_3: 'Living Standard가 수시로 갱신되며, <!doctype html> 하나로 최신 HTML을 선언',
      s13_image_alt: '정적 웹페이지 예시 화면',
      s14_title: '동적 웹페이지 (Dynamic Web Page)',
      s14_item_1: '사용자 요청 시 서버가 HTML을 실시간 생성',
      s14_item_2: '데이터베이스, 서버 로직에 따라 다른 결과를 표시',
      s14_example: 'Ex) 게시판, 쇼핑몰 상품 페이지, 날씨 검색 사이트',
      s14_image_alt: '동적 웹페이지 예시 화면',
      s15_title: '웹앱(Web Application)',
      s15_item_1: '웹 브라우저에서 실행되는 애플리케이션 수준의 기능 제공',
      s15_item_2: '프론트엔드와 백엔드가 명확히 구분되고, 대화형 UI와 실시간 데이터 반영',
      s15_example: 'Ex) Gmail, Google Docs, Figma Web, Notion, Notebooklm…',
      s15_image_alt: '웹 애플리케이션 예시 화면',
      s16_title: '웹서비스의 구조',
      s16_client_server_label: '클라이언트-서버 모델',
      s16_client_server: ' : 클라이언트와 서버 간의 요청(request)과 응답(response)을 통해 데이터를 주고받는 구조',
      s16_client: '클라이언트: 브라우저, 모바일 앱, 또는 다른 서버',
      s16_server: '서버: 요청을 처리하고 적절한 응답을 반환하는 역할',
      s16_network_label: '네트워크',
      s16_network: ': 클라이언트와 서버 간의 데이터를 전송하는 매개체(World Wide Web)',
      s16_protocol_label: '프로토콜',
      s16_http: 'HTTP/HTTPS: 웹 브라우저와 서버 간의 데이터 통신 규약. HTTPS는 HTTP에 SSL/TLS를 추가하여 보안을 강화한 프로토콜.',
      s16_rest: 'REST: Representational State Transfer의 약자로, HTTP 프로토콜을 기반으로 하는 아키텍처 스타일. RESTful 서비스는 URL을 통해 리소스를 식별하고, HTTP 요청(GET, POST, PUT, DELETE)을 사용하여 리소스를 조작.',
      s16_data_label: '데이터 형식',
      s16_image_alt: '클라이언트와 서버 사이의 요청 및 응답 구조',
      s17_title: 'Client(클라이언트)',
      s17_lead: '사용자가 웹서비스를 이용하기 위해 요청을 보내고 응답을 받아 화면에 보여주는 소프트웨어',
      s17_image_alt: '2024년 10월 기준 세계 웹브라우저와 검색시장 점유율',
      s18_title: 'Server(서버)',
      s18_lead: '클라이언트로부터 온 요청을 처리하고, 필요한 데이터를 가공하거나 데이터베이스와 연동하여 그 결과를 클라이언트에 응답하는 소프트웨어',
      s18_item_1: '사용자가 브라우저에서 요청 전송 (예: “로그인 버튼 클릭”)',
      s18_item_2: '서버가 요청을 받아 처리 (예: 입력 값 검증)',
      s18_item_3: 'DB에서 데이터 조회 (예: 아이디·비밀번호 확인)',
      s18_item_4: '서버가 결과를 응답으로 전송',
      s18_item_5: '클라이언트가 화면에 결과 표시',
      s19_lead: '웹에서 데이터를 주고받는 규약(프로토콜)',
      s19_request: '요청',
      s19_get: '데이터 조회',
      s19_post: '데이터 생성/전송',
      s19_put: '데이터 수정',
      s19_delete: '데이터 삭제',
      s19_response: '응답',
      s19_200: '정상 처리',
      s19_404: '페이지 없음',
      s19_500: '서버 오류',
      s19_302: '다른 페이지로 리다이렉트',
      s19_api_1: '프로그램끼리 대화할 수 있도록 만든 규칙·통로',
      s19_api_2: '웹에서는 HTTP 요청/응답 형식으로 기능 제공',
      s19_example: 'Ex) 서울 날씨 조회 API',
      s19_image_alt: 'JSON 데이터 형식 예시',
      s20_lead: '웹서비스에서 클라이언트 동작을 구현하는 개발 영역',
      s20_html: '웹페이지의 구조(뼈대)',
      s20_code_html: '<h1>제목</h1>',
      s20_css: '디자인, 색상, 배치',
      s20_js: '동작, 이벤트 처리',
      s20_code_event: 'onclick 이벤트',
      s20_image_alt: '2025년에 사용할 프론트엔드 프레임워크 비교표',
      s21_lead: '웹서비스의 데이터 처리, 서버 로직, 데이터베이스 관리 등 눈에 보이지 않는 동작을 담당하는 개발 영역',
      s21_item_1: '비즈니스 로직 수행(계산, 권한 확인, 데이터 가공 등)',
      s21_item_2: 'DB와 통신하여 결과 반환',
      s21_item_3: '다양한 환경과 언어로 개발 가능',
      s21_image_alt: '2025년에 사용할 백엔드 프레임워크',
      s21_fullstack: '웹서비스의 사용자 인터페이스(프론트엔드)와 서버·데이터베이스(백엔드) 모두를 개발하고 운영하는 개발',
      s22_title: '웹 브라우저에 www.naver.com을 쳤을 때 일어나는 일',
      s22_lead: '웹 브라우저에서 특정 URL을 입력했을 때 일어나는 과정을 설명',
      s22_item_1: 'DNS에 도메인을 검색하기 위한 요청',
      s22_item_2: 'www.naver.com에 대응하는 ip주소를 응답',
      s22_item_3: '받은 ip주소를 사용하여 TCP통신을 통해 해당 ip서버에 요청',
      s22_item_4: '요청을 받은 서버는 요청 내용에 대한 처리 과정을 거쳐서 응답 메시지를 생성',
      s22_item_5: '응답메시지를 TCP통신을 통해 다시 클라이언트에게 전송',
      s22_item_6: '브라우저는 받은 응답메시지를 HTTP 프로토콜을 사용하여 웹페이지를 구성',
      s22_image_alt: '브라우저, DNS, 인터넷, 서버 사이의 통신 순서',
      s23_title: '웹 서비스 개발 환경 준비',
      s24_lead: '마이크로소프트가 개발한 무료 코드 에디터',
      s24_features: '주요 특징',
      s24_item_1: '다양한 프로그래밍 언어 지원',
      s24_item_2: '풍부한 확장 기능 (Extensions)',
      s24_image_alt: 'Visual Studio Code 화면',
      s25_git_lead: '분산 버전 관리 시스템 (Distributed Version Control System)',
      s25_git_1: '소스 코드의 변경 이력을 기록 관리',
      s25_git_2: '여러 개발자가 동시에 협업할 수 있는 환경 제공',
      s25_github_lead: 'Git으로 관리되는 소스 코드를 온라인에서 저장·공유·협업할 수 있도록 지원하는 클라우드 기반 플랫폼',
      s25_gh_1: '코드 저장소 제공 ‒ Git 기반으로 프로젝트 소스를 안전하게 저장하고 관리 가능',
      s25_gh_2: '버전 관리 ‒ 코드 변경 이력 추적 및 이전 버전 복구 지원',
      s25_gh_3: '협업 기능 ‒ Pull Request, Issue, Discussions 등을 통한 팀 협업 지원',
      s25_gh_4: '프로젝트 관리 ‒ Kanban 보드, Wiki, Actions 등을 활용한 작업 관리 및 자동화',
      s25_gh_5: '오픈소스 생태계 ‒ 전 세계 개발자들과 오픈소스 프로젝트 공유 및 참여 가능',
      s25_gh_6: '정적 웹사이트 호스팅 - GitHub Pages',
      s25_gh_7: 'CI/CD 지원 ‒ GitHub Actions로 빌드, 테스트, 배포 자동화 가능',
      s25_gh_8: '보안 기능 ‒ 코드 보안 검사, 비밀키 관리, 취약점 경고 등 제공',
      s26_title: '과제: GitHub Pages 웹사이트 제작',
      s27_title: '과제 개요',
      s27_overview: 'GitHub Pages를 활용하여 웹사이트를 제작하고 배포',
      s27_learning: '학습 목표',
      s27_learning_1: '웹 서비스 개발 환경 구축',
      s27_learning_2: 'Git 기본 명령어 및 GitHub 저장소 관리 능력 습득',
      s27_learning_3: 'GitHub Pages를 통한 웹 호스팅 프로세스 경험',
      s27_requirements: '요구사항',
      s27_req_1: 'Git, GitHub CLI, VS Code 모두 설치됨',
      s27_req_2: 'GitHub 계정이 생성되고 로그인됨',
      s27_req_3: 'index.html, style.css, script.js 파일이 모두 작성됨',
      s27_req_4: 'GitHub 저장소가 생성되고 파일들이 업로드됨',
      s27_req_5: 'GitHub Pages가 활성화되어 웹사이트가 보임',
      s27_req_6: '버튼 클릭 시 텍스트가 변경됨',
      s27_reference: '참고',
      s27_deadline: '마감일',
      s27_due: '9월 7일 11시 59분 까지',
      s27_submit: 'LMS에 다음 정보를 제출',
      s27_repo: 'GitHub 저장소 URL',
      s27_pages: 'GitHub Pages URL',
      s28_title: '질문과 답변'
    },
    en: {
      s01_eyebrow: 'Practical Web Service Development · Fall 2025',
      s01_title: 'Practical Web Service Development – Week 1',
      s01_subtitle: 'Course Introduction',
      s02_title: 'Course Introduction and Operation',
      s03_title: 'Course Overview',
      s03_goal_label: 'Goal',
      s03_goal: 'Plan, build, and release your own web service to the public',
      s03_learning_label: 'What You Will Learn',
      s03_learning: 'Web front end → Server → Database → AI integration → Deployment',
      s03_result_label: 'Outcome',
      s03_result: 'Complete one practical personal portfolio project',
      s04_title: 'Instructor',
      s04_meta: 'Hyunseok Oh · Class of 2000 · 22 years of development experience',
      s04_item_1: 'Current Adjunct Professor, Department of Digital Media, Ajou University',
      s04_item_2: 'Current CEO, NNN Games',
      s04_item_3: 'Former CTO, 1MILLION',
      s04_item_4: 'Former Senior Engineer, Woowa Brothers',
      s04_item_5: 'Former Senior Engineer, SNOW',
      s04_image_alt: 'Selected development projects by the instructor',
      s05_title: 'Class Format',
      s05_lead: 'Theory + Practice (Assignments & Individual Project)',
      s05_before_label: 'Before the Midterm',
      s05_before_1: 'Theory — Lectures explain learning goals and the core concepts needed for practice',
      s05_before_2: 'Practice — Work directly with AI services through questions and answers to achieve the learning goals',
      s05_before_3: 'Submit practical assignments through the Ajou Bb course',
      s05_before_4: 'The midterm checks your understanding of the learning goals',
      s05_after_label: 'After the Midterm',
      s05_after_1: 'Complete an individual project',
      s05_project_1: 'Proposal presentation — Report',
      s05_project_2: 'Progress presentation — Demonstration',
      s05_project_3: 'Final result submission — Report',
      s05_after_2: 'Lectures on web service planning and building an AI-integrated service',
      s05_after_2_sub: 'No practical assignments',
      s06_title: 'Weekly Learning Flow',
      s06_phase_1_label: 'Weeks 1–7',
      s06_phase_1: 'Learn development technologies required for the web front end → server → database → AI integration → deployment',
      s06_phase_2_label: 'Week 8',
      s06_phase_2: 'Midterm exam (assessment of key concepts from Weeks 1–7 — written answers and handwritten code)',
      s06_phase_3_label: 'Weeks 9–10',
      s06_phase_3_1: 'Web service planning',
      s06_phase_3_2: 'Latest AI services and OpenAI API integration',
      s06_phase_4_label: 'Week 11',
      s06_phase_4: 'Project proposal presentation (5-minute speech) + proposal submission',
      s06_phase_5_label: 'Weeks 12–14',
      s06_phase_5: 'Lectures on building services that use AI integration',
      s06_phase_6_label: 'Weeks 15–16',
      s06_phase_6_1: 'Project progress or result presentation (10 minutes + live demo)',
      s06_phase_6_2: 'Submit code and a development report before the final exam period ends',
      s07_title: 'Assessment',
      s07_participation: 'Participation (50%)',
      s07_attendance: 'Attendance — 10%',
      s07_assignments: 'Assignments — 20%',
      s07_presentation: 'Project presentation — 10%',
      s07_report: 'Project report and result submission — 10%',
      s07_performance: 'Performance (50%)',
      s07_midterm: 'Midterm exam — 30%',
      s07_project: 'Project evaluation — 20%',
      s07_note: '※ Grades are assigned by total-score ranking in accordance with university regulations.',
      s08_title: 'Technology Stack',
      s09_title: 'Questions and Answers',
      s10_title: 'Web Service Overview and Development Flow',
      s11_title: 'What Is a Web Service?',
      s11_standard: 'Technical Standard Definition (W3C Web Services Architecture, 2004)',
      s11_definition: 'A software system that supports interaction between interoperable systems over a network',
      s11_w3c: 'W3C: An organization founded in October 1994 around Tim Berners-Lee to develop and promote standards for the World Wide Web.',
      s12_title: 'What Is a Web Service?',
      s12_broad: 'Broad, General Definition',
      s12_broad_1: 'Any form of service provided through the Internet',
      s12_broad_2: 'Provides content and functionality to users through a web browser or app',
      s12_kinds: 'Types',
      s13_title: 'Static Web Page',
      s13_item_1: 'HTML and CSS files remain fixed on the server',
      s13_item_2: 'The server sends the files as they are → They appear on the user’s screen',
      s13_item_3: 'Changing content requires editing and redeploying the files themselves',
      s13_example: 'Examples: Company profile pages, personal blogs in plain HTML, information sites',
      s13_html_label: 'What Is the HTML Standard?',
      s13_html_1: 'The HTML standard is the official specification for writing web documents so that all browsers understand them consistently.',
      s13_html_2: 'It defines the meaning of tags and attributes, syntax and parsing rules, and behavior for features such as forms and media—the common language of web compatibility.',
      s13_html_3: 'The Living Standard is updated continuously, and <!doctype html> declares modern HTML.',
      s13_image_alt: 'Example of a static web page',
      s14_title: 'Dynamic Web Page',
      s14_item_1: 'The server generates HTML in real time when a user makes a request',
      s14_item_2: 'The result changes according to the database and server logic',
      s14_example: 'Examples: Message boards, shopping product pages, weather search sites',
      s14_image_alt: 'Example of a dynamic web page',
      s15_title: 'Web Application',
      s15_item_1: 'Provides application-level functionality that runs in a web browser',
      s15_item_2: 'Clearly separates front end and back end, with interactive UI and real-time data updates',
      s15_example: 'Examples: Gmail, Google Docs, Figma Web, Notion, NotebookLM…',
      s15_image_alt: 'Example of a web application',
      s16_title: 'Web Service Structure',
      s16_client_server_label: 'Client–server model',
      s16_client_server: ': Data is exchanged through requests and responses between a client and a server',
      s16_client: 'Client: A browser, mobile app, or another server',
      s16_server: 'Server: Processes requests and returns appropriate responses',
      s16_network_label: 'Network',
      s16_network: ': The medium that transfers data between client and server (World Wide Web)',
      s16_protocol_label: 'Protocols',
      s16_http: 'HTTP/HTTPS: Communication rules between a web browser and a server. HTTPS strengthens security by adding SSL/TLS to HTTP.',
      s16_rest: 'REST: An architectural style based on HTTP. A RESTful service identifies resources with URLs and manipulates them with GET, POST, PUT, and DELETE requests.',
      s16_data_label: 'Data format',
      s16_image_alt: 'Request and response structure between a client and server',
      s17_title: 'Client',
      s17_lead: 'Software that sends requests to use a web service, receives responses, and presents the results on screen',
      s17_image_alt: 'Worldwide browser and search market share as of October 2024',
      s18_title: 'Server',
      s18_lead: 'Software that processes requests from clients, transforms the required data or connects to a database, and returns the result to the client',
      s18_item_1: 'The user sends a request from the browser (for example, clicks the Login button)',
      s18_item_2: 'The server receives and processes the request (for example, validates input)',
      s18_item_3: 'The server queries the database (for example, checks the ID and password)',
      s18_item_4: 'The server sends the result as a response',
      s18_item_5: 'The client displays the result on screen',
      s19_lead: 'The protocol used to exchange data on the web',
      s19_request: 'Request',
      s19_get: 'Retrieve data',
      s19_post: 'Create or send data',
      s19_put: 'Update data',
      s19_delete: 'Delete data',
      s19_response: 'Response',
      s19_200: 'Processed successfully',
      s19_404: 'Page not found',
      s19_500: 'Server error',
      s19_302: 'Redirect to another page',
      s19_api_1: 'A set of rules and a channel that let programs communicate',
      s19_api_2: 'On the web, functionality is provided through HTTP request and response formats',
      s19_example: 'Example: Seoul Weather API',
      s19_image_alt: 'Example of the JSON data format',
      s20_lead: 'The development area that implements client behavior in a web service',
      s20_html: 'Web page structure (skeleton)',
      s20_code_html: '<h1>Title</h1>',
      s20_css: 'Design, color, and layout',
      s20_js: 'Behavior and event handling',
      s20_code_event: 'onclick event',
      s20_image_alt: 'Comparison of front-end frameworks to use in 2025',
      s21_lead: 'The development area responsible for invisible operations such as web service data processing, server logic, and database management',
      s21_item_1: 'Execute business logic such as calculations, permission checks, and data transformation',
      s21_item_2: 'Communicate with the database and return results',
      s21_item_3: 'Can be developed in many environments and languages',
      s21_image_alt: 'Back-end frameworks to use in 2025',
      s21_fullstack: 'Development and operation of both the web service user interface (front end) and server and database (back end)',
      s22_title: 'What Happens When You Enter www.naver.com in a Browser',
      s22_lead: 'The sequence that occurs after entering a specific URL in a web browser',
      s22_item_1: 'Send a request to DNS to look up the domain',
      s22_item_2: 'Receive the IP address corresponding to www.naver.com',
      s22_item_3: 'Use the received IP address to send a request to that server over TCP',
      s22_item_4: 'The server processes the request and creates a response message',
      s22_item_5: 'The response message is sent back to the client over TCP',
      s22_item_6: 'The browser uses the HTTP response message to construct the web page',
      s22_image_alt: 'Communication sequence among a browser, DNS, the Internet, and a server',
      s23_title: 'Preparing the Web Service Development Environment',
      s24_lead: 'A free code editor developed by Microsoft',
      s24_features: 'Key Features',
      s24_item_1: 'Supports many programming languages',
      s24_item_2: 'A rich collection of extensions',
      s24_image_alt: 'Visual Studio Code interface',
      s25_git_lead: 'Distributed Version Control System',
      s25_git_1: 'Records and manages the change history of source code',
      s25_git_2: 'Provides an environment in which multiple developers can collaborate',
      s25_github_lead: 'A cloud-based platform for storing, sharing, and collaborating on source code managed with Git',
      s25_gh_1: 'Code repositories — Securely store and manage project source with Git',
      s25_gh_2: 'Version control — Track code history and restore earlier versions',
      s25_gh_3: 'Collaboration — Work as a team through pull requests, issues, and discussions',
      s25_gh_4: 'Project management — Manage and automate work with Kanban boards, Wikis, and Actions',
      s25_gh_5: 'Open-source ecosystem — Share and join open-source projects with developers worldwide',
      s25_gh_6: 'Static website hosting — GitHub Pages',
      s25_gh_7: 'CI/CD — Automate builds, tests, and deployments with GitHub Actions',
      s25_gh_8: 'Security — Code scanning, secret management, and vulnerability alerts',
      s26_title: 'Assignment: Build a Website with GitHub Pages',
      s27_title: 'Assignment Overview',
      s27_overview: 'Build and deploy a website with GitHub Pages',
      s27_learning: 'Learning Goals',
      s27_learning_1: 'Set up a web service development environment',
      s27_learning_2: 'Learn basic Git commands and GitHub repository management',
      s27_learning_3: 'Experience the web hosting process with GitHub Pages',
      s27_requirements: 'Requirements',
      s27_req_1: 'Git, GitHub CLI, and VS Code are all installed',
      s27_req_2: 'A GitHub account has been created and signed in',
      s27_req_3: 'index.html, style.css, and script.js have all been written',
      s27_req_4: 'A GitHub repository has been created and the files uploaded',
      s27_req_5: 'GitHub Pages has been enabled and the website is visible',
      s27_req_6: 'Clicking the button changes the text',
      s27_reference: 'Reference',
      s27_deadline: 'Deadline',
      s27_due: 'September 7 at 11:59 PM',
      s27_submit: 'Submit the following information through the LMS',
      s27_repo: 'GitHub repository URL',
      s27_pages: 'GitHub Pages URL',
      s28_title: 'Questions and Answers'
    }
  };
})();
