(function () {
  'use strict';

  window.LECTURE_CONTENT = {
    ko: {
      s01_eyebrow: '2026학년도 2학기 실전웹서비스개발',
      s01_title: '실전 웹서비스개발 – 1주차',
      s01_subtitle: '강의소개',
      s02_title: '강의 소개 및 운영 방식',
      s03_title: '강의 개요',
      s03_goal_label: '목표',
      s03_goal: '스스로 기획·개발한 웹서비스를 실제 사용자에게 선보이고 배포',
      s03_learning_label: '학습 내용',
      s03_learning: '웹 프로그래밍 기초 → 프론트엔드 → 서버 → 데이터베이스 → 보안 → AI 주도 개발 및 활용 → 배포와 운영',
      s03_result_label: '결과물',
      s03_result: '실무에 바로 쓸 수 있는 개인 포트폴리오 1개 완성',
      s04_title: '강사 소개',
      s04_meta: '오현석 00 학번 / 개발경력 23년',
      s04_career_label: '경력',
      s04_item_1: '現 아주대학교 디지털미디어학과 겸임교수',
      s04_item_2: '現 (주)트리플엔게임즈 대표',
      s04_item_3: '前 (주)원밀리언 CTO',
      s04_item_4: '前 (주)우아한형제들 시니어 엔지니어',
      s04_item_5: '前 스노우(주) 시니어 엔지니어',
      s04_web_alt: '웹 서비스 포트폴리오',
      s04_app_alt: '모바일 앱 포트폴리오',
      s04_game_alt: '게임 포트폴리오',
      s05_title: '수업 진행 방식',
      s05_lead: '이론 + 실습(과제) + 프로젝트(발표)',
      s05_weekly_label: '매주 (3시간)',
      s05_theory: '이론 (1 ~ 2시간) — 강의를 통해 학습 목표와 실습에 필요한 핵심 개념 설명',
      s05_practice: '실습 (개별 1 ~ 2시간) — 직접 AI 서비스와 질의응답을 하며 학습 목표 달성을 위한 실습 진행 · 다음 주 수업 전까지 결과 제출',
      s05_project_label: '프로젝트 (발표 3회)',
      s05_project_intro: '결과 웹 사이트 링크와 깃허브 저장소 링크 제출',
      s05_project_submission: '발표는 동영상 촬영 후 YouTube에 업로드하여 링크 제출',
      s05_milestone_1: '기획 발표 — 9월 28일 마감 · YouTube 영상',
      s05_milestone_2: '중간 발표 — 11월 2일 마감 · YouTube 영상 · 결과 웹 사이트 링크',
      s05_milestone_3: '기말 발표 — 12월 14일 마감 · YouTube 영상 · 결과 웹 사이트 링크 · 깃허브 저장소 링크',
      s05_final_label: '기말고사',
      s05_final_1: '이론 시험 (클로즈드북 · 서술형 · 필기)',
      s05_final_2: '이론과 실습을 통해 학습한 내용을 프로젝트에 적용하며 실제 자신의 지식으로 만들었는지 검증',
      s06_title: '주차별 학습 내용',
      s06_head_week: '회차',
      s06_head_date: '날짜',
      s06_head_topic: '학습 내용',
      s06_week_01: '2026 웹서비스 개발 개요',
      s06_week_02: 'HTML / CSS / JS / Web 기본',
      s06_week_03: 'JavaScript → TypeScript',
      s06_week_04: 'React + Vite',
      s06_week_05: 'UI/UX + Responsive',
      s06_week_06: 'Backend + REST API',
      s06_week_07: 'Database + Authentication',
      s06_week_08: 'Full Stack Integration',
      s06_week_09: 'Deployment',
      s06_week_10: 'AI Web Service',
      s06_week_11: 'AI Coding Agent',
      s06_week_12: 'Test / Security / Quality',
      s06_week_13: '운영 / Final Review',
      s06_phase_1_label: '1 ~ 7 주차',
      s06_phase_1: '웹 프론트엔드 → 서버 → 데이터베이스 → AI 연동 → 배포에 필요한 개발 기술 학습',
      s06_phase_2_label: '8주차',
      s06_phase_2: '중간고사 (1 ~ 7 주차 핵심 개념 평가 - 서술형, 손코딩)',
      s06_phase_3_label: '9 ~ 10 주차',
      s06_phase_3_1: '웹 서비스 기획',
      s06_phase_3_2: '최신 AI 서비스, OpenAI API 연동',
      s06_phase_4_label: '11 주차',
      s06_phase_4: '프로젝트 제안 발표 (5분 스피치) + 제안서 제출',
      s06_phase_5_label: '12 ~ 14 주차',
      s06_phase_5: 'AI 연동 활용 서비스 제작 강의',
      s06_phase_6_label: '15 ~ 16 주차',
      s06_phase_6_1: '프로젝트 진행 상황 또는 결과 발표 (10분 + 데모 시연)',
      s06_phase_6_2: '기말고사 기간 종료 전까지 - 코드 제출 및 개발 보고서 작성 후 제출',
      s07_title: '평가',
      s07_participation: '참여 점수 (50 %)',
      s07_attendance: '출석 - 10%',
      s07_assignments: '과제 - 20%',
      s07_presentation: '프로젝트 결과물 - 20%',
      s07_performance: '수행 점수 (50 %)',
      s07_midterm: '기말고사 - 30%',
      s07_project: '프로젝트 성과 평가 - 20%',
      s07_note: '※ 학교 규정에 따라 점수 총합 순위를 기준으로 학점 산정',
      s07_group: '평가 분할: 소프트웨어융합대학 계열 / 소프트웨어융합대학 계열 외',
      s07_ratio: '평가 비율: A+ ~ A0 40% · A+ ~ B0 90% · C+ ~ F 10%',
      s08_title: '학습 기술 스택',
      s08_tools_label: 'Tools',
      s08_tools: 'VS Code',
      s08_web_label: 'Web',
      s08_web: 'HTML5 · CSS3 · JavaScript (ES6+) · TypeScript',
      s08_frontend_label: 'Frontend',
      s08_frontend: 'React · Vercel',
      s08_backend_label: 'Backend',
      s08_backend: 'Node.js · Express',
      s08_database_label: 'Database',
      s08_database: 'PostgreSQL · Supabase',
      s08_ai_label: 'AI',
      s08_ai: 'Claude Code · Open Code · Codex',
      s08_etc_label: 'Etc',
      s08_etc: 'Git · GitHub · Vite',
      s09_title: '질문과 답변',
      s10_title: '웹서비스 개요 및 개발 흐름',
      s11_title: '웹서비스란 무엇인가?',
      s11_standard: '기술 표준 정의 (W3C Web Services Architecture, 2004)',
      s11_definition: '네트워크에서 상호운용 가능한 시스템 간 상호작용을 지원하도록 설계된 소프트웨어 시스템',
      s11_w3c: 'W3C: 팀 버너스리가 중심이 되어 1994년 설립된 웹 기술 국제 표준화 공동체',
      s12_title: '웹서비스의 일반적 의미와 형태',
      s12_broad: '넓은 의미(일반적 정의)',
      s12_broad_1: '인터넷을 통해 제공되는 모든 형태의 서비스',
      s12_broad_2: '웹 브라우저나 앱을 통해 사용자에게 콘텐츠·기능을 제공',
      s12_kinds: '종류',
      s13_title: '정적 웹페이지(Static Web Page)',
      s13_item_1: '서버에 미리 생성된 HTML·CSS·JavaScript·이미지 파일을 저장',
      s13_item_2: '사용자 요청 시 저장된 파일을 그대로 전달',
      s13_item_3: '서버가 요청마다 페이지 내용을 새로 생성하지 않음',
      s13_item_4: '콘텐츠 변경 시 파일을 다시 생성하거나 수정하여 배포',
      s13_item_5: 'JavaScript 화면 동작과 외부 API 사용 가능',
      s13_example: 'Ex) 회사 소개 페이지, 포트폴리오, 문서 사이트, GitHub Pages',
      s13_image_alt: '정적 웹페이지 예시 화면',
      s14_title: '동적 웹페이지 (Dynamic Web Page)',
      s14_item_1: '사용자·시간·저장된 데이터에 따라 표시 내용이 달라지는 웹페이지',
      s14_item_2: '서버가 요청에 맞는 HTML을 생성하여 전달하는 방식',
      s14_item_3: '브라우저가 API로 데이터를 받아 화면 일부를 변경하는 방식',
      s14_item_4: '데이터 변경 내용을 페이지 새로고침 또는 화면 갱신으로 반영',
      s14_example: 'Ex) 게시판 목록, 쇼핑몰 상품 페이지, 검색 결과, 날씨 조회',
      s14_image_alt: '동적 웹페이지 예시 화면',
      s15_title: '웹앱(Web Application)',
      s15_item_1: '웹 브라우저를 통해 사용자가 특정 작업을 수행할 수 있도록 만든 응용 소프트웨어',
      s15_item_2: '입력·검색·편집·저장 등 사용자 동작에 따라 화면과 상태가 변경',
      s15_item_3: '필요한 데이터를 서버의 API에 요청하고, 처리 결과를 응답받아 화면에 반영',
      s15_item_4: '전체 페이지를 다시 불러오지 않고 필요한 부분만 갱신 가능',
      s15_example: 'Ex) Gmail, Google Docs, Figma, Notion, NotebookLM',
      s15_image_alt: '웹 애플리케이션 예시 화면',
      s16_title: '클라이언트-서버 모델',
      s16_lead: '네트워크에서 서비스를 요청하는 클라이언트와 요청을 처리해 응답하는 서버가 역할을 나누는 구조',
      s16_client_label: 'Client(클라이언트)',
      s16_client_role: '서비스를 이용하기 위해 서버에 요청을 보내고 응답을 받는 소프트웨어',
      s16_server_label: 'Server(서버)',
      s16_server_role: '클라이언트의 요청을 처리하고 결과를 응답하는 소프트웨어',
      s16_database_label: 'Database(데이터베이스)',
      s16_database_role: '서비스 데이터를 구조적으로 저장하고 조회·변경하는 시스템',
      s16_http_request: 'Request(요청) →',
      s16_request_definition: '자원이나 처리를 요구하는 메시지',
      s16_http_response: '← Response(응답)',
      s16_response_definition: '처리 상태와 결과를 담은 메시지',
      s16_data_request: '조회·저장 →',
      s16_data_result: '← 데이터',
      s16_network_label: 'Network(네트워크)',
      s16_network_definition: '컴퓨터와 장치가 데이터를 주고받도록 연결된 통신 환경',
      s16_protocol_label: 'Protocol(프로토콜)',
      s16_protocol_definition: '네트워크 통신에서 데이터 교환 방법과 형식을 정한 규칙',
      s16_http_definition: '웹에서 클라이언트와 서버가 요청과 응답을 주고받기 위한 프로토콜',
      s17_title: 'Client(클라이언트)',
      s17_lead: '네트워크를 통해 서버에 서비스나 자원을 요청하고 응답을 받아 사용하는 소프트웨어 또는 장치',
      s17_role_title: '웹서비스에서의 역할',
      s17_role_1: '서버에 HTTP 요청 전송',
      s17_role_2: '서버의 HTTP 응답 수신',
      s17_role_3: '받은 데이터와 자원을 사용하여 서비스 기능 제공',
      s17_type_title: '클라이언트의 종류',
      s17_type_browser: ' — Chrome, Edge, Safari, Firefox, Whale',
      s17_type_app: ' — Web API를 이용하는 응용 프로그램',
      s17_type_program: ' — 다른 서버, 자동화 도구, IoT 장치 등',
      s17_image_alt: '2026년 8월 세계 웹브라우저 시장 점유율',
      s17_image_caption: '2026년 8월 웹브라우저 시장 점유율',
      s18_title: 'Server(서버)',
      s18_lead: '네트워크를 통해 클라이언트의 요청을 받고, 요청을 처리한 결과를 응답하는 소프트웨어 또는 컴퓨터',
      s18_client_role: '서비스 또는 자원 요청',
      s18_request_label: 'HTTP Request(HTTP 요청) →',
      s18_request_definition: '서버에 자원이나 처리를 요구하는 메시지',
      s18_response_label: '← HTTP Response(HTTP 응답)',
      s18_response_definition: '처리 상태와 결과를 클라이언트에 전달하는 메시지',
      s18_status_label: 'Status Code(상태 코드)',
      s18_status_definition: '처리 결과를 나타내는 숫자',
      s18_step_1_label: '1. 요청 수신·확인',
      s18_item_1: 'URL·HTTP Method·입력 데이터·권한 확인',
      s18_business_logic_label: '2. Business Logic(비즈니스 로직)',
      s18_business_logic_definition: '서비스의 기능과 처리 규칙을 코드로 구현한 부분',
      s18_step_3_label: '3. 응답 생성',
      s18_item_3: '처리 상태와 결과 데이터를 HTTP 응답으로 구성',
      s18_data_request: '조회·저장 →',
      s18_data_result: '← 데이터',
      s18_database_role: '서비스 데이터 저장·조회·변경',
      s18_login_label: '로그인 예시',
      s18_login_flow: '로그인 요청 → 입력값 확인 → 인증 정보 조회·검증 → 상태 코드와 로그인 결과 응답',
      s19_db_title: 'Database(데이터베이스)',
      s19_db_lead: '서로 관련된 데이터를 구조화하여 저장하고 필요할 때 조회·변경할 수 있도록 구성한 데이터 집합',
      s19_db_server_role: '서비스 처리에 필요한 데이터 요청',
      s19_db_query_label: 'Query(쿼리) →',
      s19_db_query_definition: '데이터의 조회나 변경을 DBMS에 요청하는 명령',
      s19_db_result_label: '← Result(결과)',
      s19_db_result_definition: '요청에 따라 조회되거나 변경된 결과',
      s19_db_dbms_definition: '데이터베이스를 생성하고 데이터를 조회·저장·변경하도록 관리하는 소프트웨어',
      s19_db_create: '생성',
      s19_db_read: '조회',
      s19_db_update: '수정',
      s19_db_delete: '삭제',
      s19_db_storage_request: '저장·조회 →',
      s19_db_storage_result: '← 데이터',
      s19_db_database_role: '서비스가 종료되어도 데이터를 지속적으로 보관',
      s19_db_postgresql: '관계형 DBMS',
      s19_db_supabase: 'PostgreSQL 기반 백엔드 플랫폼',
      s20_http_lead: '웹에서 클라이언트와 서버가 요청과 응답 메시지를 주고받기 위한 통신 규약',
      s20_http_client: '날씨 정보 요청',
      s20_http_request: 'HTTP Request(요청) →',
      s20_http_method_label: 'HTTP Method',
      s20_http_method_definition: '서버에 요청하는 작업의 종류',
      s20_http_response: '← HTTP Response(응답)',
      s20_http_status_label: 'Status Code',
      s20_http_status_definition: '요청 처리 결과를 나타내는 세 자리 숫자',
      s20_http_json_definition: '데이터를 표현하고 교환하는 텍스트 형식',
      s20_http_api_definition: 'HTTP 요청을 받아 기능을 수행하고 결과를 응답하는 인터페이스',
      s20_http_methods_title: '주요 HTTP Method',
      s20_http_get: '조회',
      s20_http_post: '전달·처리/생성',
      s20_http_put: '전체 생성·교체',
      s20_http_patch: '일부 수정',
      s20_http_delete: '삭제',
      s20_http_statuses_title: 'Status Code 범주',
      s20_http_2xx: '성공 · 200',
      s20_http_3xx: '리다이렉션 · 302',
      s20_http_4xx: '요청 오류 · 404',
      s20_http_5xx: '서버 오류 · 500',
      s21_title: 'AI 시대의 웹서비스 개발',
      s21_lead: '담당 영역은 전문화되어도 서비스 전체에 대한 이해와 AI 활용·검증 역량은 공통 요구',
      s21_experience_title: '사용자 경험',
      s21_experience_role: '화면과 사용자 상호작용 구현',
      s21_experience_job: '프론트엔드 개발자',
      s21_service_title: '서비스와 데이터',
      s21_service_role: '요청 처리, 비즈니스 로직, Web API와 데이터 관리',
      s21_service_job: '백엔드 · 서버 개발자',
      s21_operations_title: '배포와 운영',
      s21_operations_role: '서비스 배포와 안정적인 운영',
      s21_operations_job: '플랫폼·서비스 운영 개발자',
      s21_common_title: '모든 개발 영역의 공통 역량',
      s21_ai_label: 'AI 활용',
      s21_ai_tasks: '설계 · 코드 작성 · 테스트 · 디버깅 · 문서화 지원',
      s21_responsibility_label: '개발자 책임',
      s21_responsibility_tasks: '요구사항 판단 · 결과 검증 · 보안 · 품질 · 최종 책임',
      s22_title: '전체 흐름 정리: www.naver.com 입력부터 화면 표시까지',
      s22_lead: 'DNS로 IP 주소 확인 → TCP 연결 → HTTP 요청·응답 → 브라우저 화면 구성',
      s22_step_1_label: 'URL 분석',
      s22_item_1: '입력한 URL에서 도메인과 요청 경로 확인',
      s22_step_2_label: 'DNS 조회',
      s22_item_2: '도메인 이름에 대응하는 서버의 IP 주소 확인',
      s22_step_3_label: 'TCP 연결',
      s22_item_3: 'IP 주소를 이용해 서버와 TCP 연결 수립',
      s22_step_4_label: 'HTTP 요청·응답',
      s22_item_4: '브라우저가 HTTP 요청을 보내고 서버가 상태 코드와 데이터 응답',
      s22_step_5_label: '브라우저 렌더링',
      s22_item_5: 'HTML, CSS, JavaScript와 이미지 등을 해석하여 화면 구성',
      s22_image_alt: '웹 주소 입력부터 화면 표시까지의 5단계 흐름 그림',
      s22_image_caption: 'URL → DNS → IP → TCP → HTTP → Rendering',
      s22_url_definition: '인터넷 자원의 위치와 접근 방법을 나타내는 주소',
      s22_dns_definition: '도메인 이름을 IP 주소로 변환하는 시스템',
      s22_ip_definition: '네트워크에서 목적지를 식별하는 주소 체계',
      s22_tcp_definition: '데이터를 순서대로 안정적으로 전달하는 전송 방식',
      s22_http_definition: '웹 자원을 요청하고 응답하기 위한 통신 규약',
      s22_dns_example_label: 'DNS 조회 예시 (2026.09.04)',
      s22_dns_example: 'www.naver.com → 223.130.200.219 · 223.130.192.248 · 223.130.192.247 · 223.130.200.236',
      s22_transport_note: '※ DNS 조회 결과는 시점과 네트워크 환경에 따라 변경 가능 · TCP 연결 단계는 HTTP/1.1·HTTP/2 기준',
      s23_title: '웹 서비스 개발 환경 준비',
      s24_lead: '마이크로소프트가 개발한 무료 소스 코드 편집기',
      s24_features: '웹서비스 개발 작업 공간',
      s24_item_1: '소스 코드 작성과 프로젝트 파일 관리',
      s24_item_2: '통합 터미널을 통한 개발 명령 실행',
      s24_item_3: '확장 기능을 통한 언어·도구 지원',
      s24_item_4: 'Git·디버깅·AI 개발 도구 연동',
      s24_ui_explorer: '파일 탐색기',
      s24_ui_editor: '코드 편집기',
      s24_ui_terminal: '통합 터미널',
      s24_image_alt: 'Visual Studio Code 화면',
      s25_title: 'Git과 GitHub',
      s25_lead: 'Git으로 변경 이력을 관리하고 GitHub에서 저장소를 공유',
      s25_git_lead: '소스 코드의 변경 이력을 기록하고 관리하는 분산 버전 관리 시스템',
      s25_git_1: '변경 내용 기록',
      s25_git_2: '이전 상태 확인과 복구',
      s25_git_3: '여러 개발자의 변경 내용 통합',
      s25_github_lead: 'Git 저장소를 온라인에 저장하고 공유하는 개발 협업 플랫폼',
      s25_gh_1: '원격 저장소 제공',
      s25_gh_2: '코드 공유와 협업',
      s25_gh_3: 'GitHub Pages를 통한 웹사이트 공개',
      s25_relation: 'Git 저장소 공유',
      s25_cli: '터미널에서 GitHub 로그인과 저장소 작업을 수행하는 공식 명령줄 도구',
      s26_title: '과제: GitHub Pages 웹사이트 제작',
      s27_title: '과제 개요',
      s27_overview: 'GitHub Pages를 활용하여 웹사이트를 제작하고 배포',
      s27_learning: '학습 목표',
      s27_learning_1: '웹 서비스 개발 환경 구축',
      s27_learning_2: 'Git 기본 명령어 및 GitHub 저장소 관리 능력 습득',
      s27_learning_3: 'GitHub Pages를 통한 웹 호스팅 프로세스 경험',
      s27_requirements: '요구사항',
      s27_req_1: 'Git, GitHub CLI, VS Code 모두 설치됨',
      s27_req_2: 'GitHub 계정이 생성되고 로그인됨',
      s27_req_3: 'index.html, style.css, script.js 파일이 모두 작성됨',
      s27_req_4: 'GitHub 저장소가 생성되고 파일들이 업로드됨',
      s27_req_5: 'GitHub Pages가 활성화되어 웹사이트가 보임',
      s27_req_6: '버튼 클릭 시 텍스트가 변경됨',
      s27_reference: '참고',
      s27_deadline: '마감일',
      s27_due: '9월 13일 23:59까지',
      s27_submit: 'LMS에 다음 정보를 제출',
      s27_repo: 'GitHub 저장소 URL',
      s27_pages: 'GitHub Pages URL',
      s28_title: '질문과 답변'
    },
    en: {
      s01_eyebrow: 'Practical Web Service Development · Fall 2025',
      s01_title: 'Practical Web Service Development – Week 1',
      s01_subtitle: 'Course Introduction',
      s02_title: 'Course Introduction and Operation',
      s03_title: 'Course Overview',
      s03_goal_label: 'Goal',
      s03_goal: 'Plan, build, and release your own web service to the public',
      s03_learning_label: 'What You Will Learn',
      s03_learning: 'Web programming fundamentals → Front end → Server → Database → Security → AI-driven development & usage → Deployment & operations',
      s03_result_label: 'Outcome',
      s03_result: 'Complete one practical personal portfolio project',
      s04_title: 'Instructor',
      s04_meta: 'Hyunseok Oh · Class of 2000 · 23 years of development experience',
      s04_career_label: 'Experience',
      s04_item_1: 'Current Adjunct Professor, Department of Digital Media, Ajou University',
      s04_item_2: 'Current CEO, NNN Games',
      s04_item_3: 'Former CTO, 1MILLION',
      s04_item_4: 'Former Senior Engineer, Woowa Brothers',
      s04_item_5: 'Former Senior Engineer, SNOW',
      s04_web_alt: 'Web service portfolio',
      s04_app_alt: 'Mobile app portfolio',
      s04_game_alt: 'Game portfolio',
      s05_title: 'Class Format',
      s05_lead: 'Theory + Practice (Assignments) + Project (Presentations)',
      s05_weekly_label: 'Every Week (3 hours)',
      s05_theory: 'Theory (1–2 hours) — Lectures explain learning goals and the core concepts needed for practice',
      s05_practice: 'Practice (Individual, 1–2 hours) — Work directly with AI services through questions and answers to achieve the learning goals · Submit results before the following class',
      s05_project_label: 'Project (3 Presentations)',
      s05_project_intro: 'Submit the result website link and GitHub repository link',
      s05_project_submission: 'Record presentations, upload them to YouTube, and submit the link',
      s05_milestone_1: 'Planning presentation — Due September 28 · YouTube video',
      s05_milestone_2: 'Midterm presentation — Due November 2 · YouTube video · result website link',
      s05_milestone_3: 'Final presentation — Due December 14 · YouTube video · result website link · GitHub repository link',
      s05_final_label: 'Final Exam',
      s05_final_1: 'Theory exam (closed-book · written response · handwritten)',
      s05_final_2: 'Verify that knowledge learned through theory and practice has been made one’s own by applying it in the project',
      s06_title: 'Weekly Learning Content',
      s06_head_week: 'Session',
      s06_head_date: 'Date',
      s06_head_topic: 'Topic',
      s06_week_01: 'Web Service Development Overview for 2026',
      s06_week_02: 'HTML, CSS, JavaScript & Web Fundamentals',
      s06_week_03: 'JavaScript → TypeScript',
      s06_week_04: 'React + Vite',
      s06_week_05: 'UI/UX & Responsive Design',
      s06_week_06: 'Backend & REST APIs',
      s06_week_07: 'Database & Authentication',
      s06_week_08: 'Full Stack Integration',
      s06_week_09: 'Deployment',
      s06_week_10: 'AI Web Service',
      s06_week_11: 'AI Coding Agent',
      s06_week_12: 'Testing, Security & Quality',
      s06_week_13: 'Operations & Final Review',
      s06_phase_1_label: 'Weeks 1–7',
      s06_phase_1: 'Learn development technologies required for the web front end → server → database → AI integration → deployment',
      s06_phase_2_label: 'Week 8',
      s06_phase_2: 'Midterm exam (assessment of key concepts from Weeks 1–7 — written answers and handwritten code)',
      s06_phase_3_label: 'Weeks 9–10',
      s06_phase_3_1: 'Web service planning',
      s06_phase_3_2: 'Latest AI services and OpenAI API integration',
      s06_phase_4_label: 'Week 11',
      s06_phase_4: 'Project proposal presentation (5-minute speech) + proposal submission',
      s06_phase_5_label: 'Weeks 12–14',
      s06_phase_5: 'Lectures on building services that use AI integration',
      s06_phase_6_label: 'Weeks 15–16',
      s06_phase_6_1: 'Project progress or result presentation (10 minutes + live demo)',
      s06_phase_6_2: 'Submit code and a development report before the final exam period ends',
      s07_title: 'Assessment',
      s07_participation: 'Participation (50%)',
      s07_attendance: 'Attendance — 10%',
      s07_assignments: 'Assignments — 20%',
      s07_presentation: 'Project deliverable — 20%',
      s07_performance: 'Performance (50%)',
      s07_midterm: 'Final exam — 30%',
      s07_project: 'Project performance evaluation — 20%',
      s07_note: '※ Grades are assigned by total-score ranking in accordance with university regulations.',
      s07_group: 'Evaluation groups: College of Software Convergence majors / non-majors',
      s07_ratio: 'Evaluation ratio: A+–A0 40% · A+–B0 90% · C+–F 10%',
      s08_title: 'Technology Stack',
      s08_tools_label: 'Tools',
      s08_tools: 'VS Code',
      s08_web_label: 'Web',
      s08_web: 'HTML5 · CSS3 · JavaScript (ES6+) · TypeScript',
      s08_frontend_label: 'Frontend',
      s08_frontend: 'React · Vercel',
      s08_backend_label: 'Backend',
      s08_backend: 'Node.js · Express',
      s08_database_label: 'Database',
      s08_database: 'PostgreSQL · Supabase',
      s08_ai_label: 'AI',
      s08_ai: 'Claude Code · Open Code · Codex',
      s08_etc_label: 'Etc',
      s08_etc: 'Git · GitHub · Vite',
      s09_title: 'Questions and Answers',
      s10_title: 'Web Service Overview and Development Flow',
      s11_title: 'What Is a Web Service?',
      s11_standard: 'Technical Standard Definition (W3C Web Services Architecture, 2004)',
      s11_definition: 'A software system designed to support interoperable machine-to-machine interaction over a network',
      s11_w3c: 'W3C: An international web technology standards community founded in 1994 under the leadership of Tim Berners-Lee',
      s12_title: 'General Meaning and Forms of Web Services',
      s12_broad: 'Broad, General Definition',
      s12_broad_1: 'Any form of service provided through the Internet',
      s12_broad_2: 'Provides content and functionality to users through a web browser or app',
      s12_kinds: 'Types',
      s13_title: 'Static Web Page',
      s13_item_1: 'Store pre-generated HTML, CSS, JavaScript, image, and other files on the server',
      s13_item_2: 'Deliver the stored files as they are when a user requests them',
      s13_item_3: 'The server does not generate new page content for each request',
      s13_item_4: 'Regenerate or edit and redeploy files when content changes',
      s13_item_5: 'JavaScript interactions and external APIs can still be used',
      s13_example: 'Examples: Company profile pages, portfolios, documentation sites, and GitHub Pages',
      s13_image_alt: 'Example of a static web page',
      s14_title: 'Dynamic Web Page',
      s14_item_1: 'A web page whose displayed content changes according to the user, time, or stored data',
      s14_item_2: 'The server can generate HTML for a request and deliver it to the browser',
      s14_item_3: 'The browser can receive data from an API and update part of the screen',
      s14_item_4: 'Data changes appear through a page reload or an on-screen update',
      s14_example: 'Examples: Message-board lists, product pages, search results, and weather lookups',
      s14_image_alt: 'Example of a dynamic web page',
      s15_title: 'Web Application',
      s15_item_1: 'Application software designed to let users perform specific tasks through a web browser',
      s15_item_2: 'The screen and application state change as users enter, search, edit, and save information',
      s15_item_3: 'Requests required data from a server API and reflects the processed response on screen',
      s15_item_4: 'Can update only the required part without reloading the entire page',
      s15_example: 'Examples: Gmail, Google Docs, Figma, Notion, and NotebookLM',
      s15_image_alt: 'Example of a web application',
      s16_title: 'Client–Server Model',
      s16_lead: 'A structure in which clients request services over a network and servers process those requests and return responses',
      s16_client_label: 'Client',
      s16_client_role: 'Software that sends requests to a server and receives responses to use a service',
      s16_server_label: 'Server',
      s16_server_role: 'Software that processes client requests and returns the results as responses',
      s16_database_label: 'Database',
      s16_database_role: 'A system that stores service data in a structured form and supports retrieval and changes',
      s16_http_request: 'Request →',
      s16_request_definition: 'A message asking for a resource or operation',
      s16_http_response: '← Response',
      s16_response_definition: 'A message containing the processing status and result',
      s16_data_request: 'Read · Write →',
      s16_data_result: '← Data',
      s16_network_label: 'Network',
      s16_network_definition: 'A communication environment that connects computers and devices so they can exchange data',
      s16_protocol_label: 'Protocol',
      s16_protocol_definition: 'A set of rules defining how data is formatted and exchanged over a network',
      s16_http_definition: 'A protocol through which web clients and servers exchange requests and responses',
      s17_title: 'Client',
      s17_lead: 'Software or a device that requests services or resources from a server over a network and uses the response',
      s17_role_title: 'Role in a Web Service',
      s17_role_1: 'Send HTTP requests to a server',
      s17_role_2: 'Receive HTTP responses from the server',
      s17_role_3: 'Use the received data and resources to provide service functionality',
      s17_type_title: 'Types of Clients',
      s17_type_browser: ' — Chrome, Edge, Safari, Firefox, and Whale',
      s17_type_app: ' — Applications that use Web APIs',
      s17_type_program: ' — Other servers, automation tools, and IoT devices',
      s17_image_alt: 'Worldwide web browser market share in August 2026',
      s17_image_caption: 'Web browser market share, August 2026',
      s18_title: 'Server',
      s18_lead: 'Software or a computer that receives client requests over a network, processes them, and returns the results as responses',
      s18_client_role: 'Request a service or resource',
      s18_request_label: 'HTTP Request →',
      s18_request_definition: 'A message asking the server for a resource or operation',
      s18_response_label: '← HTTP Response',
      s18_response_definition: 'A message that delivers the processing status and result to the client',
      s18_status_label: 'Status Code',
      s18_status_definition: 'A number representing the processing result',
      s18_step_1_label: '1. Receive and Inspect',
      s18_item_1: 'Check the URL, HTTP method, input data, and permissions',
      s18_business_logic_label: '2. Business Logic',
      s18_business_logic_definition: 'Code that implements the features and processing rules of a service',
      s18_step_3_label: '3. Create Response',
      s18_item_3: 'Build an HTTP response containing the processing status and result data',
      s18_data_request: 'Read · Write →',
      s18_data_result: '← Data',
      s18_database_role: 'Store, retrieve, and change service data',
      s18_login_label: 'Login Example',
      s18_login_flow: 'Login request → Validate input → Retrieve and verify credentials → Return a status code and login result',
      s19_db_title: 'Database',
      s19_db_lead: 'A structured collection of related data designed for storage, retrieval, and modification when needed',
      s19_db_server_role: 'Request data required to process a service',
      s19_db_query_label: 'Query →',
      s19_db_query_definition: 'A command that asks a DBMS to retrieve or change data',
      s19_db_result_label: '← Result',
      s19_db_result_definition: 'Data retrieved or changed according to the request',
      s19_db_dbms_definition: 'Software that creates databases and manages data retrieval, storage, and modification',
      s19_db_create: 'Create',
      s19_db_read: 'Read',
      s19_db_update: 'Update',
      s19_db_delete: 'Delete',
      s19_db_storage_request: 'Store · Retrieve →',
      s19_db_storage_result: '← Data',
      s19_db_database_role: 'Persist data even when the service stops',
      s19_db_postgresql: 'Relational DBMS',
      s19_db_supabase: 'A backend platform built around PostgreSQL',
      s20_http_lead: 'A communication protocol through which web clients and servers exchange request and response messages',
      s20_http_client: 'Request weather information',
      s20_http_request: 'HTTP Request →',
      s20_http_method_label: 'HTTP Method',
      s20_http_method_definition: 'The type of operation requested from the server',
      s20_http_response: '← HTTP Response',
      s20_http_status_label: 'Status Code',
      s20_http_status_definition: 'A three-digit number representing the request result',
      s20_http_json_definition: 'A text format for representing and exchanging data',
      s20_http_api_definition: 'An interface that accepts HTTP requests, performs functions, and returns results',
      s20_http_methods_title: 'Common HTTP Methods',
      s20_http_get: 'Retrieve',
      s20_http_post: 'Submit · Process/Create',
      s20_http_put: 'Create/Replace All',
      s20_http_patch: 'Update Part',
      s20_http_delete: 'Delete',
      s20_http_statuses_title: 'Status Code Classes',
      s20_http_2xx: 'Success · 200',
      s20_http_3xx: 'Redirection · 302',
      s20_http_4xx: 'Request Error · 404',
      s20_http_5xx: 'Server Error · 500',
      s21_title: 'Web Service Development in the AI Era',
      s21_lead: 'Roles remain specialized, while end-to-end understanding and the ability to use and verify AI are shared requirements',
      s21_experience_title: 'User Experience',
      s21_experience_role: 'Build interfaces and user interactions',
      s21_experience_job: 'Frontend Developer',
      s21_service_title: 'Service and Data',
      s21_service_role: 'Manage requests, business logic, Web APIs, and data',
      s21_service_job: 'Backend · Server Developer',
      s21_operations_title: 'Deployment and Operations',
      s21_operations_role: 'Deploy services and operate them reliably',
      s21_operations_job: 'Platform · Service Operations Developer',
      s21_common_title: 'Shared Skills Across Every Development Area',
      s21_ai_label: 'AI Assistance',
      s21_ai_tasks: 'Design · Coding · Testing · Debugging · Documentation',
      s21_responsibility_label: 'Developer Responsibility',
      s21_responsibility_tasks: 'Requirements · Verification · Security · Quality · Final accountability',
      s22_title: 'Complete Flow: From Entering www.naver.com to Displaying the Page',
      s22_lead: 'Find the IP address with DNS → Establish a TCP connection → Exchange HTTP messages → Render the page',
      s22_step_1_label: 'Parse the URL',
      s22_item_1: 'Identify the domain and requested path in the URL',
      s22_step_2_label: 'DNS lookup',
      s22_item_2: 'Find the server IP address that corresponds to the domain name',
      s22_step_3_label: 'TCP connection',
      s22_item_3: 'Use the IP address to establish a TCP connection to the server',
      s22_step_4_label: 'HTTP request and response',
      s22_item_4: 'The browser sends an HTTP request; the server responds with a status code and data',
      s22_step_5_label: 'Browser rendering',
      s22_item_5: 'Interpret HTML, CSS, JavaScript, images, and other files to build the page',
      s22_image_alt: 'Five-step illustration from entering a web address to displaying the page',
      s22_image_caption: 'URL → DNS → IP → TCP → HTTP → Rendering',
      s22_url_definition: 'An address that identifies the location of an Internet resource and how to access it',
      s22_dns_definition: 'A system that translates a domain name into an IP address',
      s22_ip_definition: 'An addressing system that identifies a destination on a network',
      s22_tcp_definition: 'A transport method that delivers data reliably and in order',
      s22_http_definition: 'A protocol for requesting and responding with web resources',
      s22_dns_example_label: 'DNS lookup example (September 4, 2026)',
      s22_dns_example: 'www.naver.com → 223.130.200.219 · 223.130.192.248 · 223.130.192.247 · 223.130.200.236',
      s22_transport_note: '※ DNS results may vary by time and network · The TCP connection step describes HTTP/1.1 and HTTP/2',
      s23_title: 'Preparing the Web Service Development Environment',
      s24_lead: 'A free source code editor developed by Microsoft',
      s24_features: 'Web Service Development Workspace',
      s24_item_1: 'Write source code and manage project files',
      s24_item_2: 'Run development commands in the integrated terminal',
      s24_item_3: 'Add language and tool support through extensions',
      s24_item_4: 'Integrate Git, debugging, and AI development tools',
      s24_ui_explorer: 'File Explorer',
      s24_ui_editor: 'Code Editor',
      s24_ui_terminal: 'Integrated Terminal',
      s24_image_alt: 'Visual Studio Code interface',
      s25_title: 'Git and GitHub',
      s25_lead: 'Manage change history with Git and share repositories on GitHub',
      s25_git_lead: 'A distributed version control system that records and manages source code history',
      s25_git_1: 'Record changes',
      s25_git_2: 'Review and restore earlier states',
      s25_git_3: 'Merge changes from multiple developers',
      s25_github_lead: 'A development collaboration platform for storing and sharing Git repositories online',
      s25_gh_1: 'Host remote repositories',
      s25_gh_2: 'Share code and collaborate',
      s25_gh_3: 'Publish websites with GitHub Pages',
      s25_relation: 'Share Git Repository',
      s25_cli: 'The official command-line tool for GitHub sign-in and repository operations',
      s26_title: 'Assignment: Build a Website with GitHub Pages',
      s27_title: 'Assignment Overview',
      s27_overview: 'Build and deploy a website with GitHub Pages',
      s27_learning: 'Learning Goals',
      s27_learning_1: 'Set up a web service development environment',
      s27_learning_2: 'Learn basic Git commands and GitHub repository management',
      s27_learning_3: 'Experience the web hosting process with GitHub Pages',
      s27_requirements: 'Requirements',
      s27_req_1: 'Git, GitHub CLI, and VS Code are all installed',
      s27_req_2: 'A GitHub account has been created and signed in',
      s27_req_3: 'index.html, style.css, and script.js have all been written',
      s27_req_4: 'A GitHub repository has been created and the files uploaded',
      s27_req_5: 'GitHub Pages has been enabled and the website is visible',
      s27_req_6: 'Clicking the button changes the text',
      s27_reference: 'Reference',
      s27_deadline: 'Deadline',
      s27_due: 'September 13 at 11:59 PM',
      s27_submit: 'Submit the following information through the LMS',
      s27_repo: 'GitHub repository URL',
      s27_pages: 'GitHub Pages URL',
      s28_title: 'Questions and Answers'
    }
  };
})();
