const fs = require('node:fs');
const path = require('node:path');

const prismRoot = path.dirname(require.resolve('prismjs/package.json'));
const output = path.join(__dirname, '..', 'vendor', 'prism');
const languages = ['core', 'markup', 'css', 'clike', 'javascript', 'jsx', 'typescript', 'tsx', 'bash', 'json'];
const version = require('prismjs/package.json').version;
const source = languages.map((language) =>
  fs.readFileSync(path.join(prismRoot, 'components', 'prism-' + language + '.min.js'), 'utf8')
).join('\n');

fs.mkdirSync(output, { recursive: true });
fs.writeFileSync(path.join(output, 'prism.js'),
  '/* Prism ' + version + ' | MIT license: LICENSE | Generated by npm run vendor:code */\n' + source + '\n');
fs.copyFileSync(path.join(prismRoot, 'LICENSE'), path.join(output, 'LICENSE'));
console.log('Vendored Prism ' + version + ': ' + languages.join(', '));
