window.LECTURE_CONTENT = {
  ko: {
    'v2_browser-rendering_title': '웹 브라우저의 렌더링 원리',
    'v2_browser-rendering_lead': '코드의 요소·규칙이 문서 모델과 화면으로 바뀌는 과정',
    v2_render_html: 'HTML 파싱 → DOM 트리',
    v2_render_css: 'CSS 파싱 → CSSOM 트리',
    v2_render_tree: 'DOM + CSSOM → Render Tree',
    v2_render_layout: 'Layout (위치, 크기 계산)',
    v2_render_paint: 'Paint (픽셀로 그리기)',
    v2_render_diagram_alt: 'HTML → DOM, CSS → CSSOM, JavaScript의 DOM·CSSOM 변경, DOM·CSSOM → Render Tree → Layout → Paint',
    'v2_source-to-screen_title': '웹 브라우저 렌더링 과정',
    v2_dom_html: '<section class="profile">\n  <h1>자기소개</h1>\n  <p id="intro" aria-live="polite">웹 개발 학습 중</p>\n  <button id="change" type="button">소개 바꾸기</button>\n</section>',
    v2_dom_h1: '자기소개',
    v2_dom_text: '#text: 웹 개발 학습 중',
    v2_dom_button: '#text: 소개 바꾸기',
    v2_dom_target: 'p#intro가 화면의 소개 문단에 대응',
    v2_dom_visible_alt: '화면의 문단',
    v2_dom_visible: '화면의 문단',
    'v2_dom-nodes_title': 'DOM (Document Object Model)',
    'v2_dom-nodes_lead': 'HTML 문서를 객체 트리로 표현하고, 프로그램이 문서의 구조와 내용을 읽고 변경할 수 있게 하는 인터페이스',
    v2_css_rules: 'body {\n  color: #333;\n}\nbutton {\n  background: #1f6b4a;\n}\nbutton:hover {\n  background: #174f37;\n}',
    v2_css_sheet: 'CSSOM · style.css',
    v2_css_rule_fields: '선택자와 선언(속성·값)으로 구성된 규칙 객체',
    v2_css_matching_title: '매칭 (Matching)',
    v2_css_matching_definition: '선택자 조건을 만족하는 요소를 찾는 과정',
    v2_css_matching_example: '마우스를 올린 버튼 → button · button:hover 모두 해당',
    v2_css_cascade_title: '캐스케이드 (Cascade)',
    v2_css_cascade_definition: '같은 요소·속성에 겹치는 선언 중 우선순위로 적용값 결정',
    v2_css_cascade_example: '이 예제에서는 더 구체적인 button:hover의 배경색 #174f37 적용',
    v2_css_inheritance_title: '상속 (Inheritance)',
    v2_css_inheritance_definition: 'color처럼 상속되는 속성에 선언이 없으면 부모 요소의 값 사용',
    v2_css_inheritance_example: 'color를 지정하지 않은 p → body의 글자색 #333 상속',
    'v2_css-rule-objects_title': 'CSSOM (CSS Object Model)',
    'v2_css-rule-objects_lead': 'CSS 스타일시트와 규칙을 객체로 표현하고, 프로그램이 이를 읽고 변경할 수 있게 하는 인터페이스',
    v2_render_dom_title: 'DOM · 요소와 내용',
    v2_render_heading_text: '자기소개',
    v2_render_paragraph_text: '웹 개발 학습 중',
    v2_render_button_text: '소개 바꾸기',
    v2_render_cssom_title: 'CSSOM · 스타일 규칙',
    v2_render_result_title: 'Render Tree',
    v2_render_scope: 'portfolio/about.html · portfolio/style.css — 자기소개 영역의 주요 요소·스타일',
    'v2_rendering-box-tree_title': '렌더 트리 (Render Tree)',
    'v2_rendering-box-tree_lead': 'DOM의 요소에 CSSOM의 스타일을 반영해, 화면에 그릴 대상을 구성한 트리',
    v2_layout_css: '* {\n  box-sizing: border-box;\n}\n\n.profile {\n  width: 360px;\n  max-width: 100%;\n  padding: 24px;\n  background: #f0f3ef;\n  border-radius: 8px;\n}',
    v2_layout_measure: '실측: 카드 안의 버튼 위치 · 좌표 원점은 카드의 왼쪽 위',
    v2_layout_heading: '자기소개',
    v2_layout_text: '나의 첫 웹사이트 제작 중',
    v2_layout_equation: 'border-box · 360 − 24 − 24 = 콘텐츠 폭 312px · 테두리 없음',
    'v2_layout-geometry_title': '레이아웃: 위치와 크기 계산',
    'v2_layout-geometry_lead': 'CSS 값이 실제 박스의 치수와 자식 요소의 위치를 결정',
    v2_paint_css: '.profile {\n  background: #f0f3ef;\n}\n\nbutton {\n  background: #1f6b4a;\n  color: white;\n}',
    v2_paint_screen_alt: '① 카드 배경 · ② 버튼 배경 · ③ 버튼 글자',
    v2_paint_screen: '① 카드 배경 · ② 버튼 배경 · ③ 버튼 글자',
    v2_layer_heading: '자기소개',
    v2_layer_text: '웹 개발 학습 중',
    v2_layer_button: '소개 바꾸기',
    v2_paint_frame: '합성된 최종 화면',
    v2_paint_note: '레이어 경계는 DOM 태그와 1:1 관계가 아님 · 아래 레이어 표현은 개념도',
    'v2_paint-composite_title': '페인트',
    'v2_paint-composite_lead': '레이아웃에서 계산한 위치와 크기에 따라 요소의 배경·글자·테두리를 그리는 과정',
    w2_original_rendering_methods_csr_flow: 'HTML 골격 → JavaScript → 브라우저에서 UI 생성',
    w2_original_rendering_methods_csr_points0: '실행 후 상태 변경에 따라 화면 갱신',
    w2_original_rendering_methods_csr_points1: '초기 콘텐츠 표시에 JavaScript 다운로드·실행 필요',
    w2_original_rendering_methods_csr_points2: '검색 처리 시 JavaScript 렌더링 지원·실행 비용 고려',
    w2_original_rendering_methods_csr_use: '용례: 상호작용이 많은 피드·대시보드',
    w2_original_rendering_methods_csr: 'CSR · 클라이언트 렌더링',
    w2_original_rendering_methods_ssr_flow: '요청 → 서버에서 HTML 생성 → 브라우저에 제공',
    w2_original_rendering_methods_ssr_points0: '초기 응답에 주요 콘텐츠 포함',
    w2_original_rendering_methods_ssr_points1: '서버 처리 시간·부하·캐시 전략 고려',
    w2_original_rendering_methods_ssr_points2: '화면 표시와 상호작용 준비 시점은 다를 수 있음',
    w2_original_rendering_methods_ssr_use: '용례: 요청 시점의 데이터가 필요한 페이지',
    w2_original_rendering_methods_ssr: 'SSR · 서버 렌더링',
    w2_original_rendering_methods_ssg_flow: '빌드 시 HTML 생성 → 정적 파일 제공',
    w2_original_rendering_methods_ssg_points0: '요청마다 HTML을 생성할 필요 없음',
    w2_original_rendering_methods_ssg_points1: 'CDN 캐싱에 적합 · CDN은 필수 조건이 아님',
    w2_original_rendering_methods_ssg_points2: '미리 생성한 콘텐츠 변경에는 재생성 필요',
    w2_original_rendering_methods_ssg_use: '용례: 문서·블로그·마케팅 페이지',
    w2_original_rendering_methods_ssg: 'SSG · 정적 사이트 생성',
    w2_original_rendering_methods_combine: 'SSR·SSG의 초기 HTML과 클라이언트 갱신을 조합 가능 · 속도와 SEO는 코드·콘텐츠·네트워크·캐시에도 좌우됨',
    'v2_original-rendering-methods_title': '웹 브라우저 렌더링 방식',
    'v2_original-rendering-methods_lead': '주요 콘텐츠를 생성하는 위치와 시점의 차이',
    w2_original_rendering_performance_lcp: 'LCP · Largest Contentful Paint',
    w2_original_rendering_performance_lcp_body: '뷰포트 안의 가장 큰 이미지·텍스트 콘텐츠가 표시되는 시점 · 로딩 성능',
    w2_original_rendering_performance_inp: 'INP · Interaction to Next Paint',
    w2_original_rendering_performance_inp_body: '클릭·탭·키보드 입력부터 다음 화면 표시까지의 지연을 바탕으로 상호작용 응답성 평가',
    w2_original_rendering_performance_cls: 'CLS · Cumulative Layout Shift',
    w2_original_rendering_performance_cls_body: '페이지 이용 중 예기치 않은 레이아웃 이동 점수 · 세션 윈도 합계 중 최댓값',
    w2_original_rendering_performance_fcp: 'FCP는 첫 텍스트·이미지 등의 표시 시점인 보조 로딩 지표',
    w2_original_rendering_performance_vitals: 'Core Web Vitals · LCP / INP / CLS',
    w2_original_rendering_performance_study: 'Google/SOASTA 모바일 연구 · 2017년 · 1초 로딩 대비 상대 증가',
    w2_original_rendering_performance_load: '로딩 시간 변화',
    w2_original_rendering_performance_increase: '이탈 확률 증가',
    w2_original_rendering_performance_relative: '절대 이탈률이 아닌 상대 증가율 · 모든 사이트에 같은 값이 적용되는 법칙이 아님',
    w2_original_rendering_performance_seo: '성능 개선은 사용자 경험과 검색 품질에 도움 · 특정 검색 순위나 전환율을 보장하지 않음',
    w2_original_rendering_performance_bounce: '로딩 지연과 이탈 확률',
    'v2_original-rendering-performance_title': '웹 브라우저 렌더링 성능',
    'v2_original-rendering-performance_lead': '로딩·상호작용·화면 안정성이 사용자 경험에 미치는 영향',
    'v2_routing-semantic-html_title': '시맨틱 HTML과 라우팅',
    c3_sem_structure: '요소가 전달하는 문서의 역할',
    c3_tag_header: '문서·구역의 소개',
    c3_tag_nav: '주요 탐색 링크',
    c3_tag_main: '페이지의 주요 콘텐츠',
    c3_tag_article: '독립적으로 이해할 수 있는 콘텐츠',
    c3_tag_aside: '주변 콘텐츠에 부수적으로 관련된 내용',
    c3_tag_footer: '문서·구역의 작성자·저작권 등',
    c3_div: 'div는 의미가 정해지지 않은 컨테이너다. class="nav"만으로 탐색 영역의 의미가 생기지는 않는다.',
    c3_search_understanding: '검색엔진의 콘텐츠 이해',
    c3_search_semantics: '검색엔진은 콘텐츠와 HTML 구조를 분석하며, 의미에 맞는 요소는 문서의 역할을 전달하는 데 도움을 준다.',
    c3_crawl: '크롤링\n페이지 수집',
    c3_index: '인덱싱\n분석·색인 저장',
    c3_rank: '검색 요청\n결과 선택·순위 결정',
    c3_ax_title: '접근성 트리',
    c3_ax_definition: '브라우저가 DOM과 CSS·ARIA 정보를 바탕으로 요소의 역할·이름·상태 등을 구성해 보조 기술에 제공하는 트리',
    c3_ax_effect: '콘텐츠에 맞는 요소 사용 → 문서 영역 탐색 지원 · 코드의 의미와 가독성 개선',
    c3_glossary_seo: '검색엔진이 콘텐츠를 발견·이해해 관련 검색 결과에 제공할 수 있도록 개선하는 과정.',
    c3_glossary_aeo: '질문에 직접 답하는 검색·응답 시스템이 콘텐츠를 답변으로 활용하기 쉽도록 정리하는 과정.',
    c3_glossary_geo: '생성형 AI의 답변에서 콘텐츠가 활용·인용될 수 있도록 내용과 구조를 개선하는 과정.',
    'v2_original-semantic-html_title': '시맨틱 HTML',
    'v2_original-semantic-html_lead': '콘텐츠의 의미와 역할에 맞는 HTML 요소로 문서 구조를 표현하는 방식',
    c3_scheme: '스킴',
    c3_host: '호스트',
    c3_path: '경로 전체 (path)',
    c3_query: '쿼리 · sort의 값은 date',
    c3_fragment: '프래그먼트',
    c3_segments_title: '경로 세그먼트와 라우트 매개변수',
    c3_segments: 'blog · 2024 · first-post는 각각 /로 구분된 경로 세그먼트',
    c3_pattern: '라우트 정의',
    c3_actual: '실제 경로',
    c3_dynamic: '[year]·[slug]처럼 매개변수로 정의한 부분이 동적 세그먼트다. URL의 값만 보고 동적 여부를 판단할 수는 없다.',
    c3_url_route_title: 'URL에 맞는 페이지 선택',
    c3_match: '라우터\n경로 매칭',
    c3_about: 'About\n페이지',
    c3_fragment_title: '쿼리와 프래그먼트',
    c3_query_detail: '?sort=date: 요청에 포함되는 쿼리. 정렬 등 추가 조건을 전달하는 데 사용할 수 있다.',
    c3_fragment_detail: '#comments: 예를 들어 id="comments"인 요소로 이동한다. 프래그먼트는 HTTP 요청에 포함되지 않으며 브라우저에서 처리한다.',
    'v2_original-routing-url_title': '라우팅과 URL 구조',
    'v2_original-routing-url_lead': '라우팅은 URL 경로에 맞는 페이지나 요청 처리 코드를 선택하는 과정',
    c3_mpa: '새 문서로 이동 · 전형적인 MPA',
    c3_mpa1: '링크 선택 → /about 요청',
    c3_mpa2: '서버가 경로에 맞는 HTML 응답 제공',
    c3_mpa3: '브라우저가 새 문서를 로드하여 표시',
    c3_mpa4: '브라우저가 URL·방문 기록 관리',
    c3_mpa_note: 'HTML은 정적 파일이거나 서버가 생성한 결과일 수 있다. 새 문서 탐색이 항상 깜빡임이나 느린 전환을 뜻하지 않는다.',
    c3_spa: '기존 문서에서 전환 · SPA 방식',
    c3_spa1: '링크 선택 → 클라이언트 라우터가 경로 처리',
    c3_spa2: '필요한 데이터·코드 준비 (기존 자료 재사용 가능)',
    c3_spa3: '기존 문서에서 해당 화면으로 전환',
    c3_spa4: '라우터가 URL·방문 기록 갱신 및 뒤로 가기 처리',
    c3_spa_note: 'SPA는 하나의 HTML 문서를 유지하며 여러 URL의 화면을 전환한다. JSON 요청은 매번 필요한 조건이 아님.',
    c3_rendering: '렌더링과의 관계',
    c3_rendering_detail: 'SSR·CSR은 콘텐츠 생성 위치의 구분이다. 첫 요청은 SSR, 이후 이동은 클라이언트 라우팅으로 조합할 수 있다.',
    c3_speed: '속도',
    c3_speed_detail: '문서·UI 재사용은 빠른 전환에 유리하다. 실제 속도는 JavaScript 양·데이터 요청·캐시 등에 따라 달라진다.',
    c3_search: 'SEO',
    c3_search_detail: '라우팅 방식만으로 결정되지 않는다. 각 URL의 콘텐츠·링크·메타데이터를 검색엔진이 읽을 수 있어야 한다.',
    'v2_original-routing-types_title': '서버 라우팅과 클라이언트 라우팅',
    'v2_original-routing-types_lead': '페이지 이동 시 새 HTML 문서를 로드하거나, 기존 문서를 유지하며 화면을 전환',
    c4_chapter_title: '웹 브라우저 개발자 도구',
    c4_open: 'Chrome 개발자 도구 열기 · Windows: F12 / Ctrl+Shift+I · macOS: ⌥⌘I',
    c4_elements_steps: 'Elements에서 확인',
    c4_inspect: '화면의 요소를 우클릭 → 검사(Inspect)',
    c4_dom: '선택된 DOM 노드의 태그·속성·부모와 자식 확인',
    c4_semantic: 'header · nav · main · footer의 문서 역할 확인',
    c4_styles: 'Styles: 적용 규칙 · Computed: 계산된 스타일 확인',
    c4_live_dom: 'Elements는 JavaScript 변경이 반영된 현재 DOM을 표시한다. 서버가 보낸 HTML과 다를 수 있다.',
    c4_dom_map: '문서 구조와 확인 위치',
    c4_head: 'title → 문서 제목\nmeta[name="description"] → 페이지 설명\nmeta[name="viewport"] → 모바일 뷰포트 설정',
    c4_body: 'header · nav → 소개·탐색 영역\nmain → 주요 콘텐츠\nfooter → 문서 관련 정보',
    c4_metadata: 'head를 펼쳐 title·meta의 내용을 확인한다. 요소의 존재만으로 검색 노출이나 순위가 보장되지는 않는다.',
    'v2_devtools-elements_title': '문서 요소와 메타데이터',
    'v2_devtools-elements_lead': 'Elements 패널에서 현재 DOM의 구조·속성과 요소에 적용된 스타일 확인',
    c4_device_toggle: '개발자 도구에서 Device Toolbar 전환 · Windows: Ctrl+Shift+M · macOS: ⇧⌘M',
    c4_device_steps: '뷰포트별 확인',
    c4_responsive: 'Dimensions에서 Responsive 또는 기기 프리셋 선택',
    c4_dimensions: '너비·높이 변경 · 회전 버튼으로 세로/가로 전환',
    c4_wrap: '메뉴·문단의 줄바꿈과 이미지 크기 확인',
    c4_overflow: '가로 스크롤·콘텐츠 잘림·요소 겹침 확인',
    c4_css_pixels: '너비·높이는 CSS 픽셀 기준이다. 실제 기기의 물리 픽셀 해상도와 구분한다.',
    c4_device_limit: 'Device Mode는 화면과 입력 환경의 시뮬레이션이다. 실제 모바일 브라우저에서도 확인이 필요하다.',
    c4_mobile_alt: '390 CSS px에서 표시한 자기소개 페이지',
    c4_tablet_alt: '820 CSS px에서 표시한 자기소개 페이지',
    c4_viewport_caption: '같은 자기소개 페이지 · 뷰포트 너비 390 / 820 CSS px',
    'v2_devtools-viewport_title': '반응형 레이아웃과 뷰포트',
    'v2_devtools-viewport_lead': 'Device Toolbar에서 뷰포트의 너비·높이를 바꾸며 배치와 넘침 확인',
    c4_network_path: 'Network → 페이지 새로고침 → Doc 필터 → 현재 페이지 URL의 문서 요청 선택',
    c4_headers: 'Headers · 응답 정보',
    c4_headers_example: 'HTML 응답 헤더의 예시',
    c4_request_url: 'Request URL: 확인하려는 문서의 주소인지 확인',
    c4_status: 'Status Code: 응답 상태 확인 (예: 200 OK)',
    c4_content_type: 'Content-Type: text/html은 HTML 형식, charset=utf-8은 문자 인코딩 선언',
    c4_charset: 'charset이 헤더에 없을 수도 있다. HTML의 meta charset 등 인코딩 선언도 함께 확인한다.',
    c4_response: 'Response · HTML 본문',
    c4_response_html: '응답으로 받은 HTML',
    c4_response_dom: '파싱·변경 후 현재 DOM',
    c4_response_tab: 'Response 탭에서 문서 응답의 HTML 확인',
    c4_response_content: 'title·meta·본문 콘텐츠가 응답에 포함되는지 확인',
    c4_response_compare: 'Elements와 비교해 응답 HTML과 현재 DOM의 차이 확인',
    c4_doc_select: 'Doc 목록의 첫 항목으로 단정하지 않고 URL로 선택한다. 클라이언트 라우팅은 새 문서 요청 없이 동작할 수 있다.',
    'v2_devtools-network_title': '원본 HTML과 응답 헤더',
    'v2_devtools-network_lead': 'Network 패널에서 문서 요청을 선택해 응답의 형식과 HTML 본문 확인',
    'v2_original-framework-15_title': '웹 프레임워크를 활용한 개발',
    'v2_original-framework-15_lead': 'Svelte · SvelteKit · 컴포넌트 · 데이터',
    w2_16_parts_items0: '구조: 폴더·파일 규칙, 역할별 코드 분리',
    w2_16_parts_items1: '요청 처리: 라우터·미들웨어·입력 검증·인증 연동',
    w2_16_parts_items2: '데이터: 로드 함수·데이터베이스 접근 도구',
    w2_16_parts_items3: '빌드·실행: 번들링·코드 분할·렌더링·배포',
    w2_16_parts_note: '기능은 프레임워크마다 다르며 추가 라이브러리가 필요할 수 있음',
    w2_16_parts: '제공 기능의 예',
    w2_16_ui: 'UI 라이브러리·프레임워크',
    w2_16_ui_names: 'React · Vue · Angular · Svelte',
    w2_16_backend: '백엔드 프레임워크',
    w2_16_backend_names: 'Express · NestJS · Django · FastAPI · Spring Boot',
    w2_16_full: '풀스택 프레임워크',
    w2_16_full_names: 'Next.js · Nuxt · SvelteKit',
    w2_16_types: '개발 영역별 도구',
    w2_16_choose: '선택 기준: 팀의 언어·경험, 필요한 렌더링·서버 기능, 호스팅 환경, 문서·생태계·유지보수',
    'v2_original-framework-16_title': '웹 개발 프레임워크',
    'v2_original-framework-16_lead': '반복 작업과 프로젝트 구조를 위한 규칙·도구',
    w2_17_runtime_items0: '개발 서버·빌드 도구·CLI·서버 프로그램 실행',
    w2_17_runtime_items1: '브라우저의 document·window 대신 파일·프로세스 등 서버 API 사용',
    w2_17_runtime_items2: 'npm으로 프로젝트 의존성과 실행 명령 관리',
    w2_17_node_code: 'console.log(\'Hello from Node.js\');',
    w2_17_node_cmd: 'node hello.js',
    w2_17_runtime: '실행 환경과 용도',
    w2_17_io_items0: 'I/O 완료를 기다리는 동안 다른 요청의 작업 진행 가능',
    w2_17_io_items1: 'JavaScript 콜백은 주로 하나의 이벤트 루프에서 처리',
    w2_17_io_items2: '일부 I/O·연산은 운영체제와 worker pool 등이 처리',
    w2_17_io_items3: '긴 동기 연산은 이벤트 루프를 막아 다른 요청도 지연',
    w2_17_io_note: '비동기 구조만으로 높은 성능·적은 메모리가 보장되지는 않음',
    w2_17_io: '비동기 I/O와 이벤트 루프',
    w2_17_version: '실습 환경: Node.js 24 · node -v / npm -v로 확인',
    'v2_original-framework-17_title': 'Node.js 실행 환경',
    'v2_original-framework-17_lead': 'V8 엔진을 사용해 브라우저 밖에서 JavaScript 실행',
    w2_18_terminal: '터미널',
    w2_18_terminal_body: '입력·출력을 표시하는 프로그램 · Windows Terminal, macOS Terminal',
    w2_18_shell: '셸',
    w2_18_shell_body: '명령을 해석·실행하는 프로그램 · PowerShell, bash, zsh',
    w2_18_path: '경로와 현재 작업 디렉터리',
    w2_18_path_body: 'Path: 파일·폴더의 위치 표기 · cwd: 상대 경로 해석의 기준 폴더',
    w2_18_prompt: '프롬프트: 입력 대기 표시 · . 현재 폴더 · .. 상위 폴더 · ~ 홈 폴더',
    w2_18_terms: '터미널·셸·경로',
    w2_18_cli: 'cd pwd-week2\nnode -v\nnpm -v\nnpm run dev',
    w2_18_cli_items0: '같은 절차를 스크립트로 반복·자동화',
    w2_18_cli_items1: '버전·입력·환경을 고정해 재현성 향상',
    w2_18_cli_items2: '같은 명령도 작업 폴더·설정·버전에 따라 결과가 달라짐',
    w2_18_commands: '프로젝트에서 명령 실행',
    'v2_original-framework-18_title': 'CLI · 명령줄 인터페이스',
    'v2_original-framework-18_lead': '텍스트 명령으로 도구를 실행하고 작업을 자동화하는 인터페이스',
    w2_19_npm_points0: 'package.json: 의존성과 scripts 정의',
    w2_19_npm_points1: 'package-lock.json: 재현 가능한 설치를 위한 버전 기록',
    w2_19_npm_points2: 'npm install: 의존성 설치 · npm run dev: dev 스크립트 실행',
    w2_19_npm_commands: 'npm --version\nnpm install\nnpm run dev',
    w2_19_ci: '받은 실습 소스는 npm ci로 잠금 파일에 맞춰 설치',
    w2_19_npm: 'npm · 패키지와 스크립트 관리',
    w2_19_npx_body: '별도의 전역 설치 없이 명령 실행 · 로컬 패키지를 사용하거나 필요 시 npm 캐시에 설치',
    w2_19_npx_commands: 'npx sv@0.17.0 create pwd-week2\ncd pwd-week2\nnpm run dev',
    w2_19_npx_scope: '새 프로젝트 생성 명령 · 이미 받은 프로젝트에서 다시 실행하지 않음',
    w2_19_windows: 'PowerShell 실행 정책 오류 시 npm.cmd·npx.cmd 사용',
    w2_19_npx: 'npx · 패키지 명령 실행',
    'v2_original-framework-19_title': 'npm과 npx',
    'v2_original-framework-19_lead': '프로젝트 의존성 관리와 패키지 명령 실행',
    sv_svelte: 'Svelte · UI 프레임워크',
    sv_compiler: '컴파일러가 컴포넌트를 브라우저에서 실행할 JavaScript·CSS로 변환',
    sv_dom: 'Virtual DOM 비교 대신 컴파일된 코드와 런타임으로 DOM 갱신',
    sv_ui: '컴포넌트·반응형 상태·이벤트·스타일 제공',
    sv_runtime: '컴파일러 기반이어도 런타임 코드가 존재하며, 번들 크기와 성능은 앱에 따라 달라짐',
    sv_kit: 'SvelteKit · 웹 애플리케이션 프레임워크',
    sv_kit_features: '파일 기반 라우팅·데이터 로드·서버 API·배포 기능 제공',
    sv_kit_render: 'SSR·사전 렌더링(SSG)·클라이언트 탐색 지원',
    sv_languages: 'Svelte와 SvelteKit 모두 JavaScript·TypeScript 지원 · TypeScript는 선택 사항',
    sv_js: 'JavaScript',
    sv_js_file: '컴포넌트는 .svelte · 로드·API 파일은 .js',
    sv_ts: 'TypeScript',
    sv_ts_file: '컴포넌트는 동일하게 .svelte · 로드·API 파일은 .ts도 지원',
    'v2_original-framework-20_title': 'Svelte와 SvelteKit',
    'v2_original-framework-20_lead': 'HTML·CSS와 JavaScript 또는 TypeScript로 UI와 웹 애플리케이션 개발',
    sv_compare_dimension: '비교 항목',
    sv_compare_syntax: 'UI 작성',
    sv_compare_syntax0: 'JSX',
    sv_compare_syntax1: 'Template / JSX',
    sv_compare_syntax2: '.svelte',
    sv_compare_reactivity: '상태·반응성',
    sv_compare_reactivity0: 'useState / useReducer',
    sv_compare_reactivity1: 'ref / reactive',
    sv_compare_reactivity2: '$state / $derived',
    sv_compare_updates: 'DOM 갱신',
    sv_compare_updates0: '렌더 결과 재조정',
    sv_compare_updates1: '반응성·컴파일된 렌더 함수',
    sv_compare_updates2: '컴파일된 갱신 코드',
    sv_compare_language: '개발 언어',
    sv_compare_language0: 'JavaScript / TypeScript',
    sv_compare_language1: 'JavaScript / TypeScript',
    sv_compare_language2: 'JavaScript / TypeScript',
    sv_size: '번들 크기와 실행 성능',
    sv_size_conditions: '앱 기능·의존성·빌드 설정·측정 환경을 맞춰 비교해야 하며, 프레임워크 이름만으로 우열을 결정할 수 없음',
    sv_choice: '학습·유지보수 관점',
    sv_choice_conditions: '팀의 언어·도구 경험, 필요한 라이브러리, 문서와 장기 유지보수 요구를 함께 고려',
    'v2_original-framework-21_title': '프론트엔드 UI 개발 방식 비교',
    'v2_original-framework-21_lead': '문법·반응성·DOM 갱신 방식의 차이',
    sv_code_counterJS: '<script>\n  let name = $state(\'world\');\n  let count = $state(0);\n</script>\n\n<h1>Hello {name}!</h1>\n<input aria-label="Name" bind:value={name} />\n<button onclick={() => count += 1}>\n  clicks: {count}\n</button>\n\n<style>\n  h1 { color: #5b3df5; }\n</style>',
    sv_code_counterTS: '<script lang="ts">\n  let name: string = $state(\'world\');\n  let count: number = $state(0);\n</script>\n\n<h1>Hello {name}!</h1>\n<input aria-label="Name" bind:value={name} />\n<button onclick={() => count += 1}>\n  clicks: {count}\n</button>\n\n<style>\n  h1 { color: #5b3df5; }\n</style>',
    sv_file_parts: 'script: 상태·함수 · 마크업: 화면 구조 · style: 컴포넌트 범위 CSS',
    sv_module: '공유 모듈 코드는 <script module>에 작성하며 모듈 평가 시 실행 · onclick에는 두 언어 모두 함수를 전달',
    sv_ts_scope: 'Svelte 5는 타입 표기·interface를 지원하며, enum 등 실행 코드가 필요한 TS 문법에는 전처리 설정 필요',
    'v2_original-framework-22_title': 'Svelte 파일 구조와 개발 언어',
    'v2_original-framework-22_lead': '같은 .svelte 컴포넌트를 JavaScript 또는 TypeScript로 작성',
    w2_23_tree: 'pwd-week2/\n├─ src/\n│  ├─ routes/\n│  ├─ lib/\n│  ├─ app.html\n│  └─ app.css\n├─ static/\n├─ package.json\n├─ package-lock.json\n├─ svelte.config.js\n├─ vite.config.js\n├─ .gitignore\n└─ README.md',
    w2_23_roles_list0: 'src/routes: 페이지·레이아웃·load·API 라우트',
    w2_23_roles_list1: 'src/lib: 재사용 코드 · $lib 별칭으로 import',
    w2_23_roles_list2: 'src/app.html: HTML 바깥 틀 · app.css: 가져와 적용할 전역 스타일',
    w2_23_roles_list3: 'static: 변환 없이 제공할 정적 파일',
    w2_23_roles_list4: '설정 파일: 패키지·SvelteKit·Vite의 동작 구성',
    w2_23_installed: 'node_modules는 설치 시 생성 · Git에 추가하지 않음',
    w2_23_roles: '주요 파일과 폴더',
    w2_23_options: '실습 프로젝트의 구조 예시 · 생성 옵션과 사용하는 도구에 따라 파일 구성은 달라질 수 있음',
    'v2_original-framework-23_title': 'SvelteKit 프로젝트 구조',
    'v2_original-framework-23_lead': '파일의 위치와 이름으로 페이지·공유 코드·설정의 역할 구분',
    sv_static_route: 'src/routes/about/+page.svelte → /about',
    sv_code_routeLoad: 'export function load({ params }) {\n  return { id: params.id };\n}',
    sv_code_routePage: '<script>\n  let { data } = $props();\n</script>\n\n<h1>Blog post #{data.id}</h1>',
    sv_route_data: '[id]는 경로 매개변수를 정의 · data는 load 반환값으로 전달되므로 params와 data를 구분',
    sv_nested_path: '중첩 경로: src/routes/dashboard/reports/[id]/+page.svelte → /dashboard/reports/42',
    'v2_original-framework-24_title': '파일 기반 라우팅',
    'v2_original-framework-24_lead': '정적 경로는 폴더명으로, 동적 경로는 [매개변수]로 정의',
    w2_25_nested_tree: 'src/routes/\n├─ +layout.svelte\n├─ +layout.js\n├─ +page.svelte\n└─ dashboard/\n   ├─ +layout.svelte\n   ├─ +layout.js\n   ├─ +page.svelte\n   └─ reports/\n      ├─ +page.svelte\n      └─ [id]/\n         └─ +page.svelte',
    w2_25_root_page: 'routes/+page.svelte → /',
    w2_25_dashboard_page: 'dashboard/+page.svelte → /dashboard',
    w2_25_report_page: 'reports/+page.svelte → /dashboard/reports',
    w2_25_id_page: 'reports/[id]/+page.svelte → /dashboard/reports/42',
    w2_25_layout_scope: '+layout.svelte: 해당 경로와 하위 페이지의 공통 UI · children을 렌더링해 페이지 표시',
    w2_25_parent: '하위 load에서 await parent()로 상위 레이아웃의 load 결과 재사용',
    w2_25_nested: '경로와 파일의 대응',
    w2_25_optional: '모든 폴더에 +page·+layout이 필요한 것은 아님 · +layout.js는 공유 데이터가 필요할 때 추가',
    'v2_original-framework-25_title': '중첩 라우팅과 공유 레이아웃',
    'v2_original-framework-25_lead': '폴더 계층으로 URL을 구성하고 공통 UI와 데이터를 재사용',
    w2_26_state_body: '입력·토글·배열 변경을 화면에 반영',
    w2_26_code_state: '<script>\n  let name = $state(\'world\');\n  let on = $state(false);\n  let list = $state([\'a\']);\n</script>\n\n<input aria-label="Name"\n  bind:value={name} />\n<button onclick={() => on = !on}>\n  {on ? \'ON\' : \'OFF\'}\n</button>\n<button\n  onclick={() => list.push(\'item\')}>\n  추가\n</button>\n<p>{name} / {list.length}</p>',
    w2_26_state: '$state · 변경되는 상태',
    w2_26_derived_body: '의존성이 바뀌면 무효화 · 값을 읽을 때 재계산',
    w2_26_code_derived: '<script>\n  let prices = $state(\n    [1000, 2500, 3000]\n  );\n  let total = $derived(\n    prices.reduce((s, p) => s + p, 0)\n  );\n  let label = $derived(\n    total.toLocaleString(\'ko-KR\') +\n      \'원\'\n  );\n</script>\n\n<p>{total} / {label}</p>',
    w2_26_derived: '$derived · 계산된 값',
    w2_26_effect_body: '브라우저에서 최초 실행 · 동기적으로 읽은 반응형 의존성 변경 시 재실행',
    w2_26_code_focus: '<script>\n  let open = $state(false);\n  let el = $state();\n  $effect(() => {\n    if (open && el) el.focus();\n  });\n</script>\n\n<button onclick={() => open = !open}>\n  {open ? \'닫기\' : \'열기\'}\n</button>\n{#if open}\n  <input aria-label="메모"\n    bind:this={el} />\n{/if}',
    w2_26_effect: '$effect · 외부 동작 동기화',
    w2_26_effect_purpose: '표시용 파생값에는 $derived 사용 · $effect 안의 계산 자체가 금지되는 것은 아님',
    'v2_original-framework-26_title': '상태·파생값·반응형 효과',
    'v2_original-framework-26_lead': 'let·const 선언과 Svelte의 반응성 관련 runes',
    sv_code_grade: '<script>\n  let score = $state(0);\n  let grade = $derived.by(() => {\n    if (score >= 90) return \'A\';\n    if (score >= 60) return \'B\';\n    return \'C\';\n  });\n</script>\n\n<input type="number" min="0" max="100"\n  aria-label="Score" bind:value={score} />\n{#if grade === \'A\'}\n  <p>Excellent! (A)</p>\n{:else if grade === \'B\'}\n  <p>Good (B)</p>\n{:else}\n  <p>Keep practicing (C)</p>\n{/if}',
    sv_derived: '계산된 값 · $derived.by',
    sv_grade_flow: 'score 변경 → grade 재계산 → 조건에 맞는 문단 표시',
    sv_derived_pure: 'if / else로 값을 계산하고 반환 · 다른 상태를 변경하지 않는 순수 계산',
    sv_if: '템플릿 조건 블록',
    sv_if_syntax: '{#if} · {:else if} · {:else}로 화면 분기',
    sv_no_effect: '다른 상태로부터 계산할 수 있는 값은 $derived 사용 · $effect는 DOM·외부 시스템과의 동기화 등에 사용',
    'v2_original-framework-27_title': '조건문',
    'v2_original-framework-27_lead': '상태에서 등급을 계산하고, 등급에 맞는 UI를 선택',
    w2_28_each_points0: 'as todo: 항목 · as todo, i: 항목과 인덱스',
    w2_28_each_points1: '(todo.id): 항목을 추적하는 고유하고 안정적인 key',
    w2_28_each_points2: '추가 버튼: 배열에 새 항목 삽입 → 목록 갱신',
    w2_28_each_points3: 'bind:checked: 체크박스와 done을 연결',
    w2_28_js: '스크립트의 반복·계산',
    w2_28_js_body: 'for·for…of·map·forEach 등 사용 가능 · 변경에 따라 UI를 갱신할 값에 반응형 상태·파생값 사용',
    w2_28_static: '고정 배열도 {#each}로 표시 가능 · 모든 UI 데이터에 runes가 필수인 것은 아님',
    w2_28_each: '템플릿 반복 블록 · {#each}',
    w2_28_code_todos: '<script>\n  let nextId = 3;\n  let todos = $state([\n    { id: 1, text: \'Svelte 학습\', done: false },\n    { id: 2, text: \'Runes 연습\', done: true }\n  ]);\n  function add() {\n    todos.push({\n      id: nextId++, text: \'새 할 일\', done: false\n    });\n  }\n</script>\n\n<button onclick={add}>추가</button>\n<ul>\n  {#each todos as todo (todo.id)}\n    <li><label>\n      <input type="checkbox" bind:checked={todo.done} />\n      {todo.text}\n    </label></li>\n  {/each}\n</ul>',
    'v2_original-framework-28_title': '반복문과 목록 렌더링',
    'v2_original-framework-28_lead': '배열 항목을 반복 표시하고 각 항목의 상태를 갱신',
    w2_29_syntax: 'onclick={handler} · oninput={handler} · onmousemove={handler}',
    w2_29_event_points0: 'click: 클릭 · input: 입력 변화 · submit: 폼 제출',
    w2_29_event_points1: 'keydown: 키 입력 · mousemove: 마우스 이동',
    w2_29_event_points2: 'event 객체로 입력 값·좌표 등 이벤트 정보 확인',
    w2_29_window: 'svelte:window는 브라우저 창의 이벤트에 연결 · 해제 시 리스너 정리',
    w2_29_events: '이벤트 속성',
    w2_29_code_mouse: '<script>\n  let m = $state({ x: 0, y: 0 });\n  function handleMousemove(event) {\n    m.x = event.clientX;\n    m.y = event.clientY;\n  }\n</script>\n\n<svelte:window onmousemove={handleMousemove} />\n<p>마우스: {m.x} × {m.y}</p>',
    w2_29_mouse_flow0: '마우스 이동',
    w2_29_mouse_flow1: 'event.clientX / clientY',
    w2_29_mouse_flow2: 'm.x / m.y 갱신',
    w2_29_mouse_flow3: '좌표 표시',
    w2_29_coords: 'clientX·clientY는 뷰포트 기준 CSS 픽셀 좌표',
    'v2_original-framework-29_title': '이벤트와 처리 함수',
    'v2_original-framework-29_lead': '사용자 입력과 브라우저의 이벤트에 함수를 연결',
    sv_code_lifecycle: '<script>\n  import { onMount } from \'svelte\';\n  let count = $state(0);\n\n  onMount(() => {\n    const timer = setInterval(() => count++, 1000);\n    return () => clearInterval(timer);\n  });\n\n  $effect.pre(() => {\n    console.log(\'Before DOM update:\', count);\n  });\n  $effect(() => {\n    console.log(\'After DOM update:\', count);\n  });\n</script>\n\n<h1>{count}</h1>',
    sv_mount: 'onMount · 마운트 이후',
    sv_mount_note: '브라우저에서 마운트 후 실행 · SSR에서는 실행되지 않음',
    sv_cleanup: '동기 onMount 콜백이 반환한 함수는 해제 시 실행 → 타이머 정리',
    sv_effects: '$effect.pre / $effect',
    sv_effects_note: '브라우저에서 최초 실행 후, 동기적으로 읽은 반응형 의존성이 변경되면 재실행',
    sv_effects_timing: '$effect.pre: DOM 갱신 전 · $effect: DOM 갱신 후',
    sv_destroy: 'onDestroy도 해제 작업 등록에 사용 가능하며 SSR에서도 실행 · count는 $state로 선언해야 화면과 효과가 변경을 추적',
    'v2_original-framework-30_title': '라이프사이클과 반응형 효과',
    'v2_original-framework-30_lead': '마운트·해제 시 리소스를 관리하고 DOM 갱신 전후의 작업을 구분',
    w2_31_guard_script: '<script>\n  import { beforeNavigate } from \'$app/navigation\';\n  let { children } = $props();\n  let dirty = $state(false);\n\n  beforeNavigate((nav) => {\n    if (!dirty) return;\n    if (nav.type === \'leave\' ||\n        !confirm(\'저장하지 않고 이동?\')) {\n      nav.cancel();\n    }\n  });\n</script>',
    w2_31_life: 'onMount·onDestroy: 컴포넌트 생성 후·해제 시 리소스 관리',
    w2_31_before: 'beforeNavigate: 탐색 전 검사·취소',
    w2_31_on: 'onNavigate: 탐색 전 실행 · 반환한 함수는 DOM 갱신 후 실행',
    w2_31_after: 'afterNavigate: 최초 마운트·탐색 완료 후 실행',
    w2_31_load: 'load: 페이지·레이아웃의 데이터 준비',
    w2_31_guard_markup: '<label>작성 중인 내용\n  <textarea oninput={() => dirty = true}></textarea>\n</label>\n<main>{@render children()}</main>',
    w2_31_hooks: '주요 실행 지점',
    w2_31_leave: '앱 내부 이동: confirm 결과로 취소 · 탭 닫기 등 leave 탐색: cancel()로 브라우저 기본 이탈 확인 요청',
    'v2_original-framework-31_title': '훅과 페이지 탐색 제어',
    'v2_original-framework-31_lead': '정해진 실행 시점에 콜백을 등록해 동작 확장·제어',
    w2_32_code_Parent: '<script>\n  import Child from \'./Child.svelte\';\n  let message = $state(\'안녕!\');\n</script>\n\n<button onclick={() => message = \'변경된 인사말\'}>\n  변경\n</button>\n<Child msg={message} />',
    w2_32_code_Child: '<script>\n  const { msg } = $props();\n</script>\n\n<p>{msg}</p>',
    w2_32_prop_flow0: '부모의 message',
    w2_32_prop_flow1: '<Child msg={message} />',
    w2_32_prop_flow2: '$props()의 msg',
    w2_32_prop_flow3: '자식의 문단 갱신',
    w2_32_prop_rules: '부모의 값 변경은 자식에 반영 · props는 읽기 전용 입력으로 사용 · 자식에서 변경을 요청할 때 콜백 활용',
    'v2_original-framework-32_title': 'Props · 부모에서 자식으로 전달하는 값',
    'v2_original-framework-32_lead': '컴포넌트의 입력값을 $props()로 받아 화면에 사용',
    sv_code_binding_start: '<script>\n  let name = $state(\'\');\n  let agree = $state(false);\n  let color = $state(\'red\');\n  let level = $state(50);\n  let files = $state();\n</script>\n\n<label>Name: <input bind:value={name} /></label>\n<p>{name || \'(empty)\'}</p>\n<label>\n  <input type="checkbox" bind:checked={agree} />\n  I agree\n</label>\n<p>{agree ? \'Yes\' : \'No\'}</p>',
    sv_code_binding_end: '<label>Color:\n  <select bind:value={color}>\n    <option>red</option><option>green</option>\n    <option>blue</option>\n  </select>\n</label>\n<p>{color}</p>\n<label>Level: {level}\n  <input type="range" min="0" max="100"\n    bind:value={level} />\n</label>\n<label>Files:\n  <input type="file" multiple bind:files={files} />\n</label>\n{#if files}<p>{files.length} files</p>{/if}',
    sv_binding_runes: 'Svelte 5 runes 모드: 변경되는 값은 $state · value는 입력값, checked는 체크 여부, files는 FileList와 연결',
    'v2_original-framework-33_title': '양방향 바인딩',
    'v2_original-framework-33_lead': '입력이 상태를 변경하고, 상태 변경이 연결된 입력과 화면에 반영',
    w2_34_code_Card: '<script>\n  let { title, summary, href } = $props();\n</script>\n\n<article class="card">\n  <h3><a href={href}>{title}</a></h3>\n  <p>{summary}</p>\n</article>',
    w2_34_code_Cards: '<script>\n  import Card from \'$lib/Card.svelte\';\n  let { data } = $props();\n</script>\n\n<h2>Projects</h2>\n{#each data.projects as p (p.slug)}\n  <Card title={p.title} summary={p.summary}\n    href={\'/projects/\' + p.slug} />\n{:else}\n  <p>등록된 프로젝트 없음</p>\n{/each}',
    w2_34_inputs_body: '각 카드에 title·summary·href 전달 · 페이지에서 Card를 반복 사용',
    w2_34_inputs: '입력과 합성',
    w2_34_value_body: '공통 UI의 변경 위치 통합 · 독립적 테스트·역할별 코드 관리',
    w2_34_value: '유지보수와 협업',
    w2_34_data: 'data.projects는 페이지 load의 반환값 · 컴포넌트는 작은 버튼부터 큰 페이지까지 구성 가능',
    'v2_original-framework-34_title': '컴포넌트와 UI 재사용',
    'v2_original-framework-34_lead': '마크업·동작·상태·스타일을 묶는 재사용 가능한 UI 단위',
    sv_server: '서버 전용 실행',
    sv_server_only: '+server.js 코드는 브라우저 번들에 포함되지 않음 · DB·비밀키는 서버에서 사용',
    sv_secrets: '응답으로 반환한 데이터는 클라이언트에 전달되므로 인증·권한 확인과 비밀정보 제외는 별도로 구현',
    sv_method: '메서드와 응답',
    sv_method_response: 'GET·POST 등 메서드명으로 함수 export · Response 또는 json(data) 반환 · error(status, message)는 예외 발생',
    sv_context: '요청 컨텍스트',
    sv_request_context: 'request: 요청 · url: URL·쿼리 · params: 경로 매개변수 · cookies: 쿠키',
    sv_locals: 'locals: 인증 사용자 등 요청별로 공유하는 서버 측 정보',
    sv_load_kind: '페이지 데이터 로드',
    sv_load_kind_detail: '+page.js: 서버·브라우저에서 실행 가능한 universal load\n+page.server.js: 서버에서만 실행되는 load',
    'v2_original-framework-35_title': 'API 라우트와 요청 처리',
    'v2_original-framework-35_lead': '+server.js의 HTTP 메서드 함수가 요청을 처리하고 Response를 반환',
    sv_code_api: 'import { json } from \'@sveltejs/kit\';\n\nconst projects = [\n  { slug: \'timetable\',\n    title: \'Timetable Helper\',\n    summary: \'Classes and schedules\' },\n  { slug: \'gallery\',\n    title: \'Image Gallery\',\n    summary: \'A small image gallery\' },\n  { slug: \'memo\',\n    title: \'Memo Pad\',\n    summary: \'Local notes\' }\n];\n\nexport function GET() {\n  return json(projects);\n}',
    sv_code_projectsLoad: 'import { error } from \'@sveltejs/kit\';\n\nexport async function load({ fetch }) {\n  const res = await fetch(\'/api/projects\');\n  if (!res.ok) {\n    error(res.status, \'Load failed\');\n  }\n  return { projects: await res.json() };\n}',
    sv_code_projectsPage: '<script>\n  import Card from \'$lib/Card.svelte\';\n  let { data } = $props();\n</script>\n\n<h2>Projects</h2>\n{#each data.projects as p (p.slug)}\n  <Card title={p.title}\n    summary={p.summary}\n    href={\'/projects/\' + p.slug} />\n{:else}\n  <p>No projects yet.</p>\n{/each}',
    sv_api_card: 'Card는 앞서 정의한 src/lib/Card.svelte를 재사용 · API 처리, 데이터 로드, 화면 마크업은 서로 다른 파일',
    'v2_original-framework-36_title': 'API 응답과 페이지 데이터',
    'v2_original-framework-36_lead': 'API 응답을 load에서 받아 페이지 컴포넌트에 전달',
    w2_37_steps0: '.svelte 컴포넌트의 script·마크업·style 입력',
    w2_37_steps1: '상태·이벤트·바인딩을 바꾸며 출력과 비교',
    w2_37_steps2: '컴파일 오류·경고 메시지와 해당 코드 위치 확인',
    w2_37_kit_limit: 'SvelteKit의 +page·+layout·API·$app 모듈 예제는 로컬 SvelteKit 프로젝트에서 실행',
    'v2_original-framework-37_title': 'Svelte Playground',
    'v2_original-framework-37_lead': '브라우저에서 컴포넌트 코드와 실행 결과 확인',
    'v2_original-framework-38_title': '웹 서비스 배포 자동화',
    'v2_original-framework-38_lead': 'GitHub · 빌드·검증 · Vercel',
    w2_39_ci_def: '작은 변경을 공유 코드에 자주 통합하고 자동 빌드·테스트로 검증',
    w2_39_ci_goals0: '통합 오류와 회귀 문제의 조기 발견',
    w2_39_ci_goals1: '변경 검증·릴리스 준비 시간 단축',
    w2_39_ci: 'CI · Continuous Integration',
    w2_39_delivery: 'Continuous Delivery',
    w2_39_delivery_def: '변경을 항상 배포 가능한 상태로 준비 · 운영 배포에는 사람의 결정이 남을 수 있음',
    w2_39_deployment: 'Continuous Deployment',
    w2_39_deployment_def: '검증을 통과한 변경을 운영 환경까지 자동 배포',
    w2_39_cd: 'CD · Delivery / Deployment',
    w2_39_pipeline0: '코드 변경',
    w2_39_pipeline1: '빌드·테스트',
    w2_39_pipeline2: '배포 가능한 결과물',
    w2_39_pipeline3: '운영 배포',
    w2_39_devops: 'DevOps: 개발과 운영의 협업·자동화·피드백 문화와 실천 · 특정 직무나 도구 하나로 한정되지 않음',
    'v2_original-framework-39_title': 'CI/CD와 DevOps',
    'v2_original-framework-39_lead': '코드 통합·검증·배포를 반복 가능한 과정으로 구성',
    w2_40_next: 'Next.js 개발 · SvelteKit 등 여러 프레임워크 지원',
    w2_40_rich: '2021년 11월 Svelte 창시자 Rich Harris 합류 · Svelte 개발 지원',
    w2_40_support: '프레임워크 preset과 adapter가 빌드 결과를 배포 환경에 연결',
    w2_40_platform: '플랫폼과 프레임워크',
    w2_40_features_list0: '정적 파일 전송·CDN·서버 함수 실행',
    w2_40_features_list1: 'Git 연동에 따른 자동 빌드·배포',
    w2_40_features_list2: '변경 사항별 Preview 배포 URL',
    w2_40_features_list3: 'HTTPS 인증서·사용자 도메인·관측 도구',
    w2_40_features: '주요 기능',
    w2_40_tests: '자동 배포가 테스트의 자동 작성을 뜻하지는 않음 · 테스트 명령과 배포 조건은 프로젝트에 설정',
    'v2_original-framework-40_title': 'Vercel',
    'v2_original-framework-40_lead': '웹 애플리케이션의 빌드·미리보기·배포를 위한 클라우드 플랫폼',
    w2_41_setup_steps0: 'Vercel 계정 생성·로그인',
    w2_41_setup_steps1: '새 프로젝트에서 GitHub 연동과 저장소 권한 부여',
    w2_41_setup_steps2: '배포할 저장소 Import · 프로젝트 폴더 선택',
    w2_41_setup_steps3: 'SvelteKit 프레임워크 자동 감지 확인',
    w2_41_setup: '계정·저장소 연결',
    w2_41_deploy_steps0: 'Node.js 24.x · 필요한 환경 변수 설정',
    w2_41_deploy_steps1: 'Output Directory는 SvelteKit 자동 설정 유지',
    w2_41_deploy_steps2: 'Deploy 실행 · 빌드 로그와 배포 URL 확인',
    w2_41_deploy_steps3: 'Home·About·Projects·상세·메모 동작 확인',
    w2_41_deploy: '설정·검증·배포',
    w2_41_push_flow0: '코드 변경·커밋',
    w2_41_push_flow1: 'GitHub에 push',
    w2_41_push_flow2: 'Vercel 재빌드',
    w2_41_push_flow3: '배포 결과 확인',
    w2_41_url: '제출에는 대시보드의 실제 Production URL 사용 · 브랜치·설정에 따라 Preview와 Production 배포 구분',
    'v2_original-framework-41_title': 'Vercel 프로젝트 연결과 배포',
    'v2_original-framework-41_lead': 'GitHub 저장소를 연결하고 배포 결과와 후속 변경을 확인',
    'v2_original-framework-42_title': '실습: SvelteKit을 이용한 웹사이트 제작과 Vercel 배포',
    w2_43_goals_items0: 'Node.js와 npm 환경 구축',
    w2_43_goals_items1: 'SvelteKit 프레임워크로 정적 사이트 제작',
    w2_43_goals_items2: 'Git/GitHub를 활용한 버전 관리',
    w2_43_goals_items3: 'Vercel을 통한 자동 배포 파이프라인 구축',
    w2_43_requirements: '요구사항',
    w2_43_requirements_items0: 'GitHub 저장소에 프로젝트 버전 관리가 바르게 되고 있는가?',
    w2_43_requirements_items1: 'Vercel에 GitHub 저장소가 연결되어 자동 배포가 이루어 지고 있는가?',
    w2_43_requirements_items2: 'Vercel 배포한 웹서비스에서 제시한 프로젝트 코드가 모두 바르게 동작하는가? (Home, About, Projects)',
    w2_43_reference: '참고',
    w2_43_goals: '학습 목표',
    w2_43_deadline_value: '9월 20일 23:59',
    w2_43_deliverables0: 'GitHub 저장소 URL',
    w2_43_deliverables1: 'Vercel App URL',
    w2_43_github_example: '(예: https://github.com/username/pwd-week2)',
    w2_43_vercel_example: '(예: https://pwd-week2-[random].vercel.app)',
    w2_43_submit: '과제 마감일',
    'v2_original-framework-43_title': '실습 개요',
    'v2_original-framework-43_lead': 'SvelteKit을 이용한 웹사이트 제작과 Vercel 배포',
    'v2_original-framework-44_title': '질의응답',
    'v2_original-framework-44_lead': '웹 페이지 · 렌더링 · SvelteKit · 배포',
    s01_eyebrow: '2026학년도 2학기 실전웹서비스개발',
    s01_title: '실전 웹서비스개발 – 2주차',
    s01_subtitle: '웹 페이지의 구성 요소와 렌더링 원리',
    s02_title: '학습 목표',
    s02_goal_1: '웹 페이지의 구성 요소',
    s02_goal_1_detail: 'HTML·CSS·JavaScript의 구조·표현·동작 역할 구분',
    s02_goal_2: '웹 브라우저 렌더링',
    s02_goal_2_detail: 'DOM부터 페인트까지의 과정과 CSR·SSR·SSG, 성능의 중요성 설명',
    s02_goal_3: '시맨틱 HTML과 라우팅',
    s02_goal_3_detail: '요소의 의미와 접근성, URL 구조와 페이지 탐색 방식 설명',
    s02_goal_4: '웹 브라우저 개발자 도구',
    s02_goal_4_detail: 'DOM·스타일·메타데이터, 뷰포트와 HTTP 응답 확인',
    s02_goal_5: 'Svelte·SvelteKit 개발',
    s02_goal_5_detail: 'JavaScript·TypeScript로 컴포넌트·상태·이벤트·라우팅·API 구현',
    s03_title: '웹 페이지의 구성 요소와 역할',
    s03_lead: 'HTML · CSS · JavaScript',
    s47_title: 'HTML · CSS · JavaScript의 역할',
    s47_lead: 'HTML은 구조, CSS는 표현, JavaScript는 동작을 담당',
    s47_example_label: '자기소개 페이지에서 살펴보는 구조 · 표현 · 동작',
    s47_preview_title: '자기소개',
    s47_preview_before: '웹 개발 학습 중',
    s47_preview_button: '소개 바꾸기',
    s47_preview_hint: '버튼 클릭 → 소개 문구 변경',
    s47_html_role: '구조',
    s47_html: '제목 · 소개 문단 · 버튼을 HTML 요소로 정의',
    s47_html_detail: 'h1 · p · button 등의 요소와 속성',
    s47_css_role: '표현',
    s47_css: '같은 요소에 글꼴 · 여백 · 색상 · 버튼 모양 지정',
    s47_css_detail: '선택자로 대상 지정 · 속성과 값으로 스타일 선언',
    s47_js_role: '동작',
    s47_js: '버튼 클릭에 반응해 표시할 소개 문구 선택',
    s47_js_detail: '데이터와 함수로 처리 · 브라우저 API로 화면에 반영',
    s04_title: 'HTML (HyperText Markup Language)',
    s04_lead: '웹 문서의 구조와 내용을 기술',
    s04_element_label: '요소 (Element)',
    s04_element: '태그로 표현하는 문서의 구성 단위',
    s04_attribute_label: '속성 (Attribute)',
    s04_attribute: '시작 태그에 작성하는 요소의 추가 정보',
    s04_tags_label: '문서 선언과 주요 태그',
    s04_doctype: '브라우저의 표준 모드 사용을 위한 문서 선언',
    s04_html: '웹 문서 전체를 감싸는 최상위 루트 요소',
    s04_head: '문서 제목 · 인코딩 · 스타일 등 메타데이터를 담는 영역',
    s04_meta: '문자 인코딩 · 뷰포트 등 문서의 부가 정보를 지정',
    s04_body: '제목 · 문단 · 이미지 등 화면에 표시할 콘텐츠를 담는 영역',
    s04_example: '<!DOCTYPE html>\n<html lang="ko">\n  <head>\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1" />\n    <title>자기소개</title>\n    <link rel="stylesheet" href="style.css" />\n    <script src="script.js" defer></script>\n  </head>\n  <body>\n    <main>\n      <section>\n        <h1>자기소개</h1>\n        <p id="intro">웹 개발 학습 중</p>\n        <button id="change" type="button">소개 바꾸기</button>\n      </section>\n    </main>\n  </body>\n</html>',
    s04_reference: '학습 참고 자료',
    s05_title: 'CSS (Cascading Style Sheets)',
    s05_lead: '웹 문서의 색상 · 글꼴 · 배치를 지정',
    s05_selector_label: '선택자 (Selector)',
    s05_selector: '스타일을 적용할 대상을 가리키는 부분',
    s05_declaration_label: '선언 (Declaration)',
    s05_declaration: '중괄호 안에 작성하는 속성과 값의 한 쌍',
    s05_details_label: '선택자와 선언 예시',
    s05_selector_1: '태그 · 클래스 · ID',
    s05_selector_2: '결합자: 자식, 자손, 형제',
    s05_descendant: '(공백)',
    s05_selector_3: '상태 · 의사클래스',
    s05_selector_4: '의사요소',
    s05_block_label: '선언 블록',
    s05_declaration_2: '여러 선언을 중괄호로 묶어 구성',
    s05_reference: '학습 참고 자료',
    s51_title: 'JavaScript',
    s51_lead: '데이터 처리와 실행 흐름을 표현하는 프로그래밍 언어 · 브라우저 API와 연결해 페이지 기능 구현',
    s51_data_label: '데이터 처리',
    s51_data: '변수에 값 저장 · 조건과 반복으로 처리 · 함수로 작업 재사용',
    s51_event_label: '이벤트 반응',
    s51_event: '클릭 · 입력 · 페이지 로드 등의 이벤트에 실행할 함수 연결',
    s51_api_label: '브라우저 API 활용',
    s51_api: 'DOM으로 문서 변경 · fetch로 데이터 요청 · storage로 값 저장',
    s51_code_label: '소개 문구 선택과 함수 호출',
    s51_example: 'const messages = [\n  \'웹 개발 학습 중\',\n  \'HTML · CSS · JavaScript로 페이지 제작 중\'\n];\n\nfunction getIntroduction(index) {\n  return messages[index];\n}\n\nconst introduction = getIntroduction(1);\nconsole.log(introduction);',
    s51_reference: '학습 참고 자료',
    s47_preview_after: 'HTML · CSS · JavaScript로 페이지 제작 중',
    s47_preview_reset: '원래 소개로'
  },
  en: {
    'v2_browser-rendering_title': 'Web Browser Rendering Principles',
    'v2_browser-rendering_lead': 'From source elements and style rules to document models and the screen',
    v2_render_html: 'HTML parsing → DOM tree',
    v2_render_css: 'CSS parsing → CSSOM tree',
    v2_render_tree: 'DOM + CSSOM → Render Tree',
    v2_render_layout: 'Layout (position and size calculation)',
    v2_render_paint: 'Paint (drawing pixels)',
    v2_render_diagram_alt: 'HTML → DOM, CSS → CSSOM, JavaScript modifying DOM and CSSOM, DOM and CSSOM → Render Tree → Layout → Paint',
    'v2_source-to-screen_title': 'Web Browser Rendering Process',
    v2_dom_html: '<section class="profile">\n  <h1>About Me</h1>\n  <p id="intro" aria-live="polite">Learning web development.</p>\n  <button id="change" type="button">Change Introduction</button>\n</section>',
    v2_dom_h1: 'About Me',
    v2_dom_text: '#text: Learning web development.',
    v2_dom_button: '#text: Change Introduction',
    v2_dom_target: 'p#intro corresponds to the introduction paragraph',
    v2_dom_visible_alt: 'Visible paragraph',
    v2_dom_visible: 'Visible paragraph',
    'v2_dom-nodes_title': 'DOM (Document Object Model)',
    'v2_dom-nodes_lead': 'An interface representing an HTML document as an object tree, allowing programs to read and modify its structure and content',
    v2_css_rules: 'body {\n  color: #333;\n}\nbutton {\n  background: #1f6b4a;\n}\nbutton:hover {\n  background: #174f37;\n}',
    v2_css_sheet: 'CSSOM · style.css',
    v2_css_rule_fields: 'Rule objects containing a selector and declarations (properties and values)',
    v2_css_matching_title: 'Matching',
    v2_css_matching_definition: 'Finding elements that satisfy a selector’s conditions',
    v2_css_matching_example: 'A hovered button matches both button and button:hover',
    v2_css_cascade_title: 'Cascade',
    v2_css_cascade_definition: 'Choosing a declaration by priority when several target the same property on the same element',
    v2_css_cascade_example: 'Here, the more specific button:hover sets the background to #174f37',
    v2_css_inheritance_title: 'Inheritance',
    v2_css_inheritance_definition: 'Using the parent’s value when an inherited property such as color has no declaration',
    v2_css_inheritance_example: 'p has no color declaration → inherits #333 through its parents from body',
    'v2_css-rule-objects_title': 'CSSOM (CSS Object Model)',
    'v2_css-rule-objects_lead': 'An interface representing CSS stylesheets and rules as objects that programs can read and modify',
    v2_render_dom_title: 'DOM · Elements and Content',
    v2_render_heading_text: 'About Me',
    v2_render_paragraph_text: 'Learning web development.',
    v2_render_button_text: 'Change Introduction',
    v2_render_cssom_title: 'CSSOM · Style Rules',
    v2_render_result_title: 'Render Tree',
    v2_render_scope: 'portfolio/about.html · portfolio/style.css — selected elements and styles from the profile section',
    'v2_rendering-box-tree_title': 'Render Tree',
    'v2_rendering-box-tree_lead': 'A tree of rendering objects built from DOM elements and their CSSOM styles',
    v2_layout_css: '* {\n  box-sizing: border-box;\n}\n\n.profile {\n  width: 360px;\n  max-width: 100%;\n  padding: 24px;\n  background: #f0f3ef;\n  border-radius: 8px;\n}',
    v2_layout_measure: 'Measured button position · origin at the card’s top-left corner',
    v2_layout_heading: 'About Me',
    v2_layout_text: 'Building my first website.',
    v2_layout_equation: 'border-box · 360 − 24 − 24 = 312px content width · no border',
    'v2_layout-geometry_title': 'Layout: Position and Size',
    'v2_layout-geometry_lead': 'CSS values determine box dimensions and child positions',
    v2_paint_css: '.profile {\n  background: #f0f3ef;\n}\n\nbutton {\n  background: #1f6b4a;\n  color: white;\n}',
    v2_paint_screen_alt: '① Card background · ② Button background · ③ Button text',
    v2_paint_screen: '① Card background · ② Button background · ③ Button text',
    v2_layer_heading: 'About Me',
    v2_layer_text: 'Learning web development.',
    v2_layer_button: 'Change Introduction',
    v2_paint_frame: 'Composited frame',
    v2_paint_note: 'Layer boundaries do not map one-to-one to DOM tags · the layer illustration is conceptual',
    'v2_paint-composite_title': 'Paint',
    'v2_paint-composite_lead': 'Drawing element backgrounds, text, and borders using the positions and sizes calculated during layout',
    w2_original_rendering_methods_csr_flow: 'HTML shell → JavaScript → UI generated in the browser',
    w2_original_rendering_methods_csr_points0: 'UI updates in response to state changes',
    w2_original_rendering_methods_csr_points1: 'Initial content depends on JavaScript download and execution',
    w2_original_rendering_methods_csr_points2: 'Search processing depends on JavaScript support and rendering cost',
    w2_original_rendering_methods_csr_use: 'Typical use: interactive feeds and dashboards',
    w2_original_rendering_methods_csr: 'CSR · Client-side Rendering',
    w2_original_rendering_methods_ssr_flow: 'Request → HTML generated on the server → browser',
    w2_original_rendering_methods_ssr_points0: 'Main content included in the initial response',
    w2_original_rendering_methods_ssr_points1: 'Server response time, load and caching matter',
    w2_original_rendering_methods_ssr_points2: 'Content can appear before hydration makes it interactive',
    w2_original_rendering_methods_ssr_use: 'Typical use: pages requiring request-time data',
    w2_original_rendering_methods_ssr: 'SSR · Server-side Rendering',
    w2_original_rendering_methods_ssg_flow: 'HTML generated at build time → served as static files',
    w2_original_rendering_methods_ssg_points0: 'No need to generate HTML for every request',
    w2_original_rendering_methods_ssg_points1: 'Well suited to CDN caching; a CDN is optional',
    w2_original_rendering_methods_ssg_points2: 'Changes to pregenerated content require regeneration',
    w2_original_rendering_methods_ssg_use: 'Typical use: documentation, blogs and marketing pages',
    w2_original_rendering_methods_ssg: 'SSG · Static Site Generation',
    w2_original_rendering_methods_combine: 'Initial SSR or SSG can be combined with client updates; performance and SEO also depend on code, content, networks and caching',
    'v2_original-rendering-methods_title': 'Web Rendering Strategies',
    'v2_original-rendering-methods_lead': 'Differences in where and when page content is generated',
    w2_original_rendering_performance_lcp: 'LCP · Largest Contentful Paint',
    w2_original_rendering_performance_lcp_body: 'When the largest image or text content in the viewport is rendered · loading performance',
    w2_original_rendering_performance_inp: 'INP · Interaction to Next Paint',
    w2_original_rendering_performance_inp_body: 'Responsiveness based on delays from clicks, taps and keyboard input to the next paint',
    w2_original_rendering_performance_cls: 'CLS · Cumulative Layout Shift',
    w2_original_rendering_performance_cls_body: 'Unexpected layout shift scores throughout a page visit · the largest session-window total',
    w2_original_rendering_performance_fcp: 'FCP is a supporting loading metric for the first text, image or other content',
    w2_original_rendering_performance_vitals: 'Core Web Vitals · LCP / INP / CLS',
    w2_original_rendering_performance_study: 'Google/SOASTA mobile research · 2017 · relative increases compared with a 1-second load',
    w2_original_rendering_performance_load: 'Load-time Change',
    w2_original_rendering_performance_increase: 'Increase in Bounce Probability',
    w2_original_rendering_performance_relative: 'Relative increases, not absolute bounce rates or universal predictions for every site',
    w2_original_rendering_performance_seo: 'Better performance supports user experience and search quality; it does not guarantee rankings or conversion rates',
    w2_original_rendering_performance_bounce: 'Load Delay and Bounce Probability',
    'v2_original-rendering-performance_title': 'Web Rendering Performance',
    'v2_original-rendering-performance_lead': 'Loading, responsiveness and visual stability shape the user experience',
    'v2_routing-semantic-html_title': 'Semantic HTML and Routing',
    c3_sem_structure: 'Document roles expressed by elements',
    c3_tag_header: 'Introduction to a document or section',
    c3_tag_nav: 'Major navigation links',
    c3_tag_main: 'The page’s main content',
    c3_tag_article: 'Self-contained content',
    c3_tag_aside: 'Content tangentially related to its surroundings',
    c3_tag_footer: 'Authorship, copyright and related section information',
    c3_div: 'div is a generic container. class="nav" alone does not give it navigation semantics.',
    c3_search_understanding: 'How Search Engines Understand Content',
    c3_search_semantics: 'Search engines analyze content and HTML structure; appropriate elements help communicate document roles.',
    c3_crawl: 'Crawling\nDiscover and fetch',
    c3_index: 'Indexing\nAnalyze and store',
    c3_rank: 'Search query\nSelect and rank results',
    c3_ax_title: 'Accessibility Tree',
    c3_ax_definition: 'A tree built by the browser from DOM, CSS and ARIA information, exposing roles, names and states to assistive technologies',
    c3_ax_effect: 'Appropriate elements support document navigation and make code easier to understand.',
    c3_glossary_seo: 'Improving content so search engines can discover, understand and present it for relevant searches.',
    c3_glossary_aeo: 'Organizing content so search and answer systems can use it to answer questions directly.',
    c3_glossary_geo: 'Improving content and structure so generative AI can use and cite it in answers.',
    'v2_original-semantic-html_title': 'Semantic HTML',
    'v2_original-semantic-html_lead': 'Expressing document structure with HTML elements that match the meaning and role of content',
    c3_scheme: 'Scheme',
    c3_host: 'Host',
    c3_path: 'Full path',
    c3_query: 'Query · sort = date',
    c3_fragment: 'Fragment',
    c3_segments_title: 'Path Segments and Route Parameters',
    c3_segments: 'blog, 2024 and first-post are path segments separated by /',
    c3_pattern: 'Route pattern',
    c3_actual: 'Actual path',
    c3_dynamic: 'Segments are dynamic when declared as parameters such as [year] and [slug]. Actual URL values alone do not establish this.',
    c3_url_route_title: 'Selecting a Page for a URL',
    c3_match: 'Router\nMatch path',
    c3_about: 'About\npage',
    c3_fragment_title: 'Query and Fragment',
    c3_query_detail: '?sort=date: a query included in the request, usable for additional conditions such as sorting.',
    c3_fragment_detail: '#comments: can navigate to an element with id="comments". The fragment is processed in the browser and is not sent in the HTTP request.',
    'v2_original-routing-url_title': 'Routing and URL Structure',
    'v2_original-routing-url_lead': 'Routing selects a page or request handler for a URL path',
    c3_mpa: 'New-document Navigation · Typical MPA',
    c3_mpa1: 'Select link → request /about',
    c3_mpa2: 'Server returns the HTML response for the path',
    c3_mpa3: 'Browser loads and displays a new document',
    c3_mpa4: 'Browser manages the URL and session history',
    c3_mpa_note: 'HTML may be a static file or generated by the server. A new document does not necessarily mean flicker or slow navigation.',
    c3_spa: 'Same-document Navigation · SPA Style',
    c3_spa1: 'Select link → client router handles the path',
    c3_spa2: 'Prepare data and code (reuse what is already available)',
    c3_spa3: 'Update the view within the existing document',
    c3_spa4: 'Router updates URL/history and handles back navigation',
    c3_spa_note: 'A SPA keeps one HTML document while navigating between views at multiple URLs. JSON requests are not required for every transition.',
    c3_rendering: 'Relation to Rendering',
    c3_rendering_detail: 'SSR/CSR describe where content is generated. Initial SSR can be combined with later client-side navigation.',
    c3_speed: 'Speed',
    c3_speed_detail: 'Reusing the document and UI can help. Actual speed depends on JavaScript, data requests, caching and more.',
    c3_search: 'SEO',
    c3_search_detail: 'Routing alone does not determine SEO. Search engines must be able to access content, links and metadata for each URL.',
    'v2_original-routing-types_title': 'Server and Client Routing',
    'v2_original-routing-types_lead': 'Navigation can load a new HTML document or update a view within the existing document',
    c4_chapter_title: 'Web Browser Developer Tools',
    c4_open: 'Open Chrome DevTools · Windows: F12 / Ctrl+Shift+I · macOS: ⌥⌘I',
    c4_elements_steps: 'Inspect in Elements',
    c4_inspect: 'Right-click an element → Inspect',
    c4_dom: 'Read the selected node’s tag, attributes, parents and children',
    c4_semantic: 'Check the document roles of header, nav, main and footer',
    c4_styles: 'Styles: CSS rules · Computed: computed styles',
    c4_live_dom: 'Elements shows the current DOM, including JavaScript changes; it can differ from the HTML response.',
    c4_dom_map: 'Document Structure and Inspection Targets',
    c4_head: 'title → document title\nmeta[name="description"] → page description\nmeta[name="viewport"] → mobile viewport settings',
    c4_body: 'header · nav → introduction and navigation\nmain → main content\nfooter → document information',
    c4_metadata: 'Expand head to read title and meta values; their presence alone does not guarantee search visibility or ranking.',
    'v2_devtools-elements_title': 'Document Elements and Metadata',
    'v2_devtools-elements_lead': 'Inspect the current DOM structure, attributes and element styles in the Elements panel',
    c4_device_toggle: 'Toggle Device Toolbar in DevTools · Windows: Ctrl+Shift+M · macOS: ⇧⌘M',
    c4_device_steps: 'Inspect at Different Viewports',
    c4_responsive: 'Choose Responsive or a device preset under Dimensions',
    c4_dimensions: 'Change width and height; rotate between portrait and landscape',
    c4_wrap: 'Check menu and paragraph wrapping and image sizing',
    c4_overflow: 'Check horizontal scrolling, clipped content and overlap',
    c4_css_pixels: 'Dimensions are in CSS pixels, not the physical pixel resolution of a device.',
    c4_device_limit: 'Device Mode simulates display and input conditions; real mobile browsers also need testing.',
    c4_mobile_alt: 'Portfolio page at a viewport width of 390 CSS pixels',
    c4_tablet_alt: 'Portfolio page at a viewport width of 820 CSS pixels',
    c4_viewport_caption: 'The same portfolio page at viewport widths of 390 / 820 CSS pixels',
    'v2_devtools-viewport_title': 'Responsive Layout and Viewport',
    'v2_devtools-viewport_lead': 'Use the Device Toolbar to change viewport dimensions and inspect layout and overflow',
    c4_network_path: 'Network → reload the page → Doc filter → select the document request for the current page URL',
    c4_headers: 'Headers · Response Information',
    c4_headers_example: 'Example HTML response header',
    c4_request_url: 'Request URL: check that this is the intended document',
    c4_status: 'Status Code: inspect the response status (for example, 200 OK)',
    c4_content_type: 'Content-Type: text/html declares HTML; charset=utf-8 declares the text encoding',
    c4_charset: 'charset may be absent from the header; also inspect encoding declarations such as meta charset in the HTML.',
    c4_response: 'Response · HTML Body',
    c4_response_html: 'HTML received in the response',
    c4_response_dom: 'Current DOM after parsing and changes',
    c4_response_tab: 'Open Response to inspect the document’s HTML body',
    c4_response_content: 'Check whether title, meta and main content are in the response',
    c4_response_compare: 'Compare with Elements to distinguish response HTML from current DOM',
    c4_doc_select: 'Select by URL, not simply the first Doc entry; client-side navigation may not request a new document.',
    'v2_devtools-network_title': 'HTML Response and Response Headers',
    'v2_devtools-network_lead': 'Select the document request in Network to inspect its response type and HTML body',
    'v2_original-framework-15_title': 'Development with Web Frameworks',
    'v2_original-framework-15_lead': 'Svelte · SvelteKit · Components · Data',
    w2_16_parts_items0: 'Structure: file conventions and separation of responsibilities',
    w2_16_parts_items1: 'Request handling: routing, middleware, validation and authentication integration',
    w2_16_parts_items2: 'Data: loading functions and database access tools',
    w2_16_parts_items3: 'Build and runtime: bundling, code splitting, rendering and deployment',
    w2_16_parts_note: 'Features vary by framework and may require additional libraries',
    w2_16_parts: 'Examples of Framework Features',
    w2_16_ui: 'UI Libraries and Frameworks',
    w2_16_ui_names: 'React · Vue · Angular · Svelte',
    w2_16_backend: 'Backend Frameworks',
    w2_16_backend_names: 'Express · NestJS · Django · FastAPI · Spring Boot',
    w2_16_full: 'Full-stack Frameworks',
    w2_16_full_names: 'Next.js · Nuxt · SvelteKit',
    w2_16_types: 'Tools by Development Area',
    w2_16_choose: 'Selection criteria: team skills, rendering and server needs, hosting, documentation, ecosystem and maintenance',
    'v2_original-framework-16_title': 'Web Development Frameworks',
    'v2_original-framework-16_lead': 'Conventions and tools for project structure and recurring development tasks',
    w2_17_runtime_items0: 'Runs development servers, build tools, CLIs and server programs',
    w2_17_runtime_items1: 'File and process APIs instead of browser globals such as document and window',
    w2_17_runtime_items2: 'npm manages project dependencies and scripts',
    w2_17_node_code: 'console.log(\'Hello from Node.js\');',
    w2_17_node_cmd: 'node hello.js',
    w2_17_runtime: 'Runtime and Uses',
    w2_17_io_items0: 'Other requests can make progress while I/O is pending',
    w2_17_io_items1: 'JavaScript callbacks run mainly on one event loop',
    w2_17_io_items2: 'The OS and worker pool handle some I/O and other work',
    w2_17_io_items3: 'Long synchronous work blocks the event loop and delays other requests',
    w2_17_io_note: 'Asynchronous design alone does not guarantee speed or low memory use',
    w2_17_io: 'Asynchronous I/O and the Event Loop',
    w2_17_version: 'Practice environment: Node.js 24 · verify with node -v / npm -v',
    'v2_original-framework-17_title': 'The Node.js Runtime',
    'v2_original-framework-17_lead': 'JavaScript outside the browser, powered by the V8 engine',
    w2_18_terminal: 'Terminal',
    w2_18_terminal_body: 'An application displaying input and output · Windows Terminal, macOS Terminal',
    w2_18_shell: 'Shell',
    w2_18_shell_body: 'A program interpreting and executing commands · PowerShell, bash, zsh',
    w2_18_path: 'Paths and the Working Directory',
    w2_18_path_body: 'Path: a file or directory location · cwd: the directory used to resolve relative paths',
    w2_18_prompt: 'Prompt: ready for input · . current directory · .. parent directory · ~ home directory',
    w2_18_terms: 'Terminal, Shell and Paths',
    w2_18_cli: 'cd pwd-week2\nnode -v\nnpm -v\nnpm run dev',
    w2_18_cli_items0: 'Repeat and automate procedures with scripts',
    w2_18_cli_items1: 'Improve reproducibility by fixing versions, inputs and environments',
    w2_18_cli_items2: 'The same command can differ with the directory, configuration or version',
    w2_18_commands: 'Running Commands in a Project',
    'v2_original-framework-18_title': 'CLI · Command-line Interface',
    'v2_original-framework-18_lead': 'An interface for running tools and automating tasks with text commands',
    w2_19_npm_points0: 'package.json: dependencies and script definitions',
    w2_19_npm_points1: 'package-lock.json: resolved versions for reproducible installation',
    w2_19_npm_points2: 'npm install: install dependencies · npm run dev: run the dev script',
    w2_19_npm_commands: 'npm --version\nnpm install\nnpm run dev',
    w2_19_ci: 'For the supplied practice source, use npm ci to install from the lockfile',
    w2_19_npm: 'npm · Packages and Scripts',
    w2_19_npx_body: 'Runs commands without a separate global installation; uses local packages or installs them in the npm cache',
    w2_19_npx_commands: 'npx sv@0.17.0 create pwd-week2\ncd pwd-week2\nnpm run dev',
    w2_19_npx_scope: 'For creating a new project; do not rerun it inside the supplied project',
    w2_19_windows: 'If PowerShell blocks the .ps1 launcher, use npm.cmd and npx.cmd',
    w2_19_npx: 'npx · Running Package Commands',
    'v2_original-framework-19_title': 'npm and npx',
    'v2_original-framework-19_lead': 'Managing project dependencies and running package commands',
    sv_svelte: 'Svelte · UI Framework',
    sv_compiler: 'The compiler turns components into JavaScript and CSS for the browser',
    sv_dom: 'Compiled code and runtime update the DOM without Virtual DOM diffing',
    sv_ui: 'Provides components, reactive state, events and styles',
    sv_runtime: 'Compiler-based does not mean runtime-free; bundle size and performance depend on the app',
    sv_kit: 'SvelteKit · Web Application Framework',
    sv_kit_features: 'Provides filesystem routing, data loading, server APIs and deployment support',
    sv_kit_render: 'Supports SSR, prerendering (SSG) and client-side navigation',
    sv_languages: 'Both Svelte and SvelteKit support JavaScript and TypeScript; TypeScript is optional',
    sv_js: 'JavaScript',
    sv_js_file: 'Components use .svelte; load and API files use .js',
    sv_ts: 'TypeScript',
    sv_ts_file: 'Components still use .svelte; load and API files can use .ts',
    'v2_original-framework-20_title': 'Svelte and SvelteKit',
    'v2_original-framework-20_lead': 'Build UIs and web applications with HTML, CSS, and JavaScript or TypeScript',
    sv_compare_dimension: 'Dimension',
    sv_compare_syntax: 'UI syntax',
    sv_compare_syntax0: 'JSX',
    sv_compare_syntax1: 'Template / JSX',
    sv_compare_syntax2: '.svelte',
    sv_compare_reactivity: 'State / reactivity',
    sv_compare_reactivity0: 'useState / useReducer',
    sv_compare_reactivity1: 'ref / reactive',
    sv_compare_reactivity2: '$state / $derived',
    sv_compare_updates: 'DOM updates',
    sv_compare_updates0: 'Reconciliation',
    sv_compare_updates1: 'Reactivity and compiled render functions',
    sv_compare_updates2: 'Compiled update code',
    sv_compare_language: 'Languages',
    sv_compare_language0: 'JavaScript / TypeScript',
    sv_compare_language1: 'JavaScript / TypeScript',
    sv_compare_language2: 'JavaScript / TypeScript',
    sv_size: 'Bundle Size and Runtime Performance',
    sv_size_conditions: 'Compare equivalent features, dependencies, build settings and environments; the framework name alone does not determine results',
    sv_choice: 'Learning and Maintenance',
    sv_choice_conditions: 'Consider the team’s experience, required libraries, documentation and long-term maintenance needs',
    'v2_original-framework-21_title': 'Comparing Frontend UI Approaches',
    'v2_original-framework-21_lead': 'Differences in syntax, reactivity and DOM updates',
    sv_code_counterJS: '<script>\n  let name = $state(\'world\');\n  let count = $state(0);\n</script>\n\n<h1>Hello {name}!</h1>\n<input aria-label="Name" bind:value={name} />\n<button onclick={() => count += 1}>\n  clicks: {count}\n</button>\n\n<style>\n  h1 { color: #5b3df5; }\n</style>',
    sv_code_counterTS: '<script lang="ts">\n  let name: string = $state(\'world\');\n  let count: number = $state(0);\n</script>\n\n<h1>Hello {name}!</h1>\n<input aria-label="Name" bind:value={name} />\n<button onclick={() => count += 1}>\n  clicks: {count}\n</button>\n\n<style>\n  h1 { color: #5b3df5; }\n</style>',
    sv_file_parts: 'script: state and functions · markup: UI structure · style: component-scoped CSS',
    sv_module: 'Shared module code belongs in <script module> and runs when the module is evaluated; both languages pass a function to onclick',
    sv_ts_scope: 'Svelte 5 supports type annotations and interfaces; TS features that generate code, such as enums, require preprocessing',
    'v2_original-framework-22_title': 'Svelte File Structure and Languages',
    'v2_original-framework-22_lead': 'Write the same .svelte component in JavaScript or TypeScript',
    w2_23_tree: 'pwd-week2/\n├─ src/\n│  ├─ routes/\n│  ├─ lib/\n│  ├─ app.html\n│  └─ app.css\n├─ static/\n├─ package.json\n├─ package-lock.json\n├─ svelte.config.js\n├─ vite.config.js\n├─ .gitignore\n└─ README.md',
    w2_23_roles_list0: 'src/routes: pages, layouts, load functions and API routes',
    w2_23_roles_list1: 'src/lib: shared code imported with the $lib alias',
    w2_23_roles_list2: 'src/app.html: HTML shell · app.css: global styles to import',
    w2_23_roles_list3: 'static: assets served without transformation',
    w2_23_roles_list4: 'Configuration files: package, SvelteKit and Vite settings',
    w2_23_installed: 'node_modules is generated during installation and excluded from Git',
    w2_23_roles: 'Key Files and Directories',
    w2_23_options: 'Structure of the practice project; generated files vary with selected options and tools',
    'v2_original-framework-23_title': 'SvelteKit Project Structure',
    'v2_original-framework-23_lead': 'File locations and names distinguish pages, shared code and configuration',
    sv_static_route: 'src/routes/about/+page.svelte → /about',
    sv_code_routeLoad: 'export function load({ params }) {\n  return { id: params.id };\n}',
    sv_code_routePage: '<script>\n  let { data } = $props();\n</script>\n\n<h1>Blog post #{data.id}</h1>',
    sv_route_data: '[id] defines a path parameter; data contains load results, so params and data are distinct',
    sv_nested_path: 'Nested route: src/routes/dashboard/reports/[id]/+page.svelte → /dashboard/reports/42',
    'v2_original-framework-24_title': 'Filesystem Routing',
    'v2_original-framework-24_lead': 'Use directory names for static paths and [parameters] for dynamic paths',
    w2_25_nested_tree: 'src/routes/\n├─ +layout.svelte\n├─ +layout.js\n├─ +page.svelte\n└─ dashboard/\n   ├─ +layout.svelte\n   ├─ +layout.js\n   ├─ +page.svelte\n   └─ reports/\n      ├─ +page.svelte\n      └─ [id]/\n         └─ +page.svelte',
    w2_25_root_page: 'routes/+page.svelte → /',
    w2_25_dashboard_page: 'dashboard/+page.svelte → /dashboard',
    w2_25_report_page: 'reports/+page.svelte → /dashboard/reports',
    w2_25_id_page: 'reports/[id]/+page.svelte → /dashboard/reports/42',
    w2_25_layout_scope: '+layout.svelte: shared UI for the route and descendants; render children to display the page',
    w2_25_parent: 'A child load function can await parent() to reuse parent layout data',
    w2_25_nested: 'Paths and Their Files',
    w2_25_optional: 'Not every directory needs a page or layout; add +layout.js when shared data is required',
    'v2_original-framework-25_title': 'Nested Routes and Shared Layouts',
    'v2_original-framework-25_lead': 'Directory nesting defines URLs and supports shared UI and data',
    w2_26_state_body: 'Input, toggle and array changes reflected in the UI',
    w2_26_code_state: '<script>\n  let name = $state(\'world\');\n  let on = $state(false);\n  let list = $state([\'a\']);\n</script>\n\n<input aria-label="Name"\n  bind:value={name} />\n<button onclick={() => on = !on}>\n  {on ? \'ON\' : \'OFF\'}\n</button>\n<button\n  onclick={() => list.push(\'item\')}>\n  Add\n</button>\n<p>{name} / {list.length}</p>',
    w2_26_state: '$state · Mutable State',
    w2_26_derived_body: 'Invalidated when dependencies change; recomputed when read',
    w2_26_code_derived: '<script>\n  let prices = $state(\n    [1000, 2500, 3000]\n  );\n  let total = $derived(\n    prices.reduce((s, p) => s + p, 0)\n  );\n  let label = $derived(\n    total.toLocaleString(\'en-US\') +\n      \' KRW\'\n  );\n</script>\n\n<p>{total} / {label}</p>',
    w2_26_derived: '$derived · Computed Values',
    w2_26_effect_body: 'Runs initially in the browser and reruns when synchronously read reactive dependencies change',
    w2_26_code_focus: '<script>\n  let open = $state(false);\n  let el = $state();\n  $effect(() => {\n    if (open && el) el.focus();\n  });\n</script>\n\n<button onclick={() => open = !open}>\n  {open ? \'Close\' : \'Open\'}\n</button>\n{#if open}\n  <input aria-label="Note"\n    bind:this={el} />\n{/if}',
    w2_26_effect: '$effect · External Synchronization',
    w2_26_effect_purpose: 'Use $derived for computed UI values; calculations inside an effect are not prohibited',
    'v2_original-framework-26_title': 'State, Derived Values and Effects',
    'v2_original-framework-26_lead': 'JavaScript declarations and Svelte reactivity runes',
    sv_code_grade: '<script>\n  let score = $state(0);\n  let grade = $derived.by(() => {\n    if (score >= 90) return \'A\';\n    if (score >= 60) return \'B\';\n    return \'C\';\n  });\n</script>\n\n<input type="number" min="0" max="100"\n  aria-label="Score" bind:value={score} />\n{#if grade === \'A\'}\n  <p>Excellent! (A)</p>\n{:else if grade === \'B\'}\n  <p>Good (B)</p>\n{:else}\n  <p>Keep practicing (C)</p>\n{/if}',
    sv_derived: 'Derived Value · $derived.by',
    sv_grade_flow: 'score changes → grade is recalculated → matching paragraph is displayed',
    sv_derived_pure: 'Use if / else to return a value without changing other state',
    sv_if: 'Template Conditions',
    sv_if_syntax: 'Use {#if}, {:else if} and {:else} to select UI',
    sv_no_effect: 'Use $derived for values computed from state; use $effect for synchronization with the DOM or external systems',
    'v2_original-framework-27_title': 'Conditions',
    'v2_original-framework-27_lead': 'Derive a grade from state and select the corresponding UI',
    w2_28_each_points0: 'as todo: item · as todo, i: item and index',
    w2_28_each_points1: '(todo.id): a unique, stable key for tracking each item',
    w2_28_each_points2: 'Add button: insert an item into the array → update the list',
    w2_28_each_points3: 'bind:checked: connects the checkbox and done',
    w2_28_js: 'Iteration and Calculation in Scripts',
    w2_28_js_body: 'Use for, for…of, map or forEach; use reactive state or derived values when changes should update the UI',
    w2_28_static: 'A fixed array can also be rendered with {#each}; not every UI value requires runes',
    w2_28_each: 'Template Iteration · {#each}',
    w2_28_code_todos: '<script>\n  let nextId = 3;\n  let todos = $state([\n    { id: 1, text: \'Learn Svelte\', done: false },\n    { id: 2, text: \'Practice runes\', done: true }\n  ]);\n  function add() {\n    todos.push({\n      id: nextId++, text: \'New task\', done: false\n    });\n  }\n</script>\n\n<button onclick={add}>Add</button>\n<ul>\n  {#each todos as todo (todo.id)}\n    <li><label>\n      <input type="checkbox" bind:checked={todo.done} />\n      {todo.text}\n    </label></li>\n  {/each}\n</ul>',
    'v2_original-framework-28_title': 'Loops and List Rendering',
    'v2_original-framework-28_lead': 'Render array items and update each item’s state',
    w2_29_syntax: 'onclick={handler} · oninput={handler} · onmousemove={handler}',
    w2_29_event_points0: 'click: activation · input: value change · submit: form submission',
    w2_29_event_points1: 'keydown: key press · mousemove: mouse movement',
    w2_29_event_points2: 'Read values, coordinates and other details from the event object',
    w2_29_window: 'svelte:window handles window events and cleans up listeners on teardown',
    w2_29_events: 'Event Attributes',
    w2_29_code_mouse: '<script>\n  let m = $state({ x: 0, y: 0 });\n  function handleMousemove(event) {\n    m.x = event.clientX;\n    m.y = event.clientY;\n  }\n</script>\n\n<svelte:window onmousemove={handleMousemove} />\n<p>Mouse: {m.x} × {m.y}</p>',
    w2_29_mouse_flow0: 'Mouse movement',
    w2_29_mouse_flow1: 'event.clientX / clientY',
    w2_29_mouse_flow2: 'Update m.x / m.y',
    w2_29_mouse_flow3: 'Display coordinates',
    w2_29_coords: 'clientX and clientY are viewport-relative coordinates in CSS pixels',
    'v2_original-framework-29_title': 'Events and Handlers',
    'v2_original-framework-29_lead': 'Connect functions to user input and browser events',
    sv_code_lifecycle: '<script>\n  import { onMount } from \'svelte\';\n  let count = $state(0);\n\n  onMount(() => {\n    const timer = setInterval(() => count++, 1000);\n    return () => clearInterval(timer);\n  });\n\n  $effect.pre(() => {\n    console.log(\'Before DOM update:\', count);\n  });\n  $effect(() => {\n    console.log(\'After DOM update:\', count);\n  });\n</script>\n\n<h1>{count}</h1>',
    sv_mount: 'onMount · After Mount',
    sv_mount_note: 'Runs after mounting in the browser, not during SSR',
    sv_cleanup: 'A function returned by a synchronous onMount callback runs on teardown to clear the timer',
    sv_effects: '$effect.pre / $effect',
    sv_effects_note: 'Run initially in the browser, then rerun when synchronously read reactive dependencies change',
    sv_effects_timing: ' $effect.pre: before DOM updates · $effect: after DOM updates',
    sv_destroy: 'onDestroy also registers teardown and runs during SSR; declare count with $state so the UI and effects track changes',
    'v2_original-framework-30_title': 'Lifecycle and Reactive Effects',
    'v2_original-framework-30_lead': 'Manage resources on mount and teardown; distinguish work before and after DOM updates',
    w2_31_guard_script: '<script>\n  import { beforeNavigate } from \'$app/navigation\';\n  let { children } = $props();\n  let dirty = $state(false);\n\n  beforeNavigate((nav) => {\n    if (!dirty) return;\n    if (nav.type === \'leave\' ||\n        !confirm(\'Leave without saving?\')) {\n      nav.cancel();\n    }\n  });\n</script>',
    w2_31_life: 'onMount and onDestroy: resource management on mount and teardown',
    w2_31_before: 'beforeNavigate: inspect or cancel a navigation',
    w2_31_on: 'onNavigate: runs before navigation; a returned function runs after the DOM update',
    w2_31_after: 'afterNavigate: runs on initial mount and after navigation',
    w2_31_load: 'load: prepares page or layout data',
    w2_31_guard_markup: '<label>Draft\n  <textarea oninput={() => dirty = true}></textarea>\n</label>\n<main>{@render children()}</main>',
    w2_31_hooks: 'Key Execution Points',
    w2_31_leave: 'In-app navigation: cancel based on confirm; leave navigations such as closing the tab: cancel() requests the browser’s native confirmation',
    'v2_original-framework-31_title': 'Hooks and Navigation Control',
    'v2_original-framework-31_lead': 'Register callbacks at defined points to extend or control behavior',
    w2_32_code_Parent: '<script>\n  import Child from \'./Child.svelte\';\n  let message = $state(\'Hello!\');\n</script>\n\n<button onclick={() => message = \'Updated!\'}>\n  Update\n</button>\n<Child msg={message} />',
    w2_32_code_Child: '<script>\n  const { msg } = $props();\n</script>\n\n<p>{msg}</p>',
    w2_32_prop_flow0: 'Parent message',
    w2_32_prop_flow1: '<Child msg={message} />',
    w2_32_prop_flow2: 'msg from $props()',
    w2_32_prop_flow3: 'Child paragraph updates',
    w2_32_prop_rules: 'Parent updates reach the child; treat props as read-only inputs and use callbacks to request changes',
    'v2_original-framework-32_title': 'Props · Values from Parent to Child',
    'v2_original-framework-32_lead': 'Receive component inputs with $props() and use them in the UI',
    sv_code_binding_start: '<script>\n  let name = $state(\'\');\n  let agree = $state(false);\n  let color = $state(\'red\');\n  let level = $state(50);\n  let files = $state();\n</script>\n\n<label>Name: <input bind:value={name} /></label>\n<p>{name || \'(empty)\'}</p>\n<label>\n  <input type="checkbox" bind:checked={agree} />\n  I agree\n</label>\n<p>{agree ? \'Yes\' : \'No\'}</p>',
    sv_code_binding_end: '<label>Color:\n  <select bind:value={color}>\n    <option>red</option><option>green</option>\n    <option>blue</option>\n  </select>\n</label>\n<p>{color}</p>\n<label>Level: {level}\n  <input type="range" min="0" max="100"\n    bind:value={level} />\n</label>\n<label>Files:\n  <input type="file" multiple bind:files={files} />\n</label>\n{#if files}<p>{files.length} files</p>{/if}',
    sv_binding_runes: 'Svelte 5 runes mode: use $state for changing values; value binds the input value, checked the check state, and files a FileList',
    'v2_original-framework-33_title': 'Two-way Binding',
    'v2_original-framework-33_lead': 'Input updates state, and state changes update the bound input and UI',
    w2_34_code_Card: '<script>\n  let { title, summary, href } = $props();\n</script>\n\n<article class="card">\n  <h3><a href={href}>{title}</a></h3>\n  <p>{summary}</p>\n</article>',
    w2_34_code_Cards: '<script>\n  import Card from \'$lib/Card.svelte\';\n  let { data } = $props();\n</script>\n\n<h2>Projects</h2>\n{#each data.projects as p (p.slug)}\n  <Card title={p.title} summary={p.summary}\n    href={\'/projects/\' + p.slug} />\n{:else}\n  <p>No projects yet.</p>\n{/each}',
    w2_34_inputs_body: 'Pass title, summary and href to each card; compose the page from repeated Card instances',
    w2_34_inputs: 'Inputs and Composition',
    w2_34_value_body: 'Centralized UI changes, isolated testing and clear code responsibilities',
    w2_34_value: 'Maintenance and Collaboration',
    w2_34_data: 'data.projects comes from the page load function; components can range from small buttons to entire pages',
    'v2_original-framework-34_title': 'Components and UI Reuse',
    'v2_original-framework-34_lead': 'Reusable UI units combining markup, behavior, state and styles',
    sv_server: 'Server-only Execution',
    sv_server_only: '+server.js is not included in the browser bundle; access databases and secrets on the server',
    sv_secrets: 'Returned data reaches the client; implement authorization and exclude secrets from responses',
    sv_method: 'Methods and Responses',
    sv_method_response: 'Export GET, POST or other method handlers; return Response or json(data); error(status, message) throws',
    sv_context: 'Request Context',
    sv_request_context: 'request: request · url: URL and query · params: path parameters · cookies: cookies',
    sv_locals: 'locals: server-side information shared within a request, such as the authenticated user',
    sv_load_kind: 'Page Data Loading',
    sv_load_kind_detail: '+page.js: universal load that can run on server and browser\n+page.server.js: server-only load',
    'v2_original-framework-35_title': 'API Routes and Request Handling',
    'v2_original-framework-35_lead': 'HTTP method functions in +server.js handle requests and return a Response',
    sv_code_api: 'import { json } from \'@sveltejs/kit\';\n\nconst projects = [\n  { slug: \'timetable\',\n    title: \'Timetable Helper\',\n    summary: \'Classes and schedules\' },\n  { slug: \'gallery\',\n    title: \'Image Gallery\',\n    summary: \'A small image gallery\' },\n  { slug: \'memo\',\n    title: \'Memo Pad\',\n    summary: \'Local notes\' }\n];\n\nexport function GET() {\n  return json(projects);\n}',
    sv_code_projectsLoad: 'import { error } from \'@sveltejs/kit\';\n\nexport async function load({ fetch }) {\n  const res = await fetch(\'/api/projects\');\n  if (!res.ok) {\n    error(res.status, \'Load failed\');\n  }\n  return { projects: await res.json() };\n}',
    sv_code_projectsPage: '<script>\n  import Card from \'$lib/Card.svelte\';\n  let { data } = $props();\n</script>\n\n<h2>Projects</h2>\n{#each data.projects as p (p.slug)}\n  <Card title={p.title}\n    summary={p.summary}\n    href={\'/projects/\' + p.slug} />\n{:else}\n  <p>No projects yet.</p>\n{/each}',
    sv_api_card: 'Reuse src/lib/Card.svelte from the component example; API handling, data loading and UI markup belong in different files',
    'v2_original-framework-36_title': 'API Responses and Page Data',
    'v2_original-framework-36_lead': 'Fetch the API response in load and pass its data to the page component',
    w2_37_steps0: 'Enter the script, markup and style of a .svelte component',
    w2_37_steps1: 'Change state, events and bindings and compare the output',
    w2_37_steps2: 'Inspect compiler errors, warnings and their locations',
    w2_37_kit_limit: 'Run SvelteKit pages, layouts, APIs and $app module examples in a local SvelteKit project',
    'v2_original-framework-37_title': 'Svelte Playground',
    'v2_original-framework-37_lead': 'Explore component code and its output in the browser',
    'v2_original-framework-38_title': 'Automating Web Service Deployment',
    'v2_original-framework-38_lead': 'GitHub · Build and Validation · Vercel',
    w2_39_ci_def: 'Frequently integrate small changes and validate them with automated builds and tests',
    w2_39_ci_goals0: 'Early detection of integration errors and regressions',
    w2_39_ci_goals1: 'Faster validation and release preparation',
    w2_39_ci: 'CI · Continuous Integration',
    w2_39_delivery: 'Continuous Delivery',
    w2_39_delivery_def: 'Keep changes ready for release; production deployment can retain a human decision',
    w2_39_deployment: 'Continuous Deployment',
    w2_39_deployment_def: 'Automatically deploy validated changes to production',
    w2_39_cd: 'CD · Delivery / Deployment',
    w2_39_pipeline0: 'Code change',
    w2_39_pipeline1: 'Build and test',
    w2_39_pipeline2: 'Releasable artifact',
    w2_39_pipeline3: 'Production deployment',
    w2_39_devops: 'DevOps: collaborative practices, automation and feedback across development and operations; not a single job title or tool',
    'v2_original-framework-39_title': 'CI/CD and DevOps',
    'v2_original-framework-39_lead': 'A repeatable process for integration, validation and deployment',
    w2_40_next: 'Develops Next.js and supports frameworks including SvelteKit',
    w2_40_rich: 'Svelte creator Rich Harris joined in November 2021 to work on Svelte',
    w2_40_support: 'The framework preset and adapter connect build output to the deployment platform',
    w2_40_platform: 'Platform and Frameworks',
    w2_40_features_list0: 'Static delivery, CDN caching and server functions',
    w2_40_features_list1: 'Automatic builds and deployments from Git',
    w2_40_features_list2: 'Preview deployment URLs for changes',
    w2_40_features_list3: 'HTTPS certificates, custom domains and observability tools',
    w2_40_features: 'Key Features',
    w2_40_tests: 'Automatic deployment does not create tests; configure test commands and deployment conditions for the project',
    'v2_original-framework-40_title': 'Vercel',
    'v2_original-framework-40_lead': 'A cloud platform for building, previewing and deploying web applications',
    w2_41_setup_steps0: 'Create a Vercel account or sign in',
    w2_41_setup_steps1: 'Connect GitHub and grant repository access for a new project',
    w2_41_setup_steps2: 'Import the repository and select the project directory',
    w2_41_setup_steps3: 'Confirm the detected SvelteKit framework preset',
    w2_41_setup: 'Account and Repository Connection',
    w2_41_deploy_steps0: 'Set Node.js 24.x and any required environment variables',
    w2_41_deploy_steps1: 'Keep the automatically configured SvelteKit output directory',
    w2_41_deploy_steps2: 'Deploy and inspect the build log and deployment URL',
    w2_41_deploy_steps3: 'Check Home, About, Projects, detail pages and notes',
    w2_41_deploy: 'Configuration, Validation and Deployment',
    w2_41_push_flow0: 'Change and commit',
    w2_41_push_flow1: 'Push to GitHub',
    w2_41_push_flow2: 'Vercel rebuild',
    w2_41_push_flow3: 'Verify deployment',
    w2_41_url: 'Submit the actual Production URL from the dashboard; branch and project settings determine Preview versus Production deployments',
    'v2_original-framework-41_title': 'Connecting and Deploying a Vercel Project',
    'v2_original-framework-41_lead': 'Connect a GitHub repository and verify deployments and later changes',
    'v2_original-framework-42_title': 'Practice: Building a Website with SvelteKit and Deploying to Vercel',
    w2_43_goals_items0: 'Set up a Node.js and npm environment',
    w2_43_goals_items1: 'Build a static site with the SvelteKit framework',
    w2_43_goals_items2: 'Manage versions with Git/GitHub',
    w2_43_goals_items3: 'Set up an automated deployment pipeline with Vercel',
    w2_43_requirements: 'Requirements',
    w2_43_requirements_items0: 'Is the project properly version-controlled in a GitHub repository?',
    w2_43_requirements_items1: 'Is the GitHub repository connected to Vercel for automatic deployment?',
    w2_43_requirements_items2: 'Does all the provided project code work correctly in the web service deployed to Vercel? (Home, About, Projects)',
    w2_43_reference: 'Reference',
    w2_43_goals: 'Learning Objectives',
    w2_43_deadline_value: 'September 20, 23:59',
    w2_43_deliverables0: 'GitHub repository URL',
    w2_43_deliverables1: 'Vercel App URL',
    w2_43_github_example: '(Example: https://github.com/username/pwd-week2)',
    w2_43_vercel_example: '(Example: https://pwd-week2-[random].vercel.app)',
    w2_43_submit: 'Assignment Deadline',
    'v2_original-framework-43_title': 'Practice Overview',
    'v2_original-framework-43_lead': 'Building a Website with SvelteKit and Deploying to Vercel',
    'v2_original-framework-44_title': 'Questions and Discussion',
    'v2_original-framework-44_lead': 'Web Pages · Rendering · SvelteKit · Deployment',
    s01_eyebrow: 'Practical Web Service Development · Fall 2026',
    s01_title: 'Practical Web Service Development – Week 2',
    s01_subtitle: 'Web Page Components and Rendering Principles',
    s02_title: 'Learning Goals',
    s02_goal_1: 'Web Page Components',
    s02_goal_1_detail: 'Distinguish the structural, visual and behavioral roles of HTML, CSS and JavaScript',
    s02_goal_2: 'Web Browser Rendering',
    s02_goal_2_detail: 'Explain the DOM-to-paint process, CSR/SSR/SSG and the importance of performance',
    s02_goal_3: 'Semantic HTML and Routing',
    s02_goal_3_detail: 'Explain element semantics, accessibility, URL structure and page navigation',
    s02_goal_4: 'Web Browser Developer Tools',
    s02_goal_4_detail: 'Inspect the DOM, styles, metadata, viewport and HTTP responses',
    s02_goal_5: 'Svelte and SvelteKit Development',
    s02_goal_5_detail: 'Build components, state, events, routes and APIs with JavaScript or TypeScript',
    s03_title: 'Web Page Components and Roles',
    s03_lead: 'HTML · CSS · JavaScript',
    s47_title: 'The Roles of HTML, CSS and JavaScript',
    s47_lead: 'HTML defines structure, CSS controls presentation, and JavaScript adds behavior',
    s47_example_label: 'Structure, presentation and behavior in a personal introduction page',
    s47_preview_title: 'About Me',
    s47_preview_before: 'Learning web development.',
    s47_preview_button: 'Change Introduction',
    s47_preview_hint: 'Button click → updated introduction',
    s47_html_role: 'Structure',
    s47_html: 'A heading, introduction and button defined as HTML elements',
    s47_html_detail: 'Elements and attributes · h1, p and button',
    s47_css_role: 'Presentation',
    s47_css: 'Typography, spacing, colors and button styling for those elements',
    s47_css_detail: 'Selectors for elements · properties and values for styles',
    s47_js_role: 'Behavior',
    s47_js: 'An introduction selected in response to a button click',
    s47_js_detail: 'Data and functions for logic · browser APIs for page updates',
    s04_title: 'HTML (HyperText Markup Language)',
    s04_lead: 'Describes the structure and content of a web document',
    s04_element_label: 'Element',
    s04_element: 'A document unit represented by HTML tags',
    s04_attribute_label: 'Attribute',
    s04_attribute: 'Extra information written in an element\'s start tag',
    s04_tags_label: 'Document Declaration and Main Tags',
    s04_doctype: 'Document declaration for standards-mode rendering',
    s04_html: 'The root element enclosing the entire HTML document',
    s04_head: 'Document metadata such as the title, encoding and styles',
    s04_meta: 'Metadata such as character encoding and viewport settings',
    s04_body: 'Page content such as headings, paragraphs and images',
    s04_example: '<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1" />\n    <title>About Me</title>\n    <link rel="stylesheet" href="style.css" />\n    <script src="script.js" defer></script>\n  </head>\n  <body>\n    <main>\n      <section>\n        <h1>About Me</h1>\n        <p id="intro">Learning web development.</p>\n        <button id="change" type="button">Change Introduction</button>\n      </section>\n    </main>\n  </body>\n</html>',
    s04_reference: 'Reference',
    s05_title: 'CSS (Cascading Style Sheets)',
    s05_lead: 'Defines colors, typography and layout for a web document',
    s05_selector_label: 'Selector',
    s05_selector: 'The part that points at the elements a style applies to',
    s05_declaration_label: 'Declaration',
    s05_declaration: 'A property and value pair written inside the braces',
    s05_details_label: 'Selector and Declaration Examples',
    s05_selector_1: 'Tag · class · ID',
    s05_selector_2: 'Combinators: child, descendant, sibling',
    s05_descendant: '(space)',
    s05_selector_3: 'States and pseudo-classes',
    s05_selector_4: 'Pseudo-elements',
    s05_block_label: 'Declaration Block',
    s05_declaration_2: 'Several declarations grouped inside braces',
    s05_reference: 'Reference',
    s51_title: 'JavaScript',
    s51_lead: 'A programming language for data and control flow · browser APIs connect code to page features',
    s51_data_label: 'Data Processing',
    s51_data: 'Values in variables · conditions and loops · reusable functions',
    s51_event_label: 'Event Handling',
    s51_event: 'Functions responding to clicks, input and page loading',
    s51_api_label: 'Browser APIs',
    s51_api: 'Document changes through the DOM · data requests with fetch · values saved in storage',
    s51_code_label: 'Selecting an Introduction with a Function',
    s51_example: 'const messages = [\n  \'Learning web development.\',\n  \'Building pages with HTML, CSS and JavaScript.\'\n];\n\nfunction getIntroduction(index) {\n  return messages[index];\n}\n\nconst introduction = getIntroduction(1);\nconsole.log(introduction);',
    s51_reference: 'Reference',
    s47_preview_after: 'Building pages with HTML, CSS and JavaScript.',
    s47_preview_reset: 'Restore Introduction'
  }
};
