(function () {
  'use strict';

  window.LECTURE_CONTENT = {
    ko: {
      s01_eyebrow: '2026학년도 2학기 실전웹서비스개발',
      s01_title: '실전 웹서비스개발 – 2주차',
      s01_subtitle: '웹 페이지의 생성과 렌더링: HTML · CSS · JavaScript',
      s02_title: '학습 목표',
      s02_goal_1: '웹 리소스',
      s02_goal_1_detail: 'HTML(구조) · CSS(표현) · JavaScript(동작) · DOM · 시맨틱 HTML',
      s02_goal_2: '브라우저 렌더링 과정',
      s02_goal_2_detail: 'HTML 파싱 → DOM · CSS 파싱 → CSSOM · 렌더 트리 → 레이아웃 → 페인트 → 컴포지트',
      s02_goal_3: 'HTML 생성 방식',
      s02_goal_3_detail: 'CSR / SSR / SSG · 렌더링 성능',
      s02_goal_4: '라우팅',
      s02_goal_4_detail: 'URL 구조 · 서버 사이드 / 클라이언트 사이드 라우팅',
      s03_title: '웹 리소스와 브라우저 렌더링',
      s03_lead: 'HTML · CSS · JavaScript와 렌더링 파이프라인',
      s47_title: '웹 리소스',
      s47_lead: 'URL이 가리키는 대상 · 브라우저의 요청에 서버가 응답으로 돌려주는 모든 것',
      s47_broad_label: '넓은 의미',
      s47_broad: '서버가 돌려주는 모든 것 · HTML · CSS · JavaScript · 이미지 · 글꼴 · 영상 · JSON 데이터 · 응답 헤더의 Content-Type으로 종류를 구분',
      s47_narrow_label: '좁은 의미 · 이 강의의 대상',
      s47_narrow: '브라우저가 직접 해석해 페이지를 구성하는 세 가지 텍스트 리소스 · 이미지와 글꼴은 이 셋이 가리키는 부속 리소스',
      s47_html: '문서의 구조와 내용 · 제목, 문단, 이미지, 링크의 위치를 정의',
      s47_role_label: '역할',
      s47_html_role: '구조',
      s47_css: '문서의 표현 · 색, 크기, 배치, 글꼴을 지정',
      s47_css_role: '표현',
      s47_js: '문서의 동작 · 클릭과 입력에 대한 반응, 내용 변경, 서버와의 통신',
      s47_js_role: '동작',
      s47_note_label: '확인',
      s47_note: '개발자 도구 Network 패널의 Type 열(document · stylesheet · script · image · font)이 리소스 종류 · Response 탭에서 원본 텍스트 확인',
      s04_title: 'HTML5 문서 구조',
      s04_lead: 'HTML = 구조, CSS = 표현(스타일), JS = 동작',
      s04_doctype: '현재 문서가 HTML5 문서임을 브라우저에 알려주는 선언문',
      s04_html_label: '<html> 태그',
      s04_html: '웹 문서의 시작과 끝을 감싸는 최상위 루트 요소 · 모든 HTML 요소를 포함',
      s04_head_label: '<head> 태그',
      s04_head: 'HTML 문서의 메타데이터(제목, 인코딩, 스타일, 스크립트 등)를 담는 영역',
      s04_meta_label: '<meta> 태그',
      s04_meta: '문서의 부가 정보를 정의하는 메타데이터 요소 · viewport는 반응형 디자인의 핵심 · link 태그로 외부 리소스 연결',
      s04_body_label: '<body> 태그',
      s04_body: '사용자가 실제로 화면에서 보게 되는 모든 콘텐츠(텍스트, 이미지, 링크 등)를 담는 영역',
      s04_reference: '학습 참고 자료',
      s05_title: 'CSS 규칙의 구조',
      s05_lead: 'CSS는 규칙(Selector + Declaration)의 집합',
      s05_selector: '스타일을 적용할 대상을 가리키는 부분',
      s05_selector_1: '태그 · 클래스 · ID',
      s05_selector_2: '결합자: 자식, 자손, 형제',
      s05_selector_3: '상태 · 의사클래스',
      s05_selector_4: '의사요소',
      s05_declaration: '중괄호 안에 작성하는 속성과 값의 한 쌍',
      s05_declaration_2: '여러 선언이 모여 declaration block을 구성',
      s05_reference: '학습 참고 자료',
      s06_title: 'JavaScript와 화면 동작',
      s06_lead: '사용자 행동과 데이터에 반응해 문서를 바꾸는 재료 · 바뀐 문서는 브라우저가 다시 그림',
      s06_core_label: 'JS가 화면을 바꾸는 흐름',
      s06_core_1: '이벤트 발생 (클릭 · 입력 · 페이지 로드)',
      s06_core_2: 'JS가 문서에서 요소를 찾아 내용 · 속성 · 스타일을 읽고 수정',
      s06_core_3: '브라우저가 변경된 부분을 다시 렌더링',
      s06_core_4: 'JS가 다룰 수 있는 것',
      s06_core_4_1: '문서: 요소 찾기 · 텍스트와 속성 변경 · 요소 생성과 삭제 → DOM',
      s06_core_4_2: '스타일: 클래스 토글 · 인라인 스타일 변경',
      s06_core_4_3: '데이터: 서버 요청 · 저장 · 계산',
      s06_reference: '학습 참고 자료',
      s07_lead: 'HTML 문서를 파싱하여 메모리 안의 객체 트리로 변환한 결과',
      s07_features_label: '특징',
      s07_feature_1: 'JavaScript가 읽고 변경하는 대상',
      s07_feature_2: '트리 구조(부모 · 자식 · 형제)',
      s07_feature_3: 'HTML을 파싱하면서 DOM 트리가 생성',
      s07_parts_label: '구성',
      s07_part_node: '모든 구성 요소의 상위 개념',
      s07_part_element: '태그',
      s07_part_text: '텍스트',
      s07_part_attribute: '속성',
      s07_tasks_label: '주요 작업',
      s07_task_1: '찾기',
      s07_task_2: '읽기 · 쓰기',
      s07_task_3: '생성 · 삭제',
      s07_tree_label: 'HTML 텍스트 → 파싱 → DOM 트리(객체)',
      s07_reference: '학습 참고 자료',
      s08_title: '시맨틱 HTML',
      s08_lead: '태그의 의미를 살려 문서를 작성하면 검색엔진과 보조기기가 구조를 정확히 해석',
      s08_seo_label: 'SEO (Search Engine Optimization)',
      s08_seo: '웹페이지의 태그와 링크 구조를 개선하여 검색엔진의 검색 결과 페이지에 잘 노출되도록 최적화하는 과정',
      s08_seo_step_1: '크롤링 (Crawling)',
      s08_seo_step_1_detail: '검색 엔진 봇이 웹사이트 방문',
      s08_seo_step_2: '인덱싱 (Indexing)',
      s08_seo_step_2_detail: '콘텐츠를 읽고 저장',
      s08_seo_step_3: '랭킹 (Ranking)',
      s08_seo_step_3_detail: '검색 결과 순위 결정',
      s08_a11y_label: '접근성 트리 (Accessibility Tree)',
      s08_a11y: '브라우저가 DOM(+CSS, ARIA)을 해석해 만든 보조기기용 안내도 · 시맨틱 태그는 올바른 역할(role)로 매핑',
      s08_benefit_label: '그 밖의 이점',
      s08_benefit_1: '코드 가독성 개선',
      s08_benefit_2: '기본 UX와 내구성 확보',
      s08_bad_label: '✕ Non-Semantic',
      s08_good_label: '✓ Semantic',
      s09_title: '웹 브라우저 렌더링 과정',
      s09_lead: '브라우저는 전달받은 HTML과 CSS를 해석하여 화면의 픽셀로 표시',
      s09_step_1: 'HTML 파싱',
      s09_step_1_detail: '문서를 해석해 DOM 트리 생성',
      s09_step_2: 'CSS 파싱',
      s09_step_2_detail: '스타일을 해석해 CSSOM 트리 생성',
      s09_step_3: 'Render Tree',
      s09_step_3_detail: 'DOM과 CSSOM을 결합해 화면에 그릴 트리 구성',
      s09_step_4: 'Layout',
      s09_step_4_detail: '각 요소의 위치와 크기 계산',
      s09_step_5: 'Paint',
      s09_step_5_detail: '계산된 결과를 픽셀로 그리기',
      s09_step_6: 'Composite',
      s09_step_6_detail: '레이어를 합쳐 최종 화면 출력',
      s09_note_label: 'JS 변경 시 재실행 범위',
      s09_note: '변경된 단계부터 다시 실행 · 텍스트 · 구조 · 크기 변경 → Layout부터 · 색상 · 배경 변경 → Paint부터 · transform · opacity 변경 → Composite만',
      s11_title: '웹 브라우저 렌더링 성능의 중요성',
      s11_lead: '렌더링 최적화는 단순히 속도만의 문제가 아니라 사용자 경험, SEO, 전환율에 직접적인 영향을 미치는 핵심 요소',
      s11_bounce_label: '로딩 시간별 이탈률',
      s11_bounce_note: '경쟁사로 이동',
      s11_bounce_detail: '초기 로딩이 1초 늘어날 때마다 이탈률이 급격히 증가',
      s11_cwv_1: 'Google이 2020년에 도입한, 웹 페이지 사용자 경험을 측정하는 3가지 핵심 지표',
      s11_cwv_2: '2021년부터는 검색 순위에도 영향을 미치는 중요한 SEO 요소',
      s11_fcp: '첫 번째 텍스트나 이미지가 화면에 그려지는 시간',
      s11_lcp: '가장 큰 콘텐츠가 화면에 그려지는 시간',
      s11_cls: '페이지 로드 중 발생하는 레이아웃 이동 총합',
      s45_title: 'HTML 생성 방식과 라우팅',
      s45_lead: 'CSR · SSR · SSG · URL과 라우터',
      s10_title: '웹 브라우저 렌더링 방식',
      s10_lead: 'HTML을 누가, 언제 생성하는가에 따라 세 가지 방식으로 구분',
      s10_csr: '빈 HTML → JS 다운로드 → 화면 생성',
      s10_pro_label: '장점',
      s10_csr_pro: '페이지 로드 후 사용자 인터랙션에 빠르게 반응 · 자주 업데이트되는 페이지에 유리',
      s10_con_label: '단점',
      s10_csr_con: '초기 로딩이 느리고, 크롤러가 자바스크립트를 실행해야 내용을 인식하므로 SEO에 불리',
      s10_case_label: '사례',
      s10_csr_case: '소셜 미디어 플랫폼(Facebook, Instagram), 대시보드, 웹 기반 게임',
      s10_ssr: '서버에서 완성된 HTML → 즉시 표시',
      s10_ssr_pro: '빠른 초기 로딩 · 검색엔진이 쉽게 크롤링하므로 SEO에 유리',
      s10_ssr_con: '서버 부하로 인한 서버 비용 증가',
      s10_ssr_case: '뉴스 사이트와 블로그, SEO가 중요한 전자 상거래 사이트',
      s10_ssg: '빌드 시 HTML 생성 → CDN 제공',
      s10_ssg_pro: '빠른 로딩 · SEO에 유리 · 서버 부하가 적고 전 세계에 빠르게 콘텐츠 제공',
      s10_ssg_con: '동적인 콘텐츠가 많으면 빌드와 배포 과정이 반복적으로 필요',
      s10_ssg_case: '개인 블로그 또는 포트폴리오 사이트, 마케팅 랜딩 페이지',
      s12_title: '라우팅(Routing)',
      s12_lead: '사용자가 요청한 URL 주소에 따라 적절한 페이지나 콘텐츠를 보여주는 과정',
      s12_part_1_label: '프로토콜',
      s12_part_1: '통신 방식',
      s12_part_2_label: '도메인',
      s12_part_2: '서비스 주소',
      s12_part_3_label: '경로 세그먼트',
      s12_part_3: '자원의 위치',
      s12_part_4_label: '동적 세그먼트',
      s12_part_4: '값에 따라 달라지는 경로',
      s12_part_5_label: '쿼리 파라미터',
      s12_part_5: '추가 조건 전달',
      s12_part_6_label: '해시',
      s12_part_6: '페이지 내 위치',
      s12_flow_1_label: '요청',
      s12_flow_2_label: '라우터',
      s12_flow_2: '요청한 주소를 확인',
      s12_flow_3_label: '매칭',
      s12_flow_3: '/about 경로에 해당하는 페이지 선택',
      s12_flow_4_label: '표시',
      s12_flow_4: 'About 페이지 표시',
      s13_title: '서버 사이드 라우팅과 클라이언트 사이드 라우팅',
      s13_mpa_title: '1. 서버 사이드 라우팅',
      s13_mpa_lead: '페이지를 이동할 때마다 서버에서 새로운 문서를 전달받는 방식',
      s13_mpa_pro_1: '간단하고 직관적',
      s13_mpa_pro_2: 'SEO에 유리',
      s13_mpa_con_1: '페이지 전환마다 깜빡임',
      s13_mpa_con_2: '느린 페이지 전환',
      s13_actor_user: '사용자',
      s13_mpa_1: 'About 링크 클릭',
      s13_actor_browser: '브라우저',
      s13_mpa_2: 'about.html 전체 문서를 서버에 요청',
      s13_actor_server: '서버',
      s13_mpa_3: 'about.html 전체 문서를 응답',
      s13_mpa_4: '화면 전체를 다시 렌더링 (깜빡임 발생)',
      s13_spa_title: '2. 클라이언트 사이드 라우팅',
      s13_spa_lead: 'JavaScript가 페이지 전환을 처리',
      s13_spa_pro_1: '빠른 페이지 전환',
      s13_spa_pro_2: '부드러운 사용자 경험',
      s13_spa_con_1: '느린 초기 로딩',
      s13_spa_con_2: 'SEO 대응 필요',
      s13_spa_1: 'About 링크 클릭',
      s13_spa_2: 'About 페이지에 필요한 데이터만 서버에 요청',
      s13_spa_3: '요청한 데이터를 JSON으로 응답',
      s13_spa_4: '현재 페이지에서 콘텐츠 영역만 교체',
      s13_spa_def_label: 'SPA (Single Page Application)',
      s13_spa_def: '웹사이트 전체가 하나의 페이지로 구성되어 있고, 사용자가 다른 페이지로 이동할 때 전체 페이지를 새로 불러오지 않고 필요한 부분만 JavaScript로 동적으로 변경',
      s14_title: '웹 브라우저에서 확인',
      s14_lead: '크롬 브라우저 개발자 도구로 지금까지 배운 개념을 직접 확인',
      s14_devtools_label: '개발자 도구',
      s14_shortcut_label: '단축키',
      s14_devtools_1: '문서 요소들 확인',
      s14_devtools_2: '시맨틱 레이아웃 확인',
      s14_devtools_3: 'SEO · 메타 정보 확인',
      s14_viewport_label: '반응형 · 뷰포트 확인',
      s14_toggle_label: '디바이스 툴바',
      s14_viewport_1: '다양한 뷰포트(모바일 · 태블릿)로 레이아웃 결과 확인',
      s14_viewport_2: '상단 Device 해상도와 회전(rotate) 테스트',
      s14_network_label: '원본 HTML · 응답 헤더 확인',
      s14_network_1: 'Network 패널 → Doc 타입(첫 항목) 클릭',
      s14_network_3: 'Response 탭에서 서버가 보낸 원본 HTML 확인',
      s15_title: '다음 단계: 웹 프레임워크',
      s15_lead: '직접 작성의 한계와 프레임워크의 등장 · 이후 주차에서 사용하는 도구 소개',
      s48_title: '직접 작성한 웹페이지의 한계',
      s48_lead: '1주차 과제처럼 HTML · CSS · JavaScript 파일을 직접 작성하는 방식은 화면과 기능이 늘어날수록 반복 작업도 함께 증가',
      s48_item_1_label: '반복되는 마크업',
      s48_item_1: '헤더 · 내비게이션 · 푸터를 페이지마다 복사 · 한 곳을 고치면 모든 파일을 다시 수정',
      s48_item_2_label: '흩어지는 상태',
      s48_item_2: '화면과 데이터를 DOM에서 직접 동기화 · 화면이 늘어날수록 변경 추적이 어려운 구조',
      s48_item_3_label: '수작업 최적화',
      s48_item_3: '번들링 · 압축 · 캐싱 · 코드 분할을 직접 처리 · 렌더링 성능 관리의 부담',
      s48_item_4_label: '반복되는 배포',
      s48_item_4: '변경할 때마다 결과물을 직접 올리고 동작을 다시 확인',
      s48_note_label: '해결 방향',
      s48_note: '프레임워크와 빌드 도구가 이 반복 작업을 표준 방식으로 처리 · 개발자는 화면 구성과 기능 구현에 집중',
      s16_title: '웹 개발 프레임워크',
      s16_lead: '웹서비스를 더 빠르고 안전하게 만들 수 있게 미리 준비된 설계도와 도구 묶음 · 개발과 관련된 반복 작업을 표준 방식으로 제공해 개발자의 시행착오를 줄이는 것이 목적',
      s16_parts_label: '구성요소',
      s16_part_1_label: '구조',
      s16_part_1: '폴더 · 파일 규칙, 레이어드 아키텍처(컨트롤러 · 서비스 · 모델 등)',
      s16_part_2_label: '러닝키트',
      s16_part_2: '라우터, 미들웨어, ORM · 쿼리 도구, 폼 · 검증, 인증, 국제화, 테스트',
      s16_part_3_label: '빌드 · 런타임',
      s16_part_3: '번들링, 트랜스파일(예: TypeScript), 코드 스플리팅, SSR · SSG 지원',
      s16_part_4_label: '생태계',
      s16_part_4: '플러그인, CLI, 베스트 프랙티스 문서',
      s16_kinds_label: '종류',
      s16_kind_1_label: '프론트엔드(UI)',
      s16_kind_2_label: '백엔드(API)',
      s16_kind_3_label: '풀스택(프론트 + 백엔드)',
      s16_choice_label: '선택 기준',
      s16_choice_1_label: '팀 역량 · 언어',
      s16_choice_1: 'JS / TS는 Next.js · NestJS, Python은 Django / FastAPI',
      s16_choice_2_label: '렌더링 방식',
      s16_choice_2: 'CSR / SSR / SSG / ISR 필요 여부 (SEO, 초기 로드 속도 요구)',
      s16_choice_3_label: '호스팅 · 배포',
      s16_choice_3: 'Vercel · Netlify(서버리스)와 컨테이너 · 쿠버네티스 중 선택',
      s16_choice_4_label: '생태계',
      s16_choice_4: '문서 · 커뮤니티 · 플러그인의 풍부함',
      s16_course_label: '이 강의의 선택',
      s16_course: '프론트엔드 React + Vite(4주차) · 백엔드 Node.js + Express(6주차) · 데이터베이스 PostgreSQL + Supabase(7주차) · 배포 Vercel(9주차)',
      s21_title: '주요 프론트엔드 프레임워크 비교',
      s21_features_label: '이 강의에서 React를 사용하는 이유',
      s21_feature_1: '가장 큰 생태계와 풍부한 학습 자료 · 문제 해결 정보 확보가 용이',
      s21_feature_2: '컴포넌트 단위 개발 방식이 이후 주차의 프론트엔드 구조와 연결',
      s21_feature_3: '채용 시장과 실무 프로젝트에서의 높은 사용 비율',
      s21_feature_4: 'Vite와 함께 사용할 때 빠른 개발 서버와 빌드 속도 확보',
      s21_feature_5: '성숙한 TypeScript 지원 · 3주차 학습 내용과 바로 연결',
      s21_head_feature: '특징',
      s21_vdom_react: '사용',
      s21_vdom_vue: '사용',
      s21_vdom_svelte: '미사용',
      s21_row_bundle: '번들 크기',
      s21_row_curve: '학습 곡선',
      s21_curve_react: '중간 ~ 높음',
      s21_curve_vue: '낮음 ~ 중간',
      s21_curve_svelte: '낮음',
      s21_row_perf: '성능',
      s21_perf_react: '좋음',
      s21_perf_vue: '좋음',
      s21_perf_svelte: '매우 좋음',
      s21_row_eco: '생태계',
      s21_eco_react: '매우 큼',
      s21_eco_vue: '큼',
      s21_eco_svelte: '성장 중',
      s21_note_label: '참고',
      s21_note: '번들 크기는 런타임 기준의 대략적인 값 · 실제 크기는 버전과 빌드 설정에 따라 변동',
      s17_lead: 'Chrome V8 JavaScript 엔진으로 빌드된 JavaScript 런타임 환경 · 웹 브라우저 밖에서도 JavaScript를 실행할 수 있도록 하는 프로그램',
      s17_feature_1_label: '1. JavaScript 런타임',
      s17_feature_1_1: '브라우저가 없어도 컴퓨터에서 JavaScript 실행 가능',
      s17_feature_1_2: '서버 프로그래밍, 데스크톱 앱, 명령줄 도구 개발 가능',
      s17_feature_2_label: '2. 비동기 I/O',
      s17_feature_2_1: '동시에 여러 작업 처리 가능',
      s17_feature_2_2: '한 작업이 끝날 때까지 기다리지 않고 다른 작업 진행',
      s17_feature_2_3: '높은 성능과 효율성',
      s17_feature_3_label: '3. 단일 스레드 이벤트 루프',
      s17_feature_3_1: '하나의 스레드로 많은 연결을 효율적으로 처리',
      s17_feature_3_2: '적은 메모리 사용량',
      s17_feature_4_label: '4. NPM 생태계',
      s17_feature_4_1: '세계 최대 오픈소스 라이브러리 생태계',
      s17_feature_4_2: '100만개 이상의 패키지 사용 가능',
      s18_lead: '키보드로 명령어를 입력하여 컴퓨터와 상호작용하는 방식 · 짧은 텍스트 명령으로 파일 관리, 개발 도구 실행, 서버 작업 등을 빠르고 정확하게 자동화',
      s18_why_label: 'CLI를 사용하는 이유',
      s18_why_1_label: '속도 · 자동화',
      s18_why_1: '반복 작업을 스크립트 한 줄로 처리',
      s18_why_2_label: '재현성',
      s18_why_2: '같은 명령을 실행하면 항상 같은 결과',
      s18_why_3_label: '원격 작업',
      s18_why_3: '클라우드 · 서버 관리의 표준 도구',
      s18_why_4_label: '개발 생태계',
      s18_why_4: 'Node / npm, Git, React, Express, Codex, Claude, Gemini 등 대부분 CLI로 구동',
      s18_terms_label: '기본 용어',
      s18_term_1_label: '터미널(Terminal)',
      s18_term_1: '명령을 입력하는 프로그램 (예: macOS Terminal, Windows PowerShell)',
      s18_term_2_label: '셸(Shell)',
      s18_term_2: '명령을 해석하고 실행하는 엔진 (bash, zsh, PowerShell 등)',
      s18_term_3_label: '프롬프트(Prompt)',
      s18_term_3: '입력 대기 표시',
      s18_term_4_label: '경로(Path)',
      s18_term_4: '현재 위치(작업 디렉토리) · ~는 홈, .은 현재, ..은 상위',
      s19_title: 'NPM과 NPX',
      s19_npm_lead: 'JavaScript 프로그래밍 언어를 위한 패키지 관리자 · 다른 개발자들이 만든 코드 조각(패키지)을 쉽게 내려받고 관리할 수 있도록 지원하는 도구',
      s19_npm_1_label: '패키지 설치',
      s19_npm_1: '필요한 라이브러리나 도구를 쉽게 설치',
      s19_npm_2_label: '의존성 관리',
      s19_npm_2: '프로젝트에 필요한 모든 패키지를 자동으로 관리',
      s19_npm_3_label: '스크립트 실행',
      s19_npm_3: '프로젝트 실행, 빌드 등의 명령어 관리',
      s19_npm_4_label: '패키지 공유',
      s19_npm_4: '자신이 만든 코드를 다른 개발자와 공유',
      s19_npx_lead: '패키지를 설치하지 않고 실행할 수 있도록 하는 npm 패키지 실행 도구',
      s49_title: '오늘의 개념이 이어지는 곳',
      s49_lead: '2주차에서 직접 작성한 구조 · 표현 · 동작이 이후 주차에서 도구와 프레임워크로 확장',
      s49_step_1_label: '2주차 · 오늘',
      s49_step_1: 'HTML · CSS · JavaScript · DOM · 렌더링 · 라우팅을 직접 작성',
      s49_step_2_label: '3주차 · JavaScript → TypeScript',
      s49_step_2: '타입을 적용하여 실행 전에 오류를 확인',
      s49_step_3_label: '4주차 · React + Vite',
      s49_step_3: '컴포넌트와 빌드 도구로 화면을 구성하고 CSR 방식으로 렌더링',
      s49_step_4_label: '9주차 · Deployment',
      s49_step_4: '빌드 결과물을 자동으로 배포하고 운영',
      s49_setup_label: '다음 주차 준비',
      s49_setup_1: 'Node.js LTS 버전 설치',
      s49_setup_2: '터미널에서 설치 버전 확인',
      s42_title: '과제: 시맨틱 HTML · CSS · DOM으로 만드는 다중 페이지 사이트',
      s43_title: '과제 개요',
      s43_overview: '1주차 과제를 확장하여 세 개의 페이지로 구성한 개인 사이트를 제작하고 GitHub Pages에 배포',
      s43_learning_label: '학습 목표',
      s43_learning_1: '시맨틱 태그로 문서 구조 작성',
      s43_learning_2: '외부 CSS로 공통 스타일 분리와 레이아웃 구성',
      s43_learning_3: 'DOM 조작으로 사용자 상호작용 구현',
      s43_learning_4: '개발자 도구로 문서 구조와 응답 확인',
      s43_requirements_label: '요구사항',
      s43_req_1: 'index.html, about.html, projects.html 세 페이지가 작성되고 서로 링크로 연결됨',
      s43_req_2: 'header, nav, main, section, article, footer 등 시맨틱 태그로 문서 구조가 작성됨',
      s43_req_3: '외부 style.css로 공통 스타일이 분리되고 모든 페이지에 연결됨',
      s43_req_4: 'script.js에서 DOM을 변경하는 상호작용이 1개 이상 구현됨',
      s43_req_5: 'GitHub Pages에 배포되어 세 페이지가 모두 정상 표시됨',
      s43_reference: '참고',
      s43_deadline_label: '마감일',
      s43_due: '9월 20일 23:59까지',
      s43_submit_note: 'LMS에 다음 정보를 제출',
      s43_submit_1: 'GitHub 저장소 URL',
      s43_submit_2: 'GitHub Pages URL',
      s50_title: '더 알아보기',
      s50_lead: '오늘 다룬 개념을 확인하고 확장할 때 사용하는 자료',
      s50_docs_label: '문서와 표준',
      s50_docs_1: 'HTML · CSS · JavaScript · DOM 표준 문서',
      s50_docs_2: 'HTML 표준 원문',
      s50_docs_3: '예제 중심의 기초 학습 자료',
      s50_tools_label: '성능과 호환성',
      s50_tools_1: 'FCP · LCP · CLS 측정과 개선 방법',
      s50_tools_2: '배포한 페이지의 성능 점수 확인',
      s50_tools_3: '브라우저별 기능 지원 범위 확인',
      s44_discord_label: 'Discord 채널 초대'
    },
    en: {
      s01_eyebrow: 'Practical Web Service Development · Fall 2026',
      s01_title: 'Practical Web Service Development – Week 2',
      s01_subtitle: 'Building and Rendering a Web Page: HTML · CSS · JavaScript',
      s02_title: 'Learning Goals',
      s02_goal_1: 'Web resources',
      s02_goal_1_detail: 'HTML (structure) · CSS (presentation) · JavaScript (behavior) · DOM · Semantic HTML',
      s02_goal_2: 'Browser rendering pipeline',
      s02_goal_2_detail: 'HTML parsing → DOM · CSS parsing → CSSOM · Render tree → Layout → Paint → Composite',
      s02_goal_3: 'HTML generation strategies',
      s02_goal_3_detail: 'CSR / SSR / SSG · Rendering performance',
      s02_goal_4: 'Routing',
      s02_goal_4_detail: 'URL anatomy · Server-side / client-side routing',
      s03_title: 'Web Resources and Browser Rendering',
      s03_lead: 'HTML · CSS · JavaScript and the rendering pipeline',
      s47_title: 'Web Resources',
      s47_lead: 'What a URL points to · everything a server returns in response to a browser request',
      s47_broad_label: 'Broad sense',
      s47_broad: 'Everything the server returns · HTML · CSS · JavaScript · images · fonts · video · JSON data · distinguished by the Content-Type response header',
      s47_narrow_label: 'Narrow sense · the focus of this lecture',
      s47_narrow: 'The three text resources the browser interprets directly to build the page · images and fonts are supporting resources these three point to',
      s47_html: 'Structure and content of the document · defines where headings, paragraphs, images and links belong',
      s47_role_label: 'Role',
      s47_html_role: 'Structure',
      s47_css: 'Presentation of the document · specifies colors, sizes, layout and fonts',
      s47_css_role: 'Presentation',
      s47_js: 'Behavior of the document · responses to clicks and input, content changes, communication with the server',
      s47_js_role: 'Behavior',
      s47_note_label: 'Check it',
      s47_note: 'The Type column in the DevTools Network panel (document · stylesheet · script · image · font) shows the resource kind · read the raw text in the Response tab',
      s04_title: 'HTML5 Document Structure',
      s04_lead: 'HTML = structure, CSS = presentation, JS = behavior',
      s04_doctype: 'A declaration that tells the browser this document is HTML5',
      s04_html_label: '<html> tag',
      s04_html: 'The top-level root element wrapping the start and end of the document; every HTML element lives inside it',
      s04_head_label: '<head> tag',
      s04_head: 'The area holding document metadata such as title, encoding, styles, and scripts',
      s04_meta_label: '<meta> tag',
      s04_meta: 'A metadata element defining extra document information; viewport is the key to responsive design, and the link tag connects external resources',
      s04_body_label: '<body> tag',
      s04_body: 'The area holding every piece of content users actually see on screen: text, images, links, and more',
      s04_reference: 'Reference',
      s05_title: 'The Structure of a CSS Rule',
      s05_lead: 'CSS is a set of rules made of a selector and declarations',
      s05_selector: 'The part that points at the elements a style applies to',
      s05_selector_1: 'Tag · class · ID',
      s05_selector_2: 'Combinators: child, descendant, sibling',
      s05_selector_3: 'States and pseudo-classes',
      s05_selector_4: 'Pseudo-elements',
      s05_declaration: 'A property and value pair written inside the braces',
      s05_declaration_2: 'Several declarations together form a declaration block',
      s05_reference: 'Reference',
      s06_title: 'JavaScript and Screen Behavior',
      s06_lead: 'The resource that changes the document in response to user actions and data · the browser redraws what changed',
      s06_core_label: 'How JS changes the screen',
      s06_core_1: 'An event fires (click, input, page load)',
      s06_core_2: 'JS finds elements in the document and reads or changes their content, attributes and styles',
      s06_core_3: 'The browser redraws the changed area',
      s06_core_4: 'What JS can work with',
      s06_core_4_1: 'Document: find elements · change text and attributes · create and remove elements → DOM',
      s06_core_4_2: 'Style: toggle classes · change inline styles',
      s06_core_4_3: 'Data: request from a server · store · compute',
      s06_reference: 'Reference',
      s07_lead: 'The object tree in memory produced by parsing an HTML document',
      s07_features_label: 'Characteristics',
      s07_feature_1: 'The target that JavaScript reads and changes',
      s07_feature_2: 'A tree structure of parents, children, and siblings',
      s07_feature_3: 'The DOM tree is built while the HTML is parsed',
      s07_parts_label: 'Composition',
      s07_part_node: 'The parent concept of every component',
      s07_part_element: 'Tags',
      s07_part_text: 'Text',
      s07_part_attribute: 'Attributes',
      s07_tasks_label: 'Main operations',
      s07_task_1: 'Find',
      s07_task_2: 'Read and write',
      s07_task_3: 'Create and delete',
      s07_tree_label: 'HTML text → parsing → DOM tree (objects)',
      s07_reference: 'Reference',
      s08_title: 'Semantic HTML',
      s08_lead: 'Writing documents with meaningful tags lets search engines and assistive technology read the structure correctly',
      s08_seo_label: 'SEO (Search Engine Optimization)',
      s08_seo: 'The process of improving the tags and link structure of a page so it is well exposed on search engine result pages',
      s08_seo_step_1: 'Crawling',
      s08_seo_step_1_detail: 'Search engine bots visit the website',
      s08_seo_step_2: 'Indexing',
      s08_seo_step_2_detail: 'The content is read and stored',
      s08_seo_step_3: 'Ranking',
      s08_seo_step_3_detail: 'Search result order is determined',
      s08_a11y_label: 'Accessibility Tree',
      s08_a11y: 'A map for assistive technology that the browser builds from the DOM, CSS, and ARIA; semantic tags map to the correct role',
      s08_benefit_label: 'Other benefits',
      s08_benefit_1: 'Better code readability',
      s08_benefit_2: 'Solid baseline UX and durability',
      s08_bad_label: '✕ Non-Semantic',
      s08_good_label: '✓ Semantic',
      s09_title: 'Browser Rendering Pipeline',
      s09_lead: 'The browser interprets the HTML and CSS it receives and presents them as pixels on screen',
      s09_step_1: 'HTML parsing',
      s09_step_1_detail: 'Parse the document into a DOM tree',
      s09_step_2: 'CSS parsing',
      s09_step_2_detail: 'Parse the styles into a CSSOM tree',
      s09_step_3: 'Render Tree',
      s09_step_3_detail: 'Combine DOM and CSSOM into the tree to be drawn',
      s09_step_4: 'Layout',
      s09_step_4_detail: 'Compute the position and size of every element',
      s09_step_5: 'Paint',
      s09_step_5_detail: 'Draw the computed result as pixels',
      s09_step_6: 'Composite',
      s09_step_6_detail: 'Merge the layers into the final frame',
      s09_note_label: 'Re-run scope after a JS change',
      s09_note: 'The pipeline re-runs from the changed stage · text, structure, size → from Layout · color, background → from Paint · transform, opacity → Composite only',
      s11_title: 'Why Rendering Performance Matters',
      s11_lead: 'Rendering optimization is not only about speed; it directly affects user experience, SEO, and conversion',
      s11_bounce_label: 'Bounce rate by load time',
      s11_bounce_note: 'Move to a competitor',
      s11_bounce_detail: 'Every extra second of initial load sharply raises the bounce rate',
      s11_cwv_1: 'Three core metrics Google introduced in 2020 to measure page user experience',
      s11_cwv_2: 'Since 2021 they are also an SEO factor that affects search ranking',
      s11_fcp: 'Time until the first text or image is painted',
      s11_lcp: 'Time until the largest content element is painted',
      s11_cls: 'Total layout shift that occurs during page load',
      s45_title: 'HTML Generation and Routing',
      s45_lead: 'CSR · SSR · SSG · URLs and routers',
      s10_title: 'Browser Rendering Strategies',
      s10_lead: 'Three approaches, distinguished by who generates the HTML and when',
      s10_csr: 'Empty HTML → download JS → build the screen',
      s10_pro_label: 'Pros',
      s10_csr_pro: 'Responds quickly to interaction once loaded; well suited to frequently updated pages',
      s10_con_label: 'Cons',
      s10_csr_con: 'Slow initial load, and weak for SEO because crawlers must execute JavaScript to see the content',
      s10_case_label: 'Examples',
      s10_csr_case: 'Social platforms (Facebook, Instagram), dashboards, browser games',
      s10_ssr: 'Fully built HTML from the server → displayed immediately',
      s10_ssr_pro: 'Fast initial load and strong SEO because crawlers read the page easily',
      s10_ssr_con: 'Server load, and therefore higher server cost',
      s10_ssr_case: 'News sites and blogs, e-commerce sites where SEO matters',
      s10_ssg: 'HTML generated at build time → served from a CDN',
      s10_ssg_pro: 'Fast loading, strong SEO, low server load, and quick global delivery',
      s10_ssg_con: 'Content-heavy dynamic sites need repeated build and deploy cycles',
      s10_ssg_case: 'Personal blogs and portfolio sites, marketing landing pages',
      s12_title: 'Routing',
      s12_lead: 'The process of showing the right page or content for the URL a user requested',
      s12_part_1_label: 'Protocol',
      s12_part_1: 'Transport scheme',
      s12_part_2_label: 'Domain',
      s12_part_2: 'Service address',
      s12_part_3_label: 'Path segment',
      s12_part_3: 'Location of the resource',
      s12_part_4_label: 'Dynamic segment',
      s12_part_4: 'Path that varies by value',
      s12_part_5_label: 'Query parameter',
      s12_part_5: 'Extra conditions',
      s12_part_6_label: 'Hash',
      s12_part_6: 'Position within the page',
      s12_flow_1_label: 'Request',
      s12_flow_2_label: 'Router',
      s12_flow_2: 'Checks the requested address',
      s12_flow_3_label: 'Match',
      s12_flow_3: 'Selects the page mapped to /about',
      s12_flow_4_label: 'Display',
      s12_flow_4: 'The About page is displayed',
      s13_title: 'Server-Side Routing and Client-Side Routing',
      s13_mpa_title: '1. Server-side routing',
      s13_mpa_lead: 'A new document is received from the server on every page transition',
      s13_mpa_pro_1: 'Simple and straightforward',
      s13_mpa_pro_2: 'Good for SEO',
      s13_mpa_con_1: 'A flash on every page transition',
      s13_mpa_con_2: 'Slow page transitions',
      s13_actor_user: 'User',
      s13_mpa_1: 'Clicks the About link',
      s13_actor_browser: 'Browser',
      s13_mpa_2: 'Requests the entire about.html document from the server',
      s13_actor_server: 'Server',
      s13_mpa_3: 'Responds with the entire about.html document',
      s13_mpa_4: 'Repaints the entire screen (visible flash)',
      s13_spa_title: '2. Client-side routing',
      s13_spa_lead: 'JavaScript handles the page transition',
      s13_spa_pro_1: 'Fast page transitions',
      s13_spa_pro_2: 'Smooth user experience',
      s13_spa_con_1: 'Slow initial load',
      s13_spa_con_2: 'Requires extra work for SEO',
      s13_spa_1: 'Clicks the About link',
      s13_spa_2: 'Requests only the data the About page needs',
      s13_spa_3: 'Responds with the requested data as JSON',
      s13_spa_4: 'Replaces only the content area of the current page',
      s13_spa_def_label: 'SPA (Single Page Application)',
      s13_spa_def: 'The whole website is built as a single page; moving to another page does not reload everything, and JavaScript dynamically replaces only the part that changes',
      s14_title: 'Checking in the Browser',
      s14_lead: 'Use Chrome DevTools to inspect the concepts covered so far',
      s14_devtools_label: 'Developer tools',
      s14_shortcut_label: 'Shortcut',
      s14_devtools_1: 'Inspect document elements',
      s14_devtools_2: 'Review the semantic layout',
      s14_devtools_3: 'Check SEO and meta information',
      s14_viewport_label: 'Responsive and viewport check',
      s14_toggle_label: 'Device toolbar',
      s14_viewport_1: 'Check layout results across viewports (mobile, tablet)',
      s14_viewport_2: 'Test device resolutions and rotation from the top bar',
      s14_network_label: 'Raw HTML and response headers',
      s14_network_1: 'Network panel → click the Doc entry (the first item)',
      s14_network_3: 'Read the raw HTML the server sent in the Response tab',
      s15_title: 'Next Step: Web Frameworks',
      s15_lead: 'Limits of hand-written pages and why frameworks exist · a preview of the tools used in later weeks',
      s48_title: 'Limits of Hand-Written Web Pages',
      s48_lead: 'Writing HTML, CSS and JavaScript files by hand, as in the week 1 assignment, means repetitive work grows along with the number of screens and features',
      s48_item_1_label: 'Duplicated markup',
      s48_item_1: 'Header, navigation and footer copied into every page · one fix means editing every file again',
      s48_item_2_label: 'Scattered state',
      s48_item_2: 'Screen and data synchronised by hand through the DOM · changes get harder to track as screens multiply',
      s48_item_3_label: 'Manual optimisation',
      s48_item_3: 'Bundling, minification, caching and code splitting handled by hand · the burden of managing rendering performance',
      s48_item_4_label: 'Repeated deployment',
      s48_item_4: 'Uploading the result and re-checking behaviour after every change',
      s48_note_label: 'The answer',
      s48_note: 'Frameworks and build tools handle this repetitive work in a standard way so developers can focus on screens and features',
      s16_title: 'Web Development Frameworks',
      s16_lead: 'A prepared blueprint and toolkit for building web services faster and more safely; the goal is to provide repetitive development work in a standard way and reduce trial and error',
      s16_parts_label: 'Components',
      s16_part_1_label: 'Structure',
      s16_part_1: 'Folder and file conventions, layered architecture (controller, service, model, and so on)',
      s16_part_2_label: 'Running kit',
      s16_part_2: 'Router, middleware, ORM and query tools, forms and validation, auth, i18n, testing',
      s16_part_3_label: 'Build and runtime',
      s16_part_3: 'Bundling, transpiling (for example TypeScript), code splitting, SSR and SSG support',
      s16_part_4_label: 'Ecosystem',
      s16_part_4: 'Plugins, CLI, best-practice documentation',
      s16_kinds_label: 'Categories',
      s16_kind_1_label: 'Frontend (UI)',
      s16_kind_2_label: 'Backend (API)',
      s16_kind_3_label: 'Full stack (frontend + backend)',
      s16_choice_label: 'Selection criteria',
      s16_choice_1_label: 'Team skills and language',
      s16_choice_1: 'JS / TS leads to Next.js and NestJS; Python leads to Django and FastAPI',
      s16_choice_2_label: 'Rendering strategy',
      s16_choice_2: 'Whether CSR / SSR / SSG / ISR is required (SEO, initial load requirements)',
      s16_choice_3_label: 'Hosting and deployment',
      s16_choice_3: 'Vercel and Netlify (serverless) or containers and Kubernetes',
      s16_choice_4_label: 'Ecosystem',
      s16_choice_4: 'Richness of documentation, community, and plugins',
      s16_course_label: 'This course',
      s16_course: 'Frontend React + Vite (week 4) · backend Node.js + Express (week 6) · database PostgreSQL + Supabase (week 7) · deployment Vercel (week 9)',
      s21_title: 'Comparison of Major Frontend Frameworks',
      s21_features_label: 'Why this course uses React',
      s21_feature_1: 'The largest ecosystem and the most learning material · answers are easy to find',
      s21_feature_2: 'Component-based development connects directly to the frontend structure of later weeks',
      s21_feature_3: 'High adoption in the job market and in production projects',
      s21_feature_4: 'Fast dev server and build times when paired with Vite',
      s21_feature_5: 'Mature TypeScript support · connects straight to what week 3 covers',
      s21_head_feature: 'Feature',
      s21_vdom_react: 'Used',
      s21_vdom_vue: 'Used',
      s21_vdom_svelte: 'Not used',
      s21_row_bundle: 'Bundle size',
      s21_row_curve: 'Learning curve',
      s21_curve_react: 'Medium ~ high',
      s21_curve_vue: 'Low ~ medium',
      s21_curve_svelte: 'Low',
      s21_row_perf: 'Performance',
      s21_perf_react: 'Good',
      s21_perf_vue: 'Good',
      s21_perf_svelte: 'Excellent',
      s21_row_eco: 'Ecosystem',
      s21_eco_react: 'Very large',
      s21_eco_vue: 'Large',
      s21_eco_svelte: 'Growing',
      s21_note_label: 'Note',
      s21_note: 'Bundle sizes are approximate runtime figures · actual size varies with version and build configuration',
      s17_lead: 'A JavaScript runtime built on the Chrome V8 engine that allows JavaScript to run outside the web browser',
      s17_feature_1_label: '1. JavaScript runtime',
      s17_feature_1_1: 'Run JavaScript on a machine without a browser',
      s17_feature_1_2: 'Build server programs, desktop apps, and command-line tools',
      s17_feature_2_label: '2. Asynchronous I/O',
      s17_feature_2_1: 'Handle many tasks at the same time',
      s17_feature_2_2: 'Move on to other work instead of waiting for one task to finish',
      s17_feature_2_3: 'High performance and efficiency',
      s17_feature_3_label: '3. Single-threaded event loop',
      s17_feature_3_1: 'Handle many connections efficiently on a single thread',
      s17_feature_3_2: 'Low memory usage',
      s17_feature_4_label: '4. NPM ecosystem',
      s17_feature_4_1: 'The largest open source library ecosystem in the world',
      s17_feature_4_2: 'More than one million packages available',
      s18_lead: 'Interacting with a computer by entering commands from the keyboard · short text commands automate file management, tool execution, and server work quickly and precisely',
      s18_why_label: 'Why developers use the CLI',
      s18_why_1_label: 'Speed and automation',
      s18_why_1: 'Handle repetitive work with a single scripted line',
      s18_why_2_label: 'Reproducibility',
      s18_why_2: 'The same command always produces the same result',
      s18_why_3_label: 'Remote work',
      s18_why_3: 'The standard tool for managing cloud servers',
      s18_why_4_label: 'Development ecosystem',
      s18_why_4: 'Node / npm, Git, React, Express, Codex, Claude, and Gemini mostly run through a CLI',
      s18_terms_label: 'Basic terms',
      s18_term_1_label: 'Terminal',
      s18_term_1: 'The program where commands are typed (for example macOS Terminal, Windows PowerShell)',
      s18_term_2_label: 'Shell',
      s18_term_2: 'The engine that interprets and runs commands (bash, zsh, PowerShell)',
      s18_term_3_label: 'Prompt',
      s18_term_3: 'The marker showing the shell is waiting for input',
      s18_term_4_label: 'Path',
      s18_term_4: 'The current working directory; ~ is home, . is current, .. is parent',
      s19_title: 'NPM and NPX',
      s19_npm_lead: 'The package manager for JavaScript · supports downloading and managing code written by other developers',
      s19_npm_1_label: 'Install packages',
      s19_npm_1: 'Install required libraries and tools easily',
      s19_npm_2_label: 'Manage dependencies',
      s19_npm_2: 'Automatically manage every package the project needs',
      s19_npm_3_label: 'Run scripts',
      s19_npm_3: 'Manage commands such as running and building the project',
      s19_npm_4_label: 'Share packages',
      s19_npm_4: 'Share your own code with other developers',
      s19_npx_lead: 'An npm package runner that executes a package without installing it',
      s49_title: 'Where Today’s Concepts Lead',
      s49_lead: 'The structure, presentation and behaviour written by hand in week 2 grow into tools and frameworks in the weeks that follow',
      s49_step_1_label: 'Week 2 · today',
      s49_step_1: 'Writing HTML, CSS, JavaScript, DOM, rendering and routing by hand',
      s49_step_2_label: 'Week 3 · JavaScript → TypeScript',
      s49_step_2: 'Applying types to catch errors before the code runs',
      s49_step_3_label: 'Week 4 · React + Vite',
      s49_step_3: 'Composing screens from components with a build tool, rendered client side',
      s49_step_4_label: 'Week 9 · Deployment',
      s49_step_4: 'Deploying and operating the build output automatically',
      s49_setup_label: 'Before next week',
      s49_setup_1: 'Install the Node.js LTS release',
      s49_setup_2: 'Check the installed versions in the terminal',
      s42_title: 'Assignment: A Multi-Page Site with Semantic HTML, CSS and the DOM',
      s43_title: 'Assignment Overview',
      s43_overview: 'Extend the week 1 assignment into a three-page personal site and publish it on GitHub Pages',
      s43_learning_label: 'Learning goals',
      s43_learning_1: 'Write document structure with semantic tags',
      s43_learning_2: 'Separate shared styles into external CSS and build the layout',
      s43_learning_3: 'Implement user interaction through DOM manipulation',
      s43_learning_4: 'Inspect document structure and responses with developer tools',
      s43_requirements_label: 'Requirements',
      s43_req_1: 'index.html, about.html and projects.html are written and linked to each other',
      s43_req_2: 'Document structure uses semantic tags such as header, nav, main, section, article and footer',
      s43_req_3: 'Shared styles live in an external style.css linked from every page',
      s43_req_4: 'script.js implements at least one interaction that changes the DOM',
      s43_req_5: 'The site is published on GitHub Pages and all three pages render correctly',
      s43_reference: 'Reference',
      s43_deadline_label: 'Deadline',
      s43_due: 'September 20, 23:59',
      s43_submit_note: 'Submit the following through the LMS',
      s43_submit_1: 'GitHub repository URL',
      s43_submit_2: 'GitHub Pages URL',
      s50_title: 'Further Reading',
      s50_lead: 'References for checking and extending the concepts covered today',
      s50_docs_label: 'Documentation and standards',
      s50_docs_1: 'Reference documentation for HTML, CSS, JavaScript and the DOM',
      s50_docs_2: 'The HTML standard itself',
      s50_docs_3: 'Example-driven material for the basics',
      s50_tools_label: 'Performance and compatibility',
      s50_tools_1: 'How FCP, LCP and CLS are measured and improved',
      s50_tools_2: 'Performance scores for a deployed page',
      s50_tools_3: 'Browser support for individual features',
      s44_discord_label: 'Discord Channel Invitation'
    }
  };
})();
