window.LECTURE_CONTENT = {
  "ko": {
    "page_title": "03 | JavaScript → TypeScript",
    "cover_eyebrow": "2026학년도 2학기 실전웹서비스개발",
    "cover_title": "실전 웹서비스개발 – 3주차",
    "cover_subtitle": "JavaScript와 TypeScript · 문법과 코드 구조",
    "chapter_01_title": "웹 프로그래밍 언어의 역사",
    "chapter_01_subtitle": "웹의 변화 · JavaScript의 등장과 표준화",
    "topic_01_title": "웹 문서와 프로그램의 역할",
    "topic_01_subtitle": "문서 전달 → 서버의 데이터 처리 · 브라우저의 상호작용",
    "topic_01_panel_0_label": "문서 · 서버 · 브라우저",
    "topic_01_panel_0_head_0": "구성",
    "topic_01_panel_0_head_1": "역할",
    "topic_01_panel_0_head_2": "주문 서비스",
    "topic_01_panel_0_cell_0_0": "HTML",
    "topic_01_panel_0_cell_0_1": "문서 구조",
    "topic_01_panel_0_cell_0_2": "상품명 · 가격 표시",
    "topic_01_panel_0_cell_1_0": "서버 프로그램",
    "topic_01_panel_0_cell_1_1": "데이터 처리",
    "topic_01_panel_0_cell_1_2": "상품 조회 · 주문 저장",
    "topic_01_panel_0_cell_2_0": "브라우저 프로그램",
    "topic_01_panel_0_cell_2_1": "사용자 상호작용",
    "topic_01_panel_0_cell_2_2": "수량 입력 · 결과 갱신",
    "topic_02_title": "JavaScript의 탄생",
    "topic_02_subtitle": "1995년 Netscape의 브라우저 스크립트 언어",
    "topic_02_panel_0_label": "1995 · Netscape",
    "topic_02_panel_0_item_0": "Brendan Eich의 브라우저 언어 설계",
    "topic_02_panel_0_item_1": "Mocha → LiveScript → JavaScript",
    "topic_02_panel_0_item_2": "웹페이지의 입력 처리와 상호작용",
    "topic_03_title": "ECMAScript 표준화",
    "topic_03_subtitle": "공통 언어 규칙과 ES2015 이후의 문법",
    "topic_03_panel_0_label": "표준화의 주요 시점",
    "topic_03_panel_0_head_0": "시점",
    "topic_03_panel_0_head_1": "의미",
    "topic_03_panel_0_cell_0_0": "1997",
    "topic_03_panel_0_cell_0_1": "ECMA-262 초판 · 공통 언어 규칙",
    "topic_03_panel_0_cell_1_0": "2015",
    "topic_03_panel_0_cell_1_1": "ES2015 · let, const, 화살표 함수, 모듈",
    "topic_03_panel_0_cell_2_0": "TC39",
    "topic_03_panel_0_cell_2_1": "언어 사양의 제안과 검토",
    "topic_03_panel_1_label": "현대 JavaScript · ES2015 문법",
    "topic_03_panel_1_code": "const price = 3000;\nlet quantity = 2;\nconst lineTotal = (price, quantity) => price * quantity;\nconsole.log(lineTotal(price, quantity));",
    "topic_03_panel_1_output_label": "실행 결과",
    "chapter_02_title": "JavaScript의 기본 문법과 특징",
    "chapter_02_subtitle": "값과 연산 · 함수와 객체 · 이벤트와 비동기",
    "topic_04_title": "값 · 타입 · 변수",
    "topic_04_subtitle": "값의 타입과 let · const의 재할당 규칙",
    "topic_04_panel_0_label": "값과 변수 · JavaScript",
    "topic_04_panel_0_code": "const price = 3000;\nlet quantity = 2;\nquantity = 3;\nconst name = 'Notebook';\nconst available = true;\nlet selected;\nconsole.log(typeof price, typeof name);\nconsole.log(selected, null);",
    "topic_04_panel_0_output_label": "실행 결과",
    "topic_04_panel_1_label": "선언과 값",
    "topic_04_panel_1_item_0": "let · 재할당 가능 / const · 재할당 불가",
    "topic_04_panel_1_item_1": "number · string · boolean",
    "topic_04_panel_1_item_2": "undefined · 미지정 값 / null · 명시적 빈 값",
    "topic_05_title": "연산자와 형 변환",
    "topic_05_subtitle": "명시적 · 암묵적 변환에 따른 연산 결과",
    "topic_05_panel_0_label": "같은 입력, 다른 연산",
    "topic_05_panel_0_code": "const raw = '2';\nconsole.log(raw + 1);\nconsole.log(raw - 1);\nconsole.log(Number(raw) + 1);\nconsole.log(Number(''));\nconsole.log(Number('two'));",
    "topic_05_panel_0_output_label": "실행 결과",
    "topic_05_panel_1_label": "연산 결과 읽기",
    "topic_05_panel_1_item_0": "문자열 + 숫자 → 문자열 연결",
    "topic_05_panel_1_item_1": "뺄셈 → 암묵적 숫자 변환",
    "topic_05_panel_1_item_2": "Number() → 명시적 숫자 변환",
    "topic_05_panel_1_item_3": "변환 불가 → NaN",
    "topic_06_title": "조건문과 입력 검증",
    "topic_06_subtitle": "비교 · 논리 연산으로 수량과 재고 조건 검사",
    "topic_06_panel_0_label": "수량과 재고 검사",
    "topic_06_panel_0_code": "const quantity = Number('3');\nconst stock = 5;\nconst valid =\n  Number.isInteger(quantity) &&\n  quantity > 0 &&\n  quantity <= stock;\nif (valid) {\n  console.log('ready');\n} else {\n  console.log('invalid');\n}",
    "topic_06_panel_0_output_label": "실행 결과",
    "topic_06_panel_1_label": "조건의 의미",
    "topic_06_panel_1_item_0": "Number.isInteger · 정수 검사",
    "topic_06_panel_1_item_1": "quantity > 0 · 양수 검사",
    "topic_06_panel_1_item_2": "quantity <= stock · 재고 검사",
    "topic_06_panel_1_item_3": "&& · 모든 조건 충족",
    "topic_07_title": "배열과 반복문",
    "topic_07_subtitle": "배열 순회와 누적 변수로 주문 금액 합산",
    "topic_07_panel_0_label": "주문 항목의 금액 합산",
    "topic_07_panel_0_code": "const amounts = [3000, 1500, 6000];\nlet total = 0;\nfor (const amount of amounts) {\n  total = total + amount;\n}\nconsole.log(total);",
    "topic_07_panel_0_output_label": "실행 결과",
    "topic_07_panel_1_label": "반복별 값 변화",
    "topic_07_panel_1_head_0": "amount",
    "topic_07_panel_1_head_1": "total",
    "topic_07_panel_1_cell_0_0": "3000",
    "topic_07_panel_1_cell_0_1": "0 → 3000",
    "topic_07_panel_1_cell_1_0": "1500",
    "topic_07_panel_1_cell_1_1": "3000 → 4500",
    "topic_07_panel_1_cell_2_0": "6000",
    "topic_07_panel_1_cell_2_1": "4500 → 10500",
    "topic_08_title": "함수와 블록 스코프",
    "topic_08_subtitle": "매개변수 · 반환값 · 변수 접근 범위",
    "topic_08_panel_0_label": "입력 · 반환 · 접근 범위",
    "topic_08_panel_0_code": "function calculateLineTotal(price, quantity) {\n  const total = price * quantity;\n  return total;\n}\nconsole.log(calculateLineTotal(3000, 2));\nif (true) {\n  let message = 'ready';\n  console.log(message);\n}",
    "topic_08_panel_0_output_label": "실행 결과",
    "topic_08_panel_1_label": "함수 호출 읽기",
    "topic_08_panel_1_item_0": "인수 3000, 2 → 매개변수 price, quantity",
    "topic_08_panel_1_item_1": "return · 결과 반환과 함수 종료",
    "topic_08_panel_1_item_2": "total · 함수 내부 / message · if 블록 내부",
    "topic_09_title": "일급 함수 · 콜백 · 클로저",
    "topic_09_subtitle": "함수 전달과 반환 · 바깥 범위의 변수 접근",
    "topic_09_panel_0_label": "할인 함수를 반환하는 함수",
    "topic_09_panel_0_code": "function makeDiscount(rate) {\n  return (amount) => amount * (1 - rate);\n}\nconst memberPrice = makeDiscount(0.1);\nconst totals = [3000, 6000].map(memberPrice);\nconsole.log(totals);",
    "topic_09_panel_0_output_label": "실행 결과",
    "topic_09_panel_1_label": "함수의 세 가지 사용",
    "topic_09_panel_1_item_0": "일급 함수 · 변수 저장, 인수 전달, 반환",
    "topic_09_panel_1_item_1": "콜백 · map에 전달한 memberPrice",
    "topic_09_panel_1_item_2": "클로저 · makeDiscount 종료 후에도 rate에 접근",
    "topic_10_title": "객체 리터럴과 멤버",
    "topic_10_subtitle": "프로퍼티와 메서드로 상품 속성과 동작 표현",
    "topic_10_panel_0_label": "상품 객체와 메서드",
    "topic_10_panel_0_code": "const product = {\n  name: 'Notebook',\n  price: 3000,\n  stock: 5,\n  inStock() {\n    return this.stock > 0;\n  }\n};\nconsole.log(product.name, product.inStock());",
    "topic_10_panel_0_output_label": "실행 결과",
    "topic_10_panel_1_label": "객체의 멤버",
    "topic_10_panel_1_item_0": "프로퍼티 · name, price, stock",
    "topic_10_panel_1_item_1": "메서드 · inStock()",
    "topic_10_panel_1_item_2": "product.inStock()의 this → product",
    "topic_11_title": "객체 참조와 얕은 복사",
    "topic_11_subtitle": "대입의 참조 공유 · 스프레드의 중첩 참조 유지",
    "topic_11_panel_0_label": "공유 참조와 중첩 객체",
    "topic_11_panel_0_code": "const product = { stock: { count: 5 } };\nconst shared = product;\nconst copied = { ...product };\nshared.stock.count = 4;\ncopied.stock.count = 0;\nconsole.log(product.stock.count);\nconsole.log(copied === product);\nconsole.log(copied.stock === product.stock);",
    "topic_11_panel_0_output_label": "실행 결과",
    "topic_11_panel_1_label": "복사의 깊이",
    "topic_11_panel_1_item_0": "대입 · 같은 객체의 참조 공유",
    "topic_11_panel_1_item_1": "스프레드 · 바깥 객체만 복사",
    "topic_11_panel_1_item_2": "중첩 stock · 참조 공유",
    "topic_12_title": "filter · map의 목록 변환",
    "topic_12_subtitle": "조건에 맞는 상품 선택 · 필요한 값 추출",
    "topic_12_panel_0_label": "상품 배열 → 상품명 배열",
    "topic_12_panel_0_code": "const products = [\n  { name: 'Notebook', stock: 5 },\n  { name: 'Case', stock: 0 }\n];\nconst names = products\n  .filter((product) => product.stock > 0)\n  .map((product) => product.name);\nconsole.log(names);",
    "topic_12_panel_0_output_label": "실행 결과",
    "topic_12_panel_1_label": "두 콜백의 역할",
    "topic_12_panel_1_item_0": "filter · stock > 0인 상품 선택",
    "topic_12_panel_1_item_1": "map · 상품 객체를 name으로 변환",
    "topic_12_panel_1_item_2": "원본 2개 → 결과 1개 · 새 배열 생성",
    "topic_13_title": "DOM 이벤트와 입력 처리",
    "topic_13_subtitle": "처리 함수 등록 → 입력값 변환 → 주문 호출",
    "topic_13_panel_0_label": "DOM 이벤트 등록",
    "topic_13_panel_0_code": "const input = document.querySelector('#quantity');\nconst button = document.querySelector('#submit');\nbutton.addEventListener('click', () => {\n  const quantity = Number(input.value);\n  console.log(quantity);\n});",
    "topic_13_panel_1_label": "등록과 실행",
    "topic_13_panel_1_item_0": "초기화 · 콜백 등록",
    "topic_13_panel_1_item_1": "클릭 · 콜백 실행",
    "topic_13_panel_1_item_2": "input.value: \"2\" → quantity: 2",
    "topic_14_title": "Promise와 async/await",
    "topic_14_subtitle": "요청 완료 대기 · try/catch로 성공과 실패 처리",
    "topic_14_panel_0_label": "HTTP 상태 확인과 예외 처리",
    "topic_14_panel_0_code": "async function loadProducts() {\n  const response = await fetch('/products.json');\n  if (!response.ok) throw new Error('HTTP error');\n  return response.json();\n}\ntry {\n  const products = await loadProducts();\n  console.log(products.length);\n} catch (error) {\n  console.log('load failed');\n}",
    "topic_14_panel_1_label": "비동기 실행의 경계",
    "topic_14_panel_1_item_0": "await · 요청 완료까지 현재 실행 흐름 대기",
    "topic_14_panel_1_item_1": "response.ok · HTTP 성공 상태 확인",
    "topic_14_panel_1_item_2": "catch · 요청 · JSON 해석 · throw 오류 처리",
    "chapter_03_title": "JavaScript의 장점과 오류 위험",
    "chapter_03_subtitle": "유연한 코드 조합 · 형 변환과 공유 상태의 오류",
    "topic_15_title": "동적 타입과 코드 조합",
    "topic_15_subtitle": "다양한 값 · 함수 · 객체의 유연한 조합",
    "topic_15_panel_0_label": "필터 함수의 교체",
    "topic_15_panel_0_code": "const products = [\n  { name: 'Notebook', price: 3000, stock: 5 },\n  { name: 'Case', price: 8000, stock: 0 }\n];\nconst inStock = (p) => p.stock > 0;\nconst affordable = (p) => p.price < 5000;\nconsole.log(products.filter(inStock).length);\nconsole.log(products.filter(affordable).length);",
    "topic_15_panel_0_output_label": "실행 결과",
    "topic_15_panel_1_label": "유연성의 이점",
    "topic_15_panel_1_item_0": "객체 · 데이터 속성의 묶음",
    "topic_15_panel_1_item_1": "함수 · 선택 조건의 교체",
    "topic_16_title": "형 변환 · 오타 · 공유 상태 오류",
    "topic_16_subtitle": "잘못된 값 전달과 객체 변경으로 생기는 오류",
    "topic_16_panel_0_label": "잘못된 실행 결과",
    "topic_16_panel_0_code": "const product = { price: 3000, stock: 5 };\nconst alias = product;\nconsole.log(2 + '3');\nconsole.log(product.prcie * 2);\nalias.stock = 0;\nconsole.log(product.stock);",
    "topic_16_panel_0_output_label": "실행 결과",
    "topic_16_panel_1_label": "서로 다른 오류 원인",
    "topic_16_panel_1_item_0": "23 · 숫자 덧셈 대신 문자열 연결",
    "topic_16_panel_1_item_1": "NaN · 없는 속성 prcie의 undefined로 계산",
    "topic_16_panel_1_item_2": "0 · alias와 product의 참조 공유",
    "topic_17_title": "타입 검사와 실행 시 검증",
    "topic_17_subtitle": "타입 사용 오류 검사 · 실제 입력과 업무 규칙 검증",
    "topic_17_panel_0_label": "오류와 검사 위치",
    "topic_17_panel_0_head_0": "상황",
    "topic_17_panel_0_head_1": "주요 검사",
    "topic_17_panel_0_cell_0_0": "숫자 매개변수에 문자열",
    "topic_17_panel_0_cell_0_1": "타입 검사",
    "topic_17_panel_0_cell_1_0": "product.prcie 오타",
    "topic_17_panel_0_cell_1_1": "타입 검사",
    "topic_17_panel_0_cell_2_0": "수량 -1 · 재고 초과",
    "topic_17_panel_0_cell_2_1": "실행 시 업무 규칙 검증",
    "topic_17_panel_0_cell_3_0": "외부 JSON의 누락 필드",
    "topic_17_panel_0_cell_3_1": "실행 시 데이터 검증",
    "topic_17_panel_1_label": "검사의 한계",
    "topic_17_panel_1_item_0": "number는 양의 정수를 보장하지 않음",
    "topic_17_panel_1_item_1": "외부 응답은 실행 중 구조와 값 확인",
    "chapter_04_title": "TypeScript의 등장과 역할",
    "chapter_04_subtitle": "JavaScript 확장 · 타입 검사와 코드 변환",
    "topic_18_title": "TypeScript의 등장 배경",
    "topic_18_subtitle": "2012년 공개 · 대규모 JavaScript의 구조화와 오류 발견 지원",
    "topic_18_panel_0_label": "2012 · Microsoft",
    "topic_18_panel_0_item_0": "대규모 JavaScript 코드의 변경과 협업",
    "topic_18_panel_0_item_1": "2012년 10월 1일 TypeScript 공개",
    "topic_18_panel_0_item_2": "타입 계약 · 편집기 지원 · 오류 조기 발견",
    "topic_18_panel_1_label": "JavaScript와의 관계",
    "topic_18_panel_1_item_0": "기존 JavaScript 문법과 실행 환경 활용",
    "topic_18_panel_1_item_1": "타입으로 코드 구조와 사용법 표현",
    "topic_19_title": "정적 타입 검사와 코드 변환",
    "topic_19_subtitle": "실행 전 타입 검사 · 타입 표기 없는 JavaScript 출력",
    "topic_19_panel_0_label": "TypeScript · 타입 표기",
    "topic_19_panel_0_code": "function lineTotal(\n  price: number,\n  quantity: number\n): number {\n  return price * quantity;\n}\nconsole.log(lineTotal(3000, 2));",
    "topic_19_panel_0_output_label": "실행 결과",
    "topic_19_panel_1_label": "JavaScript · 타입 제거",
    "topic_19_panel_1_code": "function lineTotal(price, quantity) {\n  return price * quantity;\n}\nconsole.log(lineTotal(3000, 2));",
    "topic_19_panel_1_output_label": "실행 결과",
    "chapter_05_title": "TypeScript의 기본 문법과 특징",
    "chapter_05_subtitle": "타입 계약 · 타입 좁히기 · 외부 데이터 검증",
    "topic_20_title": "타입 표기와 추론",
    "topic_20_subtitle": "타입의 명시적 선언 · 초기값에 따른 추론",
    "topic_20_panel_0_label": "타입 추론과 표기",
    "topic_20_panel_0_code": "let quantity = 2;\nconst price: number = 3000;\nconst name: string = 'Notebook';\nconst available: boolean = true;\nconst amounts: number[] = [3000, 6000];\nquantity = '2';",
    "topic_20_panel_0_diagnostic": "타입 오류: TS2322",
    "topic_20_panel_1_label": "컴파일러의 판단",
    "topic_20_panel_1_item_0": "quantity = 2 → number 추론",
    "topic_20_panel_1_item_1": "price: number → 타입 명시",
    "topic_20_panel_1_item_2": "quantity = \"2\" → 타입 불일치",
    "topic_21_title": "함수의 매개변수 · 반환 타입",
    "topic_21_subtitle": "함수 입력과 출력의 타입 계약",
    "topic_21_panel_0_label": "함수 계약",
    "topic_21_panel_0_code": "function calculateLineTotal(\n  price: number,\n  quantity: number\n): number {\n  return price * quantity;\n}\ncalculateLineTotal(3000, 2);\ncalculateLineTotal(3000, '2');",
    "topic_21_panel_0_diagnostic": "타입 오류: TS2345",
    "topic_21_panel_1_label": "입력과 반환",
    "topic_21_panel_1_item_0": "price · quantity → number 인수",
    "topic_21_panel_1_item_1": "반환값 → number",
    "topic_21_panel_1_item_2": "문자열 \"2\" 전달 → 타입 오류",
    "topic_22_title": "객체 타입: type · interface",
    "topic_22_subtitle": "필수 속성과 각 속성의 타입 정의",
    "topic_22_panel_0_label": "type으로 상품 구조 정의",
    "topic_22_panel_0_code": "type Product = {\n  id: string;\n  name: string;\n  price: number;\n  stock: number;\n};\nconst product: Product = {\n  id: 'note',\n  name: 'Notebook',\n  price: 3000,\n  stock: 5\n};",
    "topic_22_panel_1_label": "interface로 상품 구조 정의",
    "topic_22_panel_1_code": "interface Product {\n  id: string;\n  name: string;\n  price: number;\n  stock: number;\n}\nconst product: Product = {\n  id: 'note',\n  name: 'Notebook',\n  price: 3000,\n  stock: 5\n};",
    "topic_23_title": "리터럴 타입과 유니온",
    "topic_23_subtitle": "주문 상태를 정해진 값의 집합으로 제한",
    "topic_23_panel_0_label": "주문 상태 유니온",
    "topic_23_panel_0_code": "type OrderStatus =\n  'idle' | 'submitting' | 'success' | 'error';\nlet status: OrderStatus = 'idle';\nstatus = 'submitting';\nstatus = 'done';",
    "topic_23_panel_0_diagnostic": "타입 오류: TS2322",
    "topic_23_panel_1_label": "허용 상태와 전환",
    "topic_23_panel_1_item_0": "idle · 입력 대기",
    "topic_23_panel_1_item_1": "submitting · 요청 진행",
    "topic_23_panel_1_item_2": "success 또는 error · 요청 결과",
    "topic_24_title": "선택적 속성과 undefined",
    "topic_24_subtitle": "속성이나 검색 결과의 존재 여부 확인",
    "topic_24_panel_0_label": "선택적 값과 검색 결과",
    "topic_24_panel_0_code": "type Product = {\n  id: string;\n  price: number;\n  discountPrice?: number;\n};\nconst products: Product[] = [\n  { id: 'note', price: 3000 }\n];\nconst found = products.find((p) => p.id === 'note');\nif (found !== undefined) {\n  console.log(found.discountPrice ?? found.price);\n}",
    "topic_24_panel_0_output_label": "실행 결과",
    "topic_24_panel_1_label": "두 가지 빈 값",
    "topic_24_panel_1_item_0": "find 결과 → Product 또는 undefined",
    "topic_24_panel_1_item_1": "discountPrice → number 또는 undefined",
    "topic_24_panel_1_item_2": "존재 확인 후 속성 접근",
    "topic_24_panel_1_item_3": "?? · null과 undefined에 대체값 적용",
    "topic_25_title": "조건문과 타입 좁히기",
    "topic_25_subtitle": "조건과 판별 속성으로 사용 가능한 타입 구분",
    "topic_25_panel_0_label": "판별 속성 ok로 결과 분기",
    "topic_25_panel_0_code": "type Result =\n  | { ok: true; data: number }\n  | { ok: false; message: string };\nfunction describe(result: Result): string {\n  if (result.ok) {\n    return `quantity: ${result.data}`;\n  }\n  return result.message;\n}\nconsole.log(describe({ ok: true, data: 2 }));",
    "topic_25_panel_0_output_label": "실행 결과",
    "topic_25_panel_1_label": "분기 안의 타입",
    "topic_25_panel_1_item_0": "ok: true → data 사용",
    "topic_25_panel_1_item_1": "ok: false → message 사용",
    "topic_25_panel_1_item_2": "조건 검사 전 data 접근 → 타입 오류",
    "topic_26_title": "any와 unknown",
    "topic_26_subtitle": "검사를 우회하는 any · 확인 후 사용하는 unknown",
    "topic_26_panel_0_label": "any · 검사 우회",
    "topic_26_panel_0_code": "const raw: any = 3000;\nraw.toUpperCase();",
    "topic_26_panel_0_runtime": "실행 시 TypeError",
    "topic_26_panel_1_label": "unknown · 검사 후 사용",
    "topic_26_panel_1_code": "function normalize(raw: unknown): string {\n  if (typeof raw === 'string') {\n    return raw.toUpperCase();\n  }\n  return 'not a string';\n}\nconsole.log(normalize(3000));",
    "topic_26_panel_1_output_label": "실행 결과",
    "topic_27_title": "타입 단언과 데이터 검증",
    "topic_27_subtitle": "컴파일러의 타입 판단 변경과 실제 값 검증의 차이",
    "topic_27_panel_0_label": "as는 값 검사나 변환이 아님",
    "topic_27_panel_0_code": "const raw: unknown = { price: '3000' };\nconst claimed = raw as { price: number };\nconsole.log(claimed.price + 1);\nif (\n  typeof raw === 'object' &&\n  raw !== null &&\n  'price' in raw &&\n  typeof raw.price === 'number'\n) {\n  console.log(raw.price + 1);\n} else {\n  console.log('invalid price');\n}",
    "topic_27_panel_0_output_label": "실행 결과",
    "topic_27_panel_1_label": "단언과 검증의 결과",
    "topic_27_panel_1_item_0": "as 이후에도 price는 문자열",
    "topic_27_panel_1_item_1": "컴파일러의 판단만 number로 변경",
    "topic_27_panel_1_item_2": "typeof 검사 → 문자열 가격 거부",
    "topic_28_title": "제네릭과 타입 관계",
    "topic_28_subtitle": "구체 타입이 달라도 입력 · 출력의 타입 관계 유지",
    "topic_28_panel_0_label": "첫 원소의 타입 관계",
    "topic_28_panel_0_code": "function first<T>(items: T[]): T | undefined {\n  return items[0];\n}\nconst amount = first([3000, 1500]);\nconst product = first([{ id: 'note', price: 3000 }]);\nconsole.log(amount);\nconsole.log(product?.id);\nconsole.log(first<number>([]));",
    "topic_28_panel_0_output_label": "실행 결과",
    "topic_28_panel_1_label": "T의 의미",
    "topic_28_panel_1_item_0": "숫자 배열 → number 또는 undefined",
    "topic_28_panel_1_item_1": "상품 배열 → 상품 타입 또는 undefined",
    "topic_28_panel_1_item_2": "빈 배열 → undefined",
    "topic_29_title": "모듈과 구조적 타입",
    "topic_29_subtitle": "import · export로 역할 분리 · 필요한 멤버로 호환성 판단",
    "topic_29_panel_0_label": "types.ts · 필요한 구조 내보내기",
    "topic_29_panel_0_code": "export type Named = { name: string };\nexport function label(item: Named): string {\n  return item.name;\n}",
    "topic_29_panel_1_label": "main.ts · 모듈 사용과 구조적 호환",
    "topic_29_panel_1_code": "import { label } from './types.js';\nimport type { Named } from './types.js';\nconst product = { name: 'Notebook', price: 3000 };\nconst named: Named = product;\nconsole.log(label(named));",
    "topic_29_panel_1_output_label": "실행 결과",
    "chapter_06_title": "웹 프로그래밍 패러다임",
    "chapter_06_subtitle": "실행 순서 · 계산과 상태 · 이벤트와 화면",
    "topic_30_title": "명령형 · 절차적 주문 처리",
    "topic_30_subtitle": "검증 → 계산 → 저장 요청 → 결과 반환",
    "topic_30_panel_0_label": "주문 처리 절차",
    "topic_30_panel_0_code": "async function submitOrder(raw: string) {\n  const quantity = Number(raw);\n  if (!Number.isInteger(quantity) || quantity <= 0) {\n    throw new Error('invalid quantity');\n  }\n  const total = 3000 * quantity;\n  await saveOrder(total);\n  return { status: 'success', total };\n}",
    "topic_30_panel_1_label": "절차와 실패 경로",
    "topic_30_panel_1_item_0": "수량 검증 → 실패하면 종료",
    "topic_30_panel_1_item_1": "금액 계산 → 저장 요청",
    "topic_30_panel_1_item_2": "요청 완료 → 성공 결과 반환",
    "topic_31_title": "순수 함수와 불변성",
    "topic_31_subtitle": "입력과 외부 상태를 바꾸지 않는 계산",
    "topic_31_panel_0_label": "지역 변수로 계산하는 순수 함수",
    "topic_31_panel_0_code": "function calculateTotal(amounts: number[]): number {\n  let total = 0;\n  for (const amount of amounts) {\n    total += amount;\n  }\n  return total;\n}\nconst amounts = [3000, 1500];\nconsole.log(calculateTotal(amounts));\nconsole.log(amounts.length);",
    "topic_31_panel_0_output_label": "실행 결과",
    "topic_31_panel_1_label": "순수성의 기준",
    "topic_31_panel_1_item_0": "같은 입력 → 같은 결과",
    "topic_31_panel_1_item_1": "입력 배열과 외부 상태 유지",
    "topic_31_panel_1_item_2": "지역 변수 total만 변경",
    "topic_32_title": "캡슐화와 장바구니 상태",
    "topic_32_subtitle": "상태와 동작을 묶고 메서드로 변경 제어",
    "topic_32_panel_0_label": "상태 접근을 제한하는 Cart",
    "topic_32_panel_0_code": "class Cart {\n  private items: string[] = [];\n  add(productId: string): void {\n    this.items.push(productId);\n  }\n  get count(): number {\n    return this.items.length;\n  }\n}\nconst cart = new Cart();\ncart.add('note');\nconsole.log(cart.count);",
    "topic_32_panel_0_output_label": "실행 결과",
    "topic_32_panel_1_label": "상태와 동작의 책임",
    "topic_32_panel_1_item_0": "private items · 외부 접근 제한",
    "topic_32_panel_1_item_1": "add() · 내부 배열 변경",
    "topic_32_panel_1_item_2": "count · 배열의 개수 공개",
    "topic_33_title": "이벤트와 비동기 실행",
    "topic_33_subtitle": "사용자 행동에 따른 실행 · 요청 완료 순서 관리",
    "topic_33_panel_0_label": "늦게 끝난 이전 요청 무시",
    "topic_33_panel_0_code": "let latestRequest = 0;\nasync function search(query: string): Promise<void> {\n  const requestId = ++latestRequest;\n  const products = await loadProducts(query);\n  if (requestId !== latestRequest) return;\n  renderProducts(products);\n}",
    "topic_33_panel_1_label": "응답 순서의 역전",
    "topic_33_panel_1_head_0": "시간",
    "topic_33_panel_1_head_1": "실행",
    "topic_33_panel_1_cell_0_0": "1",
    "topic_33_panel_1_cell_0_1": "검색 A 시작 · 요청 번호 1",
    "topic_33_panel_1_cell_1_0": "2",
    "topic_33_panel_1_cell_1_1": "검색 B 시작 · 요청 번호 2",
    "topic_33_panel_1_cell_2_0": "3",
    "topic_33_panel_1_cell_2_1": "B 완료 → 화면 갱신",
    "topic_33_panel_1_cell_3_0": "4",
    "topic_33_panel_1_cell_3_1": "A 완료 → 번호 불일치로 무시",
    "topic_34_title": "선언형 UI와 반응형 계산",
    "topic_34_subtitle": "상태로 화면 표현 · 의존 값 변화로 파생 값 갱신",
    "topic_34_panel_0_label": "React TSX · 상태에 따른 버튼",
    "topic_34_panel_0_code": "function OrderButton({ busy }: { busy: boolean }) {\n  return (\n    <button disabled={busy}>\n      {busy ? 'Sending' : 'Order'}\n    </button>\n  );\n}",
    "topic_34_panel_1_label": "Vue · 반응형 합계",
    "topic_34_panel_1_code": "import { computed, ref } from 'vue';\nconst quantity = ref(2);\nconst total = computed(() => 3000 * quantity.value);\nconsole.log(total.value);\nquantity.value = 3;\nconsole.log(total.value);",
    "topic_34_panel_1_output_label": "실행 결과",
    "topic_35_title": "패러다임 조합과 책임 분리",
    "topic_35_subtitle": "주문 기능의 이벤트 · 절차 · 계산 · 상태 · 화면 역할",
    "topic_35_panel_0_label": "하나의 주문 기능",
    "topic_35_panel_0_item_0": "입력 → 이벤트 처리",
    "topic_35_panel_0_item_1": "검증 → 순수 계산 → 저장 요청",
    "topic_35_panel_0_item_2": "결과 상태 → 화면 갱신",
    "topic_35_panel_1_label": "실습 파일의 책임",
    "topic_35_panel_1_head_0": "파일",
    "topic_35_panel_1_head_1": "역할",
    "topic_35_panel_1_cell_0_0": "main.ts",
    "topic_35_panel_1_cell_0_1": "이벤트와 절차 조정",
    "topic_35_panel_1_cell_1_0": "order.ts · policies.ts",
    "topic_35_panel_1_cell_1_1": "계산과 검증",
    "topic_35_panel_1_cell_2_0": "api.ts",
    "topic_35_panel_1_cell_2_1": "외부 데이터와 모의 요청",
    "topic_35_panel_1_cell_3_0": "ui.ts",
    "topic_35_panel_1_cell_3_1": "명령형 DOM 갱신",
    "topic_35_practice_link": "실습 README",
    "chapter_07_title": "TypeScript의 디자인 패턴",
    "chapter_07_subtitle": "Strategy의 정책 교체 · Adapter의 형식 변환",
    "topic_36_title": "할인 정책과 Strategy 패턴",
    "topic_36_subtitle": "계산 방식을 분리해 정책 변경 범위 축소",
    "topic_36_panel_0_label": "정책 이름으로 분기",
    "topic_36_panel_0_code": "function checkout(amount: number, kind: string) {\n  if (kind === 'member') {\n    return Math.floor(amount * 0.9);\n  }\n  return amount;\n}",
    "topic_36_panel_1_label": "교체 지점의 분리",
    "topic_36_panel_1_item_0": "정책 추가 → checkout 분기 증가",
    "topic_36_panel_1_item_1": "Strategy · 계산 함수를 별도로 정의",
    "topic_36_panel_1_item_2": "주문 함수 · 전달받은 정책 호출",
    "topic_37_title": "함수 타입과 정책 교체",
    "topic_37_subtitle": "공통 함수 타입으로 일반 · 회원 가격 정책 전달",
    "topic_37_panel_0_label": "공통 함수 타입과 정책 전달",
    "topic_37_panel_0_code": "type DiscountPolicy = (amount: number) => number;\nconst regularPrice: DiscountPolicy = (amount) => amount;\nconst memberPrice: DiscountPolicy = (amount) =>\n  Math.floor(amount * 0.9);\nfunction checkout(\n  amount: number,\n  policy: DiscountPolicy\n) {\n  return policy(amount);\n}\nconsole.log(checkout(6000, regularPrice));\nconsole.log(checkout(6000, memberPrice));",
    "topic_37_panel_0_output_label": "실행 결과",
    "topic_37_panel_1_label": "계약과 변경",
    "topic_37_panel_1_item_0": "입력 · 할인 전 금액",
    "topic_37_panel_1_item_1": "반환 · 결제 금액",
    "topic_37_panel_1_item_2": "회원 정책 · 10% 할인, 원 미만 버림",
    "topic_37_panel_1_item_3": "checkout · 전달받은 policy 호출",
    "topic_38_title": "상품 형식과 Adapter 패턴",
    "topic_38_subtitle": "외부 상품 필드를 내부 Product 형식으로 변환",
    "topic_38_panel_0_label": "검증된 외부 값의 변환",
    "topic_38_panel_0_code": "type ApiProduct = {\n  product_name: string;\n  unit_price: number;\n};\ntype Product = { name: string; price: number };\nfunction toProduct(raw: ApiProduct): Product {\n  return {\n    name: raw.product_name,\n    price: raw.unit_price\n  };\n}",
    "topic_38_panel_1_label": "Adapter의 경계",
    "topic_38_panel_1_item_0": "product_name → name",
    "topic_38_panel_1_item_1": "unit_price → price",
    "topic_38_panel_1_item_2": "입력 · 검증된 ApiProduct",
    "topic_38_panel_1_item_3": "반환 · 새로운 Product 객체",
    "topic_38_practice_link": "실습 README",
    "topic_39_title": "입력 검증과 형식 변환",
    "topic_39_subtitle": "unknown → 검증된 외부 데이터 → 내부 상품 → 주문 계산",
    "topic_39_panel_0_label": "외부 데이터의 입력 경계",
    "topic_39_panel_0_item_0": "unknown · 아직 확인하지 않은 값",
    "topic_39_panel_0_item_1": "검증기 · 필드 존재와 실제 타입 확인",
    "topic_39_panel_0_item_2": "ApiProduct → Adapter → Product",
    "topic_39_panel_0_item_3": "주문 계산 · 내부 계약만 사용",
    "topic_39_panel_1_label": "각 단계의 실패 원인",
    "topic_39_panel_1_item_0": "필드 누락 · 문자열 가격 → 검증 실패",
    "topic_39_panel_1_item_1": "잘못된 필드 매핑 → 변환 오류",
    "topic_40_title": "Strategy · Adapter 적용 기준",
    "topic_40_subtitle": "변경 지점 · 데이터 경계 · 구현 비용에 따른 선택",
    "topic_40_panel_0_label": "요구사항에 따른 선택",
    "topic_40_panel_0_head_0": "변경 요구",
    "topic_40_panel_0_head_1": "적용",
    "topic_40_panel_0_cell_0_0": "일반 · 회원 · 쿠폰 정책 교체",
    "topic_40_panel_0_cell_0_1": "Strategy · 계산 함수 교체",
    "topic_40_panel_0_cell_1_0": "외부 API의 상품 필드 변경",
    "topic_40_panel_0_cell_1_1": "Adapter · 내부 형식으로 매핑",
    "topic_40_panel_0_cell_2_0": "고정된 단가 × 수량 계산",
    "topic_40_panel_0_cell_2_1": "단순 함수 유지",
    "topic_40_panel_1_label": "추상화 비용",
    "topic_40_panel_1_item_0": "함수 · 파일 증가 → 코드 탐색 비용 증가",
    "topic_40_panel_1_item_1": "계약 추가 → 호출 관계의 복잡도 증가",
    "topic_40_practice_link": "실습 README",
    "chapter_08_title": "실습: TypeScript 상품 주문 기능",
    "chapter_08_subtitle": "기능 구현 · 코드 읽기 · 실행 검증",
    "topic_41_title": "실습 화면과 요구사항",
    "topic_41_subtitle": "HTML · CSS 제공 · 상품 선택 · 수량 검증 · 할인 구현",
    "topic_41_panel_0_label": "모의 주문서",
    "topic_41_panel_0_head_0": "입력",
    "topic_41_panel_0_head_1": "선택값",
    "topic_41_panel_0_cell_0_0": "상품",
    "topic_41_panel_0_cell_0_1": "노트 · 단가 3,000원",
    "topic_41_panel_0_cell_1_0": "수량",
    "topic_41_panel_0_cell_1_1": "2",
    "topic_41_panel_0_cell_2_0": "할인",
    "topic_41_panel_0_cell_2_1": "회원 · 10%",
    "topic_41_panel_0_cell_3_0": "결과",
    "topic_41_panel_0_cell_3_1": "6,000원 → 5,400원",
    "topic_41_panel_1_label": "구현 범위",
    "topic_41_panel_1_item_0": "제공 · HTML · CSS · 이벤트 골격",
    "topic_41_panel_1_item_1": "필수 · 수량 검증 · 주문 계산 · 회원 정책",
    "topic_41_panel_1_item_2": "선택 · 외부 데이터 Adapter",
    "topic_41_practice_link": "실습 README",
    "topic_42_title": "실습 데이터와 주문 흐름",
    "topic_42_subtitle": "상품과 입력값 → 검증과 계산 → 주문 결과",
    "topic_42_panel_0_label": "노트 2개 · 회원 주문",
    "topic_42_panel_0_item_0": "Product · price: 3000, stock: 5",
    "topic_42_panel_0_item_1": "입력 \"2\" → 수량 2 → 검증 통과",
    "topic_42_panel_0_item_2": "상품 금액 6000 → 회원 정책 → 5400",
    "topic_42_panel_0_item_3": "Result<Order> → 모의 요청 → 화면",
    "topic_42_panel_1_label": "주문 데이터",
    "topic_42_panel_1_item_0": "productId · 상품 검색 키",
    "topic_42_panel_1_item_1": "quantity · 검증된 수량",
    "topic_42_panel_1_item_2": "subtotal · 할인 전 금액",
    "topic_42_panel_1_item_3": "total · 정책 적용 금액",
    "topic_42_practice_link": "실습 README",
    "topic_43_title": "프로젝트 구조와 실행",
    "topic_43_subtitle": "제공 코드 · 수정 대상 · 실행과 타입 검사",
    "topic_43_panel_0_label": "practice · localhost:4303",
    "topic_43_panel_0_code": "npm ci\nnpm start\n\n# Second terminal\nnpm run watch\nnpm run check\nnpm test",
    "topic_43_panel_1_label": "파일과 작업",
    "topic_43_panel_1_head_0": "파일",
    "topic_43_panel_1_head_1": "작업",
    "topic_43_panel_1_cell_0_0": "src/order.ts",
    "topic_43_panel_1_cell_0_1": "TODO 1–3 · 필수 구현",
    "topic_43_panel_1_cell_1_0": "src/policies.ts",
    "topic_43_panel_1_cell_1_1": "TODO 4 · 회원 정책",
    "topic_43_panel_1_cell_2_0": "src/adapters.ts",
    "topic_43_panel_1_cell_2_1": "TODO 5 · 선택 구현",
    "topic_43_panel_1_cell_3_0": "main.ts · ui.ts · api.ts",
    "topic_43_panel_1_cell_3_1": "제공 코드 읽기",
    "topic_43_practice_link": "실습 README",
    "topic_44_title": "JavaScript 오류 재현",
    "topic_44_subtitle": "문자열 연산 · 속성 오타 · 없는 상품 접근의 결과 비교",
    "topic_44_panel_0_label": "reading/bugs.js · 실행 전 예측",
    "topic_44_panel_0_code": "const product = { price: 3000, stock: 5 };\nconsole.log('3' + 1);\nconsole.log(product.prcie * 2);\nconst found = [product].find((p) => p.price === 0);\nconsole.log(found.price);",
    "topic_44_panel_0_output_label": "실행 결과",
    "topic_44_panel_1_label": "오류 원인",
    "topic_44_panel_1_item_0": "\"3\" + 1 · 문자열 연결",
    "topic_44_panel_1_item_1": "product.prcie · 없는 속성",
    "topic_44_panel_1_item_2": "found.price · undefined의 속성 접근",
    "topic_44_practice_link": "실습 README",
    "topic_45_title": "수량 변환과 검증",
    "topic_45_subtitle": "빈 입력 거부 · 유한한 양의 정수와 재고 범위 확인",
    "topic_45_panel_0_label": "order.ts · 수량 검증",
    "topic_45_panel_0_code": "function parseQuantity(raw: string, stock: number) {\n  if (raw.trim() === '') {\n    return { ok: false, message: 'empty' };\n  }\n  const quantity = Number(raw);\n  if (\n    !Number.isFinite(quantity) ||\n    !Number.isInteger(quantity) ||\n    quantity <= 0\n  ) {\n    return { ok: false, message: 'invalid' };\n  }\n  if (quantity > stock) {\n    return { ok: false, message: 'over stock' };\n  }\n  return { ok: true, data: quantity };\n}",
    "topic_45_panel_1_label": "확인할 입력",
    "topic_45_panel_1_item_0": "빈 값 · 공백 · abc · Infinity → 실패",
    "topic_45_panel_1_item_1": "0 · -1 · 1.5 → 실패",
    "topic_45_panel_1_item_2": "재고 5: 수량 5 → 성공 / 6 → 실패",
    "topic_45_practice_link": "실습 README",
    "topic_46_title": "주문 코드의 TypeScript 전환",
    "topic_46_subtitle": "상품 구조와 함수 입력 · 출력에 타입 추가",
    "topic_46_panel_0_label": "전환 전 · JavaScript",
    "topic_46_panel_0_code": "function calculateLineTotal(price, quantity) {\n  return price * quantity;\n}\nconst product = {\n  id: 'note',\n  name: 'Notebook',\n  price: 3000,\n  stock: 5\n};",
    "topic_46_panel_1_label": "전환 후 · TypeScript",
    "topic_46_panel_1_code": "function calculateLineTotal(\n  price: number,\n  quantity: number\n): number {\n  return price * quantity;\n}\nconst product: Product = {\n  id: 'note',\n  name: 'Notebook',\n  price: 3000,\n  stock: 5\n};",
    "topic_46_practice_link": "실습 README",
    "topic_47_title": "타입 오류와 undefined 처리",
    "topic_47_subtitle": "잘못된 인수 · 속성 오타 · 값이 없는 경로 수정",
    "topic_47_panel_0_label": "존재 검사 전",
    "topic_47_panel_0_code": "const products = [{ id: 'note', price: 3000 }];\nconst found = products.find((p) => p.id === 'missing');\nconsole.log(found.price);",
    "topic_47_panel_0_diagnostic": "타입 오류: TS18048",
    "topic_47_panel_1_label": "존재 검사 후",
    "topic_47_panel_1_code": "const products = [{ id: 'note', price: 3000 }];\nconst found = products.find((p) => p.id === 'missing');\nif (found === undefined) {\n  console.log('product not found');\n} else {\n  console.log(found.price);\n}",
    "topic_47_panel_1_output_label": "실행 결과",
    "topic_47_practice_link": "실습 README",
    "topic_48_title": "할인 정책 분리 실습",
    "topic_48_subtitle": "일반 · 회원 가격 함수 구현과 주문 함수에 전달",
    "topic_48_panel_0_label": "policies.ts · 공통 정책 계약",
    "topic_48_panel_0_code": "type DiscountPolicy = (amount: number) => number;\nconst regularPrice: DiscountPolicy = (amount) => amount;\nconst memberPrice: DiscountPolicy = (amount) =>\n  Math.floor(amount * 0.9);\nconsole.log(regularPrice(6000));\nconsole.log(memberPrice(6000));\nconsole.log(memberPrice(3001));",
    "topic_48_panel_0_output_label": "실행 결과",
    "topic_48_panel_1_label": "정책 전달",
    "topic_48_panel_1_item_0": "main.ts · 일반 또는 회원 정책 선택",
    "topic_48_panel_1_item_1": "createOrder · 정책 함수 전달",
    "topic_48_panel_1_item_2": "policy(subtotal) · 결제 금액 반환",
    "topic_48_practice_link": "실습 README",
    "topic_49_title": "Adapter 확장 실습",
    "topic_49_subtitle": "제공 검증기와 상품 형식 변환 연결",
    "topic_49_panel_0_label": "adapters.ts · 검증 이후의 변환",
    "topic_49_panel_0_code": "function toProduct(raw: ApiProduct): Product {\n  return {\n    id: raw.id,\n    name: raw.product_name,\n    price: raw.unit_price,\n    stock: raw.stock\n  };\n}",
    "topic_49_panel_1_label": "fixture와 기대 결과",
    "topic_49_panel_1_head_0": "주소의 쿼리",
    "topic_49_panel_1_head_1": "기대 결과",
    "topic_49_panel_1_cell_0_0": "?fixture=valid",
    "topic_49_panel_1_cell_0_1": "검증 → 변환 → 상품 표시",
    "topic_49_panel_1_cell_1_0": "?fixture=missing",
    "topic_49_panel_1_cell_1_1": "필드 누락으로 검증 실패",
    "topic_49_panel_1_cell_2_0": "?fixture=wrong",
    "topic_49_panel_1_cell_2_1": "문자열 가격으로 검증 실패",
    "topic_49_practice_link": "실습 README",
    "topic_50_title": "정상 · 실패 · 경계 검증",
    "topic_50_subtitle": "주문 금액 · 잘못된 수량 · 상품 없음 · 요청 실패 확인",
    "topic_50_panel_0_label": "검증 시나리오",
    "topic_50_panel_0_head_0": "시나리오",
    "topic_50_panel_0_head_1": "기대 결과",
    "topic_50_panel_0_cell_0_0": "노트 2개 · 일반 / 회원",
    "topic_50_panel_0_cell_0_1": "6,000원 / 5,400원",
    "topic_50_panel_0_cell_1_0": "0 · 음수 · 소수 · 재고 초과",
    "topic_50_panel_0_cell_1_1": "주문 요청 전 거부",
    "topic_50_panel_0_cell_2_0": "없는 상품 ID · 품절 상품",
    "topic_50_panel_0_cell_2_1": "실패 결과 반환",
    "topic_50_panel_0_cell_3_0": "요청 실패 → 체크 해제 → 재시도",
    "topic_50_panel_0_cell_3_1": "오류 표시 → 버튼 복구 → 성공",
    "topic_50_panel_1_label": "자동 검사와 화면 검사",
    "topic_50_panel_1_item_0": "npm run check · 타입 검사",
    "topic_50_panel_1_item_1": "npm test · 계산과 경계값 검사",
    "topic_50_panel_1_item_2": "브라우저 · 중복 제출 방지와 실패 후 복구",
    "topic_50_practice_link": "실습 README",
    "topic_51_title": "AI 코드 예측과 검토",
    "topic_51_subtitle": "결과 예측 → 제안 검토 → 코드 수정 → 반례 실행",
    "topic_51_panel_0_label": "AI 코드 검토 절차",
    "topic_51_panel_0_item_0": "실행 전 결과와 타입 예측",
    "topic_51_panel_0_item_1": "특정 줄의 설명과 반례 요청",
    "topic_51_panel_0_item_2": "변경 전후 비교와 직접 수정",
    "topic_51_panel_0_item_3": "반례 실행과 결과 기록",
    "topic_51_panel_1_label": "검토 예시 · 수량 변환",
    "topic_51_panel_1_item_0": "제안 · Number 대신 parseInt 사용",
    "topic_51_panel_1_item_1": "반례 · parseInt(\"2abc\") → 2",
    "topic_51_panel_1_item_2": "판단 · 잘못된 수량 문자열 허용으로 제안 거절",
    "topic_51_practice_link": "실습 README",
    "topic_52_title": "제출물과 코드 설명",
    "topic_52_subtitle": "동작 코드 · 오류 기록 · 타입 검사와 실행 검증의 역할",
    "topic_52_panel_0_label": "제출물",
    "topic_52_panel_0_head_0": "자료",
    "topic_52_panel_0_head_1": "내용",
    "topic_52_panel_0_cell_0_0": "소스 코드",
    "topic_52_panel_0_cell_0_1": "필수 TODO 구현 · 실행 안내 · 잠금 파일",
    "topic_52_panel_0_cell_1_0": "review.md",
    "topic_52_panel_0_cell_1_1": "예측 · 실제 결과 · 수정 원인",
    "topic_52_panel_0_cell_2_0": "검증 결과",
    "topic_52_panel_0_cell_2_1": "타입 검사 · 기능 검사 · 브라우저 실패 시나리오",
    "topic_52_panel_1_label": "코드 설명 기준",
    "topic_52_panel_1_item_0": "입력 → 검증 → 계산 → 요청 → 화면 추적",
    "topic_52_panel_1_item_1": "타입 검사로 찾은 오류 설명",
    "topic_52_panel_1_item_2": "실행 검증이 필요한 오류 설명",
    "topic_52_practice_link": "실습 README"
  },
  "en": {
    "page_title": "03 | JavaScript → TypeScript",
    "cover_eyebrow": "Practical Web Service Development · Fall 2026",
    "cover_title": "Practical Web Service Development – Week 3",
    "cover_subtitle": "JavaScript and TypeScript · Syntax and Code Structure",
    "chapter_01_title": "History of Web Programming Languages",
    "chapter_01_subtitle": "The Evolving Web · JavaScript Origins and Standardization",
    "topic_01_title": "Roles of Web Documents and Programs",
    "topic_01_subtitle": "Document Delivery → Server Data Processing · Browser Interaction",
    "topic_01_panel_0_label": "Document, Server, and Browser",
    "topic_01_panel_0_head_0": "Component",
    "topic_01_panel_0_head_1": "Role",
    "topic_01_panel_0_head_2": "Order Service",
    "topic_01_panel_0_cell_0_0": "HTML",
    "topic_01_panel_0_cell_0_1": "Document structure",
    "topic_01_panel_0_cell_0_2": "Product name and price",
    "topic_01_panel_0_cell_1_0": "Server program",
    "topic_01_panel_0_cell_1_1": "Data processing",
    "topic_01_panel_0_cell_1_2": "Product queries and order storage",
    "topic_01_panel_0_cell_2_0": "Browser program",
    "topic_01_panel_0_cell_2_1": "User interaction",
    "topic_01_panel_0_cell_2_2": "Quantity input and result updates",
    "topic_02_title": "JavaScript Origins",
    "topic_02_subtitle": "Netscape’s Browser Scripting Language, 1995",
    "topic_02_panel_0_label": "1995 · Netscape",
    "topic_02_panel_0_item_0": "Browser language designed by Brendan Eich",
    "topic_02_panel_0_item_1": "Mocha → LiveScript → JavaScript",
    "topic_02_panel_0_item_2": "Input handling and interaction on web pages",
    "topic_03_title": "ECMAScript Standardization",
    "topic_03_subtitle": "Shared Language Rules and Syntax from ES2015 Onward",
    "topic_03_panel_0_label": "Standardization Milestones",
    "topic_03_panel_0_head_0": "Date",
    "topic_03_panel_0_head_1": "Significance",
    "topic_03_panel_0_cell_0_0": "1997",
    "topic_03_panel_0_cell_0_1": "First ECMA-262 edition · Shared language rules",
    "topic_03_panel_0_cell_1_0": "2015",
    "topic_03_panel_0_cell_1_1": "ES2015 · let, const, arrow functions, modules",
    "topic_03_panel_0_cell_2_0": "TC39",
    "topic_03_panel_0_cell_2_1": "Language specification proposals and review",
    "topic_03_panel_1_label": "Modern JavaScript · ES2015 Syntax",
    "topic_03_panel_1_code": "const price = 3000;\nlet quantity = 2;\nconst lineTotal = (price, quantity) => price * quantity;\nconsole.log(lineTotal(price, quantity));",
    "topic_03_panel_1_output_label": "Output",
    "chapter_02_title": "JavaScript Syntax and Features",
    "chapter_02_subtitle": "Values and Operations · Functions and Objects · Events and Async Operations",
    "topic_04_title": "Values, Types, and Variables",
    "topic_04_subtitle": "Value Types and Reassignment Rules for let and const",
    "topic_04_panel_0_label": "Values and Variables · JavaScript",
    "topic_04_panel_0_code": "const price = 3000;\nlet quantity = 2;\nquantity = 3;\nconst name = 'Notebook';\nconst available = true;\nlet selected;\nconsole.log(typeof price, typeof name);\nconsole.log(selected, null);",
    "topic_04_panel_0_output_label": "Output",
    "topic_04_panel_1_label": "Declarations and Values",
    "topic_04_panel_1_item_0": "let · Reassignment allowed / const · Reassignment blocked",
    "topic_04_panel_1_item_1": "number · string · boolean",
    "topic_04_panel_1_item_2": "undefined · Unset value / null · Explicit empty value",
    "topic_05_title": "Operators and Type Conversion",
    "topic_05_subtitle": "Operation Results with Explicit and Implicit Conversion",
    "topic_05_panel_0_label": "Same Input, Different Operations",
    "topic_05_panel_0_code": "const raw = '2';\nconsole.log(raw + 1);\nconsole.log(raw - 1);\nconsole.log(Number(raw) + 1);\nconsole.log(Number(''));\nconsole.log(Number('two'));",
    "topic_05_panel_0_output_label": "Output",
    "topic_05_panel_1_label": "Reading the Results",
    "topic_05_panel_1_item_0": "String + number → String concatenation",
    "topic_05_panel_1_item_1": "Subtraction → Implicit numeric conversion",
    "topic_05_panel_1_item_2": "Number() → Explicit numeric conversion",
    "topic_05_panel_1_item_3": "Failed conversion → NaN",
    "topic_06_title": "Conditions and Input Validation",
    "topic_06_subtitle": "Quantity and Stock Checks with Comparison and Logical Operators",
    "topic_06_panel_0_label": "Quantity and Stock Checks",
    "topic_06_panel_0_code": "const quantity = Number('3');\nconst stock = 5;\nconst valid =\n  Number.isInteger(quantity) &&\n  quantity > 0 &&\n  quantity <= stock;\nif (valid) {\n  console.log('ready');\n} else {\n  console.log('invalid');\n}",
    "topic_06_panel_0_output_label": "Output",
    "topic_06_panel_1_label": "Conditions",
    "topic_06_panel_1_item_0": "Number.isInteger · Integer check",
    "topic_06_panel_1_item_1": "quantity > 0 · Positive value check",
    "topic_06_panel_1_item_2": "quantity <= stock · Stock check",
    "topic_06_panel_1_item_3": "&& · All conditions required",
    "topic_07_title": "Arrays and Loops",
    "topic_07_subtitle": "Order Totals from Array Iteration and an Accumulator",
    "topic_07_panel_0_label": "Summing Order Amounts",
    "topic_07_panel_0_code": "const amounts = [3000, 1500, 6000];\nlet total = 0;\nfor (const amount of amounts) {\n  total = total + amount;\n}\nconsole.log(total);",
    "topic_07_panel_0_output_label": "Output",
    "topic_07_panel_1_label": "Values on Each Iteration",
    "topic_07_panel_1_head_0": "amount",
    "topic_07_panel_1_head_1": "total",
    "topic_07_panel_1_cell_0_0": "3000",
    "topic_07_panel_1_cell_0_1": "0 → 3000",
    "topic_07_panel_1_cell_1_0": "1500",
    "topic_07_panel_1_cell_1_1": "3000 → 4500",
    "topic_07_panel_1_cell_2_0": "6000",
    "topic_07_panel_1_cell_2_1": "4500 → 10500",
    "topic_08_title": "Functions and Block Scope",
    "topic_08_subtitle": "Parameters · Return Values · Variable Scope",
    "topic_08_panel_0_label": "Inputs, Return Values, and Scope",
    "topic_08_panel_0_code": "function calculateLineTotal(price, quantity) {\n  const total = price * quantity;\n  return total;\n}\nconsole.log(calculateLineTotal(3000, 2));\nif (true) {\n  let message = 'ready';\n  console.log(message);\n}",
    "topic_08_panel_0_output_label": "Output",
    "topic_08_panel_1_label": "Reading a Function Call",
    "topic_08_panel_1_item_0": "Arguments 3000, 2 → Parameters price, quantity",
    "topic_08_panel_1_item_1": "return · Returns a result and ends the call",
    "topic_08_panel_1_item_2": "total · Function scope / message · if block scope",
    "topic_09_title": "First-Class Functions, Callbacks, and Closures",
    "topic_09_subtitle": "Passing and Returning Functions · Access to Enclosing Variables",
    "topic_09_panel_0_label": "A Function Returning a Discount Function",
    "topic_09_panel_0_code": "function makeDiscount(rate) {\n  return (amount) => amount * (1 - rate);\n}\nconst memberPrice = makeDiscount(0.1);\nconst totals = [3000, 6000].map(memberPrice);\nconsole.log(totals);",
    "topic_09_panel_0_output_label": "Output",
    "topic_09_panel_1_label": "Three Uses of Functions",
    "topic_09_panel_1_item_0": "First-class functions · Stored, passed, and returned",
    "topic_09_panel_1_item_1": "Callback · memberPrice passed to map",
    "topic_09_panel_1_item_2": "Closure · Access to rate after makeDiscount returns",
    "topic_10_title": "Object Literals and Members",
    "topic_10_subtitle": "Product Data and Behavior as Properties and Methods",
    "topic_10_panel_0_label": "Product Object and Method",
    "topic_10_panel_0_code": "const product = {\n  name: 'Notebook',\n  price: 3000,\n  stock: 5,\n  inStock() {\n    return this.stock > 0;\n  }\n};\nconsole.log(product.name, product.inStock());",
    "topic_10_panel_0_output_label": "Output",
    "topic_10_panel_1_label": "Object Members",
    "topic_10_panel_1_item_0": "Properties · name, price, stock",
    "topic_10_panel_1_item_1": "Method · inStock()",
    "topic_10_panel_1_item_2": "this in product.inStock() → product",
    "topic_11_title": "Object References and Shallow Copies",
    "topic_11_subtitle": "Shared References in Assignment · Nested References Retained by Spread",
    "topic_11_panel_0_label": "Shared References and Nested Objects",
    "topic_11_panel_0_code": "const product = { stock: { count: 5 } };\nconst shared = product;\nconst copied = { ...product };\nshared.stock.count = 4;\ncopied.stock.count = 0;\nconsole.log(product.stock.count);\nconsole.log(copied === product);\nconsole.log(copied.stock === product.stock);",
    "topic_11_panel_0_output_label": "Output",
    "topic_11_panel_1_label": "Copy Depth",
    "topic_11_panel_1_item_0": "Assignment · Shared reference to one object",
    "topic_11_panel_1_item_1": "Spread · Copies the outer object",
    "topic_11_panel_1_item_2": "Nested stock · Shared reference",
    "topic_12_title": "List Transformation with filter and map",
    "topic_12_subtitle": "Selecting Matching Products · Extracting Required Values",
    "topic_12_panel_0_label": "Products → Product Names",
    "topic_12_panel_0_code": "const products = [\n  { name: 'Notebook', stock: 5 },\n  { name: 'Case', stock: 0 }\n];\nconst names = products\n  .filter((product) => product.stock > 0)\n  .map((product) => product.name);\nconsole.log(names);",
    "topic_12_panel_0_output_label": "Output",
    "topic_12_panel_1_label": "Roles of the Two Callbacks",
    "topic_12_panel_1_item_0": "filter · Selects products with stock > 0",
    "topic_12_panel_1_item_1": "map · Converts each product to its name",
    "topic_12_panel_1_item_2": "2 original items → 1 result · New array",
    "topic_13_title": "DOM Events and Input Handling",
    "topic_13_subtitle": "Handler Registration → Input Conversion → Order Call",
    "topic_13_panel_0_label": "DOM Event Registration",
    "topic_13_panel_0_code": "const input = document.querySelector('#quantity');\nconst button = document.querySelector('#submit');\nbutton.addEventListener('click', () => {\n  const quantity = Number(input.value);\n  console.log(quantity);\n});",
    "topic_13_panel_1_label": "Registration and Execution",
    "topic_13_panel_1_item_0": "Initialization · Callback registration",
    "topic_13_panel_1_item_1": "Click · Callback execution",
    "topic_13_panel_1_item_2": "input.value: \"2\" → quantity: 2",
    "topic_14_title": "Promise and async/await",
    "topic_14_subtitle": "Waiting for Requests · Handling Success and Failure with try/catch",
    "topic_14_panel_0_label": "HTTP Checks and Error Handling",
    "topic_14_panel_0_code": "async function loadProducts() {\n  const response = await fetch('/products.json');\n  if (!response.ok) throw new Error('HTTP error');\n  return response.json();\n}\ntry {\n  const products = await loadProducts();\n  console.log(products.length);\n} catch (error) {\n  console.log('load failed');\n}",
    "topic_14_panel_1_label": "Async Boundaries",
    "topic_14_panel_1_item_0": "await · Pauses the current flow until completion",
    "topic_14_panel_1_item_1": "response.ok · Checks HTTP success status",
    "topic_14_panel_1_item_2": "catch · Handles request, JSON parsing, and thrown errors",
    "chapter_03_title": "JavaScript Strengths and Error Risks",
    "chapter_03_subtitle": "Flexible Code Composition · Conversion and Shared State Errors",
    "topic_15_title": "Dynamic Typing and Code Composition",
    "topic_15_subtitle": "Flexible Combinations of Values, Functions, and Objects",
    "topic_15_panel_0_label": "Replacing a Filter Function",
    "topic_15_panel_0_code": "const products = [\n  { name: 'Notebook', price: 3000, stock: 5 },\n  { name: 'Case', price: 8000, stock: 0 }\n];\nconst inStock = (p) => p.stock > 0;\nconst affordable = (p) => p.price < 5000;\nconsole.log(products.filter(inStock).length);\nconsole.log(products.filter(affordable).length);",
    "topic_15_panel_0_output_label": "Output",
    "topic_15_panel_1_label": "Benefits of Flexibility",
    "topic_15_panel_1_item_0": "Objects · Grouped data properties",
    "topic_15_panel_1_item_1": "Functions · Replaceable selection conditions",
    "topic_16_title": "Conversion, Typo, and Shared State Errors",
    "topic_16_subtitle": "Errors from Incorrect Values and Object Mutations",
    "topic_16_panel_0_label": "Incorrect Results",
    "topic_16_panel_0_code": "const product = { price: 3000, stock: 5 };\nconst alias = product;\nconsole.log(2 + '3');\nconsole.log(product.prcie * 2);\nalias.stock = 0;\nconsole.log(product.stock);",
    "topic_16_panel_0_output_label": "Output",
    "topic_16_panel_1_label": "Different Error Causes",
    "topic_16_panel_1_item_0": "23 · String concatenation instead of numeric addition",
    "topic_16_panel_1_item_1": "NaN · Arithmetic with undefined from missing prcie",
    "topic_16_panel_1_item_2": "0 · Shared reference between alias and product",
    "topic_17_title": "Type Checking and Runtime Validation",
    "topic_17_subtitle": "Type Usage Checks · Input and Business Rule Validation",
    "topic_17_panel_0_label": "Errors and Where to Check Them",
    "topic_17_panel_0_head_0": "Situation",
    "topic_17_panel_0_head_1": "Primary Check",
    "topic_17_panel_0_cell_0_0": "String passed to a number parameter",
    "topic_17_panel_0_cell_0_1": "Type checking",
    "topic_17_panel_0_cell_1_0": "product.prcie typo",
    "topic_17_panel_0_cell_1_1": "Type checking",
    "topic_17_panel_0_cell_2_0": "Quantity -1 · Over stock",
    "topic_17_panel_0_cell_2_1": "Runtime business validation",
    "topic_17_panel_0_cell_3_0": "Missing field in external JSON",
    "topic_17_panel_0_cell_3_1": "Runtime data validation",
    "topic_17_panel_1_label": "Limits of Checking",
    "topic_17_panel_1_item_0": "number does not guarantee a positive integer",
    "topic_17_panel_1_item_1": "External responses need runtime shape and value checks",
    "chapter_04_title": "TypeScript Origins and Role",
    "chapter_04_subtitle": "Extending JavaScript · Type Checking and Code Transformation",
    "topic_18_title": "TypeScript Origins",
    "topic_18_subtitle": "Introduced in 2012 · Structure and Error Detection for Large JavaScript Projects",
    "topic_18_panel_0_label": "2012 · Microsoft",
    "topic_18_panel_0_item_0": "Changes and collaboration in large JavaScript projects",
    "topic_18_panel_0_item_1": "TypeScript publicly unveiled on October 1, 2012",
    "topic_18_panel_0_item_2": "Type contracts · Editor support · Earlier error detection",
    "topic_18_panel_1_label": "Relationship to JavaScript",
    "topic_18_panel_1_item_0": "Existing JavaScript syntax and runtimes",
    "topic_18_panel_1_item_1": "Types express code structure and expected usage",
    "topic_19_title": "Static Type Checking and Code Transformation",
    "topic_19_subtitle": "Pre-Execution Type Checking · JavaScript Output Without Type Annotations",
    "topic_19_panel_0_label": "TypeScript · Type Annotations",
    "topic_19_panel_0_code": "function lineTotal(\n  price: number,\n  quantity: number\n): number {\n  return price * quantity;\n}\nconsole.log(lineTotal(3000, 2));",
    "topic_19_panel_0_output_label": "Output",
    "topic_19_panel_1_label": "JavaScript · Type Erasure",
    "topic_19_panel_1_code": "function lineTotal(price, quantity) {\n  return price * quantity;\n}\nconsole.log(lineTotal(3000, 2));",
    "topic_19_panel_1_output_label": "Output",
    "chapter_05_title": "TypeScript Syntax and Features",
    "chapter_05_subtitle": "Type Contracts · Narrowing · External Data Validation",
    "topic_20_title": "Type Annotations and Inference",
    "topic_20_subtitle": "Explicit Type Annotations · Inference from Initial Values",
    "topic_20_panel_0_label": "Inference and Annotations",
    "topic_20_panel_0_code": "let quantity = 2;\nconst price: number = 3000;\nconst name: string = 'Notebook';\nconst available: boolean = true;\nconst amounts: number[] = [3000, 6000];\nquantity = '2';",
    "topic_20_panel_0_diagnostic": "Type error: TS2322",
    "topic_20_panel_1_label": "Compiler Reasoning",
    "topic_20_panel_1_item_0": "quantity = 2 → number inferred",
    "topic_20_panel_1_item_1": "price: number → Explicit annotation",
    "topic_20_panel_1_item_2": "quantity = \"2\" → Type mismatch",
    "topic_21_title": "Function Parameter and Return Types",
    "topic_21_subtitle": "Type Contracts for Function Inputs and Outputs",
    "topic_21_panel_0_label": "Function Contract",
    "topic_21_panel_0_code": "function calculateLineTotal(\n  price: number,\n  quantity: number\n): number {\n  return price * quantity;\n}\ncalculateLineTotal(3000, 2);\ncalculateLineTotal(3000, '2');",
    "topic_21_panel_0_diagnostic": "Type error: TS2345",
    "topic_21_panel_1_label": "Arguments and Return Values",
    "topic_21_panel_1_item_0": "price · quantity → number arguments",
    "topic_21_panel_1_item_1": "Return value → number",
    "topic_21_panel_1_item_2": "Passing string \"2\" → Type error",
    "topic_22_title": "Object Types: type and interface",
    "topic_22_subtitle": "Required Properties and Their Types",
    "topic_22_panel_0_label": "Product Shape with type",
    "topic_22_panel_0_code": "type Product = {\n  id: string;\n  name: string;\n  price: number;\n  stock: number;\n};\nconst product: Product = {\n  id: 'note',\n  name: 'Notebook',\n  price: 3000,\n  stock: 5\n};",
    "topic_22_panel_1_label": "Product Shape with interface",
    "topic_22_panel_1_code": "interface Product {\n  id: string;\n  name: string;\n  price: number;\n  stock: number;\n}\nconst product: Product = {\n  id: 'note',\n  name: 'Notebook',\n  price: 3000,\n  stock: 5\n};",
    "topic_23_title": "Literal Types and Unions",
    "topic_23_subtitle": "Order Status Restricted to a Defined Set of Values",
    "topic_23_panel_0_label": "Order Status Union",
    "topic_23_panel_0_code": "type OrderStatus =\n  'idle' | 'submitting' | 'success' | 'error';\nlet status: OrderStatus = 'idle';\nstatus = 'submitting';\nstatus = 'done';",
    "topic_23_panel_0_diagnostic": "Type error: TS2322",
    "topic_23_panel_1_label": "Allowed States and Transitions",
    "topic_23_panel_1_item_0": "idle · Waiting for input",
    "topic_23_panel_1_item_1": "submitting · Request in progress",
    "topic_23_panel_1_item_2": "success or error · Request result",
    "topic_24_title": "Optional Properties and undefined",
    "topic_24_subtitle": "Existence Checks for Properties and Search Results",
    "topic_24_panel_0_label": "Optional Values and Search Results",
    "topic_24_panel_0_code": "type Product = {\n  id: string;\n  price: number;\n  discountPrice?: number;\n};\nconst products: Product[] = [\n  { id: 'note', price: 3000 }\n];\nconst found = products.find((p) => p.id === 'note');\nif (found !== undefined) {\n  console.log(found.discountPrice ?? found.price);\n}",
    "topic_24_panel_0_output_label": "Output",
    "topic_24_panel_1_label": "Two Missing-Value Cases",
    "topic_24_panel_1_item_0": "find result → Product or undefined",
    "topic_24_panel_1_item_1": "discountPrice → number or undefined",
    "topic_24_panel_1_item_2": "Property access after an existence check",
    "topic_24_panel_1_item_3": "?? · Fallback for null and undefined",
    "topic_25_title": "Conditions and Type Narrowing",
    "topic_25_subtitle": "Type Refinement with Conditions and Discriminants",
    "topic_25_panel_0_label": "Branching on the ok Discriminant",
    "topic_25_panel_0_code": "type Result =\n  | { ok: true; data: number }\n  | { ok: false; message: string };\nfunction describe(result: Result): string {\n  if (result.ok) {\n    return `quantity: ${result.data}`;\n  }\n  return result.message;\n}\nconsole.log(describe({ ok: true, data: 2 }));",
    "topic_25_panel_0_output_label": "Output",
    "topic_25_panel_1_label": "Types Inside Each Branch",
    "topic_25_panel_1_item_0": "ok: true → Access data",
    "topic_25_panel_1_item_1": "ok: false → Access message",
    "topic_25_panel_1_item_2": "Access to data before narrowing → Type error",
    "topic_26_title": "any and unknown",
    "topic_26_subtitle": "any Bypasses Checks · unknown Requires Checks Before Use",
    "topic_26_panel_0_label": "any · Bypassing Checks",
    "topic_26_panel_0_code": "const raw: any = 3000;\nraw.toUpperCase();",
    "topic_26_panel_0_runtime": "Runtime: TypeError",
    "topic_26_panel_1_label": "unknown · Check Before Use",
    "topic_26_panel_1_code": "function normalize(raw: unknown): string {\n  if (typeof raw === 'string') {\n    return raw.toUpperCase();\n  }\n  return 'not a string';\n}\nconsole.log(normalize(3000));",
    "topic_26_panel_1_output_label": "Output",
    "topic_27_title": "Type Assertions and Data Validation",
    "topic_27_subtitle": "Compiler Type Assumptions Versus Actual Value Checks",
    "topic_27_panel_0_label": "as Does Not Validate or Convert Values",
    "topic_27_panel_0_code": "const raw: unknown = { price: '3000' };\nconst claimed = raw as { price: number };\nconsole.log(claimed.price + 1);\nif (\n  typeof raw === 'object' &&\n  raw !== null &&\n  'price' in raw &&\n  typeof raw.price === 'number'\n) {\n  console.log(raw.price + 1);\n} else {\n  console.log('invalid price');\n}",
    "topic_27_panel_0_output_label": "Output",
    "topic_27_panel_1_label": "Assertion Versus Validation",
    "topic_27_panel_1_item_0": "price remains a string after as",
    "topic_27_panel_1_item_1": "Only the compiler’s assumption changes to number",
    "topic_27_panel_1_item_2": "typeof check → Rejects the string price",
    "topic_28_title": "Generics and Type Relationships",
    "topic_28_subtitle": "Input–Output Type Relationships Preserved Across Concrete Types",
    "topic_28_panel_0_label": "The Type Relationship of a First Element",
    "topic_28_panel_0_code": "function first<T>(items: T[]): T | undefined {\n  return items[0];\n}\nconst amount = first([3000, 1500]);\nconst product = first([{ id: 'note', price: 3000 }]);\nconsole.log(amount);\nconsole.log(product?.id);\nconsole.log(first<number>([]));",
    "topic_28_panel_0_output_label": "Output",
    "topic_28_panel_1_label": "Meaning of T",
    "topic_28_panel_1_item_0": "Number array → number or undefined",
    "topic_28_panel_1_item_1": "Product array → Product type or undefined",
    "topic_28_panel_1_item_2": "Empty array → undefined",
    "topic_29_title": "Modules and Structural Types",
    "topic_29_subtitle": "Roles Separated by Imports and Exports · Compatibility by Required Members",
    "topic_29_panel_0_label": "types.ts · Exporting a Required Shape",
    "topic_29_panel_0_code": "export type Named = { name: string };\nexport function label(item: Named): string {\n  return item.name;\n}",
    "topic_29_panel_1_label": "main.ts · Modules and Structural Compatibility",
    "topic_29_panel_1_code": "import { label } from './types.js';\nimport type { Named } from './types.js';\nconst product = { name: 'Notebook', price: 3000 };\nconst named: Named = product;\nconsole.log(label(named));",
    "topic_29_panel_1_output_label": "Output",
    "chapter_06_title": "Web Programming Paradigms",
    "chapter_06_subtitle": "Execution Order · Computation and State · Events and UI",
    "topic_30_title": "Imperative and Procedural Order Processing",
    "topic_30_subtitle": "Validation → Calculation → Save Request → Result",
    "topic_30_panel_0_label": "Order Procedure",
    "topic_30_panel_0_code": "async function submitOrder(raw: string) {\n  const quantity = Number(raw);\n  if (!Number.isInteger(quantity) || quantity <= 0) {\n    throw new Error('invalid quantity');\n  }\n  const total = 3000 * quantity;\n  await saveOrder(total);\n  return { status: 'success', total };\n}",
    "topic_30_panel_1_label": "Procedure and Failure Paths",
    "topic_30_panel_1_item_0": "Validate quantity → Stop on failure",
    "topic_30_panel_1_item_1": "Calculate amount → Request storage",
    "topic_30_panel_1_item_2": "Await completion → Return success",
    "topic_31_title": "Pure Functions and Immutability",
    "topic_31_subtitle": "Computation Without Mutating Inputs or External State",
    "topic_31_panel_0_label": "A Pure Function with Local Variables",
    "topic_31_panel_0_code": "function calculateTotal(amounts: number[]): number {\n  let total = 0;\n  for (const amount of amounts) {\n    total += amount;\n  }\n  return total;\n}\nconst amounts = [3000, 1500];\nconsole.log(calculateTotal(amounts));\nconsole.log(amounts.length);",
    "topic_31_panel_0_output_label": "Output",
    "topic_31_panel_1_label": "Criteria for Purity",
    "topic_31_panel_1_item_0": "Same input → Same result",
    "topic_31_panel_1_item_1": "Input array and external state unchanged",
    "topic_31_panel_1_item_2": "Only the local variable total changes",
    "topic_32_title": "Encapsulation and Cart State",
    "topic_32_subtitle": "State and Behavior Combined · Changes Controlled Through Methods",
    "topic_32_panel_0_label": "Cart with Controlled State Access",
    "topic_32_panel_0_code": "class Cart {\n  private items: string[] = [];\n  add(productId: string): void {\n    this.items.push(productId);\n  }\n  get count(): number {\n    return this.items.length;\n  }\n}\nconst cart = new Cart();\ncart.add('note');\nconsole.log(cart.count);",
    "topic_32_panel_0_output_label": "Output",
    "topic_32_panel_1_label": "Responsibility for State and Behavior",
    "topic_32_panel_1_item_0": "private items · Restricted external access",
    "topic_32_panel_1_item_1": "add() · Changes the internal array",
    "topic_32_panel_1_item_2": "count · Exposes the array length",
    "topic_33_title": "Events and Async Execution",
    "topic_33_subtitle": "Execution on User Actions · Request Completion Order Management",
    "topic_33_panel_0_label": "Ignoring a Stale Response",
    "topic_33_panel_0_code": "let latestRequest = 0;\nasync function search(query: string): Promise<void> {\n  const requestId = ++latestRequest;\n  const products = await loadProducts(query);\n  if (requestId !== latestRequest) return;\n  renderProducts(products);\n}",
    "topic_33_panel_1_label": "Responses Arriving Out of Order",
    "topic_33_panel_1_head_0": "Time",
    "topic_33_panel_1_head_1": "Action",
    "topic_33_panel_1_cell_0_0": "1",
    "topic_33_panel_1_cell_0_1": "Search A starts · Request 1",
    "topic_33_panel_1_cell_1_0": "2",
    "topic_33_panel_1_cell_1_1": "Search B starts · Request 2",
    "topic_33_panel_1_cell_2_0": "3",
    "topic_33_panel_1_cell_2_1": "B completes → Update UI",
    "topic_33_panel_1_cell_3_0": "4",
    "topic_33_panel_1_cell_3_1": "A completes → Ignore stale request",
    "topic_34_title": "Declarative UI and Reactive Computation",
    "topic_34_subtitle": "UI Defined by State · Derived Values Updated by Dependency Changes",
    "topic_34_panel_0_label": "React TSX · Button Based on State",
    "topic_34_panel_0_code": "function OrderButton({ busy }: { busy: boolean }) {\n  return (\n    <button disabled={busy}>\n      {busy ? 'Sending' : 'Order'}\n    </button>\n  );\n}",
    "topic_34_panel_1_label": "Vue · Reactive Total",
    "topic_34_panel_1_code": "import { computed, ref } from 'vue';\nconst quantity = ref(2);\nconst total = computed(() => 3000 * quantity.value);\nconsole.log(total.value);\nquantity.value = 3;\nconsole.log(total.value);",
    "topic_34_panel_1_output_label": "Output",
    "topic_35_title": "Paradigm Composition and Responsibility Separation",
    "topic_35_subtitle": "Roles of Events, Procedures, Computation, State, and UI in Orders",
    "topic_35_panel_0_label": "One Order Feature",
    "topic_35_panel_0_item_0": "Input → Event handling",
    "topic_35_panel_0_item_1": "Validation → Pure calculation → Storage",
    "topic_35_panel_0_item_2": "Result state → UI update",
    "topic_35_panel_1_label": "Responsibilities in Lab Files",
    "topic_35_panel_1_head_0": "File",
    "topic_35_panel_1_head_1": "Role",
    "topic_35_panel_1_cell_0_0": "main.ts",
    "topic_35_panel_1_cell_0_1": "Events and procedure coordination",
    "topic_35_panel_1_cell_1_0": "order.ts · policies.ts",
    "topic_35_panel_1_cell_1_1": "Calculation and validation",
    "topic_35_panel_1_cell_2_0": "api.ts",
    "topic_35_panel_1_cell_2_1": "External data and mock requests",
    "topic_35_panel_1_cell_3_0": "ui.ts",
    "topic_35_panel_1_cell_3_1": "Imperative DOM updates",
    "topic_35_practice_link": "Lab README",
    "chapter_07_title": "Design Patterns in TypeScript",
    "chapter_07_subtitle": "Policy Replacement with Strategy · Format Conversion with Adapter",
    "topic_36_title": "Discount Policies and the Strategy Pattern",
    "topic_36_subtitle": "Calculations Separated to Limit the Scope of Policy Changes",
    "topic_36_panel_0_label": "Branching on Policy Names",
    "topic_36_panel_0_code": "function checkout(amount: number, kind: string) {\n  if (kind === 'member') {\n    return Math.floor(amount * 0.9);\n  }\n  return amount;\n}",
    "topic_36_panel_1_label": "Separating a Replacement Point",
    "topic_36_panel_1_item_0": "New policy → More checkout branches",
    "topic_36_panel_1_item_1": "Strategy · Separately defined calculation functions",
    "topic_36_panel_1_item_2": "Order function · Calls the supplied policy",
    "topic_37_title": "Function Types and Policy Replacement",
    "topic_37_subtitle": "Regular and Member Pricing Policies Passed with a Shared Function Type",
    "topic_37_panel_0_label": "Shared Function Type and Policy Passing",
    "topic_37_panel_0_code": "type DiscountPolicy = (amount: number) => number;\nconst regularPrice: DiscountPolicy = (amount) => amount;\nconst memberPrice: DiscountPolicy = (amount) =>\n  Math.floor(amount * 0.9);\nfunction checkout(\n  amount: number,\n  policy: DiscountPolicy\n) {\n  return policy(amount);\n}\nconsole.log(checkout(6000, regularPrice));\nconsole.log(checkout(6000, memberPrice));",
    "topic_37_panel_0_output_label": "Output",
    "topic_37_panel_1_label": "Contract and Change",
    "topic_37_panel_1_item_0": "Input · Amount before discount",
    "topic_37_panel_1_item_1": "Return · Payable amount",
    "topic_37_panel_1_item_2": "Member policy · 10% discount, rounded down",
    "topic_37_panel_1_item_3": "checkout · Calls the supplied policy",
    "topic_38_title": "Product Formats and the Adapter Pattern",
    "topic_38_subtitle": "External Product Fields Converted to the Internal Product Format",
    "topic_38_panel_0_label": "Converting Validated External Values",
    "topic_38_panel_0_code": "type ApiProduct = {\n  product_name: string;\n  unit_price: number;\n};\ntype Product = { name: string; price: number };\nfunction toProduct(raw: ApiProduct): Product {\n  return {\n    name: raw.product_name,\n    price: raw.unit_price\n  };\n}",
    "topic_38_panel_1_label": "Adapter Boundary",
    "topic_38_panel_1_item_0": "product_name → name",
    "topic_38_panel_1_item_1": "unit_price → price",
    "topic_38_panel_1_item_2": "Input · Validated ApiProduct",
    "topic_38_panel_1_item_3": "Return · New Product object",
    "topic_38_practice_link": "Lab README",
    "topic_39_title": "Input Validation and Format Conversion",
    "topic_39_subtitle": "unknown → Validated External Data → Internal Product → Order Calculation",
    "topic_39_panel_0_label": "External Data Boundary",
    "topic_39_panel_0_item_0": "unknown · An unchecked value",
    "topic_39_panel_0_item_1": "Validator · Checks fields and actual types",
    "topic_39_panel_0_item_2": "ApiProduct → Adapter → Product",
    "topic_39_panel_0_item_3": "Order calculation · Uses only the internal contract",
    "topic_39_panel_1_label": "Failure Causes by Stage",
    "topic_39_panel_1_item_0": "Missing fields or string prices → Validation failure",
    "topic_39_panel_1_item_1": "Incorrect field mapping → Conversion error",
    "topic_40_title": "Strategy and Adapter Selection Criteria",
    "topic_40_subtitle": "Selection Based on Change Points, Data Boundaries, and Implementation Cost",
    "topic_40_panel_0_label": "Selection by Requirement",
    "topic_40_panel_0_head_0": "Change",
    "topic_40_panel_0_head_1": "Choice",
    "topic_40_panel_0_cell_0_0": "Regular, member, or coupon pricing",
    "topic_40_panel_0_cell_0_1": "Strategy · Replace calculation functions",
    "topic_40_panel_0_cell_1_0": "External API product fields change",
    "topic_40_panel_0_cell_1_1": "Adapter · Map to the internal format",
    "topic_40_panel_0_cell_2_0": "Fixed unit price × quantity",
    "topic_40_panel_0_cell_2_1": "Keep a simple function",
    "topic_40_panel_1_label": "Abstraction Cost",
    "topic_40_panel_1_item_0": "More functions and files → Higher navigation cost",
    "topic_40_panel_1_item_1": "More contracts → More complex call relationships",
    "topic_40_practice_link": "Lab README",
    "chapter_08_title": "Lab: Product Ordering with TypeScript",
    "chapter_08_subtitle": "Implementation · Code Reading · Runtime Verification",
    "topic_41_title": "Lab UI and Requirements",
    "topic_41_subtitle": "Provided HTML and CSS · Product Selection, Validation, and Discounts",
    "topic_41_panel_0_label": "Mock Order Form",
    "topic_41_panel_0_head_0": "Input",
    "topic_41_panel_0_head_1": "Value",
    "topic_41_panel_0_cell_0_0": "Product",
    "topic_41_panel_0_cell_0_1": "Notebook · 3,000 won each",
    "topic_41_panel_0_cell_1_0": "Quantity",
    "topic_41_panel_0_cell_1_1": "2",
    "topic_41_panel_0_cell_2_0": "Discount",
    "topic_41_panel_0_cell_2_1": "Member · 10%",
    "topic_41_panel_0_cell_3_0": "Result",
    "topic_41_panel_0_cell_3_1": "6,000 won → 5,400 won",
    "topic_41_panel_1_label": "Implementation Scope",
    "topic_41_panel_1_item_0": "Provided · HTML, CSS, event scaffolding",
    "topic_41_panel_1_item_1": "Required · Quantity validation, order calculation, member policy",
    "topic_41_panel_1_item_2": "Optional · External data Adapter",
    "topic_41_practice_link": "Lab README",
    "topic_42_title": "Lab Data and Order Flow",
    "topic_42_subtitle": "Products and Input → Validation and Calculation → Order Result",
    "topic_42_panel_0_label": "Two Notebooks · Member Order",
    "topic_42_panel_0_item_0": "Product · price: 3000, stock: 5",
    "topic_42_panel_0_item_1": "Input \"2\" → Quantity 2 → Valid",
    "topic_42_panel_0_item_2": "Subtotal 6000 → Member policy → 5400",
    "topic_42_panel_0_item_3": "Result<Order> → Mock request → UI",
    "topic_42_panel_1_label": "Order Data",
    "topic_42_panel_1_item_0": "productId · Product lookup key",
    "topic_42_panel_1_item_1": "quantity · Validated quantity",
    "topic_42_panel_1_item_2": "subtotal · Amount before discount",
    "topic_42_panel_1_item_3": "total · Amount after the policy",
    "topic_42_practice_link": "Lab README",
    "topic_43_title": "Project Structure and Execution",
    "topic_43_subtitle": "Provided Code · Student Changes · Execution and Type Checking",
    "topic_43_panel_0_label": "practice · localhost:4303",
    "topic_43_panel_0_code": "npm ci\nnpm start\n\n# Second terminal\nnpm run watch\nnpm run check\nnpm test",
    "topic_43_panel_1_label": "Files and Tasks",
    "topic_43_panel_1_head_0": "File",
    "topic_43_panel_1_head_1": "Task",
    "topic_43_panel_1_cell_0_0": "src/order.ts",
    "topic_43_panel_1_cell_0_1": "TODO 1–3 · Required",
    "topic_43_panel_1_cell_1_0": "src/policies.ts",
    "topic_43_panel_1_cell_1_1": "TODO 4 · Member policy",
    "topic_43_panel_1_cell_2_0": "src/adapters.ts",
    "topic_43_panel_1_cell_2_1": "TODO 5 · Optional",
    "topic_43_panel_1_cell_3_0": "main.ts · ui.ts · api.ts",
    "topic_43_panel_1_cell_3_1": "Read provided code",
    "topic_43_practice_link": "Lab README",
    "topic_44_title": "JavaScript Error Reproduction",
    "topic_44_subtitle": "Result Comparison for String Operations, Property Typos, and Missing Products",
    "topic_44_panel_0_label": "reading/bugs.js · Predict Before Running",
    "topic_44_panel_0_code": "const product = { price: 3000, stock: 5 };\nconsole.log('3' + 1);\nconsole.log(product.prcie * 2);\nconst found = [product].find((p) => p.price === 0);\nconsole.log(found.price);",
    "topic_44_panel_0_output_label": "Output",
    "topic_44_panel_1_label": "Error Causes",
    "topic_44_panel_1_item_0": "\"3\" + 1 · String concatenation",
    "topic_44_panel_1_item_1": "product.prcie · Missing property",
    "topic_44_panel_1_item_2": "found.price · Property access on undefined",
    "topic_44_practice_link": "Lab README",
    "topic_45_title": "Quantity Conversion and Validation",
    "topic_45_subtitle": "Empty Input Rejection · Finite Positive Integer and Stock Checks",
    "topic_45_panel_0_label": "order.ts · Quantity Validation",
    "topic_45_panel_0_code": "function parseQuantity(raw: string, stock: number) {\n  if (raw.trim() === '') {\n    return { ok: false, message: 'empty' };\n  }\n  const quantity = Number(raw);\n  if (\n    !Number.isFinite(quantity) ||\n    !Number.isInteger(quantity) ||\n    quantity <= 0\n  ) {\n    return { ok: false, message: 'invalid' };\n  }\n  if (quantity > stock) {\n    return { ok: false, message: 'over stock' };\n  }\n  return { ok: true, data: quantity };\n}",
    "topic_45_panel_1_label": "Inputs to Check",
    "topic_45_panel_1_item_0": "Empty, whitespace, abc, Infinity → Failure",
    "topic_45_panel_1_item_1": "0, -1, 1.5 → Failure",
    "topic_45_panel_1_item_2": "Stock 5: quantity 5 → Success / 6 → Failure",
    "topic_45_practice_link": "Lab README",
    "topic_46_title": "Order Code Conversion to TypeScript",
    "topic_46_subtitle": "Types Added to Products and Function Inputs and Outputs",
    "topic_46_panel_0_label": "Before · JavaScript",
    "topic_46_panel_0_code": "function calculateLineTotal(price, quantity) {\n  return price * quantity;\n}\nconst product = {\n  id: 'note',\n  name: 'Notebook',\n  price: 3000,\n  stock: 5\n};",
    "topic_46_panel_1_label": "After · TypeScript",
    "topic_46_panel_1_code": "function calculateLineTotal(\n  price: number,\n  quantity: number\n): number {\n  return price * quantity;\n}\nconst product: Product = {\n  id: 'note',\n  name: 'Notebook',\n  price: 3000,\n  stock: 5\n};",
    "topic_46_practice_link": "Lab README",
    "topic_47_title": "Type Errors and undefined Handling",
    "topic_47_subtitle": "Corrections for Invalid Arguments, Property Typos, and Missing Values",
    "topic_47_panel_0_label": "Before an Existence Check",
    "topic_47_panel_0_code": "const products = [{ id: 'note', price: 3000 }];\nconst found = products.find((p) => p.id === 'missing');\nconsole.log(found.price);",
    "topic_47_panel_0_diagnostic": "Type error: TS18048",
    "topic_47_panel_1_label": "After an Existence Check",
    "topic_47_panel_1_code": "const products = [{ id: 'note', price: 3000 }];\nconst found = products.find((p) => p.id === 'missing');\nif (found === undefined) {\n  console.log('product not found');\n} else {\n  console.log(found.price);\n}",
    "topic_47_panel_1_output_label": "Output",
    "topic_47_practice_link": "Lab README",
    "topic_48_title": "Discount Policy Separation Lab",
    "topic_48_subtitle": "Regular and Member Pricing Functions Implemented and Passed to Order Logic",
    "topic_48_panel_0_label": "policies.ts · Shared Policy Contract",
    "topic_48_panel_0_code": "type DiscountPolicy = (amount: number) => number;\nconst regularPrice: DiscountPolicy = (amount) => amount;\nconst memberPrice: DiscountPolicy = (amount) =>\n  Math.floor(amount * 0.9);\nconsole.log(regularPrice(6000));\nconsole.log(memberPrice(6000));\nconsole.log(memberPrice(3001));",
    "topic_48_panel_0_output_label": "Output",
    "topic_48_panel_1_label": "Policy Passing",
    "topic_48_panel_1_item_0": "main.ts · Selects the regular or member policy",
    "topic_48_panel_1_item_1": "createOrder · Receives the policy function",
    "topic_48_panel_1_item_2": "policy(subtotal) · Returns the payable amount",
    "topic_48_practice_link": "Lab README",
    "topic_49_title": "Adapter Extension Lab",
    "topic_49_subtitle": "Provided Validator Connected to Product Format Conversion",
    "topic_49_panel_0_label": "adapters.ts · Conversion After Validation",
    "topic_49_panel_0_code": "function toProduct(raw: ApiProduct): Product {\n  return {\n    id: raw.id,\n    name: raw.product_name,\n    price: raw.unit_price,\n    stock: raw.stock\n  };\n}",
    "topic_49_panel_1_label": "Fixtures and Expected Results",
    "topic_49_panel_1_head_0": "URL Query",
    "topic_49_panel_1_head_1": "Expected Result",
    "topic_49_panel_1_cell_0_0": "?fixture=valid",
    "topic_49_panel_1_cell_0_1": "Validate → Adapt → Display",
    "topic_49_panel_1_cell_1_0": "?fixture=missing",
    "topic_49_panel_1_cell_1_1": "Validation fails: missing field",
    "topic_49_panel_1_cell_2_0": "?fixture=wrong",
    "topic_49_panel_1_cell_2_1": "Validation fails: string price",
    "topic_49_practice_link": "Lab README",
    "topic_50_title": "Normal, Failure, and Boundary Checks",
    "topic_50_subtitle": "Checks for Totals, Invalid Quantities, Missing Products, and Request Failures",
    "topic_50_panel_0_label": "Verification Scenarios",
    "topic_50_panel_0_head_0": "Scenario",
    "topic_50_panel_0_head_1": "Expected Result",
    "topic_50_panel_0_cell_0_0": "Two notebooks · Regular / Member",
    "topic_50_panel_0_cell_0_1": "6,000 / 5,400 won",
    "topic_50_panel_0_cell_1_0": "Zero · Negative · Fraction · Over stock",
    "topic_50_panel_0_cell_1_1": "Reject before sending an order",
    "topic_50_panel_0_cell_2_0": "Unknown product ID · Out of stock",
    "topic_50_panel_0_cell_2_1": "Return a failure result",
    "topic_50_panel_0_cell_3_0": "Request failure → Uncheck → Retry",
    "topic_50_panel_0_cell_3_1": "Error → Button restored → Success",
    "topic_50_panel_1_label": "Automated and UI Checks",
    "topic_50_panel_1_item_0": "npm run check · Type checking",
    "topic_50_panel_1_item_1": "npm test · Calculation and boundary checks",
    "topic_50_panel_1_item_2": "Browser · Duplicate prevention and failure recovery",
    "topic_50_practice_link": "Lab README",
    "topic_51_title": "AI Code Prediction and Review",
    "topic_51_subtitle": "Result Prediction → Suggestion Review → Code Changes → Counterexamples",
    "topic_51_panel_0_label": "AI Code Review Procedure",
    "topic_51_panel_0_item_0": "Predict results and types before execution",
    "topic_51_panel_0_item_1": "Request an explanation and counterexamples",
    "topic_51_panel_0_item_2": "Compare changes and edit deliberately",
    "topic_51_panel_0_item_3": "Run counterexamples and record results",
    "topic_51_panel_1_label": "Review Example · Quantity Conversion",
    "topic_51_panel_1_item_0": "Suggestion · Use parseInt instead of Number",
    "topic_51_panel_1_item_1": "Counterexample · parseInt(\"2abc\") → 2",
    "topic_51_panel_1_item_2": "Decision · Reject because invalid quantity strings are accepted",
    "topic_51_practice_link": "Lab README",
    "topic_52_title": "Deliverables and Code Explanation",
    "topic_52_subtitle": "Working Code · Error Records · Roles of Type Checking and Runtime Validation",
    "topic_52_panel_0_label": "Deliverables",
    "topic_52_panel_0_head_0": "Item",
    "topic_52_panel_0_head_1": "Contents",
    "topic_52_panel_0_cell_0_0": "Source code",
    "topic_52_panel_0_cell_0_1": "Required TODOs · Run instructions · Lockfile",
    "topic_52_panel_0_cell_1_0": "review.md",
    "topic_52_panel_0_cell_1_1": "Predictions · Observations · Reasons for changes",
    "topic_52_panel_0_cell_2_0": "Verification results",
    "topic_52_panel_0_cell_2_1": "Type checks · Behavior tests · Browser failures",
    "topic_52_panel_1_label": "Code Explanation Criteria",
    "topic_52_panel_1_item_0": "Trace input → Validation → Calculation → Request → UI",
    "topic_52_panel_1_item_1": "Explain an error caught by type checking",
    "topic_52_panel_1_item_2": "Explain an error requiring runtime validation",
    "topic_52_practice_link": "Lab README"
  }
};
