window.LECTURE_CONTENT = {
  "ko": {
    "w5_01_chapter": "LECTURE 05 · 프로그래밍과 웹데이터",
    "w5_01_title": "React Framework의 이해",
    "w5_01_lead": "컴포넌트와 상태에서 서버 데이터와 비동기 UI까지",
    "w5_02_chapter": "CHAPTER 01 · React 애플리케이션의 이해",
    "w5_02_title": "React 애플리케이션의 이해",
    "w5_02_lead": "컴포넌트와 데이터로 구성하는 사용자 인터페이스",
    "w5_03_chapter": "CHAPTER 01 · React 애플리케이션의 이해",
    "w5_03_title": "React 기초 요약",
    "w5_03_lead": "컴포넌트 구성과 현재 데이터에 따른 화면 표현",
    "w5_03_b0_0_term": "컴포넌트의 조합",
    "w5_03_b0_0_0": "App이 상품 데이터를 준비하고 ProductRow가 한 행을 표현한다.",
    "w5_03_b0_1_term": "선언형 UI",
    "w5_03_b0_1_0": "DOM 수정 명령 대신 현재 데이터에 대응하는 JSX를 반환한다.",
    "w5_03_b0_2_term": "관찰 결과",
    "w5_03_b0_2_0": "화면에는 “사과: 1000원”이 나타난다.",
    "w5_03_b1_label": "React · 개념 예제",
    "w5_03_b1_code": "function ProductRow({ product }) {\n  return (\n    <li>\n      {product.name}: {product.price}원\n    </li>\n  );\n}\nexport default function App() {\n  const product = { id: 'p1', name: '사과', price: 1000 };\n  return (\n    <ul>\n      <ProductRow product={product} />\n    </ul>\n  );\n}",
    "w5_04_chapter": "CHAPTER 01 · React 애플리케이션의 이해",
    "w5_04_title": "React와 프레임워크의 역할",
    "w5_04_lead": "UI 표현과 라우팅·데이터 처리·렌더링 도구의 관계",
    "w5_04_b0_0_term": "React의 책임",
    "w5_04_b0_0_0": "컴포넌트·상태·화면 갱신을 통해 UI를 구성한다.",
    "w5_04_b0_1_term": "프레임워크의 책임",
    "w5_04_b0_1_0": "URL과 파일 연결, 서버 실행, 데이터 처리와 빌드를 통합한다.",
    "w5_04_b0_2_term": "관찰 결과",
    "w5_04_b0_2_0": "Next.js에서 파일 경로가 /products 페이지를 만든다. Vite 단독에는 이 규칙이 없다.",
    "w5_04_b1_label": "Next.js · 페이지 파일 전체",
    "w5_04_b1_code": "// app/products/page.jsx (Next.js App Router)\nimport Link from 'next/link';\nexport default function ProductsPage() {\n  return (\n    <main>\n      <h1>상품 목록</h1>\n      <Link href=\"/products/p1\">사과 상세 보기</Link>\n    </main>\n  );\n}",
    "w5_05_chapter": "CHAPTER 02 · JSX와 컴포넌트 기반 화면 구성",
    "w5_05_title": "JSX와 컴포넌트 기반 화면 구성",
    "w5_05_lead": "데이터를 UI로 표현하고 작은 단위로 조합하는 방법",
    "w5_06_chapter": "CHAPTER 02 · JSX와 컴포넌트 기반 화면 구성",
    "w5_06_title": "JSX의 역할",
    "w5_06_lead": "JavaScript 안에서 표현하는 UI 구조와 데이터",
    "w5_06_b0_0_term": "JSX는 문법 확장",
    "w5_06_b0_0_0": "빌드 도구가 JSX를 JavaScript로 변환한다. HTML 문자열로 직접 삽입하지 않는다.",
    "w5_06_b0_1_term": "중괄호의 표현식",
    "w5_06_b0_1_0": "JavaScript 값을 UI 안에 삽입하고 계산할 수 있다.",
    "w5_06_b0_2_term": "관찰 결과",
    "w5_06_b0_2_0": "상품명과 계산된 가격으로 “사과 · 2000원”을 표시한다.",
    "w5_06_b1_label": "React · 개념 예제",
    "w5_06_b1_code": "export default function ProductTitle() {\n  const product = { name: '사과', price: 1000 };\n  return (\n    <h2>\n      {product.name} · {product.price * 2}원\n    </h2>\n  );\n}",
    "w5_07_chapter": "CHAPTER 02 · JSX와 컴포넌트 기반 화면 구성",
    "w5_07_title": "JSX 작성 규칙",
    "w5_07_lead": "요소와 속성, 표현식과 Fragment",
    "w5_07_b0_0_term": "하나의 반환 구조",
    "w5_07_b0_0_0": "Fragment(<>)는 DOM 요소를 추가하지 않고 형제 요소를 묶는다.",
    "w5_07_b0_1_term": "태그와 속성",
    "w5_07_b0_1_0": "태그를 닫고 className·htmlFor를 사용한다. style에는 객체를 전달한다.",
    "w5_07_b0_2_term": "관찰 결과",
    "w5_07_b0_2_0": "label과 input이 연결되고 설명 문장이 녹색으로 표시된다.",
    "w5_07_b1_label": "React · 개념 예제",
    "w5_07_b1_code": "export default function ProductField() {\n  return (\n    <>\n      <label htmlFor=\"product\">상품명</label>\n      <input id=\"product\" className=\"field\" />\n      <p style={{ color: 'green' }}>필수 입력</p>\n    </>\n  );\n}",
    "w5_08_chapter": "CHAPTER 02 · JSX와 컴포넌트 기반 화면 구성",
    "w5_08_title": "함수 컴포넌트와 Props",
    "w5_08_lead": "입력 데이터를 받아 화면을 반환하는 함수",
    "w5_08_b0_0_term": "Props는 읽기 전용 입력",
    "w5_08_b0_0_0": "부모가 값을 전달한다. 자식은 Props를 직접 변경하지 않는다.",
    "w5_08_b0_1_term": "같은 정의, 다른 데이터",
    "w5_08_b0_1_0": "대문자로 시작하는 컴포넌트를 JSX에서 사용한다.",
    "w5_08_b0_2_term": "관찰 결과",
    "w5_08_b0_2_0": "같은 Price가 “1000원”과 “2USD”를 각각 표시한다.",
    "w5_08_b1_label": "React · 개념 예제",
    "w5_08_b1_code": "function Price({ amount, unit = '원' }) {\n  return (\n    <strong>\n      {amount}\n      {unit}\n    </strong>\n  );\n}\nexport default function App() {\n  return (\n    <>\n      <Price amount={1000} />\n      <Price amount={2} unit=\"USD\" />\n    </>\n  );\n}",
    "w5_09_chapter": "CHAPTER 02 · JSX와 컴포넌트 기반 화면 구성",
    "w5_09_title": "컴포넌트의 분리와 조합",
    "w5_09_lead": "책임 구분과 children을 통한 UI 재사용",
    "w5_09_b0_0_term": "역할에 따른 분리",
    "w5_09_b0_0_0": "카드는 공통 외형을, 내부 내용은 사용하는 쪽이 결정한다.",
    "w5_09_b0_1_term": "children으로 조합",
    "w5_09_b0_1_0": "여는 태그와 닫는 태그 사이의 JSX가 children으로 전달된다.",
    "w5_09_b0_2_term": "관찰 결과",
    "w5_09_b0_2_0": "동일한 카드 구조 안에 다른 상품·안내 내용을 넣을 수 있다.",
    "w5_09_b1_label": "React · 개념 예제",
    "w5_09_b1_code": "function Card({ title, children }) {\n  return (\n    <section>\n      <h2>{title}</h2>\n      <div>{children}</div>\n    </section>\n  );\n}\nexport default function App() {\n  return (\n    <Card title=\"상품 정보\">\n      <p>사과 · 1000원</p>\n    </Card>\n  );\n}",
    "w5_10_chapter": "CHAPTER 02 · JSX와 컴포넌트 기반 화면 구성",
    "w5_10_title": "조건부 렌더링과 목록",
    "w5_10_lead": "조건에 따른 화면 표현과 map·key를 이용한 항목 구성",
    "w5_10_b0_0_term": "조건은 JavaScript로",
    "w5_10_b0_0_0": "삼항 연산자로 재고 여부에 따른 문구를 선택한다.",
    "w5_10_b0_1_term": "목록 항목의 식별",
    "w5_10_b0_1_0": "map은 요소 배열을 만들고 안정적인 id를 key로 사용한다.",
    "w5_10_b0_2_term": "관찰 결과",
    "w5_10_b0_2_0": "products의 순서대로 표시된다. key는 화면 문구나 일반 Props로 전달되지 않는다.",
    "w5_10_b1_label": "React · 컴포넌트 전체 / products는 부모가 전달",
    "w5_10_b1_code": "export default function ProductList({ products }) {\n  return (\n    <ul>\n      {products.map((product) => (\n        <li key={product.id}>\n          {product.name}\n          {product.stocked ? ' · 재고 있음' : ' · 품절'}\n        </li>\n      ))}\n    </ul>\n  );\n}",
    "w5_11_chapter": "CHAPTER 03 · 사용자 행동과 상태 기반 화면 갱신",
    "w5_11_title": "사용자 행동과 상태 기반 화면 갱신",
    "w5_11_lead": "사용자의 입력을 기억하고 화면에 반영하는 원리",
    "w5_12_chapter": "CHAPTER 03 · 사용자 행동과 상태 기반 화면 갱신",
    "w5_12_title": "이벤트와 State",
    "w5_12_lead": "사용자의 클릭·입력과 컴포넌트가 기억하는 값",
    "w5_12_b0_0_term": "State가 값을 기억",
    "w5_12_b0_0_0": "일반 지역 변수와 달리 렌더 사이에 값이 유지된다.",
    "w5_12_b0_1_term": "이벤트에 함수 전달",
    "w5_12_b0_1_0": "onClick에 함수를 전달하고 클릭했을 때 상태 변경을 요청한다.",
    "w5_12_b0_2_term": "관찰 결과",
    "w5_12_b0_2_0": "초기 수량 1이 클릭할 때마다 2, 3으로 증가한다.",
    "w5_12_b1_label": "React · 개념 예제",
    "w5_12_b1_code": "import { useState } from 'react';\nexport default function Quantity() {\n  const [quantity, setQuantity] = useState(1);\n  return (\n    <button onClick={() => setQuantity(quantity + 1)}>\n      수량: {quantity}\n    </button>\n  );\n}",
    "w5_13_chapter": "CHAPTER 03 · 사용자 행동과 상태 기반 화면 갱신",
    "w5_13_title": "상태 변경과 화면 갱신",
    "w5_13_lead": "컴포넌트의 UI 계산과 DOM 반영, Render와 Commit",
    "w5_13_b0_0_term": "Render: 다음 UI 계산",
    "w5_13_b0_0_0": "상태 변경으로 컴포넌트를 다시 실행한다. 렌더 중 외부 데이터를 변경하지 않는다.",
    "w5_13_b0_1_term": "Commit: DOM에 반영",
    "w5_13_b0_1_0": "React는 필요한 DOM 변경을 수행하고 브라우저가 화면을 그린다.",
    "w5_13_b0_2_term": "관찰 결과",
    "w5_13_b0_2_0": "클릭 후 숫자가 바뀌지만 제목 DOM은 유지된다. 개발 Strict Mode는 render 로그를 추가 실행할 수 있다.",
    "w5_13_b1_label": "React · 개념 예제",
    "w5_13_b1_code": "import { useState } from 'react';\nexport default function Quantity() {\n  const [quantity, setQuantity] = useState(1);\n  console.log('render', quantity);\n  return (\n    <div>\n      <h2>상품 수량</h2>\n      <button onClick={() => setQuantity((q) => q + 1)}>\n        {quantity}\n      </button>\n    </div>\n  );\n}",
    "w5_14_chapter": "CHAPTER 03 · 사용자 행동과 상태 기반 화면 갱신",
    "w5_14_title": "상태의 스냅샷과 업데이트",
    "w5_14_lead": "각 렌더의 상태 값과 이전 상태를 이용한 갱신",
    "w5_14_b0_0_term": "렌더의 스냅샷",
    "w5_14_b0_0_0": "같은 이벤트 안의 count는 해당 렌더의 값이다. setter가 지역 값을 즉시 바꾸지 않는다.",
    "w5_14_b0_1_term": "업데이트 함수",
    "w5_14_b0_1_0": "c => c + 1은 대기열에서 이전 결과를 받아 다음 값을 계산한다.",
    "w5_14_b0_2_term": "관찰 결과",
    "w5_14_b0_2_0": "0에서 “값 두 번”은 1, 이어 “함수 두 번”은 3이 된다.",
    "w5_14_b1_label": "React · 개념 예제",
    "w5_14_b1_code": "import { useState } from 'react';\nexport default function Counter() {\n  const [count, setCount] = useState(0);\n  function replace() {\n    setCount(count + 1);\n    setCount(count + 1);\n  }\n  function increment() {\n    setCount((c) => c + 1);\n    setCount((c) => c + 1);\n  }\n  return (\n    <>\n      <p>{count}</p>\n      <button onClick={replace}>값 두 번</button>\n      <button onClick={increment}>함수 두 번</button>\n    </>\n  );\n}",
    "w5_15_chapter": "CHAPTER 03 · 사용자 행동과 상태 기반 화면 갱신",
    "w5_15_title": "객체와 배열의 상태 변경",
    "w5_15_lead": "불변성을 유지하는 데이터 갱신",
    "w5_15_b0_0_term": "새 배열과 새 객체",
    "w5_15_b0_0_0": "map으로 새 배열을 만들고 변경 항목만 객체 전개로 복사한다.",
    "w5_15_b0_1_term": "원본 상태 보존",
    "w5_15_b0_1_0": "products[0].stocked에 직접 대입하지 않는다. 복사는 필요한 깊이까지 수행한다.",
    "w5_15_b0_2_term": "관찰 결과",
    "w5_15_b0_2_0": "버튼의 “품절”이 클릭 후 “재고 있음”으로 바뀐다.",
    "w5_15_b1_label": "React · 개념 예제",
    "w5_15_b1_code": "import { useState } from 'react';\nexport default function Stock() {\n  const [products, setProducts] = useState([\n    { id: 'p1', name: '사과', stocked: false }\n  ]);\n  function restock() {\n    setProducts((items) =>\n      items.map((p) =>\n        p.id === 'p1' ? { ...p, stocked: true } : p\n      )\n    );\n  }\n  return (\n    <button onClick={restock}>\n      {products[0].stocked ? '재고 있음' : '품절'}\n    </button>\n  );\n}",
    "w5_16_chapter": "CHAPTER 03 · 사용자 행동과 상태 기반 화면 갱신",
    "w5_16_title": "상태의 설계와 공유",
    "w5_16_lead": "최소 상태, 파생값과 공통 부모의 변경 책임",
    "w5_16_b0_0_term": "최소 상태와 파생값",
    "w5_16_b0_0_0": "query만 상태로 둔다. visible과 개수는 매 렌더에서 계산한다.",
    "w5_16_b0_1_term": "단일 변경 책임",
    "w5_16_b0_1_0": "입력과 목록의 공통 부모가 상태를 소유한다. 분리할 때 값과 콜백을 전달한다.",
    "w5_16_b0_2_term": "관찰 결과",
    "w5_16_b0_2_0": "검색어가 바뀌면 목록과 개수가 함께 갱신된다. 이를 위한 Effect는 필요 없다.",
    "w5_16_b1_label": "React · 컴포넌트 전체 / products는 부모가 전달",
    "w5_16_b1_code": "import { useState } from 'react';\nexport default function Search({ products }) {\n  const [query, setQuery] = useState('');\n  const visible = products.filter((p) =>\n    p.name.includes(query)\n  );\n  return (\n    <>\n      <input\n        value={query}\n        onChange={(e) => setQuery(e.target.value)}\n      />\n      <p>{visible.length}개</p>\n      <ul>\n        {visible.map((p) => (\n          <li key={p.id}>{p.name}</li>\n        ))}\n      </ul>\n    </>\n  );\n}",
    "w5_17_chapter": "CHAPTER 03 · 사용자 행동과 상태 기반 화면 갱신",
    "w5_17_title": "컴포넌트의 식별과 상태 보존",
    "w5_17_lead": "화면의 위치와 key에 따른 상태 유지·초기화",
    "w5_17_b0_0_term": "위치·타입·key",
    "w5_17_b0_0_0": "React는 트리 안의 식별을 기준으로 상태를 보존한다.",
    "w5_17_b0_1_term": "명시적 초기화",
    "w5_17_b0_1_0": "상품 id가 바뀌면 Quantity의 key가 바뀌어 새 상태로 시작한다.",
    "w5_17_b0_2_term": "비교 실험",
    "w5_17_b0_2_0": "수량을 3으로 만든 뒤 상품을 바꾸면 1로 초기화된다. key를 제거하면 3이 유지된다.",
    "w5_17_b1_label": "React · 컴포넌트 전체 / 부모가 선택한 productId 전달",
    "w5_17_b1_code": "import { useState } from 'react';\nfunction Quantity() {\n  const [count, setCount] = useState(1);\n  return (\n    <button onClick={() => setCount((c) => c + 1)}>\n      수량: {count}\n    </button>\n  );\n}\nexport default function App({ productId }) {\n  return <Quantity key={productId} />;\n}",
    "w5_18_chapter": "CHAPTER 04 · Hooks와 외부 시스템 동기화",
    "w5_18_title": "Hooks와 외부 시스템 동기화",
    "w5_18_lead": "상태 관리, 참조와 외부 연결의 역할 구분",
    "w5_19_chapter": "CHAPTER 04 · Hooks와 외부 시스템 동기화",
    "w5_19_title": "Hooks의 역할과 호출 규칙",
    "w5_19_lead": "함수 컴포넌트의 기능 확장과 일관된 호출 순서",
    "w5_19_b0_0_term": "최상위에서 호출",
    "w5_19_b0_0_0": "Hook을 조건문·반복문·이벤트 안에서 호출하지 않는다. 조기 반환보다 먼저 호출한다.",
    "w5_19_b0_1_term": "호출 위치",
    "w5_19_b0_1_0": "함수 컴포넌트와 커스텀 Hook 안에서 React의 기능을 사용한다.",
    "w5_19_b0_2_term": "관찰 결과",
    "w5_19_b0_2_0": "visible이 바뀌어도 Hook 호출 순서는 같다. 부모가 컴포넌트를 제거하면 상태는 사라진다.",
    "w5_19_b1_label": "React · 개념 예제",
    "w5_19_b1_code": "import { useState } from 'react';\nexport default function ProductPanel({ visible }) {\n  const [count, setCount] = useState(1);\n  if (!visible) return null;\n  return (\n    <button onClick={() => setCount((c) => c + 1)}>\n      수량: {count}\n    </button>\n  );\n}",
    "w5_20_chapter": "CHAPTER 04 · Hooks와 외부 시스템 동기화",
    "w5_20_title": "State와 Ref의 구분",
    "w5_20_lead": "화면을 갱신하는 값과 렌더 사이에 유지하는 참조",
    "w5_20_b0_0_term": "State: 화면 데이터",
    "w5_20_b0_0_0": "query가 바뀌면 렌더가 예약되고 검색어 표시가 갱신된다.",
    "w5_20_b0_1_term": "Ref: 유지되는 참조",
    "w5_20_b0_1_0": "inputRef.current로 DOM에 접근한다. Ref 변경 자체는 렌더를 예약하지 않는다.",
    "w5_20_b0_2_term": "관찰 결과",
    "w5_20_b0_2_0": "입력하면 문구가 바뀌고 버튼을 누르면 입력창에 포커스가 이동한다.",
    "w5_20_b1_label": "React · 개념 예제",
    "w5_20_b1_code": "import { useRef, useState } from 'react';\nexport default function SearchField() {\n  const inputRef = useRef(null);\n  const [query, setQuery] = useState('');\n  return (\n    <>\n      <input\n        ref={inputRef}\n        value={query}\n        onChange={(e) => setQuery(e.target.value)}\n      />\n      <button onClick={() => inputRef.current.focus()}>\n        검색창으로 이동\n      </button>\n      <p>검색어: {query}</p>\n    </>\n  );\n}",
    "w5_21_chapter": "CHAPTER 04 · Hooks와 외부 시스템 동기화",
    "w5_21_title": "이벤트 처리와 Effect",
    "w5_21_lead": "사용자 행동에 따른 작업과 외부 시스템 동기화",
    "w5_21_b0_0_term": "이벤트: 특정 행동",
    "w5_21_b0_0_0": "사용자가 입력할 때 onChange에서 상태를 변경한다.",
    "w5_21_b0_1_term": "Effect: 외부와 동기화",
    "w5_21_b0_1_0": "React 화면 밖의 브라우저 탭 제목을 name과 맞춘다. 파생값 계산은 렌더에서 한다.",
    "w5_21_b0_2_term": "관찰 결과",
    "w5_21_b0_2_0": "입력값을 바꾸면 탭 제목이 바뀐다. 제거되면 원래 제목으로 돌아간다.",
    "w5_21_b1_label": "React · 개념 예제",
    "w5_21_b1_code": "import { useEffect, useState } from 'react';\nexport default function ProductName() {\n  const [name, setName] = useState('사과');\n  useEffect(() => {\n    const previous = document.title;\n    document.title = `상품: ${name}`;\n    return () => {\n      document.title = previous;\n    };\n  }, [name]);\n  return (\n    <input\n      value={name}\n      onChange={(e) => setName(e.target.value)}\n    />\n  );\n}",
    "w5_22_chapter": "CHAPTER 04 · Hooks와 외부 시스템 동기화",
    "w5_22_title": "Effect의 의존성과 정리",
    "w5_22_lead": "연결의 시작·갱신·종료와 cleanup",
    "w5_22_b0_0_term": "의존성은 사용 값",
    "w5_22_b0_0_0": "Effect가 읽는 반응형 값 productId를 의존성으로 선언한다.",
    "w5_22_b0_1_term": "정리 후 다시 시작",
    "w5_22_b0_1_0": "id 변경 시 이전 타이머를 정리하고 새 타이머를 만든다. 제거할 때도 정리한다.",
    "w5_22_b0_2_term": "관찰 결과",
    "w5_22_b0_2_0": "p1 → p2 변경 시 stop p1 뒤 start p2. 개발 Strict Mode에서는 추가 setup·cleanup 검사가 있다.",
    "w5_22_b1_label": "React · 로그로 연결 수명 관찰 / productId는 Props",
    "w5_22_b1_code": "import { useEffect } from 'react';\nexport default function Poll({ productId }) {\n  useEffect(() => {\n    console.log('start', productId);\n    const timer = setInterval(() => {\n      console.log('poll', productId);\n    }, 1000);\n    return () => {\n      clearInterval(timer);\n      console.log('stop', productId);\n    };\n  }, [productId]);\n  return <p>조회 대상: {productId}</p>;\n}",
    "w5_23_chapter": "CHAPTER 04 · Hooks와 외부 시스템 동기화",
    "w5_23_title": "커스텀 Hook과 로직 재사용",
    "w5_23_lead": "공통 상태·동기화 로직의 추출과 독립적인 상태",
    "w5_23_b0_0_term": "로직의 추출",
    "w5_23_b0_0_0": "use로 시작하는 함수 안에 반복되는 Hook 사용을 묶는다.",
    "w5_23_b0_1_term": "상태는 호출마다 독립",
    "w5_23_b0_1_0": "같은 Hook을 호출해도 상태 값 자체를 공유하지 않는다. 공유가 필요하면 상태를 올린다.",
    "w5_23_b0_2_term": "관찰 결과",
    "w5_23_b0_2_0": "사과 버튼을 눌러도 배 수량은 1을 유지한다.",
    "w5_23_b1_label": "React · 개념 예제",
    "w5_23_b1_code": "import { useState } from 'react';\nfunction useQuantity() {\n  const [value, setValue] = useState(1);\n  return [value, () => setValue((v) => v + 1)];\n}\nexport default function TwoProducts() {\n  const [apple, addApple] = useQuantity();\n  const [pear, addPear] = useQuantity();\n  return (\n    <>\n      <button onClick={addApple}>사과: {apple}</button>\n      <button onClick={addPear}>배: {pear}</button>\n    </>\n  );\n}",
    "w5_24_chapter": "CHAPTER 05 · 라우팅과 애플리케이션 데이터 흐름",
    "w5_24_title": "라우팅과 애플리케이션 데이터 흐름",
    "w5_24_lead": "하나의 화면을 여러 페이지의 서비스로 확장하는 방법",
    "w5_25_chapter": "CHAPTER 05 · 라우팅과 애플리케이션 데이터 흐름",
    "w5_25_title": "URL과 페이지의 연결",
    "w5_25_lead": "경로, 동적 매개변수와 화면 선택",
    "w5_25_b0_0_term": "파일 기반 경로",
    "w5_25_b0_0_0": "app/products/[id]/page.jsx가 상품 상세 경로를 정의한다.",
    "w5_25_b0_1_term": "동적 매개변수",
    "w5_25_b0_1_0": "[id] 부분의 URL 값은 params로 전달된다. 현재 App Router에서 await로 읽는다.",
    "w5_25_b0_2_term": "관찰 결과",
    "w5_25_b0_2_0": "/products/p1 → “상품 ID: p1”, /products/p2 → “상품 ID: p2”.",
    "w5_25_b1_label": "Next.js App Router · 페이지 파일 전체",
    "w5_25_b1_code": "// app/products/[id]/page.jsx\nexport default async function ProductPage({ params }) {\n  const { id } = await params;\n  return <h1>상품 ID: {id}</h1>;\n}",
    "w5_26_chapter": "CHAPTER 05 · 라우팅과 애플리케이션 데이터 흐름",
    "w5_26_title": "공통 레이아웃과 중첩 라우트",
    "w5_26_lead": "여러 페이지가 공유하는 구조와 하위 화면 구성",
    "w5_26_b0_0_term": "레이아웃은 공통 구조",
    "w5_26_b0_0_0": "상품 목록과 상세 페이지가 같은 메뉴를 사용한다.",
    "w5_26_b0_1_term": "중첩 경로와 children",
    "w5_26_b0_1_0": "프레임워크가 현재 하위 페이지를 children 위치에 구성한다. 루트 layout은 html·body를 포함한다.",
    "w5_26_b0_2_term": "관찰 결과",
    "w5_26_b0_2_0": "목록에서 상세로 이동해도 상품 영역의 공통 메뉴는 유지된다.",
    "w5_26_b1_label": "Next.js · 중첩 layout 파일 전체 / 루트 layout 별도",
    "w5_26_b1_code": "// app/products/layout.jsx\nimport Link from 'next/link';\nexport default function ProductsLayout({ children }) {\n  return (\n    <section>\n      <nav>\n        <Link href=\"/products\">상품 목록</Link>\n      </nav>\n      <main>{children}</main>\n    </section>\n  );\n}",
    "w5_27_chapter": "CHAPTER 05 · 라우팅과 애플리케이션 데이터 흐름",
    "w5_27_title": "UI 상태와 서버 데이터",
    "w5_27_lead": "검색 조건과 상품 데이터의 출처·수명·변경 책임",
    "w5_27_b0_0_term": "UI 상태",
    "w5_27_b0_0_0": "query는 이 화면에서 사용자가 입력하는 일시적인 값이다.",
    "w5_27_b0_1_term": "서버 데이터",
    "w5_27_b0_1_0": "products의 원본은 서버에 있다. 자식이 필터링해도 원본 저장 내용은 바뀌지 않는다.",
    "w5_27_b0_2_term": "관찰 결과",
    "w5_27_b0_2_0": "입력은 결과 개수만 바꾼다. 상품 저장·수정은 별도의 서버 작업이 필요하다.",
    "w5_27_b1_label": "Next.js · Client Component 전체 / 서버에서 products 전달",
    "w5_27_b1_code": "'use client';\nimport { useState } from 'react';\nexport default function ProductFilter({ products }) {\n  const [query, setQuery] = useState('');\n  const visible = products.filter((p) =>\n    p.name.includes(query)\n  );\n  return (\n    <>\n      <input\n        value={query}\n        onChange={(e) => setQuery(e.target.value)}\n      />\n      <p>검색 결과: {visible.length}개</p>\n    </>\n  );\n}",
    "w5_28_chapter": "CHAPTER 05 · 라우팅과 애플리케이션 데이터 흐름",
    "w5_28_title": "페이지에 필요한 데이터 조회",
    "w5_28_lead": "라우트와 데이터 로딩의 연결",
    "w5_28_b0_0_term": "페이지가 필요한 데이터 선언",
    "w5_28_b0_0_0": "Server Component 페이지에서 조회를 기다린 뒤 UI를 반환한다.",
    "w5_28_b0_1_term": "조회 계층의 역할",
    "w5_28_b0_1_0": "listProducts는 서버 전용 DB 조회 함수다. DB 연결·실패 처리는 별도 구현한다.",
    "w5_28_b0_2_term": "관찰 결과",
    "w5_28_b0_2_0": "서버 조회 결과의 이름을 표시한다. 브라우저 useEffect가 서버 조회를 대신하지 않는다.",
    "w5_28_b1_label": "Next.js · 구조 예시 / listProducts 구현 별도",
    "w5_28_b1_code": "// app/products/page.jsx\nimport { listProducts } from '@/lib/products';\nexport default async function ProductsPage() {\n  const products = await listProducts();\n  return (\n    <ul>\n      {products.map((p) => (\n        <li key={p.id}>{p.name}</li>\n      ))}\n    </ul>\n  );\n}",
    "w5_29_chapter": "CHAPTER 05 · 라우팅과 애플리케이션 데이터 흐름",
    "w5_29_title": "데이터 변경과 화면 동기화",
    "w5_29_lead": "저장·수정·삭제 이후 캐시와 데이터 재검증",
    "w5_29_b0_0_term": "변경과 조회는 다른 작업",
    "w5_29_b0_0_0": "저장 성공만으로 모든 화면의 오래된 데이터가 자동 교체되지는 않는다.",
    "w5_29_b0_1_term": "재검증의 대상",
    "w5_29_b0_1_0": "저장 후 /products 경로를 재검증한다. 실제 갱신 시점은 호출 위치·캐시 정책에 따라 달라진다.",
    "w5_29_b0_2_term": "관찰할 흐름",
    "w5_29_b0_2_0": "권한 검사 → 입력 검사 → 저장 → 재검증. 오류이면 저장과 재검증을 실행하지 않는다.",
    "w5_29_b1_label": "Next.js · Server Function 예시 / DB·권한 함수 별도",
    "w5_29_b1_code": "'use server';\nimport { revalidatePath } from 'next/cache';\nimport { saveProduct } from '@/lib/products';\nimport { requireEditor } from '@/lib/auth';\nexport async function createProduct(formData) {\n  await requireEditor();\n  const name = String(formData.get('name') ?? '').trim();\n  if (!name) return { error: '상품명을 입력하세요' };\n  await saveProduct({ name });\n  revalidatePath('/products');\n  return { error: null };\n}",
    "w5_30_chapter": "CHAPTER 06 · 렌더링 전략과 서버·클라이언트 경계",
    "w5_30_title": "렌더링 전략과 서버·클라이언트 경계",
    "w5_30_lead": "화면의 생성 시점과 코드의 실행 위치",
    "w5_31_chapter": "CHAPTER 06 · 렌더링 전략과 서버·클라이언트 경계",
    "w5_31_title": "클라이언트 렌더링과 서버 렌더링",
    "w5_31_lead": "CSR·SSR·사전 렌더링의 화면 생성 과정",
    "w5_31_b0_0_term": "CSR: 브라우저에서 시작",
    "w5_31_b0_0_0": "브라우저가 코드를 받아 UI를 구성한다. root 요소가 있는 HTML이 필요하다.",
    "w5_31_b0_1_term": "SSR과 사전 렌더링",
    "w5_31_b0_1_0": "SSR은 요청 시, 사전 렌더링은 요청 전에 HTML을 준비한다. Next.js는 경로와 정책에 따라 조합한다.",
    "w5_31_b0_2_term": "코드의 실행 환경",
    "w5_31_b0_2_0": "위·아래 코드는 별도 환경의 API 비교다. renderToString 호출만으로 서버 서비스가 만들어지지는 않는다.",
    "w5_31_b1_label": "React DOM · 구조 비교 / 브라우저·서버 파일 분리",
    "w5_31_b1_code": "// CSR entry: browser execution\nimport { createRoot } from 'react-dom/client';\nfunction App() {\n  return <h1>상품 목록</h1>;\n}\ncreateRoot(document.getElementById('root')).render(<App />);\n\n// SSR API shape: separate server execution\nimport { renderToString } from 'react-dom/server';\nconst html = renderToString(<App />);",
    "w5_32_chapter": "CHAPTER 06 · 렌더링 전략과 서버·클라이언트 경계",
    "w5_32_title": "Hydration과 상호작용",
    "w5_32_lead": "서버에서 생성한 HTML과 브라우저 코드의 연결",
    "w5_32_b0_0_term": "HTML 표시와 상호작용 연결",
    "w5_32_b0_0_0": "서버가 Quantity의 초기 HTML을 보낸 뒤 브라우저가 같은 트리를 연결한다.",
    "w5_32_b0_1_term": "초기 결과의 일치",
    "w5_32_b0_1_0": "서버 HTML과 브라우저의 첫 렌더가 일치해야 한다. 시간·난수·환경 분기에 주의한다.",
    "w5_32_b0_2_term": "관찰 결과",
    "w5_32_b0_2_0": "서버 HTML은 “수량: 1”을 먼저 보여주고 Hydration 후 클릭으로 2가 된다. Next.js는 연결을 관리한다.",
    "w5_32_b1_label": "React DOM · 구조 예시 / 서버가 같은 Quantity HTML 제공",
    "w5_32_b1_code": "// Shared component: server and browser\nimport { useState } from 'react';\nfunction Quantity() {\n  const [count, setCount] = useState(1);\n  return (\n    <button onClick={() => setCount((c) => c + 1)}>\n      수량: {count}\n    </button>\n  );\n}\n// Browser entry after matching server HTML arrives\nimport { hydrateRoot } from 'react-dom/client';\nhydrateRoot(document.getElementById('root'), <Quantity />);",
    "w5_33_chapter": "CHAPTER 06 · 렌더링 전략과 서버·클라이언트 경계",
    "w5_33_title": "Server Components와 Client Components",
    "w5_33_lead": "서버의 데이터 처리와 브라우저의 상태·이벤트 분담",
    "w5_33_b0_0_term": "서버 컴포넌트",
    "w5_33_b0_0_0": "기본 App Router 페이지는 서버에서 실행하며 DB에 접근할 수 있다. 브라우저용 상태·이벤트는 쓰지 않는다.",
    "w5_33_b0_1_term": "클라이언트 경계",
    "w5_33_b0_1_0": "quantity.jsx 맨 위의 use client가 클라이언트 모듈 경계를 선언한다. 초기 HTML은 서버에서 준비될 수도 있다.",
    "w5_33_b0_2_term": "구분의 기준",
    "w5_33_b0_2_0": "RSC는 코드 실행 경계이고 SSR은 HTML 생성 전략이다. 같은 의미로 사용하지 않는다.",
    "w5_33_b1_label": "Next.js · 구조 예시 / 별도 Quantity·조회 함수, 상품 1개 이상 가정",
    "w5_33_b1_code": "// app/products/page.jsx — Server Component\nimport Quantity from './quantity';\nimport { listProducts } from '@/lib/products';\nexport default async function Page() {\n  const products = await listProducts();\n  return (\n    <>\n      <h1>{products[0].name}</h1>\n      <Quantity />\n    </>\n  );\n}\n// quantity.jsx starts with 'use client'\n// Quantity is the state/event component from topic 08.",
    "w5_34_chapter": "CHAPTER 06 · 렌더링 전략과 서버·클라이언트 경계",
    "w5_34_title": "서버·클라이언트 데이터 전달",
    "w5_34_lead": "컴포넌트 경계, 직렬화와 서버 전용 정보",
    "w5_34_b0_0_term": "전달할 데이터 선택",
    "w5_34_b0_0_0": "클라이언트에 필요한 필드만 전달한다. 비밀 키·내부 원가·DB 연결 객체는 제외한다.",
    "w5_34_b0_1_term": "직렬화 가능한 Props",
    "w5_34_b0_1_0": "React가 지원하는 직렬화 가능한 값을 전달한다. JSON에만 한정되지는 않는다.",
    "w5_34_b0_2_term": "관찰 결과",
    "w5_34_b0_2_0": "주제 21의 ProductFilter가 받은 데이터로 브라우저에서 검색한다. 전달된 데이터는 사용자가 볼 수 있다.",
    "w5_34_b1_label": "Next.js · 구조 예시 / 주제 21 컴포넌트·DB 함수 별도",
    "w5_34_b1_code": "// app/products/page.jsx — server\nimport ProductFilter from './product-filter';\nimport { listProducts } from '@/lib/products';\nexport default async function Page() {\n  const products = await listProducts();\n  const publicProducts = products.map((p) => ({\n    id: p.id,\n    name: p.name,\n    price: p.price\n  }));\n  return <ProductFilter products={publicProducts} />;\n}",
    "w5_35_chapter": "CHAPTER 07 · 비동기 작업과 폼 제출",
    "w5_35_title": "비동기 작업과 폼 제출",
    "w5_35_lead": "대기·성공·실패를 포함하는 사용자 작업의 완성",
    "w5_36_chapter": "CHAPTER 07 · 비동기 작업과 폼 제출",
    "w5_36_title": "비동기 작업의 UI 상태",
    "w5_36_lead": "로딩, 빈 결과, 제출 중과 실패 상태",
    "w5_36_b0_0_term": "상태에 따라 다른 화면",
    "w5_36_b0_0_0": "조회 중과 실패는 빈 결과와 구분한다. 성공 후 항목이 없는 경우에만 빈 결과를 보여준다.",
    "w5_36_b0_1_term": "제출 중의 피드백",
    "w5_36_b0_1_0": "조회 중은 읽기 작업, 제출 중은 변경 작업이다. 진행 표시와 중복 제출 방지를 함께 설계한다.",
    "w5_36_b0_2_term": "비교 입력",
    "w5_36_b0_2_0": "loading → 조회 중, error → 조회 실패, success + [] → 검색 결과 없음.",
    "w5_36_b1_label": "React · 표시 컴포넌트 전체 / status·products는 부모가 관리",
    "w5_36_b1_code": "export default function Results({ status, products }) {\n  if (status === 'loading') return <p>조회 중</p>;\n  if (status === 'error') return <p role=\"alert\">조회 실패</p>;\n  if (products.length === 0) return <p>검색 결과 없음</p>;\n  return (\n    <ul>\n      {products.map((p) => (\n        <li key={p.id}>{p.name}</li>\n      ))}\n    </ul>\n  );\n}",
    "w5_37_chapter": "CHAPTER 07 · 비동기 작업과 폼 제출",
    "w5_37_title": "Suspense와 점진적 화면 표시",
    "w5_37_lead": "준비 중인 영역의 fallback과 스트리밍",
    "w5_37_b0_0_term": "경계 안의 준비 대기",
    "w5_37_b0_0_0": "제목은 먼저 표시하고 데이터가 준비되는 목록에 fallback을 표시할 수 있다.",
    "w5_37_b0_1_term": "지원되는 데이터 연결",
    "w5_37_b0_1_0": "App Router의 async Server Component 예시다. Effect 안의 fetch를 Suspense가 자동 감지하지 않는다.",
    "w5_37_b0_2_term": "관찰 결과",
    "w5_37_b0_2_0": "목록 조회가 대기하면 “상품 조회 중”을 거쳐 목록이 나타난다. 캐시·응답 속도에 따라 대기가 보이지 않을 수 있다.",
    "w5_37_b1_label": "Next.js · 페이지 구조 예시 / 조회 함수 별도",
    "w5_37_b1_code": "// app/products/page.jsx\nimport { Suspense } from 'react';\nimport { listProducts } from '@/lib/products';\nasync function ProductList() {\n  const products = await listProducts();\n  return <p>{products.map((p) => p.name).join(' · ')}</p>;\n}\nexport default function Page() {\n  return (\n    <>\n      <h1>상품 목록</h1>\n      <Suspense fallback={<p>상품 조회 중</p>}>\n        <ProductList />\n      </Suspense>\n    </>\n  );\n}",
    "w5_38_chapter": "CHAPTER 07 · 비동기 작업과 폼 제출",
    "w5_38_title": "폼 제출과 Actions",
    "w5_38_lead": "입력 데이터 수집과 제출 결과·진행 상태 관리",
    "w5_38_b0_0_term": "FormData와 Action",
    "w5_38_b0_0_0": "name 속성으로 입력을 수집한다. action 함수는 폼 제출을 처리한다.",
    "w5_38_b0_1_term": "결과·진행 상태",
    "w5_38_b0_1_0": "useActionState는 이전 결과·FormData를 함수에 전달하고 결과와 pending을 제공한다.",
    "w5_38_b0_2_term": "관찰 결과",
    "w5_38_b0_2_0": "제출 중 버튼이 비활성화되고 확인 결과가 표시된다. 이 예제는 지연·입력 확인만 하며 저장하지 않는다.",
    "w5_38_b1_label": "React · 개념 예제",
    "w5_38_b1_code": "import { useActionState } from 'react';\nasync function validateName(previous, formData) {\n  await new Promise((resolve) => setTimeout(resolve, 500));\n  const name = String(formData.get('name') ?? '').trim();\n  return name ? `확인: ${name}` : '상품명을 입력하세요';\n}\nexport default function ProductForm() {\n  const [message, action, pending] = useActionState(\n    validateName,\n    ''\n  );\n  return (\n    <form action={action}>\n      <input name=\"name\" aria-label=\"상품명\" />\n      <button disabled={pending}>\n        {pending ? '확인 중' : '확인'}\n      </button>\n      <p role=\"status\">{message}</p>\n    </form>\n  );\n}",
    "w5_39_chapter": "CHAPTER 07 · 비동기 작업과 폼 제출",
    "w5_39_title": "서버의 데이터 변경과 검증",
    "w5_39_lead": "Server Function·라우트 action의 역할과 입력·권한 검사",
    "w5_39_b0_0_term": "서버에서도 검사",
    "w5_39_b0_0_0": "브라우저 검사는 우회 가능하다. 서버 진입점에서 인증·권한과 입력을 검사한다.",
    "w5_39_b0_1_term": "프레임워크의 변경 진입점",
    "w5_39_b0_1_0": "Next.js는 Server Function을, React Router는 라우트 action을 제공한다. 여기서는 Next.js API를 사용한다.",
    "w5_39_b0_2_term": "연결과 결과",
    "w5_39_b0_2_0": "주제 30의 action 함수 대신 연결할 때 초기 결과는 { error: null }로 맞춘다. 저장 후 재검증은 주제 23처럼 추가한다.",
    "w5_39_b1_label": "Next.js · Server Function 예시 / DB·권한 함수 별도",
    "w5_39_b1_code": "'use server';\nimport { requireEditor } from '@/lib/auth';\nimport { saveProduct } from '@/lib/products';\nexport async function createProduct(previous, formData) {\n  await requireEditor();\n  const name = String(formData.get('name') ?? '').trim();\n  if (!name || name.length > 40) {\n    return { error: '상품명은 1~40자입니다' };\n  }\n  await saveProduct({ name });\n  return { error: null };\n}",
    "w5_40_chapter": "CHAPTER 07 · 비동기 작업과 폼 제출",
    "w5_40_title": "낙관적 UI와 오류 복구",
    "w5_40_lead": "응답 전 화면 갱신과 실패 시 결과 처리",
    "w5_40_b0_0_term": "임시 표시와 확정 상태",
    "w5_40_b0_0_0": "useOptimistic은 Action 중 임시로 재고를 표시한다. 서버 응답을 받은 뒤 확정 상태를 갱신한다.",
    "w5_40_b0_1_term": "실패 시 복구",
    "w5_40_b0_1_0": "실패하면 확정 상태를 바꾸지 않는다. Action이 끝나면 표시가 확정 상태로 돌아가고 오류를 알린다.",
    "w5_40_b0_2_term": "비교 실험",
    "w5_40_b0_2_0": "initial=false에서 지연 성공은 품절 → 재고 있음 유지. 지연 실패는 재고 있음 → 품절 복구.",
    "w5_40_b1_label": "React · 컴포넌트 전체 / saveStock은 Promise<boolean> 반환 또는 reject",
    "w5_40_b1_code": "import { useOptimistic, useState } from 'react';\nexport default function Stock({ initial, saveStock }) {\n  const [stocked, setStocked] = useState(initial);\n  const [shown, show] = useOptimistic(stocked);\n  const [error, setError] = useState('');\n  async function action() {\n    setError('');\n    show(true);\n    await saveStock(true)\n      .then(setStocked)\n      .catch(() => setError('저장 실패: 다시 시도하세요'));\n  }\n  return (\n    <form action={action}>\n      <p>{shown ? '재고 있음' : '품절'}</p>\n      <button>입고 처리</button>\n      <p role=\"alert\">{error}</p>\n    </form>\n  );\n}",
    "page_title": "05 | React Framework의 이해"
  },
  "en": {
    "w5_01_chapter": "LECTURE 05 · PROGRAMMING AND WEB DATA",
    "w5_01_title": "Understanding React Framework",
    "w5_01_lead": "From components and state to server data and async UI",
    "w5_02_chapter": "CHAPTER 01 · Understanding React Applications",
    "w5_02_title": "Understanding React Applications",
    "w5_02_lead": "User interfaces composed from components and data",
    "w5_03_chapter": "CHAPTER 01 · Understanding React Applications",
    "w5_03_title": "React Fundamentals Recap",
    "w5_03_lead": "Components and views derived from current data",
    "w5_03_b0_0_term": "Component composition",
    "w5_03_b0_0_0": "App provides product data; ProductRow describes one row.",
    "w5_03_b0_1_term": "Declarative UI",
    "w5_03_b0_1_0": "Return JSX for current data instead of issuing DOM mutation commands.",
    "w5_03_b0_2_term": "Observe",
    "w5_03_b0_2_0": "The screen displays “사과: 1000원”.",
    "w5_03_b1_label": "React · Teaching example",
    "w5_03_b1_code": "function ProductRow({ product }) {\n  return (\n    <li>\n      {product.name}: {product.price}원\n    </li>\n  );\n}\nexport default function App() {\n  const product = { id: 'p1', name: '사과', price: 1000 };\n  return (\n    <ul>\n      <ProductRow product={product} />\n    </ul>\n  );\n}",
    "w5_04_chapter": "CHAPTER 01 · Understanding React Applications",
    "w5_04_title": "React and Frameworks",
    "w5_04_lead": "How UI relates to routing, data, and rendering tools",
    "w5_04_b0_0_term": "React responsibilities",
    "w5_04_b0_0_0": "Build UI through components, state, and updates.",
    "w5_04_b0_1_term": "Framework responsibilities",
    "w5_04_b0_1_0": "Integrate URL conventions, server execution, data handling, and builds.",
    "w5_04_b0_2_term": "Observe",
    "w5_04_b0_2_0": "Next.js maps this file to /products. Vite alone does not provide this convention.",
    "w5_04_b1_label": "Next.js · Complete page file",
    "w5_04_b1_code": "// app/products/page.jsx (Next.js App Router)\nimport Link from 'next/link';\nexport default function ProductsPage() {\n  return (\n    <main>\n      <h1>상품 목록</h1>\n      <Link href=\"/products/p1\">사과 상세 보기</Link>\n    </main>\n  );\n}",
    "w5_05_chapter": "CHAPTER 02 · JSX and Component-Based UI",
    "w5_05_title": "JSX and Component-Based UI",
    "w5_05_lead": "Express data as UI and compose small units",
    "w5_06_chapter": "CHAPTER 02 · JSX and Component-Based UI",
    "w5_06_title": "The Role of JSX",
    "w5_06_lead": "UI structure and data expressed in JavaScript",
    "w5_06_b0_0_term": "JSX is a syntax extension",
    "w5_06_b0_0_0": "Build tools transform JSX into JavaScript; JSX is not an HTML string.",
    "w5_06_b0_1_term": "Expressions in braces",
    "w5_06_b0_1_0": "Insert and compute JavaScript values inside the UI.",
    "w5_06_b0_2_term": "Observe",
    "w5_06_b0_2_0": "Displays “사과 · 2000원” from the name and computed price.",
    "w5_06_b1_label": "React · Teaching example",
    "w5_06_b1_code": "export default function ProductTitle() {\n  const product = { name: '사과', price: 1000 };\n  return (\n    <h2>\n      {product.name} · {product.price * 2}원\n    </h2>\n  );\n}",
    "w5_07_chapter": "CHAPTER 02 · JSX and Component-Based UI",
    "w5_07_title": "JSX Rules",
    "w5_07_lead": "Elements, attributes, expressions, and Fragments",
    "w5_07_b0_0_term": "One returned structure",
    "w5_07_b0_0_0": "A Fragment (<>) groups siblings without adding a DOM element.",
    "w5_07_b0_1_term": "Tags and attributes",
    "w5_07_b0_1_0": "Close tags and use className and htmlFor. Pass an object to style.",
    "w5_07_b0_2_term": "Observe",
    "w5_07_b0_2_0": "The label targets the input and the description appears green.",
    "w5_07_b1_label": "React · Teaching example",
    "w5_07_b1_code": "export default function ProductField() {\n  return (\n    <>\n      <label htmlFor=\"product\">상품명</label>\n      <input id=\"product\" className=\"field\" />\n      <p style={{ color: 'green' }}>필수 입력</p>\n    </>\n  );\n}",
    "w5_08_chapter": "CHAPTER 02 · JSX and Component-Based UI",
    "w5_08_title": "Function Components and Props",
    "w5_08_lead": "Functions that receive data and return UI",
    "w5_08_b0_0_term": "Props are read-only inputs",
    "w5_08_b0_0_0": "The parent passes values; the child does not mutate its props.",
    "w5_08_b0_1_term": "Same definition, different data",
    "w5_08_b0_1_0": "Use a capitalized component name in JSX.",
    "w5_08_b0_2_term": "Observe",
    "w5_08_b0_2_0": "The same Price renders “1000원” and “2USD”.",
    "w5_08_b1_label": "React · Teaching example",
    "w5_08_b1_code": "function Price({ amount, unit = '원' }) {\n  return (\n    <strong>\n      {amount}\n      {unit}\n    </strong>\n  );\n}\nexport default function App() {\n  return (\n    <>\n      <Price amount={1000} />\n      <Price amount={2} unit=\"USD\" />\n    </>\n  );\n}",
    "w5_09_chapter": "CHAPTER 02 · JSX and Component-Based UI",
    "w5_09_title": "Splitting and Composing Components",
    "w5_09_lead": "Separate responsibilities and reuse UI through children",
    "w5_09_b0_0_term": "Separate by responsibility",
    "w5_09_b0_0_0": "Card owns the shared structure; its caller chooses the content.",
    "w5_09_b0_1_term": "Compose with children",
    "w5_09_b0_1_0": "JSX between the opening and closing tags becomes children.",
    "w5_09_b0_2_term": "Observe",
    "w5_09_b0_2_0": "The same card structure can contain different products or guidance.",
    "w5_09_b1_label": "React · Teaching example",
    "w5_09_b1_code": "function Card({ title, children }) {\n  return (\n    <section>\n      <h2>{title}</h2>\n      <div>{children}</div>\n    </section>\n  );\n}\nexport default function App() {\n  return (\n    <Card title=\"상품 정보\">\n      <p>사과 · 1000원</p>\n    </Card>\n  );\n}",
    "w5_10_chapter": "CHAPTER 02 · JSX and Component-Based UI",
    "w5_10_title": "Conditional Rendering and Lists",
    "w5_10_lead": "Conditions, map, and keys for list items",
    "w5_10_b0_0_term": "Conditions use JavaScript",
    "w5_10_b0_0_0": "A ternary expression selects the stock label.",
    "w5_10_b0_1_term": "Identify list items",
    "w5_10_b0_1_0": "map produces elements; stable IDs serve as keys.",
    "w5_10_b0_2_term": "Observe",
    "w5_10_b0_2_0": "Items follow products order. key is neither displayed text nor a normal prop.",
    "w5_10_b1_label": "React · Complete component / parent supplies products",
    "w5_10_b1_code": "export default function ProductList({ products }) {\n  return (\n    <ul>\n      {products.map((product) => (\n        <li key={product.id}>\n          {product.name}\n          {product.stocked ? ' · 재고 있음' : ' · 품절'}\n        </li>\n      ))}\n    </ul>\n  );\n}",
    "w5_11_chapter": "CHAPTER 03 · User Actions and State Updates",
    "w5_11_title": "User Actions and State Updates",
    "w5_11_lead": "Remember user input and reflect it in the UI",
    "w5_12_chapter": "CHAPTER 03 · User Actions and State Updates",
    "w5_12_title": "Events and State",
    "w5_12_lead": "User clicks and input, and values a component remembers",
    "w5_12_b0_0_term": "State remembers a value",
    "w5_12_b0_0_0": "Unlike local variables, state persists between renders.",
    "w5_12_b0_1_term": "Pass a function to the event",
    "w5_12_b0_1_0": "Pass a function to onClick; a click requests an update.",
    "w5_12_b0_2_term": "Observe",
    "w5_12_b0_2_0": "The initial quantity 1 increases to 2 and 3 with clicks.",
    "w5_12_b1_label": "React · Teaching example",
    "w5_12_b1_code": "import { useState } from 'react';\nexport default function Quantity() {\n  const [quantity, setQuantity] = useState(1);\n  return (\n    <button onClick={() => setQuantity(quantity + 1)}>\n      수량: {quantity}\n    </button>\n  );\n}",
    "w5_13_chapter": "CHAPTER 03 · User Actions and State Updates",
    "w5_13_title": "State Updates and Rendering",
    "w5_13_lead": "UI calculation and DOM changes: render and commit",
    "w5_13_b0_0_term": "Render: calculate the next UI",
    "w5_13_b0_0_0": "An update re-runs the component. Do not mutate external data during render.",
    "w5_13_b0_1_term": "Commit: apply changes to DOM",
    "w5_13_b0_1_0": "React applies needed DOM changes; the browser paints the screen.",
    "w5_13_b0_2_term": "Observe",
    "w5_13_b0_2_0": "The number changes while the heading DOM stays. Development Strict Mode may produce extra render logs.",
    "w5_13_b1_label": "React · Teaching example",
    "w5_13_b1_code": "import { useState } from 'react';\nexport default function Quantity() {\n  const [quantity, setQuantity] = useState(1);\n  console.log('render', quantity);\n  return (\n    <div>\n      <h2>상품 수량</h2>\n      <button onClick={() => setQuantity((q) => q + 1)}>\n        {quantity}\n      </button>\n    </div>\n  );\n}",
    "w5_14_chapter": "CHAPTER 03 · User Actions and State Updates",
    "w5_14_title": "State Snapshots and Updates",
    "w5_14_lead": "Per-render state values and updates based on previous state",
    "w5_14_b0_0_term": "Snapshot of a render",
    "w5_14_b0_0_0": "count in the event is that render’s value. A setter does not immediately mutate it.",
    "w5_14_b0_1_term": "Updater function",
    "w5_14_b0_1_0": "c => c + 1 computes the next value from the previous queued result.",
    "w5_14_b0_2_term": "Observe",
    "w5_14_b0_2_0": "From 0, “값 두 번” gives 1; then “함수 두 번” gives 3.",
    "w5_14_b1_label": "React · Teaching example",
    "w5_14_b1_code": "import { useState } from 'react';\nexport default function Counter() {\n  const [count, setCount] = useState(0);\n  function replace() {\n    setCount(count + 1);\n    setCount(count + 1);\n  }\n  function increment() {\n    setCount((c) => c + 1);\n    setCount((c) => c + 1);\n  }\n  return (\n    <>\n      <p>{count}</p>\n      <button onClick={replace}>값 두 번</button>\n      <button onClick={increment}>함수 두 번</button>\n    </>\n  );\n}",
    "w5_15_chapter": "CHAPTER 03 · User Actions and State Updates",
    "w5_15_title": "Updating Objects and Arrays",
    "w5_15_lead": "Update data while preserving immutability",
    "w5_15_b0_0_term": "New array and object",
    "w5_15_b0_0_0": "map creates a new array; spread copies the changed item.",
    "w5_15_b0_1_term": "Preserve the previous state",
    "w5_15_b0_1_0": "Do not assign to products[0].stocked directly. Copy each level that changes.",
    "w5_15_b0_2_term": "Observe",
    "w5_15_b0_2_0": "Clicking changes “품절” to “재고 있음”.",
    "w5_15_b1_label": "React · Teaching example",
    "w5_15_b1_code": "import { useState } from 'react';\nexport default function Stock() {\n  const [products, setProducts] = useState([\n    { id: 'p1', name: '사과', stocked: false }\n  ]);\n  function restock() {\n    setProducts((items) =>\n      items.map((p) =>\n        p.id === 'p1' ? { ...p, stocked: true } : p\n      )\n    );\n  }\n  return (\n    <button onClick={restock}>\n      {products[0].stocked ? '재고 있음' : '품절'}\n    </button>\n  );\n}",
    "w5_16_chapter": "CHAPTER 03 · User Actions and State Updates",
    "w5_16_title": "Designing and Sharing State",
    "w5_16_lead": "Minimal state, derived values, and a shared parent",
    "w5_16_b0_0_term": "Minimal state and derived values",
    "w5_16_b0_0_0": "Store query as state; calculate visible items and count during render.",
    "w5_16_b0_1_term": "One owner of updates",
    "w5_16_b0_1_0": "Their shared parent owns state. Pass values and callbacks when splitting components.",
    "w5_16_b0_2_term": "Observe",
    "w5_16_b0_2_0": "Changing the query updates both list and count, without an Effect.",
    "w5_16_b1_label": "React · Complete component / parent supplies products",
    "w5_16_b1_code": "import { useState } from 'react';\nexport default function Search({ products }) {\n  const [query, setQuery] = useState('');\n  const visible = products.filter((p) =>\n    p.name.includes(query)\n  );\n  return (\n    <>\n      <input\n        value={query}\n        onChange={(e) => setQuery(e.target.value)}\n      />\n      <p>{visible.length}개</p>\n      <ul>\n        {visible.map((p) => (\n          <li key={p.id}>{p.name}</li>\n        ))}\n      </ul>\n    </>\n  );\n}",
    "w5_17_chapter": "CHAPTER 03 · User Actions and State Updates",
    "w5_17_title": "Component Identity and State",
    "w5_17_lead": "Preserve or reset state through position and keys",
    "w5_17_b0_0_term": "Position, type, and key",
    "w5_17_b0_0_0": "React preserves state according to identity in the tree.",
    "w5_17_b0_1_term": "Explicit reset",
    "w5_17_b0_1_0": "A new product ID changes Quantity’s key and starts fresh state.",
    "w5_17_b0_2_term": "Compare",
    "w5_17_b0_2_0": "Set quantity to 3 and switch products: it resets to 1. Without key, 3 persists.",
    "w5_17_b1_label": "React · Complete component / parent passes selected productId",
    "w5_17_b1_code": "import { useState } from 'react';\nfunction Quantity() {\n  const [count, setCount] = useState(1);\n  return (\n    <button onClick={() => setCount((c) => c + 1)}>\n      수량: {count}\n    </button>\n  );\n}\nexport default function App({ productId }) {\n  return <Quantity key={productId} />;\n}",
    "w5_18_chapter": "CHAPTER 04 · Hooks and External Synchronization",
    "w5_18_title": "Hooks and External Synchronization",
    "w5_18_lead": "Distinguish state, references, and external connections",
    "w5_19_chapter": "CHAPTER 04 · Hooks and External Synchronization",
    "w5_19_title": "Hooks and Their Rules",
    "w5_19_lead": "Extend function components with consistent Hook calls",
    "w5_19_b0_0_term": "Call at the top level",
    "w5_19_b0_0_0": "Do not call Hooks in conditions, loops, or events. Call them before early returns.",
    "w5_19_b0_1_term": "Where Hooks belong",
    "w5_19_b0_1_0": "Use React features inside function components or custom Hooks.",
    "w5_19_b0_2_term": "Observe",
    "w5_19_b0_2_0": "Hook order stays consistent when visible changes. Removing the component discards its state.",
    "w5_19_b1_label": "React · Teaching example",
    "w5_19_b1_code": "import { useState } from 'react';\nexport default function ProductPanel({ visible }) {\n  const [count, setCount] = useState(1);\n  if (!visible) return null;\n  return (\n    <button onClick={() => setCount((c) => c + 1)}>\n      수량: {count}\n    </button>\n  );\n}",
    "w5_20_chapter": "CHAPTER 04 · Hooks and External Synchronization",
    "w5_20_title": "State Versus Ref",
    "w5_20_lead": "Values that update UI and references that persist",
    "w5_20_b0_0_term": "State: UI data",
    "w5_20_b0_0_0": "Changing query schedules a render and updates its display.",
    "w5_20_b0_1_term": "Ref: persistent reference",
    "w5_20_b0_1_0": "inputRef.current accesses the DOM. Ref changes alone do not schedule renders.",
    "w5_20_b0_2_term": "Observe",
    "w5_20_b0_2_0": "Typing updates the text; clicking the button focuses the input.",
    "w5_20_b1_label": "React · Teaching example",
    "w5_20_b1_code": "import { useRef, useState } from 'react';\nexport default function SearchField() {\n  const inputRef = useRef(null);\n  const [query, setQuery] = useState('');\n  return (\n    <>\n      <input\n        ref={inputRef}\n        value={query}\n        onChange={(e) => setQuery(e.target.value)}\n      />\n      <button onClick={() => inputRef.current.focus()}>\n        검색창으로 이동\n      </button>\n      <p>검색어: {query}</p>\n    </>\n  );\n}",
    "w5_21_chapter": "CHAPTER 04 · Hooks and External Synchronization",
    "w5_21_title": "Events and Effects",
    "w5_21_lead": "User-triggered work and synchronization with external systems",
    "w5_21_b0_0_term": "Event: a specific action",
    "w5_21_b0_0_0": "onChange updates state when the user types.",
    "w5_21_b0_1_term": "Effect: synchronize externally",
    "w5_21_b0_1_0": "Synchronize the browser tab title with name. Compute derived values during render.",
    "w5_21_b0_2_term": "Observe",
    "w5_21_b0_2_0": "Editing changes the tab title; unmounting restores the original title.",
    "w5_21_b1_label": "React · Teaching example",
    "w5_21_b1_code": "import { useEffect, useState } from 'react';\nexport default function ProductName() {\n  const [name, setName] = useState('사과');\n  useEffect(() => {\n    const previous = document.title;\n    document.title = `상품: ${name}`;\n    return () => {\n      document.title = previous;\n    };\n  }, [name]);\n  return (\n    <input\n      value={name}\n      onChange={(e) => setName(e.target.value)}\n    />\n  );\n}",
    "w5_22_chapter": "CHAPTER 04 · Hooks and External Synchronization",
    "w5_22_title": "Effect Dependencies and Cleanup",
    "w5_22_lead": "Start, update, and stop connections with cleanup",
    "w5_22_b0_0_term": "Dependencies follow used values",
    "w5_22_b0_0_0": "Declare the reactive value productId read by the Effect.",
    "w5_22_b0_1_term": "Clean up before restarting",
    "w5_22_b0_1_0": "Clean up the previous timer before starting a new one; also clean up on unmount.",
    "w5_22_b0_2_term": "Observe",
    "w5_22_b0_2_0": "Switching p1 → p2 logs stop p1 then start p2. Development Strict Mode adds a setup/cleanup check.",
    "w5_22_b1_label": "React · Observe connection lifetime in logs / productId is a prop",
    "w5_22_b1_code": "import { useEffect } from 'react';\nexport default function Poll({ productId }) {\n  useEffect(() => {\n    console.log('start', productId);\n    const timer = setInterval(() => {\n      console.log('poll', productId);\n    }, 1000);\n    return () => {\n      clearInterval(timer);\n      console.log('stop', productId);\n    };\n  }, [productId]);\n  return <p>조회 대상: {productId}</p>;\n}",
    "w5_23_chapter": "CHAPTER 04 · Hooks and External Synchronization",
    "w5_23_title": "Custom Hooks and Logic Reuse",
    "w5_23_lead": "Extract shared logic while keeping state independent",
    "w5_23_b0_0_term": "Extract logic",
    "w5_23_b0_0_0": "Group repeated Hook usage in a function whose name starts with use.",
    "w5_23_b0_1_term": "Each call owns its state",
    "w5_23_b0_1_0": "Calling the same Hook does not share state. Lift state when sharing is needed.",
    "w5_23_b0_2_term": "Observe",
    "w5_23_b0_2_0": "Clicking the apple button leaves the pear quantity at 1.",
    "w5_23_b1_label": "React · Teaching example",
    "w5_23_b1_code": "import { useState } from 'react';\nfunction useQuantity() {\n  const [value, setValue] = useState(1);\n  return [value, () => setValue((v) => v + 1)];\n}\nexport default function TwoProducts() {\n  const [apple, addApple] = useQuantity();\n  const [pear, addPear] = useQuantity();\n  return (\n    <>\n      <button onClick={addApple}>사과: {apple}</button>\n      <button onClick={addPear}>배: {pear}</button>\n    </>\n  );\n}",
    "w5_24_chapter": "CHAPTER 05 · Routing and Application Data Flow",
    "w5_24_title": "Routing and Application Data Flow",
    "w5_24_lead": "Expand one screen into a service with multiple pages",
    "w5_25_chapter": "CHAPTER 05 · Routing and Application Data Flow",
    "w5_25_title": "Connecting URLs to Pages",
    "w5_25_lead": "Paths, dynamic parameters, and page selection",
    "w5_25_b0_0_term": "File-based paths",
    "w5_25_b0_0_0": "app/products/[id]/page.jsx defines the product detail route.",
    "w5_25_b0_1_term": "Dynamic parameters",
    "w5_25_b0_1_0": "The [id] URL segment is provided through params, read with await in the current App Router.",
    "w5_25_b0_2_term": "Observe",
    "w5_25_b0_2_0": "/products/p1 displays “상품 ID: p1”; /products/p2 displays “상품 ID: p2”.",
    "w5_25_b1_label": "Next.js App Router · Complete page file",
    "w5_25_b1_code": "// app/products/[id]/page.jsx\nexport default async function ProductPage({ params }) {\n  const { id } = await params;\n  return <h1>상품 ID: {id}</h1>;\n}",
    "w5_26_chapter": "CHAPTER 05 · Routing and Application Data Flow",
    "w5_26_title": "Shared Layouts and Nested Routes",
    "w5_26_lead": "Shared page structures and nested views",
    "w5_26_b0_0_term": "Layouts provide shared structure",
    "w5_26_b0_0_0": "Product list and detail pages share navigation.",
    "w5_26_b0_1_term": "Nested routes and children",
    "w5_26_b0_1_0": "The framework places the current nested page in children. The root layout includes html and body.",
    "w5_26_b0_2_term": "Observe",
    "w5_26_b0_2_0": "Navigating from list to detail retains the shared product navigation.",
    "w5_26_b1_label": "Next.js · Complete nested layout / root layout required separately",
    "w5_26_b1_code": "// app/products/layout.jsx\nimport Link from 'next/link';\nexport default function ProductsLayout({ children }) {\n  return (\n    <section>\n      <nav>\n        <Link href=\"/products\">상품 목록</Link>\n      </nav>\n      <main>{children}</main>\n    </section>\n  );\n}",
    "w5_27_chapter": "CHAPTER 05 · Routing and Application Data Flow",
    "w5_27_title": "UI State and Server Data",
    "w5_27_lead": "Origins, lifetimes, and ownership of filters and product data",
    "w5_27_b0_0_term": "UI state",
    "w5_27_b0_0_0": "query is a temporary value entered by the user on this screen.",
    "w5_27_b0_1_term": "Server data",
    "w5_27_b0_1_0": "The source of products lives on the server. Filtering in the child does not change stored data.",
    "w5_27_b0_2_term": "Observe",
    "w5_27_b0_2_0": "Typing changes the result count; storing or editing a product requires a server operation.",
    "w5_27_b1_label": "Next.js · Complete Client Component / server supplies products",
    "w5_27_b1_code": "'use client';\nimport { useState } from 'react';\nexport default function ProductFilter({ products }) {\n  const [query, setQuery] = useState('');\n  const visible = products.filter((p) =>\n    p.name.includes(query)\n  );\n  return (\n    <>\n      <input\n        value={query}\n        onChange={(e) => setQuery(e.target.value)}\n      />\n      <p>검색 결과: {visible.length}개</p>\n    </>\n  );\n}",
    "w5_28_chapter": "CHAPTER 05 · Routing and Application Data Flow",
    "w5_28_title": "Fetching Page Data",
    "w5_28_lead": "Connect a route to the data it needs",
    "w5_28_b0_0_term": "Declare data where it is needed",
    "w5_28_b0_0_0": "The Server Component page awaits data before returning UI.",
    "w5_28_b0_1_term": "The data-access layer",
    "w5_28_b0_1_0": "listProducts is a server-only database query function. Connection and failure handling require a separate implementation.",
    "w5_28_b0_2_term": "Observe",
    "w5_28_b0_2_0": "Displays names returned by the server query. A browser useEffect does not replace this server query.",
    "w5_28_b1_label": "Next.js · Structure example / listProducts implemented separately",
    "w5_28_b1_code": "// app/products/page.jsx\nimport { listProducts } from '@/lib/products';\nexport default async function ProductsPage() {\n  const products = await listProducts();\n  return (\n    <ul>\n      {products.map((p) => (\n        <li key={p.id}>{p.name}</li>\n      ))}\n    </ul>\n  );\n}",
    "w5_29_chapter": "CHAPTER 05 · Routing and Application Data Flow",
    "w5_29_title": "Mutations and UI Synchronization",
    "w5_29_lead": "Revalidate data and caches after saving, editing, or deleting",
    "w5_29_b0_0_term": "Mutation and query differ",
    "w5_29_b0_0_0": "A successful save does not automatically replace stale data everywhere.",
    "w5_29_b0_1_term": "Revalidation target",
    "w5_29_b0_1_0": "Revalidate /products after saving; update timing depends on the call context and cache policy.",
    "w5_29_b0_2_term": "Observe the flow",
    "w5_29_b0_2_0": "Authorization → validation → save → revalidate. A validation error skips saving and revalidation.",
    "w5_29_b1_label": "Next.js · Server Function example / DB and authorization helpers required",
    "w5_29_b1_code": "'use server';\nimport { revalidatePath } from 'next/cache';\nimport { saveProduct } from '@/lib/products';\nimport { requireEditor } from '@/lib/auth';\nexport async function createProduct(formData) {\n  await requireEditor();\n  const name = String(formData.get('name') ?? '').trim();\n  if (!name) return { error: '상품명을 입력하세요' };\n  await saveProduct({ name });\n  revalidatePath('/products');\n  return { error: null };\n}",
    "w5_30_chapter": "CHAPTER 06 · Rendering and Server–Client Boundaries",
    "w5_30_title": "Rendering and Server–Client Boundaries",
    "w5_30_lead": "When UI is generated and where code executes",
    "w5_31_chapter": "CHAPTER 06 · Rendering and Server–Client Boundaries",
    "w5_31_title": "Client and Server Rendering",
    "w5_31_lead": "How CSR, SSR, and prerendering generate UI",
    "w5_31_b0_0_term": "CSR: begin in the browser",
    "w5_31_b0_0_0": "The browser receives code and builds UI. The HTML must include a root element.",
    "w5_31_b0_1_term": "SSR and prerendering",
    "w5_31_b0_1_0": "SSR prepares HTML on request; prerendering prepares it beforehand. Next.js combines these according to route policies.",
    "w5_31_b0_2_term": "Execution environments",
    "w5_31_b0_2_0": "The blocks compare APIs in separate environments. Calling renderToString alone does not build a server service.",
    "w5_31_b1_label": "React DOM · API comparison / separate browser and server files",
    "w5_31_b1_code": "// CSR entry: browser execution\nimport { createRoot } from 'react-dom/client';\nfunction App() {\n  return <h1>상품 목록</h1>;\n}\ncreateRoot(document.getElementById('root')).render(<App />);\n\n// SSR API shape: separate server execution\nimport { renderToString } from 'react-dom/server';\nconst html = renderToString(<App />);",
    "w5_32_chapter": "CHAPTER 06 · Rendering and Server–Client Boundaries",
    "w5_32_title": "Hydration and Interaction",
    "w5_32_lead": "Connect server-generated HTML to browser code",
    "w5_32_b0_0_term": "HTML display and interactivity",
    "w5_32_b0_0_0": "The server sends initial Quantity HTML; the browser attaches the same tree.",
    "w5_32_b0_1_term": "Matching initial output",
    "w5_32_b0_1_0": "Server HTML must match the first browser render. Time, randomness, and environment branches can cause mismatches.",
    "w5_32_b0_2_term": "Observe",
    "w5_32_b0_2_0": "Server HTML shows “수량: 1”; after hydration, a click gives 2. Next.js manages hydration.",
    "w5_32_b1_label": "React DOM · Structure example / server supplies matching Quantity HTML",
    "w5_32_b1_code": "// Shared component: server and browser\nimport { useState } from 'react';\nfunction Quantity() {\n  const [count, setCount] = useState(1);\n  return (\n    <button onClick={() => setCount((c) => c + 1)}>\n      수량: {count}\n    </button>\n  );\n}\n// Browser entry after matching server HTML arrives\nimport { hydrateRoot } from 'react-dom/client';\nhydrateRoot(document.getElementById('root'), <Quantity />);",
    "w5_33_chapter": "CHAPTER 06 · Rendering and Server–Client Boundaries",
    "w5_33_title": "Server and Client Components",
    "w5_33_lead": "Split server data work from browser state and events",
    "w5_33_b0_0_term": "Server Component",
    "w5_33_b0_0_0": "An App Router page runs on the server by default and can access a database. Browser state and events belong elsewhere.",
    "w5_33_b0_1_term": "Client boundary",
    "w5_33_b0_1_0": "use client at the top of quantity.jsx declares a client module boundary. Its initial HTML may still be prepared on the server.",
    "w5_33_b0_2_term": "Distinction",
    "w5_33_b0_2_0": "RSC describes code execution boundaries; SSR is an HTML generation strategy.",
    "w5_33_b1_label": "Next.js · Structure example / separate Quantity and query helper; assumes a product exists",
    "w5_33_b1_code": "// app/products/page.jsx — Server Component\nimport Quantity from './quantity';\nimport { listProducts } from '@/lib/products';\nexport default async function Page() {\n  const products = await listProducts();\n  return (\n    <>\n      <h1>{products[0].name}</h1>\n      <Quantity />\n    </>\n  );\n}\n// quantity.jsx starts with 'use client'\n// Quantity is the state/event component from topic 08.",
    "w5_34_chapter": "CHAPTER 06 · Rendering and Server–Client Boundaries",
    "w5_34_title": "Passing Data Across the Boundary",
    "w5_34_lead": "Serialization and server-only information at component boundaries",
    "w5_34_b0_0_term": "Select data to pass",
    "w5_34_b0_0_0": "Pass only required fields; exclude secrets, internal costs, and database connection objects.",
    "w5_34_b0_1_term": "Serializable props",
    "w5_34_b0_1_0": "Pass values supported by React serialization; this is not limited to JSON.",
    "w5_34_b0_2_term": "Observe",
    "w5_34_b0_2_0": "ProductFilter from topic 21 filters the received data in the browser. Users can inspect data sent to the client.",
    "w5_34_b1_label": "Next.js · Structure example / topic 21 component and DB helper required",
    "w5_34_b1_code": "// app/products/page.jsx — server\nimport ProductFilter from './product-filter';\nimport { listProducts } from '@/lib/products';\nexport default async function Page() {\n  const products = await listProducts();\n  const publicProducts = products.map((p) => ({\n    id: p.id,\n    name: p.name,\n    price: p.price\n  }));\n  return <ProductFilter products={publicProducts} />;\n}",
    "w5_35_chapter": "CHAPTER 07 · Async Work and Form Submission",
    "w5_35_title": "Async Work and Form Submission",
    "w5_35_lead": "Complete user tasks through waiting, success, and failure",
    "w5_36_chapter": "CHAPTER 07 · Async Work and Form Submission",
    "w5_36_title": "UI States for Async Work",
    "w5_36_lead": "Loading, empty results, pending submission, and failure",
    "w5_36_b0_0_term": "Different views for different states",
    "w5_36_b0_0_0": "Distinguish loading and failure from empty results. Show empty only after a successful query with no items.",
    "w5_36_b0_1_term": "Submission feedback",
    "w5_36_b0_1_0": "Loading concerns reads; pending submission concerns mutations. Provide progress feedback and prevent duplicate submission.",
    "w5_36_b0_2_term": "Compare inputs",
    "w5_36_b0_2_0": "loading → 조회 중; error → 조회 실패; success + [] → 검색 결과 없음.",
    "w5_36_b1_label": "React · Complete display component / parent manages status and products",
    "w5_36_b1_code": "export default function Results({ status, products }) {\n  if (status === 'loading') return <p>조회 중</p>;\n  if (status === 'error') return <p role=\"alert\">조회 실패</p>;\n  if (products.length === 0) return <p>검색 결과 없음</p>;\n  return (\n    <ul>\n      {products.map((p) => (\n        <li key={p.id}>{p.name}</li>\n      ))}\n    </ul>\n  );\n}",
    "w5_37_chapter": "CHAPTER 07 · Async Work and Form Submission",
    "w5_37_title": "Suspense and Progressive Display",
    "w5_37_lead": "Fallbacks and streaming for areas still being prepared",
    "w5_37_b0_0_term": "Wait within a boundary",
    "w5_37_b0_0_0": "The title can appear first while a fallback covers the list waiting for data.",
    "w5_37_b0_1_term": "Supported data integration",
    "w5_37_b0_1_0": "This uses an async Server Component in App Router. Suspense does not automatically detect fetch inside an Effect.",
    "w5_37_b0_2_term": "Observe",
    "w5_37_b0_2_0": "A slow query may show “상품 조회 중” before the list. Cached or fast responses may hide the wait.",
    "w5_37_b1_label": "Next.js · Page structure example / query helper required",
    "w5_37_b1_code": "// app/products/page.jsx\nimport { Suspense } from 'react';\nimport { listProducts } from '@/lib/products';\nasync function ProductList() {\n  const products = await listProducts();\n  return <p>{products.map((p) => p.name).join(' · ')}</p>;\n}\nexport default function Page() {\n  return (\n    <>\n      <h1>상품 목록</h1>\n      <Suspense fallback={<p>상품 조회 중</p>}>\n        <ProductList />\n      </Suspense>\n    </>\n  );\n}",
    "w5_38_chapter": "CHAPTER 07 · Async Work and Form Submission",
    "w5_38_title": "Forms and Actions",
    "w5_38_lead": "Collect input and manage submission results and progress",
    "w5_38_b0_0_term": "FormData and an Action",
    "w5_38_b0_0_0": "The name attribute identifies submitted fields. An action function handles form submission.",
    "w5_38_b0_1_term": "Result and pending state",
    "w5_38_b0_1_0": "useActionState passes previous state and FormData, and exposes the result and pending state.",
    "w5_38_b0_2_term": "Observe",
    "w5_38_b0_2_0": "The button is disabled while pending, then shows the validation result. This example simulates delay and validates input without saving.",
    "w5_38_b1_label": "React · Teaching example",
    "w5_38_b1_code": "import { useActionState } from 'react';\nasync function validateName(previous, formData) {\n  await new Promise((resolve) => setTimeout(resolve, 500));\n  const name = String(formData.get('name') ?? '').trim();\n  return name ? `확인: ${name}` : '상품명을 입력하세요';\n}\nexport default function ProductForm() {\n  const [message, action, pending] = useActionState(\n    validateName,\n    ''\n  );\n  return (\n    <form action={action}>\n      <input name=\"name\" aria-label=\"상품명\" />\n      <button disabled={pending}>\n        {pending ? '확인 중' : '확인'}\n      </button>\n      <p role=\"status\">{message}</p>\n    </form>\n  );\n}",
    "w5_39_chapter": "CHAPTER 07 · Async Work and Form Submission",
    "w5_39_title": "Server Mutations and Validation",
    "w5_39_lead": "Server Functions, route actions, and input and permission checks",
    "w5_39_b0_0_term": "Validate on the server too",
    "w5_39_b0_0_0": "Browser checks can be bypassed. Check authentication, authorization, and inputs at the server entry point.",
    "w5_39_b0_1_term": "Framework mutation entry points",
    "w5_39_b0_1_0": "Next.js offers Server Functions; React Router offers route actions. This example uses Next.js APIs.",
    "w5_39_b0_2_term": "Integration and results",
    "w5_39_b0_2_0": "When replacing the topic 30 action, initialize state as { error: null }. Add post-save revalidation as in topic 23.",
    "w5_39_b1_label": "Next.js · Server Function example / DB and authorization helpers required",
    "w5_39_b1_code": "'use server';\nimport { requireEditor } from '@/lib/auth';\nimport { saveProduct } from '@/lib/products';\nexport async function createProduct(previous, formData) {\n  await requireEditor();\n  const name = String(formData.get('name') ?? '').trim();\n  if (!name || name.length > 40) {\n    return { error: '상품명은 1~40자입니다' };\n  }\n  await saveProduct({ name });\n  return { error: null };\n}",
    "w5_40_chapter": "CHAPTER 07 · Async Work and Form Submission",
    "w5_40_title": "Optimistic UI and Error Recovery",
    "w5_40_lead": "Update before the response and handle failure",
    "w5_40_b0_0_term": "Temporary view and confirmed state",
    "w5_40_b0_0_0": "useOptimistic temporarily shows stock during an Action. Update confirmed state after the server response.",
    "w5_40_b0_1_term": "Recovery on failure",
    "w5_40_b0_1_0": "On failure, leave confirmed state unchanged. When the Action ends, display returns to that state and shows the error.",
    "w5_40_b0_2_term": "Compare",
    "w5_40_b0_2_0": "With initial=false, delayed success keeps 재고 있음; delayed failure restores 품절.",
    "w5_40_b1_label": "React · Complete component / saveStock returns Promise<boolean> or rejects",
    "w5_40_b1_code": "import { useOptimistic, useState } from 'react';\nexport default function Stock({ initial, saveStock }) {\n  const [stocked, setStocked] = useState(initial);\n  const [shown, show] = useOptimistic(stocked);\n  const [error, setError] = useState('');\n  async function action() {\n    setError('');\n    show(true);\n    await saveStock(true)\n      .then(setStocked)\n      .catch(() => setError('저장 실패: 다시 시도하세요'));\n  }\n  return (\n    <form action={action}>\n      <p>{shown ? '재고 있음' : '품절'}</p>\n      <button>입고 처리</button>\n      <p role=\"alert\">{error}</p>\n    </form>\n  );\n}",
    "page_title": "05 | Understanding React Framework"
  }
};
