window.LECTURE_CONTENT = {
  "ko": {
    "slide_01_title": "React 기초",
    "slide_01_subtitle": "React의 등장 배경·UI 설계 철학·화면 갱신과 첫 실행",
    "slide_02_title": "React의 소개와 등장 배경",
    "slide_02_subtitle": "React의 역할·탄생 배경·실제 활용",
    "slide_03_title": "React의 역할과 적용 범위",
    "slide_03_subtitle": "웹 서비스의 사용자 인터페이스를 구성하는 JavaScript 라이브러리",
    "slide_03_b0_definition0": "React - 데이터를 화면으로 표현하는 UI 라이브러리",
    "slide_03_b1_heading": "웹 서비스 안에서의 위치",
    "slide_03_b1_head0": "구성",
    "slide_03_b1_head1": "담당 역할",
    "slide_03_b1_cell0_0": "React",
    "slide_03_b1_cell0_1": "화면 구성 · 사용자 동작에 따른 UI 갱신",
    "slide_03_b1_cell1_0": "HTML · CSS · 브라우저",
    "slide_03_b1_cell1_1": "문서 구조 · 스타일 · 실제 화면 표시",
    "slide_03_b1_cell2_0": "서버 · 데이터베이스",
    "slide_03_b1_cell2_1": "요청 처리 · 공유 데이터 저장",
    "slide_04_title": "React의 등장 배경",
    "slide_04_subtitle": "복잡해진 웹 화면과 데이터 변화 관리의 어려움",
    "slide_04_b0_heading": "웹 UI 개발 방식의 확장",
    "slide_04_b0_head0": "방식",
    "slide_04_b0_head1": "개발의 중심",
    "slide_04_b0_cell0_0": "HTML · CSS",
    "slide_04_b0_cell0_1": "문서 구조와 스타일로 콘텐츠 표현",
    "slide_04_b0_cell1_0": "JavaScript · jQuery",
    "slide_04_b0_cell1_1": "DOM 요소 선택 · 이벤트 연결 · 화면 직접 수정",
    "slide_04_b0_cell2_0": "React의 컴포넌트",
    "slide_04_b0_cell2_1": "현재 데이터에 맞는 UI 정의와 조합",
    "slide_04_b1_definition0": "UI 관리 - 데이터와 DOM의 일치 유지",
    "slide_04_b1_detail0_0": "이벤트별 갱신 코드의 분산 → 관리 부담 증가",
    "slide_04_b1_definition1": "React의 접근(2013) - 컴포넌트 중심의 UI 구성",
    "slide_04_b1_detail1_0": "화면 구조와 표시 로직의 결합",
    "slide_04_b1_detail1_1": "데이터 변화에 따른 갱신 계산",
    "slide_05_title": "Facebook 웹의 React 활용",
    "slide_05_subtitle": "2020년 Facebook.com 재설계에 적용한 UI 구성",
    "slide_05_b0_alt": "Facebook.com의 탐색·스토리·피드·설정 화면",
    "slide_05_b0_caption": "Facebook.com · 2020년 기술 회고의 화면",
    "slide_05_b1_definition0": "화면 영역 - 역할별 UI 구성",
    "slide_05_b1_detail0_0": "왼쪽 - 탐색",
    "slide_05_b1_detail0_1": "가운데 - 스토리 · 피드",
    "slide_05_b1_detail0_2": "오른쪽 - 설정 메뉴",
    "slide_05_b1_definition1": "React 적용 - 영역 조합과 상호작용",
    "slide_05_b1_detail1_0": "사용자 동작에 반응하는 웹 UI",
    "slide_05_b1_definition2": "기술 구성 - UI와 기반 구조의 재설계",
    "slide_05_b1_detail2_0": "React · Relay · CSS",
    "slide_05_b1_detail2_1": "데이터 · 탐색 구조",
    "slide_06_title": "React의 주요 발전 과정",
    "slide_06_subtitle": "공개 이후 이어진 개발 방식과 학습 환경의 변화",
    "slide_06_b0_heading": "주요 전환점",
    "slide_06_b0_head0": "시기",
    "slide_06_b0_head1": "변화",
    "slide_06_b0_head2": "의미",
    "slide_06_b0_cell0_0": "2013.05",
    "slide_06_b0_cell0_1": "React 공개",
    "slide_06_b0_cell0_2": "Facebook에서 발전한 UI 도구의 공개",
    "slide_06_b0_cell1_0": "2019.02",
    "slide_06_b0_cell1_1": "React 16.8 · Hooks 도입",
    "slide_06_b0_cell1_2": "함수 중심 작성 방식의 확대",
    "slide_06_b0_cell2_0": "2023.03",
    "slide_06_b0_cell2_1": "react.dev 학습 문서 공개",
    "slide_06_b0_cell2_2": "함수 컴포넌트 중심의 학습 체계",
    "slide_06_b0_cell3_0": "2024.12",
    "slide_06_b0_cell3_1": "React 19 정식 출시",
    "slide_06_b0_cell3_2": "UI와 데이터 처리 기능의 확장",
    "slide_06_b1_heading": "학습의 기준",
    "slide_06_b1_item0": "작성 문법의 변화에도 이어지는 컴포넌트 · 데이터 · 화면의 관계",
    "slide_07_title": "개발자 설문으로 보는 React 사용 현황",
    "slide_07_subtitle": "2025년 전문 개발자 응답자의 사용 경험과 조사 해석",
    "slide_07_b0_heading": "2025 Stack Overflow · 전문 개발자",
    "slide_07_b0_head0": "선택 기술",
    "slide_07_b0_head1": "지난 1년 사용 경험",
    "slide_07_b0_cell0_0": "React",
    "slide_07_b0_cell0_1": "46.9%",
    "slide_07_b0_cell1_0": "jQuery",
    "slide_07_b0_cell1_1": "24.1%",
    "slide_07_b0_cell2_0": "Angular",
    "slide_07_b0_cell2_1": "19.8%",
    "slide_07_b0_cell3_0": "Vue.js",
    "slide_07_b0_cell3_1": "18.4%",
    "slide_07_b0_cell4_0": "Svelte",
    "slide_07_b0_cell4_1": "6.9%",
    "slide_07_b1_definition0": "조사 범위 - 문항 응답자의 기술 사용 경험",
    "slide_07_b1_detail0_0": "해당 문항 응답자 19,460명",
    "slide_07_b1_detail0_1": "여러 기술 선택 가능",
    "slide_07_b1_detail0_2": "전체 웹사이트 점유율 · 품질 순위와 구분",
    "slide_08_title": "React의 UI 설계 철학",
    "slide_08_subtitle": "화면의 구성 요소·재사용·데이터와 표현의 관계",
    "slide_09_title": "컴포넌트 기반 화면 구성",
    "slide_09_subtitle": "상품 검색 화면을 역할별 요소로 나누고 조합하는 방식",
    "slide_09_b1_definition0": "컴포넌트 - 역할을 가진 UI 단위",
    "slide_09_b1_detail0_0": "검색 영역 · 결과 목록 · 상품 행으로 구성",
    "slide_09_b1_definition1": "SearchBar - 검색 조건 입력",
    "slide_09_b1_detail1_0": "상품명 입력 · 재고 조건 선택",
    "slide_09_b1_definition2": "ProductTable - 결과 목록 표시",
    "slide_09_b1_detail2_0": "분류별 상품 · 검색 결과 개수",
    "slide_09_b1_definition3": "ProductRow - 상품 한 행의 표현",
    "slide_09_b1_detail3_0": "상품명 · 가격 · 재고 여부",
    "slide_10_title": "컴포넌트의 재사용과 일관성",
    "slide_10_subtitle": "같은 상품 행에 서로 다른 데이터를 표시하는 방식",
    "slide_10_b1_definition0": "컴포넌트 재사용 - 같은 UI 정의에 다른 데이터 적용",
    "slide_10_b1_detail0_0": "사과 $1 · 용과 $1 · 패션프루트 $2",
    "slide_10_b1_definition1": "공통 표현 규칙 - 모든 상품 행의 표시 방식",
    "slide_10_b1_detail1_0": "상품명 - 왼쪽",
    "slide_10_b1_detail1_1": "가격 - 오른쪽",
    "slide_10_b1_detail1_2": "품절 - 색상 · 문구로 구분",
    "slide_10_b1_definition2": "일관성 - 같은 표시 규칙을 모든 행에 반영",
    "slide_10_b1_detail2_0": "표시 규칙 수정 → 모든 상품 행에 반영",
    "slide_11_title": "데이터 변화와 화면 표현",
    "slide_11_subtitle": "검색 조건에 따라 달라지는 상품 목록과 결과 표시",
    "slide_12_title": "명령형과 선언형 프로그래밍",
    "slide_12_subtitle": "React에서는 현재 상태에 맞는 UI를 선언형으로 정의",
    "slide_12_b0_definition0": "명령형 - 작업의 순서와 방법을 직접 지정",
    "slide_12_b0_detail0_0": "UI 개발 - 변경할 DOM 요소와 수정 명령 지정",
    "slide_12_b0_detail0_1": "요소 선택 · 이벤트 처리 · 텍스트와 속성 수정",
    "slide_12_b1_definition0": "선언형 - 원하는 결과의 조건이나 형태를 정의",
    "slide_12_b1_detail0_0": "React - 현재 상태에 맞는 UI 선언",
    "slide_12_b1_detail0_1": "상태 변경 → UI 재계산 → 필요한 DOM 변경 반영",
    "slide_13_title": "jQuery와 React의 코드 비교",
    "slide_13_subtitle": "같은 클릭 카운터로 비교하는 DOM 수정 명령과 UI 선언",
    "slide_13_b1_heading": "명령형(jQuery)",
    "slide_13_b1_code": "let count = 0;\nconst button = $('<button>').appendTo(host);\nbutton.text(`Clicked ${count} times`);\nbutton.on('click', () => {\n  count += 1;\n  button.text(`Clicked ${count} times`);\n});",
    "slide_13_b1_explanation_definition0": "DOM 갱신 - 수정 순서의 직접 지정",
    "slide_13_b1_explanation_detail0_0": "버튼 생성 → 이벤트 연결 → 텍스트 수정",
    "slide_13_b1_explanation_detail0_1": "host - 버튼을 추가할 DOM 요소",
    "slide_13_b2_heading": "선언형(React)",
    "slide_13_b2_code": "function Counter() {\n  const [count, setCount] = useState(0);\n  return (\n    <button onClick={() => setCount(count + 1)}>\n      Clicked {count} times\n    </button>\n  );\n}",
    "slide_13_b2_explanation_definition0": "JSX - JavaScript 안의 UI 표현",
    "slide_13_b2_explanation_detail0_0": "현재 count에 맞는 버튼 UI 선언",
    "slide_13_b2_explanation_definition1": "useState(0) - 상태 초기값 0",
    "slide_13_b2_explanation_detail1_0": "setCount → 상태 변경 → React의 버튼 텍스트 갱신",
    "slide_14_title": "React Native와 UI 설계 방식의 확장",
    "slide_14_subtitle": "Shopify 사례로 보는 웹·모바일의 공통 관점과 차이",
    "slide_14_b0_heading": "Shopify · 2025년 기술 회고",
    "slide_14_b0_text": "iOS·Android에서 반복되는 개발을 줄이기 위한 React Native 활용",
    "slide_14_b1_heading": "공유하는 관점과 달라지는 대상",
    "slide_14_b1_head0": "관점",
    "slide_14_b1_head1": "웹 · React + React DOM",
    "slide_14_b1_head2": "모바일 · React Native",
    "slide_14_b1_cell0_0": "설계 방식",
    "slide_14_b1_cell0_1": "컴포넌트 조합 · 데이터에 따른 UI",
    "slide_14_b1_cell0_2": "컴포넌트 조합 · 데이터에 따른 UI",
    "slide_14_b1_cell1_0": "표시 대상",
    "slide_14_b1_cell1_1": "브라우저의 DOM",
    "slide_14_b1_cell1_2": "플랫폼의 네이티브 UI",
    "slide_14_b1_cell2_0": "플랫폼 연결",
    "slide_14_b1_cell2_1": "웹 API와 HTML 요소",
    "slide_14_b1_cell2_2": "기기 기능 · 플랫폼별 처리",
    "slide_15_title": "React의 화면 갱신",
    "slide_15_subtitle": "UI 계산·DOM 반영·입력 요소의 유지",
    "slide_16_title": "DOM과 Virtual DOM의 역할",
    "slide_16_subtitle": "실제 문서 구조와 메모리에서 표현하는 UI 구조",
    "slide_17_title": "React의 화면 갱신 과정",
    "slide_17_subtitle": "데이터 변화에 따른 UI 계산·비교와 DOM 반영",
    "slide_18_title": "화면 갱신과 입력 요소의 유지",
    "slide_18_subtitle": "시계가 갱신되는 동안 유지되는 입력창의 내용",
    "slide_18_b1_definition0": "UI 재계산 - 새 시간 데이터에 맞는 화면 계산",
    "slide_18_b1_detail0_0": "1초마다 바뀌는 시간",
    "slide_18_b1_definition1": "DOM 반영 - 변경된 시간 텍스트의 갱신",
    "slide_18_b1_detail1_0": "동일한 입력 요소 유지",
    "slide_18_b1_definition2": "입력 보존 - 작성 중인 내용과 위치의 유지",
    "slide_18_b1_detail2_0": "문자열 · 포커스 · 커서 위치 유지",
    "slide_19_title": "DOM 갱신 방식과 성능",
    "slide_19_subtitle": "직접 조작과 React의 갱신 책임·실제 변경 범위",
    "slide_19_b1_heading": "같은 결과에 도달하는 서로 다른 책임",
    "slide_19_b1_head0": "관점",
    "slide_19_b1_head1": "jQuery",
    "slide_19_b1_head2": "React",
    "slide_19_b1_cell0_0": "갱신 지시",
    "slide_19_b1_cell0_1": "개발자가 button.text(...) 호출",
    "slide_19_b1_cell0_2": "개발자는 UI 정의 · React가 DOM 변경 계산",
    "slide_19_b1_cell1_0": "이 버튼의 변경",
    "slide_19_b1_cell1_1": "버튼 노드 유지 · 안의 텍스트 교체",
    "slide_19_b1_cell1_2": "버튼 노드 유지 · 숫자 텍스트 갱신",
    "slide_19_b2_definition0": "갱신 비용 - 화면 갱신에 필요한 작업량",
    "slide_19_b2_detail0_0": "UI 계산 · 비교 · DOM 변경 · 브라우저의 레이아웃 · 페인트",
    "slide_19_b2_definition1": "VDOM - UI 갱신을 관리하는 방법",
    "slide_19_b2_detail1_0": "실제 속도 - 구현과 측정으로 판단",
    "slide_20_title": "React를 사용하는 서비스",
    "slide_20_subtitle": "아이콘을 선택해 새 탭에서 실제 서비스 화면 살펴보기",
    "slide_20_b0_service0_label": "인스타그램 사이트 열기 (새 탭)",
    "slide_20_b0_service0_name": "인스타그램",
    "slide_20_b0_service1_label": "페이스북 사이트 열기 (새 탭)",
    "slide_20_b0_service1_name": "페이스북",
    "slide_20_b0_service2_label": "넷플릭스 사이트 열기 (새 탭)",
    "slide_20_b0_service2_name": "넷플릭스",
    "slide_20_b0_service3_label": "스포티파이 사이트 열기 (새 탭)",
    "slide_20_b0_service3_name": "스포티파이",
    "slide_20_b0_service4_label": "에어비앤비 사이트 열기 (새 탭)",
    "slide_20_b0_service4_name": "에어비앤비",
    "slide_20_b0_service5_label": "Microsoft Teams 사이트 열기 (새 탭)",
    "slide_20_b0_service5_name": "Microsoft Teams",
    "slide_21_title": "프로젝트 셋업과 Hello World",
    "slide_21_subtitle": "개발 환경에서 첫 React 화면까지의 실행 흐름",
    "slide_22_title": "React 개발 환경과 도구",
    "slide_22_subtitle": "Node.js·npm·Vite의 역할과 실행 환경 확인",
    "slide_22_b0_heading": "개발 도구의 역할",
    "slide_22_b0_head0": "도구",
    "slide_22_b0_head1": "역할",
    "slide_22_b0_cell0_0": "Node.js",
    "slide_22_b0_cell0_1": "개발 도구를 컴퓨터에서 실행하는 환경",
    "slide_22_b0_cell1_0": "npm",
    "slide_22_b0_cell1_1": "프로젝트 생성 도구 실행 · 패키지 설치",
    "slide_22_b0_cell2_0": "Vite",
    "slide_22_b0_cell2_1": "개발 서버 · 변경 반영 · 배포용 빌드",
    "slide_22_b1_heading": "터미널 · 설치 확인",
    "slide_22_b1_code": "node -v\nnpm -v",
    "slide_22_b2_definition0": "실행 조건 - Vite 가이드의 Node.js 버전 요구사항",
    "slide_22_b2_detail0_0": "Node.js 20.19+ 또는 22.12+",
    "slide_22_b2_detail0_1": "템플릿의 추가 버전 조건 확인",
    "slide_23_title": "React 프로젝트 생성과 실행",
    "slide_23_subtitle": "프로젝트 생성·패키지 설치·개발 서버 접속",
    "slide_23_b0_heading": "터미널 · 생성 → 설치 → 실행",
    "slide_23_b0_code": "npm create vite@latest pwd-week4-demo -- --template react-ts\ncd pwd-week4-demo\nnpm install\nnpm run dev",
    "slide_23_b1_heading": "터미널 · 실행 출력",
    "slide_23_b1_code": "VITE v8.3.0  ready in 110 ms\n➜  Local:   http://127.0.0.1:4320/",
    "slide_23_b2_alt": "Vite React TypeScript 프로젝트의 초기 브라우저 화면",
    "slide_23_b2_caption": "Local 주소 접속 · React + TypeScript 템플릿",
    "slide_24_title": "Hello World와 화면 변경 확인",
    "slide_24_subtitle": "App.tsx의 문구 수정이 브라우저에 반영되는 과정",
    "slide_24_b0_heading": "src/App.tsx · 최초 화면",
    "slide_24_b0_code": "export default function App() {\n  return <h1>Hello, World!</h1>;\n}",
    "slide_24_b1_heading": "src/App.tsx · 문구 변경 후 저장",
    "slide_24_b1_code": "export default function App() {\n  return <h1>Hello, React!</h1>;\n}",
    "page_title": "04 | React 기초",
    "ui_deck_label": "React 기초"
  },
  "en": {
    "slide_01_title": "React Fundamentals",
    "slide_01_subtitle": "Origins, UI Design Philosophy, Screen Updates, and First Run",
    "slide_02_title": "Introducing React and Its Origins",
    "slide_02_subtitle": "The Role, Background, and Adoption of React",
    "slide_03_title": "The Role and Scope of React",
    "slide_03_subtitle": "A JavaScript Library for Building Web User Interfaces",
    "slide_03_b0_definition0": "React - A UI library for presenting data",
    "slide_03_b1_heading": "Its Place in a Web Service",
    "slide_03_b1_head0": "Part",
    "slide_03_b1_head1": "Responsibility",
    "slide_03_b1_cell0_0": "React",
    "slide_03_b1_cell0_1": "UI composition · Updates following user actions",
    "slide_03_b1_cell1_0": "HTML · CSS · Browser",
    "slide_03_b1_cell1_1": "Document structure · Styling · Display",
    "slide_03_b1_cell2_0": "Server · Database",
    "slide_03_b1_cell2_1": "Request processing · Shared data storage",
    "slide_04_title": "The Origins of React",
    "slide_04_subtitle": "Growing Interface Complexity and Changing Data",
    "slide_04_b0_heading": "Expanding Approaches to Web UI",
    "slide_04_b0_head0": "Approach",
    "slide_04_b0_head1": "Development Focus",
    "slide_04_b0_cell0_0": "HTML · CSS",
    "slide_04_b0_cell0_1": "Content expressed through document structure and styling",
    "slide_04_b0_cell1_0": "JavaScript · jQuery",
    "slide_04_b0_cell1_1": "DOM selection · Event handling · Direct UI updates",
    "slide_04_b0_cell2_0": "React Components",
    "slide_04_b0_cell2_1": "UI definition and composition for current data",
    "slide_04_b1_definition0": "UI Management - Keeping data and DOM in sync",
    "slide_04_b1_detail0_0": "Scattered update logic → Greater maintenance effort",
    "slide_04_b1_definition1": "React’s Approach (2013) - UI composition with components",
    "slide_04_b1_detail1_0": "UI structure and display logic in the same component",
    "slide_04_b1_detail1_1": "Updates calculated as data changes",
    "slide_05_title": "React at Facebook",
    "slide_05_subtitle": "UI Composition in the 2020 Facebook.com Redesign",
    "slide_05_b0_alt": "Facebook.com navigation, stories, feed, and settings",
    "slide_05_b0_caption": "Facebook.com · Image from the 2020 engineering report",
    "slide_05_b1_definition0": "UI Areas - Composition by role",
    "slide_05_b1_detail0_0": "Left - Navigation",
    "slide_05_b1_detail0_1": "Center - Stories · Feed",
    "slide_05_b1_detail0_2": "Right - Settings",
    "slide_05_b1_definition1": "React’s Role - Composition and interaction",
    "slide_05_b1_detail1_0": "Web UI responding to user actions",
    "slide_05_b1_definition2": "System - UI and infrastructure redesign",
    "slide_05_b1_detail2_0": "React · Relay · CSS",
    "slide_05_b1_detail2_1": "Data · Navigation structure",
    "slide_06_title": "Key Milestones in React",
    "slide_06_subtitle": "Changes in Development and Learning Since Its Public Release",
    "slide_06_b0_heading": "Key Milestones",
    "slide_06_b0_head0": "Date",
    "slide_06_b0_head1": "Change",
    "slide_06_b0_head2": "Significance",
    "slide_06_b0_cell0_0": "2013.05",
    "slide_06_b0_cell0_1": "React released publicly",
    "slide_06_b0_cell0_2": "Public release of the UI tool developed at Facebook",
    "slide_06_b0_cell1_0": "2019.02",
    "slide_06_b0_cell1_1": "React 16.8 · Hooks introduced",
    "slide_06_b0_cell1_2": "Broader use of function-based components",
    "slide_06_b0_cell2_0": "2023.03",
    "slide_06_b0_cell2_1": "New react.dev learning docs",
    "slide_06_b0_cell2_2": "Learning organized around function components",
    "slide_06_b0_cell3_0": "2024.12",
    "slide_06_b0_cell3_1": "React 19 released",
    "slide_06_b0_cell3_2": "Expanded UI and data-handling features",
    "slide_06_b1_heading": "Learning Focus",
    "slide_06_b1_item0": "Components, data, and UI across changes in syntax",
    "slide_07_title": "React Usage in Developer Surveys",
    "slide_07_subtitle": "Professional Developer Responses in 2025 and Survey Interpretation",
    "slide_07_b0_heading": "2025 Stack Overflow · Professional Developers",
    "slide_07_b0_head0": "Selected Technology",
    "slide_07_b0_head1": "Used in the Past Year",
    "slide_07_b0_cell0_0": "React",
    "slide_07_b0_cell0_1": "46.9%",
    "slide_07_b0_cell1_0": "jQuery",
    "slide_07_b0_cell1_1": "24.1%",
    "slide_07_b0_cell2_0": "Angular",
    "slide_07_b0_cell2_1": "19.8%",
    "slide_07_b0_cell3_0": "Vue.js",
    "slide_07_b0_cell3_1": "18.4%",
    "slide_07_b0_cell4_0": "Svelte",
    "slide_07_b0_cell4_1": "6.9%",
    "slide_07_b1_definition0": "Survey Scope - Technology use among respondents",
    "slide_07_b1_detail0_0": "19,460 responses to this question",
    "slide_07_b1_detail0_1": "Multiple selections allowed",
    "slide_07_b1_detail0_2": "Distinct from website market share or quality rankings",
    "slide_08_title": "React UI Design Philosophy",
    "slide_08_subtitle": "UI Elements, Reuse, and the Relationship Between Data and Presentation",
    "slide_09_title": "Component-Based UI Composition",
    "slide_09_subtitle": "Dividing a Product Search Interface by Responsibility",
    "slide_09_b1_definition0": "Component - A UI unit with a role",
    "slide_09_b1_detail0_0": "Search area · Results · Product rows",
    "slide_09_b1_definition1": "SearchBar - Search criteria input",
    "slide_09_b1_detail1_0": "Product-name input · Stock selection",
    "slide_09_b1_definition2": "ProductTable - Results display",
    "slide_09_b1_detail2_0": "Products by category · Result count",
    "slide_09_b1_definition3": "ProductRow - A single product row",
    "slide_09_b1_detail3_0": "Name · Price · Stock status",
    "slide_10_title": "Component Reuse and Consistency",
    "slide_10_subtitle": "Different Product Data Displayed with the Same Row Component",
    "slide_10_b1_definition0": "Component Reuse - One UI definition with different data",
    "slide_10_b1_detail0_0": "Apple $1 · Dragonfruit $1 · Passionfruit $2",
    "slide_10_b1_definition1": "Shared Rules - Presentation of every product row",
    "slide_10_b1_detail1_0": "Name - Left",
    "slide_10_b1_detail1_1": "Price - Right",
    "slide_10_b1_detail1_2": "Out of stock - Color · Text",
    "slide_10_b1_definition2": "Consistency - Shared rules across all rows",
    "slide_10_b1_detail2_0": "Row rule change → All product rows updated",
    "slide_11_title": "Data Changes and UI Output",
    "slide_11_subtitle": "Product Lists and Result Counts That Follow Search Criteria",
    "slide_12_title": "Imperative and Declarative Programming",
    "slide_12_subtitle": "React Declaratively Describes the UI for the Current State",
    "slide_12_b0_definition0": "Imperative - Explicit steps and operations",
    "slide_12_b0_detail0_0": "UI development - DOM targets and update commands",
    "slide_12_b0_detail0_1": "Element selection · Events · Text and attribute updates",
    "slide_12_b1_definition0": "Declarative - Conditions or form of the desired result",
    "slide_12_b1_detail0_0": "React - UI declared for the current state",
    "slide_12_b1_detail0_1": "State change → UI recalculation → Required DOM updates",
    "slide_13_title": "jQuery and React Code Comparison",
    "slide_13_subtitle": "DOM Update Commands and UI Declarations for the Same Counter",
    "slide_13_b1_heading": "Imperative (jQuery)",
    "slide_13_b1_code": "let count = 0;\nconst button = $('<button>').appendTo(host);\nbutton.text(`Clicked ${count} times`);\nbutton.on('click', () => {\n  count += 1;\n  button.text(`Clicked ${count} times`);\n});",
    "slide_13_b1_explanation_definition0": "DOM Updates - Explicit update steps",
    "slide_13_b1_explanation_detail0_0": "Button creation → Event handling → Text updates",
    "slide_13_b1_explanation_detail0_1": "host - The DOM element receiving the button",
    "slide_13_b2_heading": "Declarative (React)",
    "slide_13_b2_code": "function Counter() {\n  const [count, setCount] = useState(0);\n  return (\n    <button onClick={() => setCount(count + 1)}>\n      Clicked {count} times\n    </button>\n  );\n}",
    "slide_13_b2_explanation_definition0": "JSX - UI expressed within JavaScript",
    "slide_13_b2_explanation_detail0_0": "Button UI declared for the current count",
    "slide_13_b2_explanation_definition1": "useState(0) - Initial state value 0",
    "slide_13_b2_explanation_detail1_0": "setCount → State change → React updates the button text",
    "slide_14_title": "Extending React UI Design with React Native",
    "slide_14_subtitle": "Shared Concepts and Platform Differences at Shopify",
    "slide_14_b0_heading": "Shopify · 2025 Engineering Retrospective",
    "slide_14_b0_text": "React Native to reduce duplicated development across iOS and Android",
    "slide_14_b1_heading": "Shared Concepts and Different Targets",
    "slide_14_b1_head0": "Aspect",
    "slide_14_b1_head1": "Web · React + React DOM",
    "slide_14_b1_head2": "Mobile · React Native",
    "slide_14_b1_cell0_0": "Design",
    "slide_14_b1_cell0_1": "Component composition and data-driven UI",
    "slide_14_b1_cell0_2": "Component composition and data-driven UI",
    "slide_14_b1_cell1_0": "Render target",
    "slide_14_b1_cell1_1": "Browser DOM",
    "slide_14_b1_cell1_2": "Platform-native UI",
    "slide_14_b1_cell2_0": "Platform integration",
    "slide_14_b1_cell2_1": "Web APIs and HTML elements",
    "slide_14_b1_cell2_2": "Device features and platform-specific behavior",
    "slide_15_title": "UI Updates in React",
    "slide_15_subtitle": "UI Calculation, DOM Updates, and Input Preservation",
    "slide_16_title": "DOM and Virtual DOM",
    "slide_16_subtitle": "The Browser Document and an In-Memory UI Representation",
    "slide_17_title": "The React UI Update Process",
    "slide_17_subtitle": "Calculating, Comparing, and Applying UI Changes",
    "slide_18_title": "UI Updates and Input Preservation",
    "slide_18_subtitle": "Typed Text Retained While a Clock Updates",
    "slide_18_b1_definition0": "UI Recalculation - UI calculated from new time data",
    "slide_18_b1_detail0_0": "Time updated every second",
    "slide_18_b1_definition1": "DOM Updates - Changes to the time text",
    "slide_18_b1_detail1_0": "The same input element retained",
    "slide_18_b1_definition2": "Input Preservation - Retained text and editing position",
    "slide_18_b1_detail2_0": "Typed text · Focus · Caret position",
    "slide_19_title": "DOM Updates and Performance",
    "slide_19_subtitle": "Update Responsibilities and Actual Changes in jQuery and React",
    "slide_19_b1_heading": "Different Responsibilities for the Same Result",
    "slide_19_b1_head0": "Aspect",
    "slide_19_b1_head1": "jQuery",
    "slide_19_b1_head2": "React",
    "slide_19_b1_cell0_0": "Update logic",
    "slide_19_b1_cell0_1": "Developer calls button.text(...)",
    "slide_19_b1_cell0_2": "Developer defines UI · React calculates DOM changes",
    "slide_19_b1_cell1_0": "Observed changes",
    "slide_19_b1_cell1_1": "Button retained · Its text replaced",
    "slide_19_b1_cell1_2": "Button retained · Number text updated",
    "slide_19_b2_definition0": "Update Cost - The work needed to update the screen",
    "slide_19_b2_detail0_0": "UI calculation · Comparison · DOM changes · Browser layout · Paint",
    "slide_19_b2_definition1": "VDOM - A way to manage UI updates",
    "slide_19_b2_detail1_0": "Actual speed - Judged through implementation and measurement",
    "slide_20_title": "Web Services Using React",
    "slide_20_subtitle": "Select an Icon to Explore the Service in a New Tab",
    "slide_20_b0_service0_label": "Instagram website (opens in a new tab)",
    "slide_20_b0_service0_name": "Instagram",
    "slide_20_b0_service1_label": "Facebook website (opens in a new tab)",
    "slide_20_b0_service1_name": "Facebook",
    "slide_20_b0_service2_label": "Netflix website (opens in a new tab)",
    "slide_20_b0_service2_name": "Netflix",
    "slide_20_b0_service3_label": "Spotify website (opens in a new tab)",
    "slide_20_b0_service3_name": "Spotify",
    "slide_20_b0_service4_label": "Airbnb website (opens in a new tab)",
    "slide_20_b0_service4_name": "Airbnb",
    "slide_20_b0_service5_label": "Microsoft Teams website (opens in a new tab)",
    "slide_20_b0_service5_name": "Microsoft Teams",
    "slide_21_title": "Project Setup and Hello World",
    "slide_21_subtitle": "From a Development Environment to the First React Screen",
    "slide_22_title": "React Development Tools",
    "slide_22_subtitle": "Node.js, npm, Vite, and Environment Checks",
    "slide_22_b0_heading": "Development Tool Roles",
    "slide_22_b0_head0": "Tool",
    "slide_22_b0_head1": "Role",
    "slide_22_b0_cell0_0": "Node.js",
    "slide_22_b0_cell0_1": "Environment for running development tools",
    "slide_22_b0_cell1_0": "npm",
    "slide_22_b0_cell1_1": "Project scaffolding tools · Package installation",
    "slide_22_b0_cell2_0": "Vite",
    "slide_22_b0_cell2_1": "Dev server · Live updates · Production builds",
    "slide_22_b1_heading": "Terminal · Installation Checks",
    "slide_22_b1_code": "node -v\nnpm -v",
    "slide_22_b2_definition0": "Runtime Requirement - The Node.js versions in the Vite guide",
    "slide_22_b2_detail0_0": "Node.js 20.19+ or 22.12+",
    "slide_22_b2_detail0_1": "Check for higher version requirements in the template",
    "slide_23_title": "Creating and Running a React Project",
    "slide_23_subtitle": "Project Scaffolding, Package Installation, and the Dev Server",
    "slide_23_b0_heading": "Terminal · Scaffold → Install → Run",
    "slide_23_b0_code": "npm create vite@latest pwd-week4-demo -- --template react-ts\ncd pwd-week4-demo\nnpm install\nnpm run dev",
    "slide_23_b1_heading": "Terminal · Run Output",
    "slide_23_b1_code": "VITE v8.3.0  ready in 110 ms\n➜  Local:   http://127.0.0.1:4320/",
    "slide_23_b2_alt": "Initial browser screen of a Vite React TypeScript project",
    "slide_23_b2_caption": "Open the Local URL · React + TypeScript template",
    "slide_24_title": "Hello World and Live Updates",
    "slide_24_subtitle": "Changes in App.tsx Reflected in the Browser",
    "slide_24_b0_heading": "src/App.tsx · First Screen",
    "slide_24_b0_code": "export default function App() {\n  return <h1>Hello, World!</h1>;\n}",
    "slide_24_b1_heading": "src/App.tsx · Text Changed and Saved",
    "slide_24_b1_code": "export default function App() {\n  return <h1>Hello, React!</h1>;\n}",
    "page_title": "04 | React Fundamentals",
    "ui_deck_label": "React Fundamentals"
  }
};
