window.LECTURE_CONTENT = {
  "ko": {
    "slide_01_title": "React 기초",
    "slide_01_subtitle": "React의 등장 배경·UI 설계 철학",
    "slide_02_title": "React 등장 배경",
    "slide_02_subtitle": "",
    "slide_03_title": "React의 등장 배경",
    "slide_03_subtitle": "데이터 변화에 맞춰 화면을 직접 수정하고 일치를 유지해야 했던 문제",
    "slide_03_b0_heading": "기존의 DOM 직접 수정 방식",
    "slide_03_b0_head0": "상황",
    "slide_03_b0_head1": "개발자가 관리하던 일",
    "slide_03_b0_cell0_0": "데이터 변경",
    "slide_03_b0_cell0_1": "변경된 값과 영향을 받는 화면 요소 확인",
    "slide_03_b0_cell1_0": "화면 갱신",
    "slide_03_b0_cell1_1": "DOM 요소를 찾아 텍스트 · 속성 · 목록을 직접 수정",
    "slide_03_b0_cell2_0": "화면 복잡화",
    "slide_03_b0_cell2_1": "여러 갱신 코드가 데이터와 화면을 일치시키도록 관리",
    "slide_03_b1_definition0": "문제 - 화면 수정 책임이 개발 코드 곳곳에 분산",
    "slide_03_b1_detail0_0": "데이터가 바뀔 때마다 DOM과의 일치를 직접 유지",
    "slide_03_b1_definition1": "React의 제안(2013) - 현재 데이터에 맞는 화면을 기술",
    "slide_03_b1_detail1_0": "React = re(다시) + act(작동): 바뀐 데이터에 맞는 화면을 다시 기술",
    "slide_03_b1_detail1_1": "컴포넌트가 데이터에 따른 화면을 반환",
    "slide_03_b1_detail1_2": "React가 이전 결과와 비교해 필요한 DOM 변경을 반영",
    "slide_04_title": "React의 역할",
    "slide_04_subtitle": "데이터에 맞는 웹 서비스 화면을 구성하는 JavaScript 라이브러리",
    "slide_04_b0_heading": "웹 서비스 안에서의 위치",
    "slide_04_b0_server": "서버 · 데이터베이스",
    "slide_04_b0_server_role": "요청 처리 · 공유 데이터 저장",
    "slide_04_b0_exchange": "요청 · 데이터",
    "slide_04_b0_browser": "브라우저",
    "slide_04_b0_react": "React",
    "slide_04_b0_react_role": "컴포넌트로 UI 계산 · 변경 반영",
    "slide_04_b0_display": "DOM · CSS",
    "slide_04_b0_display_role": "문서 구조 · 스타일 · 화면 표시",
    "slide_05_title": "Facebook.com 재설계",
    "slide_05_subtitle": "React UI와 CSS·코드 로딩·데이터·탐색 구조의 변화",
    "slide_05_b0_alt": "2020년 재설계된 Facebook.com의 탐색·피드·설정 화면",
    "slide_05_b0_caption": "PHP 서버 화면 → React 기반 브라우저 앱 · 2020년",
    "slide_05_b1_definition0": "CSS - 스타일과 다크 모드",
    "slide_05_b1_detail0_0": "원자적 CSS로 홈 화면 CSS 80% 축소 · 변수로 테마 전환",
    "slide_05_b1_definition1": "JavaScript - 필요한 코드부터",
    "slide_05_b1_detail1_0": "첫 화면 표시와 이후 기능에 맞춰 코드를 3단계로 분리",
    "slide_05_b1_definition2": "데이터 - Relay · GraphQL",
    "slide_05_b1_detail2_0": "필요한 데이터를 미리 요청 · 피드 항목을 순차 전달",
    "slide_05_b1_definition3": "탐색 - 다음 화면 준비",
    "slide_05_b1_detail3_0": "이동할 화면의 코드 · 데이터를 미리 가져와 전환 지연 감소",
    "slide_06_title": "React의 발전 과정",
    "slide_06_subtitle": "",
    "slide_06_b0_head0": "시기",
    "slide_06_b0_head1": "변화",
    "slide_06_b0_head2": "의미",
    "slide_06_b0_cell0_0": "2013.05",
    "slide_06_b0_cell0_1": "React 오픈소스 공개",
    "slide_06_b0_cell0_2": "데이터에 맞는 UI를 컴포넌트로 기술",
    "slide_06_b0_cell1_0": "2017.09",
    "slide_06_b0_cell1_1": "React 16 · Fiber 도입",
    "slide_06_b0_cell1_2": "렌더링 코어 재작성 · 후속 비동기 기능의 기반",
    "slide_06_b0_cell2_0": "2019.02",
    "slide_06_b0_cell2_1": "React 16.8 · Hooks 도입",
    "slide_06_b0_cell2_2": "함수 컴포넌트에서 상태와 로직 재사용",
    "slide_06_b0_cell3_0": "2022.03",
    "slide_06_b0_cell3_1": "React 18 · 동시성 렌더러",
    "slide_06_b0_cell3_2": "긴급도에 따른 화면 갱신 · 자동 배칭",
    "slide_06_b0_cell4_0": "2024.12",
    "slide_06_b0_cell4_1": "React 19 · Actions · 서버 컴포넌트",
    "slide_06_b0_cell4_2": "폼 작업 상태 관리 · 서버에서 컴포넌트 실행",
    "slide_07_title": "React 사용 현황",
    "slide_07_subtitle": "",
    "slide_07_b0_heading": "2025 Stack Overflow · 전문 개발자",
    "slide_07_b0_head0": "선택 기술",
    "slide_07_b0_head1": "지난 1년 사용 경험",
    "slide_07_b0_cell0_0": "React",
    "slide_07_b0_cell0_1": "46.9%",
    "slide_07_b0_cell1_0": "jQuery",
    "slide_07_b0_cell1_1": "24.1%",
    "slide_07_b0_cell2_0": "Angular",
    "slide_07_b0_cell2_1": "19.8%",
    "slide_07_b0_cell3_0": "Vue.js",
    "slide_07_b0_cell3_1": "18.4%",
    "slide_07_b0_cell4_0": "Svelte",
    "slide_07_b0_cell4_1": "6.9%",
    "slide_08_title": "React를 사용하는 서비스",
    "slide_08_subtitle": "아이콘을 선택해 새 탭에서 실제 서비스 화면 살펴보기",
    "slide_08_b0_service0_label": "인스타그램 사이트 열기 (새 탭)",
    "slide_08_b0_service0_name": "인스타그램",
    "slide_08_b0_service1_label": "페이스북 사이트 열기 (새 탭)",
    "slide_08_b0_service1_name": "페이스북",
    "slide_08_b0_service2_label": "넷플릭스 사이트 열기 (새 탭)",
    "slide_08_b0_service2_name": "넷플릭스",
    "slide_08_b0_service3_label": "스포티파이 사이트 열기 (새 탭)",
    "slide_08_b0_service3_name": "스포티파이",
    "slide_08_b0_service4_label": "에어비앤비 사이트 열기 (새 탭)",
    "slide_08_b0_service4_name": "에어비앤비",
    "slide_08_b0_service5_label": "Microsoft Teams 사이트 열기 (새 탭)",
    "slide_08_b0_service5_name": "Microsoft Teams",
    "slide_09_title": "React의 UI 설계 철학",
    "slide_09_subtitle": "화면의 구성 요소·재사용·데이터와 표현의 관계",
    "slide_10_title": "React UI 설계 철학",
    "slide_10_subtitle": "화면을 컴포넌트로 구성하고, 현재 데이터와 상태에 따른 모습을 선언",
    "slide_10_b0_definition0": "컴포넌트 - 화면을 나누어 조합하는 UI 단위",
    "slide_10_b0_detail0_0": "예 - 검색창 · 상품 목록 · 상품 행",
    "slide_10_b0_definition1": "상태 - 컴포넌트가 기억하고 갱신하는 값",
    "slide_10_b0_detail1_0": "예 - 검색어 · 재고만 보기 선택 여부",
    "slide_10_b1_text": "상태 변경 → 관련 컴포넌트의 UI 재계산 → 조합된 페이지에 반영",
    "slide_11_title": "컴포넌트 기반 화면 구성",
    "slide_11_subtitle": "상품 검색 화면의 컴포넌트 경계와 포함 관계",
    "slide_11_b1_definition0": "ProductApp - 상품 검색 화면 전체",
    "slide_11_b1_detail0_0": "SearchBar와 ProductTable을 조합",
    "slide_11_b1_definition1": "SearchBar - 검색 조건 입력",
    "slide_11_b1_detail1_0": "상품명 입력 · 재고 조건 선택",
    "slide_11_b1_definition2": "ProductTable - 결과 목록 표시",
    "slide_11_b1_detail2_0": "분류별 상품 · 검색 결과 개수",
    "slide_11_b1_definition3": "ProductRow ×6 - 상품 한 행의 반복",
    "slide_11_b1_detail3_0": "각 행에 상품명 · 가격 · 재고 여부 표시",
    "slide_12_title": "컴포넌트의 재사용과 일관성",
    "slide_12_subtitle": "ProductRow 하나로 여섯 상품 행을 표시",
    "slide_12_b1_definition0": "ProductRow - 같은 UI 정의를 여섯 번 사용",
    "slide_12_b1_detail0_0": "사과 $1 · 용과 $1 · 패션프루트 $2 등 서로 다른 상품 데이터",
    "slide_12_b1_definition1": "표시 규칙 - 모든 상품 행에 공통 적용",
    "slide_12_b1_detail1_0": "상품명 - 왼쪽",
    "slide_12_b1_detail1_1": "가격 - 오른쪽",
    "slide_12_b1_detail1_2": "품절 - 색상 · 문구로 구분",
    "slide_12_b1_definition2": "재사용의 효과 - 한 곳의 표시 규칙을 모든 행에 적용",
    "slide_12_b1_detail2_0": "ProductRow 수정 → 여섯 상품 행에 함께 반영",
    "slide_13_title": "데이터 변화와 화면 표현",
    "slide_13_subtitle": "재고 조건 선택 → 품절 2개 제외 → 결과 6개 → 4개",
    "slide_14_title": "명령형과 선언형 프로그래밍",
    "slide_14_subtitle": "클릭 카운터로 비교하는 DOM 직접 수정과 UI 선언",
    "slide_14_b0_definition0": "명령형 - 작업의 순서와 방법을 직접 지정",
    "slide_14_b0_detail0_0": "jQuery - 버튼을 만들고 클릭 이벤트를 연결",
    "slide_14_b0_detail0_1": "클릭 후 button.text(...)로 화면의 텍스트를 직접 수정",
    "slide_14_b1_definition0": "선언형 - 원하는 결과의 조건이나 형태를 정의",
    "slide_14_b1_detail0_0": "React - 현재 count에 맞는 버튼 UI를 기술",
    "slide_14_b1_detail0_1": "클릭 후 setCount(...)로 상태 변경 · React가 화면 갱신",
    "slide_14_b2_heading": "jQuery · DOM 직접 수정",
    "slide_14_b2_code": "let count = 0;\nconst button = $('<button>').appendTo(host);\nbutton.text(`Clicked ${count} times`);\nbutton.on('click', () => {\n  count += 1;\n  button.text(`Clicked ${count} times`);\n});",
    "slide_14_b2_caption": "count 증가 → button.text(...) 호출",
    "slide_14_b3_heading": "React · 상태에 따른 UI",
    "slide_14_b3_code": "function Counter() {\n  const [count, setCount] = useState(0);\n  return (\n    <button onClick={() => setCount(count + 1)}>\n      Clicked {count} times\n    </button>\n  );\n}",
    "slide_14_b3_caption": "setCount(...) 호출 → 현재 count에 맞는 버튼 UI",
    "slide_15_title": "React UI 설계 방식의 확장",
    "slide_15_subtitle": "",
    "slide_15_b0_text": "React의 컴포넌트 기반·선언형 UI 접근은 다른 UI 프레임워크 설계에도 영향",
    "slide_15_b1_definition0": "React Native - React의 UI 모델을 모바일 앱에 적용",
    "slide_15_b1_detail0_0": "컴포넌트와 상태 개념을 iOS · Android 개발에 활용",
    "slide_15_b1_definition1": "Flutter - React에서 영감을 받은 UI 설계",
    "slide_15_b1_detail1_0": "공식 문서에서 위젯 · 상태에 따른 선언형 화면 구성을 설명",
    "slide_16_title": "React의 화면 갱신",
    "slide_16_subtitle": "Virtual DOM의 개념과 화면 갱신 구조",
    "slide_17_title": "Virtual DOM이란?",
    "slide_17_subtitle": "실제 DOM과 구분되는 메모리의 UI 표현",
    "slide_17_b0_definition0": "DOM - 브라우저가 관리하는 실제 문서 구조",
    "slide_17_b0_detail0_0": "화면의 요소 · 텍스트 · 속성을 담는 노드",
    "slide_17_b0_definition1": "Virtual DOM - 원하는 UI를 나타내는 메모리의 표현",
    "slide_17_b0_detail1_0": "React가 현재 UI와 다음 UI를 대조할 때 사용하는 개념적 모델",
    "slide_17_b0_definition2": "화면 표시 - 최종 변경은 실제 DOM에 반영",
    "slide_17_b0_detail2_0": "브라우저는 갱신된 DOM을 바탕으로 화면 표시",
    "slide_18_title": "DOM 직접 갱신과 React의 차이",
    "slide_18_subtitle": "재고 조건 변경 시 검색 결과 6개 → 4개",
    "slide_18_b0_heading": "같은 재고 필터 변경 · 검색 결과 6개 → 4개",
    "slide_18_b0_head0": "비교",
    "slide_18_b0_head1": "DOM 직접 갱신",
    "slide_18_b0_head2": "React · Virtual DOM 활용",
    "slide_18_b0_cell0_0": "개발자가 작성",
    "slide_18_b0_cell0_1": "품절 행 제거 · 결과 개수 수정 명령",
    "slide_18_b0_cell0_2": "재고 조건 상태와 그 상태에 맞는 UI",
    "slide_18_b0_cell1_0": "변경할 요소 결정",
    "slide_18_b0_cell1_1": "개발 코드가 DOM 노드를 찾아 지정",
    "slide_18_b0_cell1_2": "React가 이전 · 새 UI를 대조해 결정",
    "slide_18_b0_cell2_0": "최종 화면",
    "slide_18_b0_cell2_1": "실제 DOM 갱신",
    "slide_18_b0_cell2_2": "실제 DOM 갱신",
    "slide_18_b1_text": "차이 - 실제 DOM 사용 여부가 아니라 변경할 요소를 결정하는 책임",
    "slide_19_title": "React의 화면 갱신 과정",
    "slide_19_subtitle": "상태 변경 → UI 계산·대조 → DOM 반영",
    "slide_19_b0_name0": "Trigger",
    "slide_19_b0_detail0": "상태 변경",
    "slide_19_b0_name1": "Render",
    "slide_19_b0_detail1": "UI 계산·대조",
    "slide_19_b0_name2": "Commit",
    "slide_19_b0_detail2": "DOM 변경",
    "slide_19_b0_name3": "Browser",
    "slide_19_b0_detail3": "화면 표시",
    "slide_19_b1_definition0": "① Trigger - 재고 조건 상태 변경",
    "slide_19_b1_detail0_0": "「재고 있는 상품만」 선택",
    "slide_19_b1_definition1": "② Render - 새 UI 계산과 이전 결과 대조",
    "slide_19_b1_detail1_0": "컴포넌트 실행 · 결과 4개와 상품 행 구성 계산",
    "slide_19_b1_definition2": "③ Commit - 필요한 DOM 변경 반영",
    "slide_19_b1_detail2_0": "품절 행 2개 제거 · 결과 개수 6 → 4",
    "slide_19_b1_definition3": "④ Browser - 갱신된 화면 표시",
    "slide_19_b1_detail3_0": "DOM 변경 후 브라우저가 화면을 그림",
    "slide_20_title": "Virtual DOM의 효과와 한계",
    "slide_20_subtitle": "갱신 책임의 분리와 계산 비용",
    "slide_20_b0_definition0": "효과 - UI 정의와 DOM 갱신 책임 분리",
    "slide_20_b0_detail0_0": "개발자는 상태에 맞는 화면을 기술 · React가 필요한 변경을 반영",
    "slide_20_b0_definition1": "장점 - 변경 범위 관리와 기존 요소 유지",
    "slide_20_b0_detail1_0": "차이가 없는 DOM 노드는 유지 · 복잡한 화면의 갱신 코드 감소",
    "slide_20_b0_definition2": "비용 - UI 계산과 대조 작업",
    "slide_20_b0_detail2_0": "메모리의 UI 표현 · 컴포넌트 재실행에 필요한 작업량",
    "slide_20_b0_definition3": "한계 - 성능 우위는 자동으로 보장되지 않음",
    "slide_20_b0_detail3_0": "단순한 직접 갱신이 더 적은 작업일 수 있음 · 실제 속도는 측정으로 판단",
    "slide_21_title": "프로젝트 셋업과 Hello World",
    "slide_21_subtitle": "개발 환경에서 첫 React 화면까지의 실행 흐름",
    "slide_22_title": "React 개발 환경과 도구",
    "slide_22_subtitle": "Node.js·npm·Vite의 역할과 실행 환경 확인",
    "slide_22_b0_heading": "개발 도구의 역할",
    "slide_22_b0_head0": "도구",
    "slide_22_b0_head1": "역할",
    "slide_22_b0_cell0_0": "Node.js",
    "slide_22_b0_cell0_1": "개발 도구를 컴퓨터에서 실행하는 환경",
    "slide_22_b0_cell1_0": "npm",
    "slide_22_b0_cell1_1": "프로젝트 생성 도구 실행 · 패키지 설치",
    "slide_22_b0_cell2_0": "Vite",
    "slide_22_b0_cell2_1": "개발 서버 · 변경 반영 · 배포용 빌드",
    "slide_22_b1_heading": "터미널 · 설치 확인",
    "slide_22_b1_code": "node -v\nnpm -v",
    "slide_22_b2_definition0": "실행 조건 - Vite 가이드의 Node.js 버전 요구사항",
    "slide_22_b2_detail0_0": "Node.js 20.19+ 또는 22.12+",
    "slide_22_b2_detail0_1": "템플릿의 추가 버전 조건 확인",
    "slide_23_title": "React 프로젝트 생성과 실행",
    "slide_23_subtitle": "프로젝트 생성·패키지 설치·개발 서버 접속",
    "slide_23_b0_heading": "터미널 · 생성 → 설치 → 실행",
    "slide_23_b0_code": "npm create vite@latest pwd-week4-demo -- --template react-ts\ncd pwd-week4-demo\nnpm install\nnpm run dev",
    "slide_23_b0_caption": "첫 명령은 한 줄로 입력 · 설치 확인 메시지가 나오면 y 선택",
    "slide_23_b1_heading": "터미널 · 실행 출력 예시",
    "slide_23_b1_code": "VITE v8.x.x  ready\n➜  Local:   http://localhost:5173/",
    "slide_23_b1_caption": "실제 접속 주소는 터미널의 Local 출력 확인",
    "slide_23_b2_alt": "Vite React TypeScript 프로젝트의 초기 브라우저 화면",
    "slide_23_b2_caption": "Local 주소 접속 · React + TypeScript 템플릿",
    "slide_24_title": "Hello World와 화면 변경 확인",
    "slide_24_subtitle": "App.tsx의 문구 수정이 브라우저에 반영되는 과정",
    "slide_24_b0_heading": "src/App.tsx · 최초 화면",
    "slide_24_b0_code": "export default function App() {\n  return <h1>Hello, World!</h1>;\n}",
    "slide_24_b1_heading": "src/App.tsx · 문구 변경 후 저장",
    "slide_24_b1_code": "export default function App() {\n  return <h1>Hello, React!</h1>;\n}",
    "page_title": "04 | React 기초",
    "ui_deck_label": "React 기초"
  },
  "en": {
    "slide_01_title": "React Fundamentals",
    "slide_01_subtitle": "Origins and UI Design Philosophy",
    "slide_02_title": "React Origins",
    "slide_02_subtitle": "",
    "slide_03_title": "The Origins of React",
    "slide_03_subtitle": "The Challenge of Keeping the UI in Sync with Changing Data",
    "slide_03_b0_heading": "Direct DOM Updates",
    "slide_03_b0_head0": "Situation",
    "slide_03_b0_head1": "What the Developer Managed",
    "slide_03_b0_cell0_0": "Data changed",
    "slide_03_b0_cell0_1": "Find changed values and affected UI elements",
    "slide_03_b0_cell1_0": "UI update",
    "slide_03_b0_cell1_1": "Select DOM nodes and update text, attributes, and lists",
    "slide_03_b0_cell2_0": "Growing UI complexity",
    "slide_03_b0_cell2_1": "Keep scattered update code and displayed data in sync",
    "slide_03_b1_definition0": "Problem - UI update logic spread across the code",
    "slide_03_b1_detail0_0": "Manually keep the DOM in sync as data changes",
    "slide_03_b1_definition1": "React’s Proposal (2013) - Describe the UI for current data",
    "slide_03_b1_detail1_0": "React = re (again) + act: describe the UI again for the changed data",
    "slide_03_b1_detail1_1": "Components return a UI description from the data",
    "slide_03_b1_detail1_2": "React compares results and applies the needed DOM changes",
    "slide_04_title": "The Role of React",
    "slide_04_subtitle": "A JavaScript library for building web interfaces that reflect data",
    "slide_04_b0_heading": "Its Place in a Web Service",
    "slide_04_b0_server": "Server · Database",
    "slide_04_b0_server_role": "Process requests · Store shared data",
    "slide_04_b0_exchange": "Requests · Data",
    "slide_04_b0_browser": "Browser",
    "slide_04_b0_react": "React",
    "slide_04_b0_react_role": "Compute UI with components · Apply updates",
    "slide_04_b0_display": "DOM · CSS",
    "slide_04_b0_display_role": "Document structure · Styling · Display",
    "slide_05_title": "Facebook.com Redesign",
    "slide_05_subtitle": "React UI · CSS · JS · Data · Navigation",
    "slide_05_b0_alt": "Navigation, feed, and settings in the redesigned 2020 Facebook.com",
    "slide_05_b0_caption": "PHP server pages → React client app · 2020",
    "slide_05_b1_definition0": "CSS - Styles and Dark Mode",
    "slide_05_b1_detail0_0": "Atomic CSS cut homepage CSS by 80%; variables switch themes",
    "slide_05_b1_definition1": "JavaScript - Load What Is Needed First",
    "slide_05_b1_detail1_0": "Code split into three tiers for first paint and later features",
    "slide_05_b1_definition2": "Data - Relay and GraphQL",
    "slide_05_b1_detail2_0": "Preload needed data and stream feed stories as they arrive",
    "slide_05_b1_definition3": "Navigation - Prepare the Next Screen",
    "slide_05_b1_detail3_0": "Prefetch code and data for the destination to reduce delays",
    "slide_06_title": "The Evolution of React",
    "slide_06_subtitle": "",
    "slide_06_b0_head0": "Date",
    "slide_06_b0_head1": "Change",
    "slide_06_b0_head2": "Significance",
    "slide_06_b0_cell0_0": "2013.05",
    "slide_06_b0_cell0_1": "React open-sourced",
    "slide_06_b0_cell0_2": "Describe data-driven UI with components",
    "slide_06_b0_cell1_0": "2017.09",
    "slide_06_b0_cell1_1": "React 16 · Fiber",
    "slide_06_b0_cell1_2": "Rebuilt rendering core · Foundation for later async features",
    "slide_06_b0_cell2_0": "2019.02",
    "slide_06_b0_cell2_1": "React 16.8 · Hooks",
    "slide_06_b0_cell2_2": "State and reusable logic in function components",
    "slide_06_b0_cell3_0": "2022.03",
    "slide_06_b0_cell3_1": "React 18 · Concurrent renderer",
    "slide_06_b0_cell3_2": "Prioritized UI updates · Automatic batching",
    "slide_06_b0_cell4_0": "2024.12",
    "slide_06_b0_cell4_1": "React 19 · Actions and Server Components",
    "slide_06_b0_cell4_2": "Form action state · Components run on the server",
    "slide_07_title": "React Usage",
    "slide_07_subtitle": "",
    "slide_07_b0_heading": "2025 Stack Overflow · Professional Developers",
    "slide_07_b0_head0": "Selected Technology",
    "slide_07_b0_head1": "Used in the Past Year",
    "slide_07_b0_cell0_0": "React",
    "slide_07_b0_cell0_1": "46.9%",
    "slide_07_b0_cell1_0": "jQuery",
    "slide_07_b0_cell1_1": "24.1%",
    "slide_07_b0_cell2_0": "Angular",
    "slide_07_b0_cell2_1": "19.8%",
    "slide_07_b0_cell3_0": "Vue.js",
    "slide_07_b0_cell3_1": "18.4%",
    "slide_07_b0_cell4_0": "Svelte",
    "slide_07_b0_cell4_1": "6.9%",
    "slide_08_title": "Web Services Using React",
    "slide_08_subtitle": "Select an Icon to Explore the Service in a New Tab",
    "slide_08_b0_service0_label": "Instagram website (opens in a new tab)",
    "slide_08_b0_service0_name": "Instagram",
    "slide_08_b0_service1_label": "Facebook website (opens in a new tab)",
    "slide_08_b0_service1_name": "Facebook",
    "slide_08_b0_service2_label": "Netflix website (opens in a new tab)",
    "slide_08_b0_service2_name": "Netflix",
    "slide_08_b0_service3_label": "Spotify website (opens in a new tab)",
    "slide_08_b0_service3_name": "Spotify",
    "slide_08_b0_service4_label": "Airbnb website (opens in a new tab)",
    "slide_08_b0_service4_name": "Airbnb",
    "slide_08_b0_service5_label": "Microsoft Teams website (opens in a new tab)",
    "slide_08_b0_service5_name": "Microsoft Teams",
    "slide_09_title": "React UI Design Philosophy",
    "slide_09_subtitle": "UI Elements, Reuse, and the Relationship Between Data and Presentation",
    "slide_10_title": "React UI Design Philosophy",
    "slide_10_subtitle": "Compose the UI from components and describe its appearance for the current data and state",
    "slide_10_b0_definition0": "Component - A UI unit composed with others",
    "slide_10_b0_detail0_0": "Examples - Search field · Product list · Product row",
    "slide_10_b0_definition1": "State - A value a component remembers and updates",
    "slide_10_b0_detail1_0": "Examples - Search query · In-stock-only selection",
    "slide_10_b1_text": "State change → UI recalculated for affected components → Composed page updated",
    "slide_11_title": "Component-Based UI Composition",
    "slide_11_subtitle": "Component boundaries and nesting in a product search screen",
    "slide_11_b1_definition0": "ProductApp - The complete product search screen",
    "slide_11_b1_detail0_0": "Combines SearchBar and ProductTable",
    "slide_11_b1_definition1": "SearchBar - Search criteria input",
    "slide_11_b1_detail1_0": "Product-name input · Stock selection",
    "slide_11_b1_definition2": "ProductTable - Results display",
    "slide_11_b1_detail2_0": "Products by category · Result count",
    "slide_11_b1_definition3": "ProductRow ×6 - Repeated product row",
    "slide_11_b1_detail3_0": "Each row shows name · price · availability",
    "slide_12_title": "Component Reuse and Consistency",
    "slide_12_subtitle": "One ProductRow component displays six products",
    "slide_12_b1_definition0": "ProductRow - One UI definition used six times",
    "slide_12_b1_detail0_0": "Different product data such as Apple $1 · Dragonfruit $1 · Passionfruit $2",
    "slide_12_b1_definition1": "Display rules - Shared by every product row",
    "slide_12_b1_detail1_0": "Name - Left",
    "slide_12_b1_detail1_1": "Price - Right",
    "slide_12_b1_detail1_2": "Out of stock - Color · Text",
    "slide_12_b1_definition2": "Benefit of reuse - One set of display rules across all rows",
    "slide_12_b1_detail2_0": "Edit ProductRow → Apply to all six product rows",
    "slide_13_title": "Data Changes and UI Output",
    "slide_13_subtitle": "Stock filter selected → Two unavailable products removed → Results 6 → 4",
    "slide_14_title": "Imperative and Declarative Programming",
    "slide_14_subtitle": "Two Ways to Update the Same Counter",
    "slide_14_b0_definition0": "Imperative - Explicit steps and operations",
    "slide_14_b0_detail0_0": "jQuery - Create the button and attach a click handler",
    "slide_14_b0_detail0_1": "After a click, update the displayed text with button.text(...)",
    "slide_14_b1_definition0": "Declarative - Conditions or form of the desired result",
    "slide_14_b1_detail0_0": "React - Describe the button UI for the current count",
    "slide_14_b1_detail0_1": "After a click, setCount(...) changes state and React updates the UI",
    "slide_14_b2_heading": "jQuery · Direct DOM Update",
    "slide_14_b2_code": "let count = 0;\nconst button = $('<button>').appendTo(host);\nbutton.text(`Clicked ${count} times`);\nbutton.on('click', () => {\n  count += 1;\n  button.text(`Clicked ${count} times`);\n});",
    "slide_14_b2_caption": "Increment count → Call button.text(...)",
    "slide_14_b3_heading": "React · UI from State",
    "slide_14_b3_code": "function Counter() {\n  const [count, setCount] = useState(0);\n  return (\n    <button onClick={() => setCount(count + 1)}>\n      Clicked {count} times\n    </button>\n  );\n}",
    "slide_14_b3_caption": "Call setCount(...) → Button UI for the current count",
    "slide_15_title": "Extending React UI Design Across Environments",
    "slide_15_subtitle": "",
    "slide_15_b0_text": "React’s component-based, declarative approach also influenced other UI frameworks",
    "slide_15_b1_definition0": "React Native - React’s UI model applied to mobile apps",
    "slide_15_b1_detail0_0": "Components and state used to build iOS and Android apps",
    "slide_15_b1_definition1": "Flutter - UI design inspired by React",
    "slide_15_b1_detail1_0": "Its official documentation describes declarative screens built from widgets and state",
    "slide_16_title": "UI Updates in React",
    "slide_16_subtitle": "Virtual DOM Concepts and the UI Update Process",
    "slide_17_title": "What Is the Virtual DOM?",
    "slide_17_subtitle": "An In-Memory UI Representation Distinct from the Real DOM",
    "slide_17_b0_definition0": "DOM - The document structure managed by the browser",
    "slide_17_b0_detail0_0": "Nodes containing screen elements, text, and attributes",
    "slide_17_b0_definition1": "Virtual DOM - An in-memory representation of the desired UI",
    "slide_17_b0_detail1_0": "A conceptual model React uses to compare the current and next UI",
    "slide_17_b0_definition2": "Display - Final changes are applied to the real DOM",
    "slide_17_b0_detail2_0": "The browser displays the updated DOM",
    "slide_18_title": "Direct DOM Updates and React",
    "slide_18_subtitle": "Stock Filter Changes the Result Count from 6 to 4",
    "slide_18_b0_heading": "Same Stock Filter Change · Results 6 → 4",
    "slide_18_b0_head0": "Comparison",
    "slide_18_b0_head1": "Direct DOM Updates",
    "slide_18_b0_head2": "React · Virtual DOM",
    "slide_18_b0_cell0_0": "Developer writes",
    "slide_18_b0_cell0_1": "Commands to remove unavailable rows and change the count",
    "slide_18_b0_cell0_2": "Stock-filter state and the UI for that state",
    "slide_18_b0_cell1_0": "Who selects changes",
    "slide_18_b0_cell1_1": "Application code finds and selects DOM nodes",
    "slide_18_b0_cell1_2": "React compares previous and next UI",
    "slide_18_b0_cell2_0": "Final output",
    "slide_18_b0_cell2_1": "Real DOM updated",
    "slide_18_b0_cell2_2": "Real DOM updated",
    "slide_18_b1_text": "Difference - Who decides which DOM nodes to change",
    "slide_19_title": "The React UI Update Process",
    "slide_19_subtitle": "State Change → UI Calculation and Comparison → DOM Commit",
    "slide_19_b0_name0": "Trigger",
    "slide_19_b0_detail0": "State change",
    "slide_19_b0_name1": "Render",
    "slide_19_b0_detail1": "Calculate · Compare UI",
    "slide_19_b0_name2": "Commit",
    "slide_19_b0_detail2": "Update DOM",
    "slide_19_b0_name3": "Browser",
    "slide_19_b0_detail3": "Display screen",
    "slide_19_b1_definition0": "① Trigger - Stock-filter state changes",
    "slide_19_b1_detail0_0": "Select “Only products in stock”",
    "slide_19_b1_definition1": "② Render - Calculate and compare the next UI",
    "slide_19_b1_detail1_0": "Run components · Calculate four results and their rows",
    "slide_19_b1_definition2": "③ Commit - Apply necessary DOM changes",
    "slide_19_b1_detail2_0": "Remove two unavailable rows · Change result count 6 → 4",
    "slide_19_b1_definition3": "④ Browser - Display the updated screen",
    "slide_19_b1_detail3_0": "The browser paints after DOM changes",
    "slide_20_title": "Virtual DOM Benefits and Limits",
    "slide_20_subtitle": "Update Responsibility and the Cost of UI Calculation",
    "slide_20_b0_definition0": "Effect - Separate UI definition from DOM update decisions",
    "slide_20_b0_detail0_0": "Developers describe the UI for state · React applies required changes",
    "slide_20_b0_definition1": "Benefit - Manage updates and preserve existing elements",
    "slide_20_b0_detail1_0": "Unchanged DOM nodes remain · Less manual update code for complex screens",
    "slide_20_b0_definition2": "Cost - UI calculation and comparison",
    "slide_20_b0_detail2_0": "In-memory UI representation · Work to re-run components",
    "slide_20_b0_definition3": "Limit - Performance is not automatically better",
    "slide_20_b0_detail3_0": "A simple direct update may do less work · Measure actual performance",
    "slide_21_title": "Project Setup and Hello World",
    "slide_21_subtitle": "From a Development Environment to the First React Screen",
    "slide_22_title": "React Development Tools",
    "slide_22_subtitle": "Node.js, npm, Vite, and Environment Checks",
    "slide_22_b0_heading": "Development Tool Roles",
    "slide_22_b0_head0": "Tool",
    "slide_22_b0_head1": "Role",
    "slide_22_b0_cell0_0": "Node.js",
    "slide_22_b0_cell0_1": "Environment for running development tools",
    "slide_22_b0_cell1_0": "npm",
    "slide_22_b0_cell1_1": "Project scaffolding tools · Package installation",
    "slide_22_b0_cell2_0": "Vite",
    "slide_22_b0_cell2_1": "Dev server · Live updates · Production builds",
    "slide_22_b1_heading": "Terminal · Installation Checks",
    "slide_22_b1_code": "node -v\nnpm -v",
    "slide_22_b2_definition0": "Runtime Requirement - The Node.js versions in the Vite guide",
    "slide_22_b2_detail0_0": "Node.js 20.19+ or 22.12+",
    "slide_22_b2_detail0_1": "Check for higher version requirements in the template",
    "slide_23_title": "Creating and Running a React Project",
    "slide_23_subtitle": "Project Scaffolding, Package Installation, and the Dev Server",
    "slide_23_b0_heading": "Terminal · Scaffold → Install → Run",
    "slide_23_b0_code": "npm create vite@latest pwd-week4-demo -- --template react-ts\ncd pwd-week4-demo\nnpm install\nnpm run dev",
    "slide_23_b0_caption": "Enter the first command on one line · If npm asks to install, enter y",
    "slide_23_b1_heading": "Terminal · Example Output",
    "slide_23_b1_code": "VITE v8.x.x  ready\n➜  Local:   http://localhost:5173/",
    "slide_23_b1_caption": "Use the Local URL shown in your terminal",
    "slide_23_b2_alt": "Initial browser screen of a Vite React TypeScript project",
    "slide_23_b2_caption": "Open the Local URL · React + TypeScript template",
    "slide_24_title": "Hello World and Live Updates",
    "slide_24_subtitle": "Changes in App.tsx Reflected in the Browser",
    "slide_24_b0_heading": "src/App.tsx · First Screen",
    "slide_24_b0_code": "export default function App() {\n  return <h1>Hello, World!</h1>;\n}",
    "slide_24_b1_heading": "src/App.tsx · Text Changed and Saved",
    "slide_24_b1_code": "export default function App() {\n  return <h1>Hello, React!</h1>;\n}",
    "page_title": "04 | React Fundamentals",
    "ui_deck_label": "React Fundamentals"
  }
};
